left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_Plantuml << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : uniqueidentifier
}

entity repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : uniqueidentifier
  **included_RepoObject_guid** : uniqueidentifier
}

docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
