left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
}

entity docs.RepoObject_Plantuml << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml_Entity_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_referenced_level_T << U >> {
  **StartingNode_guid** : uniqueidentifier
  **LastNode_guid** : uniqueidentifier
  * **referenced_level** : int
}

entity repo.RepoObject_referencing_level_T << U >> {
  **StartingNode_guid** : uniqueidentifier
  **LastNode_guid** : uniqueidentifier
  * **referencing_level** : int
}

docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
repo.RepoObject <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
repo.RepoObject_referenced_level_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
repo.RepoObject_referencing_level_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
