left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_Plantuml_ObjectRefList << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity graph.RepoObject << U >> {
}

entity graph.RepoObject_ReferencingReferenced << V >> {
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity graph.RepoObject_ReferencingReferenced_u_v << V >> {
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity graph.RepoObject_S << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.Match_RepoObject_referenced_UspPersistence << V >> {
  **FirstNode** : uniqueidentifier
  **LastNode** : uniqueidentifier
}

entity repo.RepoObject_reference_union_node_id << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_referenced_level << V >> {
  **StartingNode_guid** : uniqueidentifier
  **LastNode_guid** : uniqueidentifier
  * **referenced_level** : int
}

entity repo.RepoObject_referencing_level << V >> {
  **StartingNode_guid** : uniqueidentifier
  **LastNode_guid** : uniqueidentifier
  * **referencing_level** : int
}

entity repo.usp_main << P >> {
}

entity repo.usp_sync_guid_RepoObject << P >> {
}

graph.RepoObject <.. repo.usp_sync_guid_RepoObject
graph.RepoObject <.. repo.usp_main
graph.RepoObject <.. repo.RepoObject_reference_union_node_id
graph.RepoObject <.. repo.Match_RepoObject_referenced_UspPersistence
graph.RepoObject <.. graph.RepoObject_ReferencingReferenced_u_v
graph.RepoObject <.. graph.RepoObject_ReferencingReferenced
graph.RepoObject <.. repo.RepoObject_referenced_level
graph.RepoObject <.. repo.RepoObject_referencing_level
graph.RepoObject <.. docs.RepoObject_Plantuml_ObjectRefList
graph.RepoObject_S <.. repo.usp_sync_guid_RepoObject
graph.RepoObject_S <.. graph.RepoObject
