left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.ftv_RepoObject_ReferenceTree_referenced << IF >> {
}

entity repo.ftv_RepoObject_ReferenceTree_referencing << IF >> {
}

entity graph.ReferencedObject << U >> {
}

entity graph.RepoObject << U >> {
}

entity graph.RepoObject_ReferencingReferenced << V >> {
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity repo.ftv_RepoObject_ReferenceTree << IF >> {
}

entity repo.ftv_RepoObject_ReferenceTree_via_fullname << IF >> {
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_ReferencedList << V >> {
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObject_ReferencingList << V >> {
  **Referenced_guid** : uniqueidentifier
}

graph.ReferencedObject <.. graph.RepoObject_ReferencingReferenced
graph.RepoObject <.. graph.RepoObject_ReferencingReferenced
graph.RepoObject_ReferencingReferenced <.. repo.RepoObject_ReferencingList
graph.RepoObject_ReferencingReferenced <.. repo.RepoObject_ReferencedList
graph.RepoObject_ReferencingReferenced <.. repo.ftv_RepoObject_ReferenceTree
graph.RepoObject_ReferencingReferenced <.. repo.ftv_RepoObject_ReferenceTree_via_fullname
graph.RepoObject_ReferencingReferenced <.. 
graph.RepoObject_ReferencingReferenced <.. 
graph.RepoObject_ReferencingReferenced <.. repo.RepoObject_gross
repo.RepoObject_ReferencedList <.. repo.RepoObject_gross
repo.RepoObject_ReferencingList <.. repo.RepoObject_gross
