left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.usp_AntoraExport << P >> {
}

entity docs.usp_AntoraExport_navigation << P >> {
}

entity docs.usp_AntoraExport_ObjectPage << P >> {
}

entity docs.usp_AntoraExport_ObjectPageTemplate << P >> {
}

entity docs.usp_AntoraExport_ObjectPartialProperties << P >> {
}

entity docs.usp_AntoraExport_ObjectPuml << P >> {
}

entity docs.usp_AntoraExport_Page_IndexSemanticGroup << P >> {
}

entity docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
}

entity docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
}

entity docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
}

entity docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
}

entity graph.usp_PERSIST_Index << P >> {
}

entity graph.usp_PERSIST_RepoObject << P >> {
}

entity graph.usp_PERSIST_RepoObjectColumn << P >> {
}

entity logs.ExecutionLog << U >> {
  * **id** : bigint
}

entity logs.usp_ExecutionLog_insert << P >> {
}

entity repo.usp_Index_finish << P >> {
}

entity repo.usp_Index_ForeignKey << P >> {
}

entity repo.usp_index_inheritance << P >> {
}

entity repo.usp_Index_Settings << P >> {
}

entity repo.usp_Index_virtual_set << P >> {
}

entity repo.usp_main << P >> {
}

entity repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
}

entity repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
}

entity repo.usp_PERSIST_RepoObject_referenced_level_T << P >> {
}

entity repo.usp_PERSIST_RepoObject_referencing_level_T << P >> {
}

entity repo.usp_persistence_set << P >> {
}

entity repo.usp_RepoObject_Inheritance << P >> {
}

entity repo.usp_RepoObject_update_SysObjectQueryPlan << P >> {
}

entity repo.usp_RepoObjectColumn_Inheritance << P >> {
}

entity repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
}

entity repo.usp_RepoObjectProperty_collect << P >> {
}

entity repo.usp_RepoObjectSource_FirstResultSet << P >> {
}

entity repo.usp_RepoObjectSource_QueryPlan << P >> {
}

entity repo.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
}

entity repo.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
}

entity repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
}

entity repo.usp_sync_guid << P >> {
}

entity repo.usp_sync_guid_RepoObject << P >> {
}

entity repo.usp_sync_guid_RepoObjectColumn << P >> {
}

entity repo.usp_update_Referencing_Count << P >> {
}

entity sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T << P >> {
}

entity sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T << P >> {
}

entity uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
}

docs.usp_AntoraExport_navigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPageTemplate <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialProperties <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_AntoraExport_Page_IndexSemanticGroup <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
graph.usp_PERSIST_Index <.. repo.usp_Index_finish
graph.usp_PERSIST_RepoObject <.. repo.usp_sync_guid_RepoObject
graph.usp_PERSIST_RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectSource_FirstResultSet
logs.usp_ExecutionLog_insert <.. repo.usp_Index_Settings
logs.usp_ExecutionLog_insert <.. repo.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectSource_QueryPlan
logs.usp_ExecutionLog_insert <.. repo.usp_Index_virtual_set
logs.usp_ExecutionLog_insert <.. repo.usp_index_inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObject_update_SysObjectQueryPlan
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
logs.usp_ExecutionLog_insert <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject
logs.usp_ExecutionLog_insert <.. repo.usp_main
logs.usp_ExecutionLog_insert <.. repo.usp_persistence_set
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Adoc_T
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_navigation
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_Page_IndexSemanticGroup
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPageTemplate
logs.usp_ExecutionLog_insert <.. graph.usp_PERSIST_Index
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_referenced_level_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_referencing_level_T
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPage
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPartialProperties
logs.usp_ExecutionLog_insert <.. repo.usp_Index_ForeignKey
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPuml
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_IndexList_T
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectProperty_collect
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
logs.usp_ExecutionLog_insert <.. repo.usp_Index_finish
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObject_Inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectColumn_Inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
logs.usp_ExecutionLog_insert <.. repo.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
logs.usp_ExecutionLog_insert <.. repo.usp_sync_ExtendedProperties_Repo2Sys_Delete
logs.usp_ExecutionLog_insert <.. graph.usp_PERSIST_RepoObject
logs.usp_ExecutionLog_insert <.. graph.usp_PERSIST_RepoObjectColumn
logs.usp_ExecutionLog_insert <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
logs.usp_ExecutionLog_insert <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
logs.usp_ExecutionLog_insert <.. docs.usp_PERSIST_RepoObject_Plantuml_T
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_PERSIST_RepoObject_referenced_level_T <.. docs.usp_AntoraExport_ObjectPuml
repo.usp_PERSIST_RepoObject_referencing_level_T <.. docs.usp_AntoraExport_ObjectPuml
repo.usp_RepoObject_Inheritance <.. repo.usp_main
repo.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
repo.usp_RepoObjectColumn_Inheritance <.. repo.usp_main
repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id <.. repo.usp_main
repo.usp_RepoObjectProperty_collect <.. docs.usp_AntoraExport
repo.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
repo.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo.usp_update_Referencing_Count <.. repo.usp_main
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
