left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.Index_union << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_virtual << U >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Index_virtual_IndexPatternColumnGuid << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.IndexColumn_virtual << U >> {
  * **index_guid** : uniqueidentifier
  * **index_column_id** : int
}

entity repo.usp_index_inheritance << P >> {
}

repo.Index_virtual <.. repo.Index_union
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual <.. repo.usp_index_inheritance
repo.Index_virtual_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual_IndexPatternColumnGuid <.. repo.usp_index_inheritance
repo.IndexColumn_virtual <.. repo.usp_index_inheritance
repo.IndexColumn_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
