left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.ftv_query_plan_extract_source << IF >> {
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity repo.RepoObjectSource_QueryPlan << U >> {
}

entity repo.SysObjectColumn_QueryPlanExpression << V >> {
}

entity repo.usp_ExecutionLog_insert << P >> {
}

entity repo.usp_main << P >> {
}

entity repo.usp_RepoObjectSource_QueryPlan << P >> {
}

repo.ftv_query_plan_extract_source <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObjectColumn <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObjectSource_QueryPlan <.. repo.usp_RepoObjectSource_QueryPlan
repo.SysObjectColumn_QueryPlanExpression <.. repo.usp_RepoObjectSource_QueryPlan
repo.usp_ExecutionLog_insert <.. repo.usp_RepoObjectSource_QueryPlan
repo.usp_ExecutionLog_insert <.. repo.usp_main
repo.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
