left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  * **T2_json_key** : nvarchar(4000)
}

entity repo.RepoObject_SqlModules_39_object << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_SqlModules_52_Identitfier_QuoteName << V >> {
}

entity repo.RepoObject_SqlModules_61_SelectIdentifier_Union << V >> {
}

entity repo.RepoObject_SqlModules_61_SelectIdentifier_Union_T << U >> {
}

entity repo.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T << P >> {
}

repo.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName <.. repo.RepoObject_SqlModules_61_SelectIdentifier_Union
repo.RepoObject_SqlModules_39_object <.. repo.RepoObject_SqlModules_61_SelectIdentifier_Union
repo.RepoObject_SqlModules_52_Identitfier_QuoteName <.. repo.RepoObject_SqlModules_61_SelectIdentifier_Union
repo.RepoObject_SqlModules_61_SelectIdentifier_Union <.. repo.RepoObject_SqlModules_61_SelectIdentifier_Union_T
repo.RepoObject_SqlModules_61_SelectIdentifier_Union <.. repo.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
repo.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. repo.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
