left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity logs.usp_ExecutionLog_insert << P >> {
}

entity repo.RepoObject_Inheritance_temp << U >> {
}

entity repo.RepoObjectProperty << U >> {
  * **RepoObjectProperty_id** : int
}

entity repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
}

entity repo.usp_main << P >> {
}

entity repo.usp_RepoObject_Inheritance << P >> {
}

logs.usp_ExecutionLog_insert <.. repo.usp_RepoObject_Inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_main
repo.RepoObject_Inheritance_temp <.. repo.usp_RepoObject_Inheritance
repo.RepoObjectProperty <.. repo.usp_RepoObject_Inheritance
repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition <.. repo.usp_RepoObject_Inheritance
repo.usp_RepoObject_Inheritance <.. repo.usp_main
