left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.ExecutionLog_plantUML_Sequence_start_stop << V >> {
  * **id** : bigint
}

entity repo.ExecutionLog << U >> {
  * **id** : bigint
}

entity repo.ExecutionLog_gross << V >> {
  * **id** : bigint
}

entity repo.ExecutionLog_parent << V >> {
  * **id** : bigint
}

entity repo.usp_ExecutionLog_insert << P >> {
}

repo.ExecutionLog <.. repo.usp_ExecutionLog_insert
repo.ExecutionLog <.. repo.ExecutionLog_gross
repo.ExecutionLog <.. repo.ExecutionLog_parent
repo.ExecutionLog <.. docs.ExecutionLog_plantUML_Sequence_start_stop
repo.ExecutionLog_parent <.. docs.ExecutionLog_plantUML_Sequence_start_stop
