left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_Adoc << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.ExtendedProperty_Repo2Sys_level1 << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  * **property_name** : nvarchar(128)
}

entity repo.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  **level2type** : varchar(10)
  * **level2name** : nvarchar(128)
  * **property_name** : nvarchar(128)
}

entity repo.fs_get_RepoObjectProperty_nvarchar << FN >> {
}

entity repo.PropertyName_RepoObject << V >> {
  * **property_name** : nvarchar(128)
}

entity repo.RepoObjectProperty << U >> {
  * **RepoObjectProperty_id** : int
}

entity repo.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **property_name** : nvarchar(128)
}

entity repo.RepoObjectProperty_sys_repo << V >> {
}

entity repo.usp_RepoObject_Inheritance << P >> {
}

entity repo.usp_RepoObjectProperty_collect << P >> {
}

entity repo.usp_RepoObjectProperty_set << P >> {
}

entity repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
}

repo.PropertyName_RepoObject <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectProperty <.. repo.usp_RepoObject_Inheritance
repo.RepoObjectProperty <.. repo.ExtendedProperty_Repo2Sys_level2_RepoObject
repo.RepoObjectProperty <.. repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
repo.RepoObjectProperty <.. repo.RepoObjectProperty_sys_repo
repo.RepoObjectProperty <.. repo.usp_RepoObjectProperty_collect
repo.RepoObjectProperty <.. repo.usp_RepoObjectProperty_set
repo.RepoObjectProperty <.. repo.ExtendedProperty_Repo2Sys_level1
repo.RepoObjectProperty <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectProperty <.. repo.PropertyName_RepoObject
repo.RepoObjectProperty <.. docs.RepoObject_Adoc
repo.RepoObjectProperty <.. repo.fs_get_RepoObjectProperty_nvarchar
repo.RepoObjectProperty_sys_repo <.. repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
