left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObjectProperty_Collect_source_uspgenerator << V >> {
}

entity repo.RepoObjectProperty_Collect_source_ROGross << V >> {
}

entity docs.usp_AntoraExport << P >> {
}

entity logs.usp_ExecutionLog_insert << P >> {
}

entity repo.RepoObjectProperty << U >> {
  * **RepoObjectProperty_id** : int
}

entity repo.RepoObjectProperty_Collect_source_sql_modules_definition << V >> {
}

entity repo.usp_RepoObjectProperty_collect << P >> {
}

 <.. repo.usp_RepoObjectProperty_collect
 <.. repo.usp_RepoObjectProperty_collect
logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectProperty_collect
repo.RepoObjectProperty <.. repo.usp_RepoObjectProperty_collect
repo.RepoObjectProperty_Collect_source_sql_modules_definition <.. repo.usp_RepoObjectProperty_collect
repo.usp_RepoObjectProperty_collect <.. docs.usp_AntoraExport
