left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.Index_union << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_virtual << U >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Index_virtual_ForUpdate << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Index_virtual_IndexPatternColumnGuid << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Index_virtual_SysObject << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.IndexColumn_virtual_gross << V >> {
  * **index_column_id** : int
}

entity repo.IndexColumn_virtual_referenced_setpoint << V >> {
  * **index_guid** : uniqueidentifier
  * **index_column_id** : int
}

entity repo.IndexReferencedReferencing << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.usp_Index_finish << P >> {
}

entity repo.usp_index_inheritance << P >> {
}

entity repo.usp_Index_virtual_set << P >> {
}

repo.Index_union <.. repo.usp_Index_finish
repo.Index_union <.. repo.IndexReferencedReferencing
repo.Index_virtual <.. repo.IndexReferencedReferencing
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual <.. repo.usp_index_inheritance
repo.Index_virtual <.. repo.Index_virtual_SysObject
repo.Index_virtual <.. repo.IndexColumn_virtual_gross
repo.Index_virtual <.. repo.IndexColumn_virtual_referenced_setpoint
repo.Index_virtual <.. repo.usp_Index_finish
repo.Index_virtual <.. repo.usp_Index_virtual_set
repo.Index_virtual <.. repo.Index_virtual_ForUpdate
repo.Index_virtual <.. repo.Index_union
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.Index_virtual_IndexPatternColumnGuid <.. repo.usp_index_inheritance
repo.Index_virtual_IndexPatternColumnGuid <.. repo.Index_union
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.usp_Index_finish <.. repo.usp_index_inheritance
