left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.IndexReferencedReferencing << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  * **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_reference_union_node_id << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_reference_BySamePredecessors << V >> {
}

entity repo.RepoObjectColumn_reference_FirstResultSet << V >> {
}

entity repo.RepoObjectColumn_reference_QueryPlan << V >> {
}

entity repo.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
}

entity repo.usp_main << P >> {
}

repo.RepoObject_reference_persistence <.. repo.RepoObject_reference_union
repo.RepoObject_reference_SqlExpressionDependencies <.. repo.RepoObject_reference_union
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_SqlExpressionDependencies
repo.RepoObject_reference_union <.. repo.IndexReferencedReferencing
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_FirstResultSet
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_BySamePredecessors
repo.RepoObject_reference_union <.. repo.usp_main
repo.RepoObject_reference_union <.. repo.RepoObject_reference_union_node_id
repo.RepoObjectColumn_reference_FirstResultSet <.. repo.RepoObjectColumn_reference_BySamePredecessors
