left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObjectProperty_from_sql_modules_definition << V >> {
}

entity repo.usp_RepoObjectProperty_collect << P >> {
}

entity sqlparse.RepoObject_SqlModules_Repo_Sys << V >> {
}

entity tool.ftv_extract_substrings << IF >> {
}

repo.RepoObjectProperty_from_sql_modules_definition <.. repo.usp_RepoObjectProperty_collect
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObjectProperty_from_sql_modules_definition
tool.ftv_extract_substrings <.. repo.RepoObjectProperty_from_sql_modules_definition
