left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.ftv_sqlparse_with_some_children << IF >> {
}

entity repo.RepoObject_SqlModules_10_statement << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_SqlModules_20_statement_children << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity repo.RepoObject_SqlModules_21_statement_children_helper << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity repo.RepoObject_SqlModules_22_identifier_alias_AS << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  **RowNumber** : bigint
}

entity repo.RepoObject_SqlModules_23_normalized_wo_nolock << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity repo.RepoObject_SqlModules_24_IdentifierList_children << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  * **T2_json_key** : nvarchar(4000)
}

entity repo.RepoObject_SqlModules_29_1_object_is_union << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_SqlModules_29_2_object_is_GroupBy << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_SqlModules_32_ObjectClass << V >> {
  * **RepoObject_guid** : uniqueidentifier
  **class** : nvarchar(500)
}

entity repo.RepoObject_SqlModules_33_ObjectNormalized << V >> {
  * **RepoObject_guid** : uniqueidentifier
  **normalized** : nvarchar(max)
}

entity repo.RepoObject_SqlModules_41_from << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity repo.RepoObject_SqlModules_51_Identitfier << V >> {
}

entity repo.RepoObject_SqlModules_Identitfier << V >> {
}

repo.ftv_sqlparse_with_some_children <.. repo.RepoObject_SqlModules_20_statement_children
repo.ftv_sqlparse_with_some_children <.. repo.RepoObject_SqlModules_24_IdentifierList_children
repo.RepoObject_SqlModules_10_statement <.. repo.RepoObject_SqlModules_20_statement_children
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_21_statement_children_helper
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_29_1_object_is_union
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_29_2_object_is_GroupBy
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_32_ObjectClass
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_51_Identitfier
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_Identitfier
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_33_ObjectNormalized
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_22_identifier_alias_AS
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_23_normalized_wo_nolock
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_24_IdentifierList_children
repo.RepoObject_SqlModules_20_statement_children <.. repo.RepoObject_SqlModules_41_from
repo.RepoObject_SqlModules_22_identifier_alias_AS <.. repo.RepoObject_SqlModules_41_from
