left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObjectColumnProperty_ForUpdate << V >> {
}

entity docs.RepoObject_ColumnList << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity graph.RepoObjectColumn_S << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity repo.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
}

entity repo.IndexColumn_union << V >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_ColumnList << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_gross << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_reference_FirstResultSet << V >> {
}

entity repo.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : int
  **referencing_minor_id** : int
  **referenced_id** : int
  **referenced_minor_id** : int
}

entity repo.RepoObjectColumn_ReferencedList << V >> {
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_ReferencingList << V >> {
  **Referenced_guid** : uniqueidentifier
}

repo.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
repo.IndexColumn_union <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObjectColumn_reference_FirstResultSet
repo.RepoObject <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_gross <.. 
repo.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross
