left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.usp_AntoraExport_ObjectPuml << P >> {
}

entity logs.usp_ExecutionLog_insert << P >> {
}

entity repo.RepoObject_referencing_level << V >> {
  **StartingNode_guid** : uniqueidentifier
  **LastNode_guid** : uniqueidentifier
  * **referencing_level** : int
}

entity repo.RepoObject_referencing_level_T << U >> {
  **StartingNode_guid** : uniqueidentifier
  **LastNode_guid** : uniqueidentifier
  * **referencing_level** : int
}

entity repo.usp_PERSIST_RepoObject_referencing_level_T << P >> {
}

logs.usp_ExecutionLog_insert <.. docs.usp_AntoraExport_ObjectPuml
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_RepoObject_referencing_level_T
repo.RepoObject_referencing_level <.. repo.usp_PERSIST_RepoObject_referencing_level_T
repo.RepoObject_referencing_level <.. repo.RepoObject_referencing_level_T
repo.RepoObject_referencing_level_T <.. repo.usp_PERSIST_RepoObject_referencing_level_T
repo.usp_PERSIST_RepoObject_referencing_level_T <.. docs.usp_AntoraExport_ObjectPuml
