left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.type_level1type_level2type << V >> {
  **type** : nvarchar(128)
}

entity repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  * **level2type** : nvarchar(6)
  * **level2name** : nvarchar(128)
  * **property_name** : nvarchar(128)
}

entity repo.ExtendedProperty_Repo2Sys_level2_Union << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  **level2type** : nvarchar(10)
  * **level2name** : nvarchar(128)
  * **property_name** : nvarchar(128)
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity repo.RepoObjectColumnProperty << U >> {
  * **RepoObjectColumnProperty_id** : int
}

config.type_level1type_level2type <.. repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn <.. repo.ExtendedProperty_Repo2Sys_level2_Union
repo.RepoObject <.. repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
repo.RepoObjectColumn <.. repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
repo.RepoObjectColumnProperty <.. repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
