left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObject_SqlModules_61_SelectIdentifier_Union << V >> {
}

entity repo.RepoObject_SqlModules_61_SelectIdentifier_Union_T << U >> {
}

entity repo.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
}

entity repo.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
}

entity repo.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T << P >> {
}

repo.RepoObject_SqlModules_61_SelectIdentifier_Union <.. repo.RepoObject_SqlModules_61_SelectIdentifier_Union_T
repo.RepoObject_SqlModules_61_SelectIdentifier_Union <.. repo.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
repo.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. repo.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. repo.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. repo.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T
