left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.SysObject_RepoObject_via_name << V >> {
}

entity repo.usp_sync_guid_RepoObject << P >> {
}

entity repo_sys.IndexColumn_unique << V >> {
}

entity repo_sys.SysObject << V >> {
}

repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo_sys.SysObject <.. repo.usp_sync_guid_RepoObject
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
