left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.join_type << V >> {
  * **join_type** : varchar(16)
}

entity sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity sqlparse.RepoObject_SqlModules_22_identifier_alias_AS << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  **RowNumber** : bigint
}

entity sqlparse.RepoObject_SqlModules_39_object << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity sqlparse.RepoObject_SqlModules_41_from << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity sqlparse.RepoObject_SqlModules_41_from_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T << P >> {
}

config.join_type <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_22_identifier_alias_AS <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from_T <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
