= Database documentation generator

[abstract]
== Abstract

* setup Antora (one time task)
* setup sqldb-docs repository (one time per project task)
* setup Antora Playbook project (one time per project task)
* setup _optional_ additional docs repositories containing additional documentation (one time per project task)
* recurring steps
** Export files for Antora
+
.AntoraExport
====
[source,sql]
----
include::sqldb:partial$docs.usp_AntoraExport.adoc[tag=exampleusage]
----
====
+
** generate the static site
+
In the Antora Playbook project call Antora to build the local or the final site.
+
*** You can use the prepared PowerShell scripts
+
[source,powershell]
....
./local-playbook.ps1
....
+
[source,powershell]
....
./playbook.ps1
....
*** you can also use Windows bat files:
+
[source]
....
local-playbook.bat
....
+
[source]
....
playbook.bat
....

== Setup for Antora usage

https://docs.antora.org/antora/2.3/install-and-run-quickstart/[Install and Run Antora Quickstart]

https://docs.antora.org/antora/2.3/how-antora-works/[How Antora Works]

____
Antora’s default site generator handles all aspects of creating a documentation site, from fetching and aggregating to converting and arranging the content to publishing the files of the generated site.
____

We recommend using at least two git repositories, one for the documentation content, another for the playbooks and the final generated documentation.

It is a good idea to use additional docs repositories for additional manually created documentation.

=== setup sqldb-docs repository

Antora can collect the content from different repositories. So, if you want to combine the database documentation with other content, you can also distribute this content to different repositories. For example, the DataHandwerk documentation combines architecture, manual, and database documentation in a common and interlinked documentation. And we use two source repositories:

* https://github.com/DataHandwerk/DataHandwerk-docs contains manually created content like architecture, manual
* https://github.com/DataHandwerk/sqldb-docs contains automatically created content, created using xref:sqldb:docs.usp_AntoraExport.adoc[]

steps

* create a new git repository, in our case this is https://github.com/DataHandwerk/sqldb-docs
** you can also create and use local repositories
* at least one commit is required to enable Antora to use the repository
* create required folder structure +
On Windows you can use `xcopy` to copy an existing folder structure without files
+
[source]
----
xcopy C:\SourceFolder D:\TargetFolder /t /e
----
+
[source]
----
xcopy D:\Repos\GitHub\DataHandwerk\sqldb-docs D:\Repos\aaa\bbb\MyDataBase_sqldb /t /e
----
+
////
in the following steps replace "D:\Repos\GitHub\DataHandwerk\sqldb-docs" by your own folder and repository name
+
** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\attachments (optional)
** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\examples (optional)
** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\images (optional)
** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\pages
*** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\pages\index
*** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\pages\nav
*** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\pages\other (optional)
** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\partials
*** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\partials\docsnippet
*** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\partials\navlist
*** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\partials\puml
**** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\partials\puml\entity_0_30_objectref
**** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\partials\puml\entity_1_1_colref
**** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\partials\puml\entity_1_1_fk
**** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\partials\puml\entity_1_1_objectref
**** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\partials\puml\entity_30_0_objectref
////
* create the Antora navigation file +
You can copy an existing file (and adapt if required)
** D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\nav.adoc
** file content (Remove the `/` at the beginning of the line before the `include`.)
+
....
/include::partial$navlist/nav-by-schema.adoc[]
* xref:index/IndexSemanticGroup.adoc[]
....
* update the parameter 'Adoc_AntoraDocModulFolder'
====
[source,sql]
----
--keep the "\" at the end of the Parameter_value!
Update
    [config].[Parameter]
Set
    [Parameter_value] = 'D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\'
Where
    [Parameter_name]  = 'Adoc_AntoraDocModulFolder'
    And sub_Parameter = '';
----
====
* your source repositories should contain a file `antora.yml` in the same folder, where the folder `modules` is located. Read about `antora.yml` in https://docs.antora.org/antora/2.3/component-version-descriptor/
+
In DataHandwerk We use two (2) docs source repositories, and we need the `antora.yml` in each source repository. The `title` should be contained only in the main `antora.yml`.
+
The DataHandwerk content of `"D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\antora.yml"` is
+
====
[source,yaml]
....
name: dhw <1>
# title: DataHandwerk <2>
version: 0.1.0 <3>
# nav:
# - modules/sqldb/nav.adoc <4>
....
<1> use the same project name in all `antora.yml`
<2> don't define a title here, but define it only once in the main `antora.yml`
<3> use the same version(s) to get a consistent documentation
<4> don't include the `sqldb` navigation file here, but use the main `antora.yml` to define the whole navigation in one place!
====

=== setup additional docs source repository

DataHandwerk `sqldb-docs` contains only automatically generated documentation. Additional manual documentation is located in an additional repository `DataHandwerk-docs`

you can use xcopy to get a folder structure to start your own documentation: +
[source]
----
xcopy D:\Repos\GitHub\DataHandwerk\DataHandwerk-docs D:\Repos\aaa\bbb\MyDataBase-docs /t /e
----

DataHandwerk main `antora.yml` is located in `D:\Repos\GitHub\DataHandwerk\DataHandwerk-docs\docs` and has this content

====
[source,yaml]
....
name: dhw <1>
title: DataHandwerk
version: 0.1.0
nav: <2>
- modules/ROOT/nav.adoc
- modules/arc/nav.adoc
- modules/sqldb/nav.adoc <3>
- modules/manual/nav.adoc
....
<1> this project name is used in the playbooks
<2> 4 navigation files for 4 modules are included
<3> include the navigation file for `sqldb` module in the main `antora.yml`
====

You could copy this file and modify.

=== setup Antora Playbook project

learn about https://docs.antora.org/antora/2.3/playbook/[the Antora Playbook]

____
An Antora playbook makes it easy for technical writers to control what content is included in your site, what user interface (UI) is applied to it, and where the site is published using a playbook file. The settings in the playbook file, in combination with CLI options and environment variables, tell Antora how to operate.
____

____
A playbook is usually located in a playbook project. A playbook project repository is responsible for generating a documentation site. It’s strictly a _configuration as code_ repository—​it does not contain any content. Instead, it contains a playbook file, and, in certain situations, supplemental UI files and extension code.
____

Create a new project folder, for example
`D:\Repos\aaa\bbb\MyProject-site`

Copy some files and folders from the DataHandwerk project and adapt them:

* `supplemental-ui` (Folder)
* local-playbook.bat
* local-playbook.ps1
* local-playbook.yml
* playbook.bat
* playbook.ps1
* playbook.yml
* local-playbook-validate.ps1
* .gitignore


DataHandwerk documentation uses the following Playbook project: https://github.com/DataHandwerk/datahandwerk.github.io +
It is also the output for the generated documentation.

Some content explained:

* two (2) playbooks are included, one to create local output, one to create the final site.
** They are different in the output folder.
** they are different in the `kroki-fetch-diagram: true` option. It takes a lot of time to generate all diagrams and this option is used only to create the final site.
** They could be also different in sources for testing
+
====
[source,yaml]
....
site:
  title: DataHandwerk Docs
  url: https://DataHandwerk.github.io
  start_page: dhw::index.adoc <1>
  # start_page: dhw:arc:architecture.adoc
  keys:
    google_analytics: 'G-abcdefghij'
content:
  sources:
  - url: D:\Repos\GitHub\DataHandwerk\DataHandwerk-docs
    branches: HEAD
    start_path: docs
  - url: D:\Repos\GitHub\DataHandwerk\sqldb-docs
    branches: HEAD
    start_path: docs
asciidoc:
  attributes:
    page-pagination: ''
    experimental: ''
    :plantuml-server-url: http://www.plantuml.com/plantuml
    # You can use the kroki-fetch-diagram option to download the images from Kroki at build time. In other words, while viewing pages you won't rely on Kroki anymore.
    # However, in Antora, this is not currently compatible with inline SVG images.
    # kroki-fetch-diagram: true <3>
  extensions:
  - asciidoctor-kroki <2>
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui <5>
output:
  clean: true
  dir: ./local <4>
urls:
  redirect_facility: static
runtime:
  fetch: true <6>
....
<1> in case you have only the database documentation you need to set the `start_page` to some page in your module (for example 'myproject:sqldb:dbo.MyTable.adoc'). 'dhw' or 'myproject' is the project name defined in the `antora.yml`
<2> required to render diagrams
<3> kroki-fetch-diagram is required for the final site, but it takes a lot of time and should be disabled if you want to check the results locally. Keep in mind that some big diagrams will not be shown if this option is disabled, but they will be rendered for the final site if enabled
<4> put the output dir for the local playbook into `.gitignore` to exclude from version control
<5> the antora-ui-default needs to be adapted a bit to show your own menu content
<6> force source repository fetch in General instead of using it every time in the antora command
====
* the ".gitignore" file should contain some entries to avoid committing some content into the repository.
+
====
....
/local <1>
node_modules
npm
.idea
package-lock.json
build
....
====
<1> exclude the site generated from the local-target playbook from source control
* D:\Repos\GitHub\DataHandwerk\datahandwerk.github.io\supplemental-ui\partials\header-content.hbs +
contains the customer menu and customer search. It overwrites the default in antora-ui-default
* some scripts to simplify the call of Antora (optional)
** local-playbook.ps1
+
[source,powershell]
....
antora --fetch local-playbook.yml
....
** local-playbook-validate.ps1
+
[source,powershell]
....
antora --generator @antora/xref-validator local-playbook.yml
....
+
https://gitlab.com/antora/xref-validator/
+
`$ npm install -g gitlab:antora/xref-validator`
** playbook.ps1
+
[source,powershell]
....
antora --fetch playbook.yml
New-Item .\docs\.nojekyll -ItemType file -Force <1>
....
<1> the file `.nojekyll` needs to be created if the site should be published as GitHub page. See: https://docs.antora.org/antora/2.3/publish-to-github-pages/#nojekyll
** playbook.bat
+
[source]
....
antora --fetch playbook.yml
copy /y NUL .\docs\.nojekyll <1>
....
<1> the file `.nojekyll` needs to be created if the site should be published as GitHub page. See: https://docs.antora.org/antora/2.3/publish-to-github-pages/#nojekyll

== Export files for Antora

include::sqldb:partial$docs.usp_AntoraExport.adoc[tag=ms_description]

.Usage
====
[source,sql]
----
include::sqldb:partial$docs.usp_AntoraExport.adoc[tag=exampleusage]
----
====

== generate the static site

NOTE: The parameter 'dwh_readonly' is 0 by default. +
No guid will be written as extended properties into the connected DWH database. This parameter should and can remain 0 if a database should only be documented but not modified.

IMPORTANT: Antora uses git repositories as sources. You must put the source repositories under Git version control, there must be at least one commit.

IMPORTANT: Antora Export will not delete any content. After Antora Export and before creating the site you should check the `D:\Repos\GitHub\DataHandwerk\sqldb-docs\docs\modules\sqldb\pages` for outdated files and delete them to avoid them to be generated. Just sort the folder by file creation date. +
You can also clean up the partials. This is not so important, because these files are only used when they are included into the pages.

export the automated documentation
[source,sql]
----
--initial setup
Exec repo.usp_main;

--use the sqlparser
--...
--after using the sqlparser persist the results

Exec sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T;
Exec sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T;

--process the sqlparser results
Exec repo.usp_main;

--import extended properties from source database into repository
Exec [property].[usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate]

--export files for automated documentation
Exec docs.usp_AntoraExport

----



In the Antora Playbook project call Antora to build the local or the final site.

* You can use the prepared PowerShell scripts
+
[source,powershell]
....
./local-playbook.ps1
....
+
[source,powershell]
....
./playbook.ps1
....
* you can also use Windows bat files:
+
[source]
....
local-playbook.bat
....
+
[source]
....
playbook.bat
....


The result is a static site. You can browse the content locally on the PC where you created the documentation.

If you want to publish the site as GitHub page, you need to create `.nojekyll`: https://docs.antora.org/antora/2.3/publish-to-github-pages/#nojekyll

=== use local PlantUML Server

It is possible to use a local PlantUML server.

https://plantuml.com/server

https://sourceforge.net/projects/plantuml/ +
here you can download a plantuml.war file to be used in a local webserver lice tomcat.

// tag::to-do[]
// end::to-do[]
