= SqlParser.py

// tag::shortdescription[]
The Python project https://pypi.org/project/sqlparse/[sqlparse] will be used, to extract column references from database views sql code.

A pyhton script `SqlParser.py` was created

* to read sql_modules_definition
* to write the parsed view definition back into the repository database
// end::shortdescription[]

== usage

The Python Script `SqlParser.py` can be executed with parameters or with an ini-file (default is SqlParser.ini in the same directory). +
2 parameters are required:

* server
* database

When you are in the folder, where the script is located, for example here
====
D:\Repos\GitHub\DataHandwerk\DataHandwerk-toolkit-mssql\python\SqlParser\
====

and the `SqlParser.ini` contains your server and database, then you can just call the script:

====
`py sqlparser.py`
====

or you can use paramaters:

====
`py sqlparser.py --server localhost\sql2019 --database dhw_master`
====

In case _Python is not installed on your PC_ the generated *windows executable* can be used

====
```
D:\Repos\GitHub\DataHandwerk\DataHandwerk-toolkit-mssql\python\SqlParser\dist\SqlParser>SqlParser.exe
usage: SqlParser.exe [-h] --server SERVER --database DATABASE [-c MY_CONFIG] [-v]
SqlParser.exe: error: the following arguments are required: --server, --database
```
====

example, when you are in the folder, where the `SqlParser.exe` is located:

====
`SqlParser --server localhost\sql2019 --database dhw_master`
====

====
`SqlParser --server localhost\sql2019 --database dhw_self`
====

== what does it do

The folowing query is used to read the [sql_modules_definition] for views, but only in case it was changed since last parsing

```sql
SELECT
    [RepoObject_guid]
    , [sql_modules_definition]
FROM
    [sqlparse].[RepoObject_SqlModules_Repo_Sys]
WHERE
    is_outdated = 1
    AND sysobject_type = 'V'
```

the sqlparse results are written into [sqlparse].[RepoObject_SqlModules]

```sql
INSERT INTO [sqlparse].[RepoObject_SqlModules]
([RepoObject_guid]
,[sql_modules_formatted]
,[sql_modules_formatted2]
,[sql_modules_json])
VALUES
(?, ?, ?, ?)
```

== How to freeze the script (create exe executable)

Instruction for the developer, when the script changes.

https://pyinstaller.readthedocs.io/en/stable/usage.html

call this from the folder, where `SqlParser.py` is located:

`pyinstaller SqlParser.py`

this will create one-folder-executable in `.\dist\SqlParser`

It is also possible to create a onefile-executable, but the "Bundling to One Folder" has some advantages (read the usage documentation for pyinstaller)

`pyinstaller --onefile --windowed SqlParser.py`
