'Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity workflow.ProcedureDependency << U >> {
  * **id** : int
}

entity config.fs_dwh_database_name << FN >> {
}

entity config.fs_get_parameter_value << FN >> {
}

entity config.ftv_dwh_database << IF >> {
}

entity config.ftv_get_parameter_value << IF >> {
}

entity config.join_type << V >> {
  * **join_type** : varchar(16)
}

entity config.Parameter << U >> {
  * **Parameter_name** : varchar(100)
  * **sub_Parameter** : nvarchar(128)
}

entity config.spt_values << U >> {
}

entity config.type << V >> {
  **type** : nvarchar(128)
}

entity config.type_level1type_level2type << V >> {
  **type** : nvarchar(128)
}

entity graph.Index << U >> {
}

entity graph.Index_S << V >> {
  * **Index_guid** : uniqueidentifier
}

entity graph.ReferencedObject << U >> {
}

entity graph.ReferencedObjectColumn << U >> {
}

entity graph.ReferencingObject << U >> {
}

entity graph.ReferencingObjectColumn << U >> {
}

entity graph.RepoObject << U >> {
}

entity graph.RepoObject_ReferencingReferenced << V >> {
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity graph.RepoObject_S << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity graph.RepoObjectColumn << U >> {
}

entity graph.RepoObjectColumn_ReferencingReferenced << V >> {
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity graph.RepoObjectColumn_S << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity graph.usp_PERSIST_Index << P >> {
}

entity graph.usp_PERSIST_RepoObject << P >> {
}

entity graph.usp_PERSIST_RepoObjectColumn << P >> {
}

entity logs.ExecutionLog << U >> {
  * **id** : bigint
}

entity logs.usp_ExecutionLog_insert << P >> {
}

entity repo.ForeignKey_Indexes << V >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_IndexPattern << V >> {
  * **constraint_object_id** : int
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_virtual << U >> {
  * **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_virtual_Indexes << V >> {
  * **ForeignKey_guid** : uniqueidentifier
}

entity repo.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
}

entity repo.fs_get_RepoObjectProperty_nvarchar << FN >> {
}

entity repo.ftv_query_plan_extract_source << IF >> {
}

entity repo.Index_ColumList << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_gross << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Index_IndexPattern << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.Index_Settings << U >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Index_union << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_unique_IndexPatternColumnGuid << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_virtual << U >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Index_virtual_ForUpdate << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Index_virtual_IndexPatternColumnGuid << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  **RowNumberInReferencing** : bigint
}

entity repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  **RowNumberInReferencing** : bigint
}

entity repo.IndexColumn_union << V >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
}

entity repo.IndexColumn_virtual << U >> {
  * **index_guid** : uniqueidentifier
  * **index_column_id** : int
}

entity repo.IndexColumn_virtual_gross << V >> {
  * **index_column_id** : int
}

entity repo.IndexColumn_virtual_referenced_setpoint << V >> {
  * **index_guid** : uniqueidentifier
  * **index_column_id** : int
}

entity repo.IndexReferencedReferencing << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.Match_RepoObject_referenced_UspPersistence << V >> {
  **FirstNode** : uniqueidentifier
  **LastNode** : uniqueidentifier
}

entity repo.PropertyName_RepoObject << V >> {
  * **property_name** : nvarchar(128)
}

entity repo.PropertyName_RepoObjectColumn << V >> {
  * **property_name** : nvarchar(128)
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_ColumnList << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_Inheritance_temp << U >> {
}

entity repo.RepoObject_persistence << U >> {
  * **target_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_QueryPlan << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  * **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_ReferencedList << V >> {
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObject_ReferencingList << V >> {
  **Referenced_guid** : uniqueidentifier
}

entity repo.RepoObject_RequiredRepoObjectMerge << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **ro2_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_gross << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_HistValidColums_setpoint << V >> {
  * **RepoObject_guid** : uniqueidentifier
  **RepoObjectColumn_name** : sysname
}

entity repo.RepoObjectColumn_Inheritance_temp << U >> {
}

entity repo.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : int
  **referencing_minor_id** : int
  **referenced_id** : int
  **referenced_minor_id** : int
}

entity repo.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : int
  **referencing_minor_id** : int
  **referenced_id** : int
  **referenced_minor_id** : int
}

entity repo.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  * **referencing_id** : int
  * **referencing_minor_id** : int
  **referenced_id** : int
  * **referenced_minor_id** : int
}

entity repo.RepoObjectColumn_reference_SqlModules << V >> {
  **referencing_id** : int
  **referencing_minor_id** : int
  **referenced_id** : int
  **referenced_minor_id** : int
}

entity repo.RepoObjectColumn_reference_union << V >> {
}

entity repo.RepoObjectColumn_ReferencedList << V >> {
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_ReferencingList << V >> {
  **Referenced_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_RequiredRepoObjectColumnMerge << V >> {
}

entity repo.RepoObjectColumnProperty << U >> {
  * **RepoObjectColumnProperty_id** : int
}

entity repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
}

entity repo.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
}

entity repo.RepoObjectProperty << U >> {
  * **RepoObjectProperty_id** : int
}

entity repo.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **property_name** : nvarchar(128)
}

entity repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
}

entity repo.RepoObjectSource_FirstResultSet << U >> {
  * **RepoObject_guid** : uniqueidentifier
  * **column_ordinal** : int
}

entity repo.RepoObjectSource_QueryPlan << U >> {
}

entity repo.SysColumn_RepoObjectColumn_via_guid << V >> {
}

entity repo.SysColumn_RepoObjectColumn_via_name << V >> {
}

entity repo.SysObject_RepoObject_via_guid << V >> {
}

entity repo.SysObject_RepoObject_via_name << V >> {
}

entity repo.SysObjectColumn_QueryPlanExpression << V >> {
}

entity repo.usp_Index_finish << P >> {
}

entity repo.usp_Index_ForeignKey << P >> {
}

entity repo.usp_index_inheritance << P >> {
}

entity repo.usp_Index_Settings << P >> {
}

entity repo.usp_Index_virtual_set << P >> {
}

entity repo.usp_main << P >> {
}

entity repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
}

entity repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
}

entity repo.usp_RepoObject_Inheritance << P >> {
}

entity repo.usp_RepoObject_update_SysObjectQueryPlan << P >> {
}

entity repo.usp_RepoObjectColumn_Inheritance << P >> {
}

entity repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
}

entity repo.usp_RepoObjectSource_FirstResultSet << P >> {
}

entity repo.usp_RepoObjectSource_QueryPlan << P >> {
}

entity repo.usp_sync_guid << P >> {
}

entity repo.usp_sync_guid_RepoObject << P >> {
}

entity repo.usp_sync_guid_RepoObjectColumn << P >> {
}

entity repo.usp_update_Referencing_Count << P >> {
}

entity repo_sys.ExtendedProperties << V >> {
}

entity repo_sys.ForeignKey << V >> {
}

entity repo_sys.ForeignKeyColumn << V >> {
}

entity repo_sys.Index_unique << V >> {
}

entity repo_sys.IndexColumn_unique << V >> {
}

entity repo_sys.RepoObjectReferenced << V >> {
}

entity repo_sys.RepoObjectReferencing << V >> {
}

entity repo_sys.sql_expression_dependencies << V >> {
}

entity repo_sys.SysColumn << V >> {
}

entity repo_sys.SysObject << V >> {
}

entity repo_sys.usp_AddOrUpdateExtendedProperty << P >> {
}

entity sqlparse.ftv_sqlparse << IF >> {
}

entity sqlparse.ftv_sqlparse_children_pivot << IF >> {
}

entity sqlparse.ftv_sqlparse_with_some_children << IF >> {
}

entity sqlparse.RepoObject_SqlModules << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity sqlparse.RepoObject_SqlModules_10_statement << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity sqlparse.RepoObject_SqlModules_21_statement_children_helper << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity sqlparse.RepoObject_SqlModules_22_identifier_alias_AS << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  **RowNumber** : bigint
}

entity sqlparse.RepoObject_SqlModules_24_IdentifierList_children << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  * **T2_json_key** : nvarchar(4000)
}

entity sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  * **T2_json_key** : nvarchar(4000)
}

entity sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  * **T2_json_key** : nvarchar(4000)
}

entity sqlparse.RepoObject_SqlModules_29_1_object_is_union << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity sqlparse.RepoObject_SqlModules_31_object << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity sqlparse.RepoObject_SqlModules_32_ObjectClass << V >> {
  * **RepoObject_guid** : uniqueidentifier
  **class** : nvarchar(500)
}

entity sqlparse.RepoObject_SqlModules_33_ObjectNormalized << V >> {
  * **RepoObject_guid** : uniqueidentifier
  **normalized** : nvarchar(max)
}

entity sqlparse.RepoObject_SqlModules_39_object << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity sqlparse.RepoObject_SqlModules_41_from << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity sqlparse.RepoObject_SqlModules_41_from_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
}

entity sqlparse.RepoObject_SqlModules_42_from_Identifier << V >> {
}

entity sqlparse.RepoObject_SqlModules_43_from_Identifier << V >> {
}

entity sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName << V >> {
}

entity sqlparse.RepoObject_SqlModules_51_Identitfier << V >> {
}

entity sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName << V >> {
}

entity sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union << V >> {
}

entity sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T << U >> {
}

entity sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
}

entity sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
}

entity sqlparse.RepoObject_SqlModules_79_reference_union << V >> {
}

entity sqlparse.RepoObject_SqlModules_Repo_Sys << V >> {
}

entity sys_dwh.columns << SN >> {
}

entity sys_dwh.computed_columns << SN >> {
}

entity sys_dwh.default_constraints << SN >> {
}

entity sys_dwh.dm_sql_referenced_entities << SN >> {
}

entity sys_dwh.extended_properties << SN >> {
}

entity sys_dwh.foreign_key_columns << SN >> {
}

entity sys_dwh.foreign_keys << SN >> {
}

entity sys_dwh.identity_columns << SN >> {
}

entity sys_dwh.index_columns << SN >> {
}

entity sys_dwh.indexes << SN >> {
}

entity sys_dwh.objects << SN >> {
}

entity sys_dwh.parameters << SN >> {
}

entity sys_dwh.schemas << SN >> {
}

entity sys_dwh.sql_expression_dependencies << SN >> {
}

entity sys_dwh.sql_modules << SN >> {
}

entity sys_dwh.tables << SN >> {
}

entity sys_dwh.types << SN >> {
}

entity uspgenerator.GeneratorUsp << U >> {
  * **id** : int
}

entity uspgenerator.GeneratorUspStep << U >> {
  * **id** : int
}

entity uspgenerator.GeneratorUspStep_Persistence << V >> {
  * **usp_id** : int
}

entity uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint << V >> {
  * **usp_id** : int
}

entity uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
}

 <.. repo.usp_main
config.fs_dwh_database_name <.. repo_sys.usp_AddOrUpdateExtendedProperty
config.fs_get_parameter_value <.. repo.usp_main
config.fs_get_parameter_value <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
config.ftv_dwh_database <.. repo.usp_update_Referencing_Count
config.ftv_dwh_database <.. repo.RepoObjectColumn_reference_QueryPlan
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.ftv_dwh_database <.. repo_sys.SysColumn
config.ftv_dwh_database <.. repo_sys.sql_expression_dependencies
config.ftv_get_parameter_value <.. repo.RepoObjectColumn_HistValidColums_setpoint
config.join_type <.. sqlparse.RepoObject_SqlModules_41_from
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. config.fs_dwh_database_name
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. repo.PropertyName_RepoObject
config.Parameter <.. repo.PropertyName_RepoObjectColumn
config.Parameter <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
config.spt_values <.. config.type
config.type <.. config.type_level1type_level2type
config.type <.. repo.RepoObject_gross
config.type_level1type_level2type <.. repo.usp_sync_guid_RepoObjectColumn
config.type_level1type_level2type <.. repo.usp_sync_guid_RepoObject
graph.Index <.. graph.usp_PERSIST_Index
graph.Index_S <.. graph.usp_PERSIST_Index
graph.Index_S <.. graph.Index
graph.ReferencedObject <.. graph.RepoObject_ReferencingReferenced
graph.ReferencedObject <.. repo.Match_RepoObject_referenced_UspPersistence
graph.ReferencedObject <.. repo.usp_main
graph.ReferencedObjectColumn <.. repo.usp_main
graph.ReferencedObjectColumn <.. graph.RepoObjectColumn_ReferencingReferenced
graph.ReferencingObject <.. repo.usp_main
graph.ReferencingObjectColumn <.. repo.usp_main
graph.RepoObject <.. repo.usp_main
graph.RepoObject <.. repo.usp_sync_guid_RepoObject
graph.RepoObject <.. graph.RepoObject_ReferencingReferenced
graph.RepoObject <.. graph.usp_PERSIST_RepoObject
graph.RepoObject <.. repo.Match_RepoObject_referenced_UspPersistence
graph.RepoObject_ReferencingReferenced <.. repo.RepoObject_ReferencedList
graph.RepoObject_ReferencingReferenced <.. repo.RepoObject_ReferencingList
graph.RepoObject_ReferencingReferenced <.. repo.RepoObject_gross
graph.RepoObject_S <.. repo.usp_sync_guid_RepoObject
graph.RepoObject_S <.. graph.usp_PERSIST_RepoObject
graph.RepoObject_S <.. graph.RepoObject
graph.RepoObjectColumn <.. graph.usp_PERSIST_RepoObjectColumn
graph.RepoObjectColumn <.. graph.RepoObjectColumn_ReferencingReferenced
graph.RepoObjectColumn <.. repo.usp_main
graph.RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
graph.RepoObjectColumn_ReferencingReferenced <.. repo.RepoObjectColumn_ReferencedList
graph.RepoObjectColumn_ReferencingReferenced <.. repo.RepoObjectColumn_ReferencingList
graph.RepoObjectColumn_S <.. graph.usp_PERSIST_RepoObjectColumn
graph.RepoObjectColumn_S <.. graph.RepoObjectColumn
graph.RepoObjectColumn_S <.. repo.usp_sync_guid_RepoObjectColumn
graph.usp_PERSIST_Index <.. repo.usp_Index_finish
graph.usp_PERSIST_RepoObject <.. repo.usp_sync_guid_RepoObject
graph.usp_PERSIST_RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectSource_QueryPlan
logs.usp_ExecutionLog_insert <.. repo.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectSource_FirstResultSet
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
logs.usp_ExecutionLog_insert <.. repo.usp_Index_Settings
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObject_update_SysObjectQueryPlan
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid
logs.usp_ExecutionLog_insert <.. repo.usp_main
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject
logs.usp_ExecutionLog_insert <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
logs.usp_ExecutionLog_insert <.. repo.usp_index_inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_Index_virtual_set
logs.usp_ExecutionLog_insert <.. repo.usp_Index_ForeignKey
logs.usp_ExecutionLog_insert <.. repo.usp_Index_finish
logs.usp_ExecutionLog_insert <.. graph.usp_PERSIST_Index
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
logs.usp_ExecutionLog_insert <.. graph.usp_PERSIST_RepoObjectColumn
logs.usp_ExecutionLog_insert <.. graph.usp_PERSIST_RepoObject
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectColumn_Inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObject_Inheritance
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_IndexPattern <.. repo.ForeignKey_Indexes
repo.ForeignKey_virtual <.. repo.ForeignKey_virtual_Indexes
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
repo.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
repo.ftv_query_plan_extract_source <.. repo.usp_RepoObjectSource_QueryPlan
repo.Index_ColumList <.. repo.Index_gross
repo.Index_ColumList <.. uspgenerator.GeneratorUspStep_Persistence
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. graph.Index_S
repo.Index_IndexPattern <.. repo.usp_Index_Settings
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.Index_Settings <.. repo.Index_gross
repo.Index_Settings <.. repo.usp_Index_Settings
repo.Index_Settings <.. repo.RepoObject_gross
repo.Index_Settings <.. repo.Index_virtual_ForUpdate
repo.Index_Settings <.. repo.usp_Index_finish
repo.Index_union <.. repo.usp_Index_finish
repo.Index_union <.. repo.Index_gross
repo.Index_union <.. repo.IndexReferencedReferencing
repo.Index_unique_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual <.. repo.Index_union
repo.Index_virtual <.. repo.IndexReferencedReferencing
repo.Index_virtual <.. repo.IndexColumn_virtual_gross
repo.Index_virtual <.. repo.IndexColumn_virtual_referenced_setpoint
repo.Index_virtual <.. repo.usp_index_inheritance
repo.Index_virtual <.. repo.usp_Index_virtual_set
repo.Index_virtual <.. repo.usp_Index_finish
repo.Index_virtual <.. repo.Index_virtual_ForUpdate
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.Index_virtual_IndexPatternColumnGuid <.. repo.usp_index_inheritance
repo.Index_virtual_IndexPatternColumnGuid <.. repo.Index_union
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_union <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_union <.. repo.Index_IndexPattern
repo.IndexColumn_union <.. repo.Index_ColumList
repo.IndexColumn_union <.. repo.RepoObjectColumn_gross
repo.IndexColumn_virtual <.. repo.IndexColumn_virtual_gross
repo.IndexColumn_virtual <.. repo.usp_index_inheritance
repo.IndexColumn_virtual <.. repo.usp_Index_virtual_set
repo.IndexColumn_virtual <.. repo.usp_sync_guid_RepoObjectColumn
repo.IndexColumn_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.IndexColumn_virtual <.. repo.usp_Index_finish
repo.IndexColumn_virtual_gross <.. repo.IndexColumn_union
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.Match_RepoObject_referenced_UspPersistence <.. repo.usp_main
repo.PropertyName_RepoObject <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.PropertyName_RepoObjectColumn <.. repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
repo.RepoObject <.. repo_sys.ForeignKey
repo.RepoObject <.. repo.usp_Index_finish
repo.RepoObject <.. repo.Index_virtual_ForUpdate
repo.RepoObject <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObject <.. repo.RepoObject_RequiredRepoObjectMerge
repo.RepoObject <.. repo.RepoObjectColumn_reference_SqlModules
repo.RepoObject <.. graph.RepoObject_S
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObject <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject <.. repo.usp_Index_virtual_set
repo.RepoObject <.. repo.usp_sync_guid_RepoObject
repo.RepoObject <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObject <.. repo.usp_update_Referencing_Count
repo.RepoObject <.. repo.usp_RepoObjectSource_FirstResultSet
repo.RepoObject <.. repo.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.SysObject_RepoObject_via_guid
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObject <.. repo.IndexColumn_virtual_gross
repo.RepoObject <.. repo_sys.RepoObjectReferenced
repo.RepoObject <.. repo_sys.RepoObjectReferencing
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_Repo_Sys
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo_sys.Index_unique
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_39_object
repo.RepoObject <.. repo.RepoObjectColumn_reference_Persistence
repo.RepoObject <.. repo.RepoObject_reference_persistence
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_10_statement
repo.RepoObject_ColumnList <.. repo.RepoObject_gross
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
repo.RepoObject_gross <.. repo.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. repo.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObject_gross <.. repo.Match_RepoObject_referenced_UspPersistence
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_Inheritance_temp <.. repo.usp_RepoObject_Inheritance
repo.RepoObject_persistence <.. repo.usp_Index_finish
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObject
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence <.. repo.RepoObject_gross
repo.RepoObject_persistence <.. repo.RepoObject_reference_persistence
repo.RepoObject_persistence <.. repo.RepoObjectColumn_reference_Persistence
repo.RepoObject_persistence <.. repo.RepoObjectColumn_HistValidColums_setpoint
repo.RepoObject_QueryPlan <.. repo.RepoObject_gross
repo.RepoObject_QueryPlan <.. repo.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_reference_persistence <.. repo.RepoObject_reference_union
repo.RepoObject_reference_SqlExpressionDependencies <.. repo.RepoObject_reference_union
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_SqlExpressionDependencies
repo.RepoObject_reference_union <.. repo.IndexReferencedReferencing
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObject_reference_union <.. repo.usp_main
repo.RepoObject_ReferencedList <.. repo.RepoObject_gross
repo.RepoObject_ReferencingList <.. repo.RepoObject_gross
repo.RepoObject_RequiredRepoObjectMerge <.. repo.usp_sync_guid_RepoObject
repo.RepoObjectColumn <.. repo.usp_Index_virtual_set
repo.RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.RepoObjectColumn <.. repo.usp_update_Referencing_Count
repo.RepoObjectColumn <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObjectColumn <.. repo.RepoObjectColumn_RequiredRepoObjectColumnMerge
repo.RepoObjectColumn <.. repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectColumn <.. repo.RepoObjectColumn_reference_SqlModules
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObjectColumn <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. repo.IndexColumn_virtual_gross
repo.RepoObjectColumn <.. repo.RepoObjectColumn_reference_Persistence
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_HistValidColums_setpoint <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_Inheritance_temp <.. repo.usp_RepoObjectColumn_Inheritance
repo.RepoObjectColumn_reference_Persistence <.. repo.RepoObjectColumn_reference_union
repo.RepoObjectColumn_reference_QueryPlan <.. repo.SysObjectColumn_QueryPlanExpression
repo.RepoObjectColumn_reference_SqlExpressionDependencies <.. repo.RepoObjectColumn_reference_union
repo.RepoObjectColumn_reference_SqlModules <.. repo.RepoObjectColumn_reference_union
repo.RepoObjectColumn_reference_union <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.RepoObjectColumn_reference_union <.. repo.usp_main
repo.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_RequiredRepoObjectColumnMerge <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumnProperty <.. repo.usp_RepoObjectColumn_Inheritance
repo.RepoObjectColumnProperty <.. repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectColumnProperty <.. repo.PropertyName_RepoObjectColumn
repo.RepoObjectColumnProperty <.. repo.fs_get_RepoObjectColumnProperty_nvarchar
repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition <.. repo.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition
repo.RepoObjectColumnProperty_InheritanceType_resulting_InheritanceDefinition <.. repo.usp_RepoObjectColumn_Inheritance
repo.RepoObjectProperty <.. repo.usp_RepoObject_Inheritance
repo.RepoObjectProperty <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectProperty <.. repo.PropertyName_RepoObject
repo.RepoObjectProperty <.. repo.fs_get_RepoObjectProperty_nvarchar
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition <.. repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition
repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition <.. repo.usp_RepoObject_Inheritance
repo.RepoObjectSource_FirstResultSet <.. repo.usp_RepoObjectSource_FirstResultSet
repo.RepoObjectSource_QueryPlan <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObjectSource_QueryPlan <.. repo.RepoObjectColumn_reference_QueryPlan
repo.SysColumn_RepoObjectColumn_via_guid <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_guid <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo.SysObjectColumn_QueryPlanExpression <.. repo.usp_RepoObjectSource_QueryPlan
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_RepoObject_Inheritance <.. repo.usp_main
repo.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
repo.usp_RepoObjectColumn_Inheritance <.. repo.usp_main
repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id <.. repo.usp_main
repo.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
repo.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoObject <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo.usp_update_Referencing_Count <.. repo.usp_main
repo_sys.ExtendedProperties <.. repo_sys.SysColumn
repo_sys.ExtendedProperties <.. repo_sys.SysObject
repo_sys.ForeignKey <.. repo_sys.ForeignKeyColumn
repo_sys.ForeignKey <.. repo.ForeignKey_IndexPattern
repo_sys.ForeignKeyColumn <.. repo.ForeignKey_IndexPattern
repo_sys.Index_unique <.. repo.Index_union
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.IndexColumn_unique <.. repo.Index_unique_IndexPatternColumnGuid
repo_sys.RepoObjectReferenced <.. repo.usp_update_Referencing_Count
repo_sys.RepoObjectReferencing <.. repo.usp_update_Referencing_Count
repo_sys.sql_expression_dependencies <.. repo.RepoObjectColumn_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. repo.RepoObject_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo_sys.sql_expression_dependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.SysColumn <.. repo_sys.ForeignKeyColumn
repo_sys.SysObject <.. repo.usp_sync_guid_RepoObject
repo_sys.SysObject <.. repo_sys.SysColumn
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_guid
repo_sys.SysObject <.. repo_sys.sql_expression_dependencies
repo_sys.SysObject <.. sqlparse.RepoObject_SqlModules_Repo_Sys
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoObject
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoObjectColumn
sqlparse.ftv_sqlparse <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.ftv_sqlparse_children_pivot <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.ftv_sqlparse_with_some_children <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_10_statement
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules <.. sqlparse.RepoObject_SqlModules_Repo_Sys
sqlparse.RepoObject_SqlModules_10_statement <.. sqlparse.RepoObject_SqlModules_20_statement_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_21_statement_children_helper
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_1_object_is_union
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_32_ObjectClass
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_33_ObjectNormalized
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_24_IdentifierList_children
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_51_Identitfier
sqlparse.RepoObject_SqlModules_21_statement_children_helper <.. sqlparse.RepoObject_SqlModules_31_object
sqlparse.RepoObject_SqlModules_22_identifier_alias_AS <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_24_IdentifierList_children <.. sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit
sqlparse.RepoObject_SqlModules_25_IdentifierList_children_IdentifierSplit <.. sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName
sqlparse.RepoObject_SqlModules_26_IdentifierList_children_IdentifierSplit_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_29_1_object_is_union <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_29_2_object_is_GroupBy <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_31_object <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_32_ObjectClass <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_33_ObjectNormalized <.. sqlparse.RepoObject_SqlModules_39_object
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_39_object <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from_T <.. sqlparse.RepoObject_SqlModules_42_from_Identifier
sqlparse.RepoObject_SqlModules_42_from_Identifier <.. sqlparse.RepoObject_SqlModules_43_from_Identifier
sqlparse.RepoObject_SqlModules_43_from_Identifier <.. sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_44_from_Identifier_QuoteName <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_51_Identitfier <.. sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName
sqlparse.RepoObject_SqlModules_52_Identitfier_QuoteName <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union <.. sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
sqlparse.RepoObject_SqlModules_61_SelectIdentifier_Union_T <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias <.. sqlparse.RepoObject_SqlModules_79_reference_union
sqlparse.RepoObject_SqlModules_79_reference_union <.. repo.RepoObjectColumn_reference_SqlModules
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_gross
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.columns <.. repo_sys.SysColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
sys_dwh.default_constraints <.. repo_sys.SysColumn
sys_dwh.dm_sql_referenced_entities <.. repo_sys.RepoObjectReferenced
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.foreign_key_columns <.. repo_sys.ForeignKeyColumn
sys_dwh.foreign_keys <.. repo_sys.ForeignKey
sys_dwh.identity_columns <.. repo_sys.SysColumn
sys_dwh.index_columns <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.Index_unique
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.SysObject
sys_dwh.parameters <.. repo_sys.ExtendedProperties
sys_dwh.schemas <.. repo_sys.SysObject
sys_dwh.sql_expression_dependencies <.. repo_sys.sql_expression_dependencies
sys_dwh.sql_modules <.. repo_sys.SysObject
sys_dwh.tables <.. repo_sys.SysObject
sys_dwh.types <.. repo_sys.SysColumn
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUspStep_Persistence
uspgenerator.GeneratorUsp <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
uspgenerator.GeneratorUsp <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
