'Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.ftv_dwh_database << IF >> {
}

entity config.Parameter << U >> {
  * **Parameter_name** : varchar(100)
  * **sub_Parameter** : nvarchar(128)
}

entity logs.ExecutionLog << U >> {
  * **id** : bigint
}

entity logs.usp_ExecutionLog_insert << P >> {
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity repo.usp_update_Referencing_Count << P >> {
}

entity repo_sys.RepoObjectReferenced << V >> {
}

entity repo_sys.RepoObjectReferencing << V >> {
}

entity sys_dwh.dm_sql_referenced_entities << SN >> {
}

config.ftv_dwh_database <.. repo.usp_update_Referencing_Count
config.Parameter <.. config.ftv_dwh_database
logs.ExecutionLog <.. logs.usp_ExecutionLog_insert
logs.usp_ExecutionLog_insert <.. repo.usp_update_Referencing_Count
repo.RepoObject <.. repo.usp_update_Referencing_Count
repo.RepoObject <.. repo_sys.RepoObjectReferenced
repo.RepoObject <.. repo_sys.RepoObjectReferencing
repo.RepoObjectColumn <.. repo.usp_update_Referencing_Count
repo_sys.RepoObjectReferenced <.. repo.usp_update_Referencing_Count
repo_sys.RepoObjectReferencing <.. repo.usp_update_Referencing_Count
sys_dwh.dm_sql_referenced_entities <.. repo_sys.RepoObjectReferenced
