'Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.fs_dwh_database_name << FN >> {
}

entity config.ftv_dwh_database << IF >> {
}

entity config.Parameter << U >> {
  * **Parameter_name** : varchar(100)
  * **sub_Parameter** : nvarchar(128)
}

entity config.spt_values << U >> {
}

entity config.type << V >> {
  **type** : nvarchar(128)
}

entity config.type_level1type_level2type << V >> {
  **type** : nvarchar(128)
}

entity repo_sys.ExtendedProperties << V >> {
}

entity repo_sys.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
}

entity repo_sys.usp_dropextendedproperty_level_1 << P >> {
}

entity sys_dwh.columns << SN >> {
}

entity sys_dwh.extended_properties << SN >> {
}

entity sys_dwh.indexes << SN >> {
}

entity sys_dwh.objects << SN >> {
}

entity sys_dwh.parameters << SN >> {
}

config.fs_dwh_database_name <.. repo_sys.usp_dropextendedproperty_level_1
config.ftv_dwh_database <.. repo_sys.ExtendedProperties
config.Parameter <.. config.fs_dwh_database_name
config.Parameter <.. config.ftv_dwh_database
config.spt_values <.. config.type
config.type <.. config.type_level1type_level2type
config.type_level1type_level2type <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
repo_sys.ExtendedProperties <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
repo_sys.ExtendedProperties_ParameterForAddUpdateDrop <.. repo_sys.usp_dropextendedproperty_level_1
sys_dwh.columns <.. repo_sys.ExtendedProperties
sys_dwh.extended_properties <.. repo_sys.ExtendedProperties
sys_dwh.indexes <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties
sys_dwh.objects <.. repo_sys.ExtendedProperties_ParameterForAddUpdateDrop
sys_dwh.parameters <.. repo_sys.ExtendedProperties
