= [config].[usp_init_spt_values]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
9590291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1794105432
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-03-28 10:32:21
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:config.spt_values.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:config.usp_connect_database.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[spt_values]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----
CREATE PROCEDURE [config].usp_init_spt_values
AS
--
TRUNCATE TABLE [config].[spt_values]

-- [noformat] don't want any formatting here, because this is created in ADS

----data script created in Azure Data Studio
--
--create table [#tempspt_values] (
--[name] [nvarchar] (35) NULL,
--[number] [int],
--[type] [nchar] (3),
--[low] [int] NULL,
--[high] [int] NULL,
--[status] [int] NULL);


insert [config].[spt_values] ([name],[number],[type],[low],[high],[status])
select 'rpc',1,'A  ',NULL,NULL,0 UNION ALL
select 'pub',2,'A  ',NULL,NULL,0 UNION ALL
select 'sub',4,'A  ',NULL,NULL,0 UNION ALL
select 'dist',8,'A  ',NULL,NULL,0 UNION ALL
select 'dpub',16,'A  ',NULL,NULL,0 UNION ALL
select 'rpc out',64,'A  ',NULL,NULL,0 UNION ALL
select 'data access',128,'A  ',NULL,NULL,0 UNION ALL
select 'collation compatible',256,'A  ',NULL,NULL,0 UNION ALL
select 'system',512,'A  ',NULL,NULL,0 UNION ALL
select 'use remote collation',1024,'A  ',NULL,NULL,0 UNION ALL
select 'lazy schema validation',2048,'A  ',NULL,NULL,0 UNION ALL
select 'remote proc transaction promotion',4096,'A  ',NULL,NULL,0 UNION ALL
select 'YES OR NO',-1,'B  ',NULL,NULL,0 UNION ALL
select 'no',0,'B  ',NULL,NULL,0 UNION ALL
select 'yes',1,'B  ',NULL,NULL,0 UNION ALL
select 'none',2,'B  ',NULL,NULL,0 UNION ALL
select 'DATABASE STATUS',0,'D  ',NULL,NULL,0 UNION ALL
select 'autoclose',1,'D  ',NULL,NULL,0 UNION ALL
select 'select into/bulkcopy',4,'D  ',NULL,NULL,0 UNION ALL
select 'trunc. log on chkpt.',8,'D  ',NULL,NULL,0 UNION ALL
select 'torn page detection',16,'D  ',NULL,NULL,0 UNION ALL
select 'loading',32,'D  ',NULL,NULL,0 UNION ALL
select 'pre recovery',64,'D  ',NULL,NULL,0 UNION ALL
select 'recovering',128,'D  ',NULL,NULL,0 UNION ALL
select 'not recovered',256,'D  ',NULL,NULL,0 UNION ALL
select 'offline',512,'D  ',0,1,0 UNION ALL
select 'read only',1024,'D  ',NULL,NULL,0 UNION ALL
select 'dbo use only',2048,'D  ',NULL,NULL,0 UNION ALL
select 'single user',4096,'D  ',NULL,NULL,0 UNION ALL
select 'emergency mode',32768,'D  ',NULL,NULL,0 UNION ALL
select 'missing files',262144,'D  ',NULL,NULL,0 UNION ALL
select 'autoshrink',4194304,'D  ',NULL,NULL,0 UNION ALL
select 'ALL SETTABLE OPTIONS',4202013,'D  ',NULL,NULL,0 UNION ALL
select 'cleanly shutdown',1073741824,'D  ',NULL,NULL,0 UNION ALL
select 'DATABASE OPTIONS',0,'D2 ',NULL,NULL,0 UNION ALL
select 'db chaining',1024,'D2 ',NULL,NULL,0 UNION ALL
select 'numeric roundabort',2048,'D2 ',NULL,NULL,0 UNION ALL
select 'arithabort',4096,'D2 ',NULL,NULL,0 UNION ALL
select 'ANSI padding',8192,'D2 ',NULL,NULL,0 UNION ALL
select 'ANSI null default',16384,'D2 ',NULL,NULL,0 UNION ALL
select 'concat null yields null',65536,'D2 ',NULL,NULL,0 UNION ALL
select 'recursive triggers',131072,'D2 ',NULL,NULL,0 UNION ALL
select 'default to local cursor',1048576,'D2 ',NULL,NULL,0 UNION ALL
select 'quoted identifier',8388608,'D2 ',NULL,NULL,0 UNION ALL
select 'auto create statistics',16777216,'D2 ',NULL,NULL,0 UNION ALL
select 'cursor close on commit',33554432,'D2 ',NULL,NULL,0 UNION ALL
select 'ANSI nulls',67108864,'D2 ',NULL,NULL,0 UNION ALL
select 'ANSI warnings',268435456,'D2 ',NULL,NULL,0 UNION ALL
select 'full text enabled',536870912,'D2 ',NULL,NULL,0 UNION ALL
select 'auto update statistics',1073741824,'D2 ',NULL,NULL,0 UNION ALL
select 'ALL SETTABLE OPTIONS',1469283328,'D2 ',NULL,NULL,0 UNION ALL
select 'DB Owners',16384,'DBR',-1,NULL,0 UNION ALL
select 'DB Access Administrators',16385,'DBR',-1,NULL,0 UNION ALL
select 'DB Security Administrators',16386,'DBR',-1,NULL,0 UNION ALL
select 'DB DDL Administrators',16387,'DBR',-1,NULL,0 UNION ALL
select 'DB Backup Operator',16389,'DBR',-1,NULL,0 UNION ALL
select 'DB Data Reader',16390,'DBR',-1,NULL,0 UNION ALL
select 'DB Data Writer',16391,'DBR',-1,NULL,0 UNION ALL
select 'DB Deny Data Reader',16392,'DBR',-1,NULL,0 UNION ALL
select 'DB Deny Data Writer',16393,'DBR',-1,NULL,0 UNION ALL
select 'DATABASE CATEGORY',0,'DC ',NULL,NULL,0 UNION ALL
select 'published',1,'DC ',NULL,NULL,0 UNION ALL
select 'subscribed',2,'DC ',NULL,NULL,0 UNION ALL
select 'merge publish',4,'DC ',NULL,NULL,0 UNION ALL
select 'ALL SETTABLE OPTIONS',7,'DC ',NULL,NULL,0 UNION ALL
select 'Distributed',16,'DC ',NULL,NULL,0 UNION ALL
select 'SQLSERVER HOST TYPE',0,'E  ',0,NULL,0 UNION ALL
select 'WINDOWS/NT',1,'E  ',8192,NULL,0 UNION ALL
select 'int high bit',2,'E  ',-2147483648,NULL,0 UNION ALL
select 'int4 high byte',3,'E  ',1,NULL,0 UNION ALL
select 'SERVER AUDIT',8257,'EOB',NULL,NULL,0 UNION ALL
select 'CHECK CONSTRAINT',8259,'EOB',NULL,NULL,0 UNION ALL
select 'DEFAULT',8260,'EOB',NULL,NULL,0 UNION ALL
select 'FOREIGN KEY CONSTRAINT',8262,'EOB',NULL,NULL,0 UNION ALL
select 'STORED PROCEDURE',8272,'EOB',NULL,NULL,0 UNION ALL
select 'RULE',8274,'EOB',NULL,NULL,0 UNION ALL
select 'TABLE',8275,'EOB',NULL,NULL,0 UNION ALL
select 'TRIGGER',8276,'EOB',NULL,NULL,0 UNION ALL
select 'TABLE',8277,'EOB',NULL,NULL,0 UNION ALL
select 'VIEW',8278,'EOB',NULL,NULL,0 UNION ALL
select 'STORED PROCEDURE',8280,'EOB',NULL,NULL,0 UNION ALL
select 'DATABASE AUDIT SPECIFICATION',16708,'EOB',NULL,NULL,0 UNION ALL
select 'SERVER AUDIT SPECIFICATION',16723,'EOB',NULL,NULL,0 UNION ALL
select 'TRIGGER',16724,'EOB',NULL,NULL,0 UNION ALL
select 'DATABASE',16964,'EOB',NULL,NULL,0 UNION ALL
select 'OBJECT',16975,'EOB',NULL,NULL,0 UNION ALL
select 'DATABASE SCOPED CREDENTIAL',17220,'EOB',NULL,NULL,0 UNION ALL
select 'EDGE CONSTRAINT',17221,'EOB',NULL,NULL,0 UNION ALL
select 'FULLTEXT CATALOG',17222,'EOB',NULL,NULL,0 UNION ALL
select 'STORED PROCEDURE',17232,'EOB',NULL,NULL,0 UNION ALL
select 'SCHEMA',17235,'EOB',NULL,NULL,0 UNION ALL
select 'CREDENTIAL',17475,'EOB',NULL,NULL,0 UNION ALL
select 'EXTERNAL DATA SOURCE',17477,'EOB',NULL,NULL,0 UNION ALL
select 'EVENT NOTIFICATION',17491,'EOB',NULL,NULL,0 UNION ALL
select 'DATABASE EVENT SESSION',17732,'EOB',NULL,NULL,0 UNION ALL
select 'EVENT SESSION',17747,'EOB',NULL,NULL,0 UNION ALL
select 'AGGREGATE',17985,'EOB',NULL,NULL,0 UNION ALL
select 'EXTERNAL FILE FORMAT',17989,'EOB',NULL,NULL,0 UNION ALL
select 'FUNCTION',17993,'EOB',NULL,NULL,0 UNION ALL
select 'PARTITION FUNCTION',18000,'EOB',NULL,NULL,0 UNION ALL
select 'STORED PROCEDURE',18002,'EOB',NULL,NULL,0 UNION ALL
select 'FUNCTION',18004,'EOB',NULL,NULL,0 UNION ALL
select 'AVAILABILITY GROUP',18241,'EOB',NULL,NULL,0 UNION ALL
select 'RESOURCE GOVERNOR',18258,'EOB',NULL,NULL,0 UNION ALL
select 'SERVER ROLE',18259,'EOB',NULL,NULL,0 UNION ALL
select 'WINDOWS GROUP',18263,'EOB',NULL,NULL,0 UNION ALL
select 'ASYMMETRIC KEY',19265,'EOB',NULL,NULL,0 UNION ALL
select 'COLUMN ENCRYPTION KEY',19267,'EOB',NULL,NULL,0 UNION ALL
select 'DATABASE ENCRYPTION KEY',19268,'EOB',NULL,NULL,0 UNION ALL
select 'MASTER KEY',19277,'EOB',NULL,NULL,0 UNION ALL
select 'PRIMARY KEY',19280,'EOB',NULL,NULL,0 UNION ALL
select 'SYMMETRIC KEY',19283,'EOB',NULL,NULL,0 UNION ALL
select 'ASYMMETRIC KEY LOGIN',19521,'EOB',NULL,NULL,0 UNION ALL
select 'CERTIFICATE LOGIN',19523,'EOB',NULL,NULL,0 UNION ALL
select 'FULLTEXT STOPLIST',19526,'EOB',NULL,NULL,0 UNION ALL
select 'EXTERNAL GROUP LOGIN',19536,'EOB',NULL,NULL,0 UNION ALL
select 'ROLE',19538,'EOB',NULL,NULL,0 UNION ALL
select 'SQL LOGIN',19539,'EOB',NULL,NULL,0 UNION ALL
select 'WINDOWS LOGIN',19543,'EOB',NULL,NULL,0 UNION ALL
select 'EXTERNAL LOGIN',19544,'EOB',NULL,NULL,0 UNION ALL
select 'COLUMN MASTER KEY',19779,'EOB',NULL,NULL,0 UNION ALL
select 'REMOTE SERVICE BINDING',20034,'EOB',NULL,NULL,0 UNION ALL
select 'EVENT NOTIFICATION',20036,'EOB',NULL,NULL,0 UNION ALL
select 'EVENT NOTIFICATION',20037,'EOB',NULL,NULL,0 UNION ALL
select 'FUNCTION',20038,'EOB',NULL,NULL,0 UNION ALL
select 'EVENT NOTIFICATION',20047,'EOB',NULL,NULL,0 UNION ALL
select 'SYNONYM',20051,'EOB',NULL,NULL,0 UNION ALL
select 'SERVER CONFIG',20291,'EOB',NULL,NULL,0 UNION ALL
select 'SEQUENCE OBJECT',20307,'EOB',NULL,NULL,0 UNION ALL
select 'CRYPTOGRAPHIC PROVIDER',20547,'EOB',NULL,NULL,0 UNION ALL
select 'ENDPOINT',20549,'EOB',NULL,NULL,0 UNION ALL
select 'SEARCH PROPERTY LIST',20550,'EOB',NULL,NULL,0 UNION ALL
select 'SECURITY POLICY',20563,'EOB',NULL,NULL,0 UNION ALL
select 'QUEUE',20819,'EOB',NULL,NULL,0 UNION ALL
select 'UNIQUE CONSTRAINT',20821,'EOB',NULL,NULL,0 UNION ALL
select 'APPLICATION ROLE',21057,'EOB',NULL,NULL,0 UNION ALL
select 'CERTIFICATE',21059,'EOB',NULL,NULL,0 UNION ALL
select 'DATABASE SCOPED RESOURCE GOVERNOR',21060,'EOB',NULL,NULL,0 UNION ALL
select 'EXTERNAL RESOURCE POOL',21061,'EOB',NULL,NULL,0 UNION ALL
select 'BROKER PRIORITY',21072,'EOB',NULL,NULL,0 UNION ALL
select 'SERVER',21075,'EOB',NULL,NULL,0 UNION ALL
select 'TRIGGER',21076,'EOB',NULL,NULL,0 UNION ALL
select 'ASSEMBLY',21313,'EOB',NULL,NULL,0 UNION ALL
select 'DATABASE SCOPED CONFIGURATION',21316,'EOB',NULL,NULL,0 UNION ALL
select 'FUNCTION',21318,'EOB',NULL,NULL,0 UNION ALL
select 'FUNCTION',21321,'EOB',NULL,NULL,0 UNION ALL
select 'PARTITION SCHEME',21328,'EOB',NULL,NULL,0 UNION ALL
select 'SQL USER',21333,'EOB',NULL,NULL,0 UNION ALL
select 'CONTRACT',21571,'EOB',NULL,NULL,0 UNION ALL
select 'TRIGGER',21572,'EOB',NULL,NULL,0 UNION ALL
select 'FUNCTION',21574,'EOB',NULL,NULL,0 UNION ALL
select 'MESSAGE TYPE',21581,'EOB',NULL,NULL,0 UNION ALL
select 'ROUTE',21586,'EOB',NULL,NULL,0 UNION ALL
select 'STATISTICS',21587,'EOB',NULL,NULL,0 UNION ALL
select 'ASYMMETRIC KEY USER',21825,'EOB',NULL,NULL,0 UNION ALL
select 'CERTIFICATE USER',21827,'EOB',NULL,NULL,0 UNION ALL
select 'AUDIT',21828,'EOB',NULL,NULL,0 UNION ALL
select 'GROUP USER',21831,'EOB',NULL,NULL,0 UNION ALL
select 'EXTERNAL GROUP USER',21840,'EOB',NULL,NULL,0 UNION ALL
select 'SQL USER',21843,'EOB',NULL,NULL,0 UNION ALL
select 'WINDOWS USER',21847,'EOB',NULL,NULL,0 UNION ALL
select 'EXTERNAL USER',21848,'EOB',NULL,NULL,0 UNION ALL
select 'SERVICE',22099,'EOB',NULL,NULL,0 UNION ALL
select 'INDEX',22601,'EOB',NULL,NULL,0 UNION ALL
select 'LOGIN',22604,'EOB',NULL,NULL,0 UNION ALL
select 'XML SCHEMA COLLECTION',22611,'EOB',NULL,NULL,0 UNION ALL
select 'TYPE',22868,'EOB',NULL,NULL,0 UNION ALL
select 'SERVER AUDIT',8257,'EOD',NULL,NULL,0 UNION ALL
select 'CHECK CONSTRAINT',8259,'EOD',NULL,NULL,0 UNION ALL
select 'DEFAULT',8260,'EOD',NULL,NULL,0 UNION ALL
select 'FOREIGN KEY CONSTRAINT',8262,'EOD',NULL,NULL,0 UNION ALL
select 'STORED PROCEDURE',8272,'EOD',NULL,NULL,0 UNION ALL
select 'RULE',8274,'EOD',NULL,NULL,0 UNION ALL
select 'TABLE SYSTEM',8275,'EOD',NULL,NULL,0 UNION ALL
select 'TRIGGER SERVER',8276,'EOD',NULL,NULL,0 UNION ALL
select 'TABLE',8277,'EOD',NULL,NULL,0 UNION ALL
select 'VIEW',8278,'EOD',NULL,NULL,0 UNION ALL
select 'STORED PROCEDURE EXTENDED',8280,'EOD',NULL,NULL,0 UNION ALL
select 'DATABASE AUDIT SPECIFICATION',16708,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL LANGUAGE',16716,'EOD',NULL,NULL,0 UNION ALL
select 'SERVER AUDIT SPECIFICATION',16723,'EOD',NULL,NULL,0 UNION ALL
select 'TRIGGER ASSEMBLY',16724,'EOD',NULL,NULL,0 UNION ALL
select 'DATABASE',16964,'EOD',NULL,NULL,0 UNION ALL
select 'OBJECT',16975,'EOD',NULL,NULL,0 UNION ALL
select 'DATABASE SCOPED CREDENTIAL',17220,'EOD',NULL,NULL,0 UNION ALL
select 'EDGE CONSTRAINT',17221,'EOD',NULL,NULL,0 UNION ALL
select 'FULLTEXT CATALOG',17222,'EOD',NULL,NULL,0 UNION ALL
select 'STORED PROCEDURE ASSEMBLY',17232,'EOD',NULL,NULL,0 UNION ALL
select 'SCHEMA',17235,'EOD',NULL,NULL,0 UNION ALL
select 'CREDENTIAL',17475,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL DATA SOURCE',17477,'EOD',NULL,NULL,0 UNION ALL
select 'EVENT NOTIFICATION SERVER',17491,'EOD',NULL,NULL,0 UNION ALL
select 'DATABASE EVENT SESSION',17732,'EOD',NULL,NULL,0 UNION ALL
select 'EVENT SESSION',17747,'EOD',NULL,NULL,0 UNION ALL
select 'AGGREGATE',17985,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL FILE FORMAT',17989,'EOD',NULL,NULL,0 UNION ALL
select 'FUNCTION TABLE-VALUED INLINE SQL',17993,'EOD',NULL,NULL,0 UNION ALL
select 'PARTITION FUNCTION',18000,'EOD',NULL,NULL,0 UNION ALL
select 'STORED PROCEDURE REPLICATION FILTER',18002,'EOD',NULL,NULL,0 UNION ALL
select 'FUNCTION TABLE-VALUED SQL',18004,'EOD',NULL,NULL,0 UNION ALL
select 'AVAILABILITY GROUP',18241,'EOD',NULL,NULL,0 UNION ALL
select 'RESOURCE GOVERNOR',18258,'EOD',NULL,NULL,0 UNION ALL
select 'SERVER ROLE',18259,'EOD',NULL,NULL,0 UNION ALL
select 'WINDOWS GROUP',18263,'EOD',NULL,NULL,0 UNION ALL
select 'ASYMMETRIC KEY',19265,'EOD',NULL,NULL,0 UNION ALL
select 'COLUMN ENCRYPTION KEY',19267,'EOD',NULL,NULL,0 UNION ALL
select 'DATABASE ENCRYPTION KEY',19268,'EOD',NULL,NULL,0 UNION ALL
select 'MASTER KEY',19277,'EOD',NULL,NULL,0 UNION ALL
select 'PRIMARY KEY',19280,'EOD',NULL,NULL,0 UNION ALL
select 'SYMMETRIC KEY',19283,'EOD',NULL,NULL,0 UNION ALL
select 'ASYMMETRIC KEY LOGIN',19521,'EOD',NULL,NULL,0 UNION ALL
select 'CERTIFICATE LOGIN',19523,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL LIBRARY',19525,'EOD',NULL,NULL,0 UNION ALL
select 'FULLTEXT STOPLIST',19526,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL GROUP LOGIN',19536,'EOD',NULL,NULL,0 UNION ALL
select 'ROLE',19538,'EOD',NULL,NULL,0 UNION ALL
select 'SQL LOGIN',19539,'EOD',NULL,NULL,0 UNION ALL
select 'WINDOWS LOGIN',19543,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL LOGIN',19544,'EOD',NULL,NULL,0 UNION ALL
select 'COLUMN MASTER KEY',19779,'EOD',NULL,NULL,0 UNION ALL
select 'REMOTE SERVICE BINDING',20034,'EOD',NULL,NULL,0 UNION ALL
select 'EVENT NOTIFICATION DATABASE',20036,'EOD',NULL,NULL,0 UNION ALL
select 'EVENT NOTIFICATION',20037,'EOD',NULL,NULL,0 UNION ALL
select 'FUNCTION SCALAR SQL',20038,'EOD',NULL,NULL,0 UNION ALL
select 'EVENT NOTIFICATION OBJECT',20047,'EOD',NULL,NULL,0 UNION ALL
select 'SYNONYM',20051,'EOD',NULL,NULL,0 UNION ALL
select 'SERVER CONFIG',20291,'EOD',NULL,NULL,0 UNION ALL
select 'SEQUENCE OBJECT',20307,'EOD',NULL,NULL,0 UNION ALL
select 'Undocumented',20545,'EOD',NULL,NULL,0 UNION ALL
select 'CRYPTOGRAPHIC PROVIDER',20547,'EOD',NULL,NULL,0 UNION ALL
select 'ENDPOINT',20549,'EOD',NULL,NULL,0 UNION ALL
select 'SEARCH PROPERTY LIST',20550,'EOD',NULL,NULL,0 UNION ALL
select 'SECURITY POLICY',20563,'EOD',NULL,NULL,0 UNION ALL
select 'ADHOC QUERY',20801,'EOD',NULL,NULL,0 UNION ALL
select 'PREPARED ADHOC QUERY',20816,'EOD',NULL,NULL,0 UNION ALL
select 'QUEUE',20819,'EOD',NULL,NULL,0 UNION ALL
select 'UNIQUE CONSTRAINT',20821,'EOD',NULL,NULL,0 UNION ALL
select 'APPLICATION ROLE',21057,'EOD',NULL,NULL,0 UNION ALL
select 'CERTIFICATE',21059,'EOD',NULL,NULL,0 UNION ALL
select 'DATABASE SCOPED RESOURCE GOVERNOR',21060,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL RESOURCE POOL',21061,'EOD',NULL,NULL,0 UNION ALL
select 'BROKER PRIORITY',21072,'EOD',NULL,NULL,0 UNION ALL
select 'SERVER',21075,'EOD',NULL,NULL,0 UNION ALL
select 'TRIGGER',21076,'EOD',NULL,NULL,0 UNION ALL
select 'XREL TREE',21080,'EOD',NULL,NULL,0 UNION ALL
select 'ASSEMBLY',21313,'EOD',NULL,NULL,0 UNION ALL
select 'DATABASE SCOPED CONFIGURATION',21316,'EOD',NULL,NULL,0 UNION ALL
select 'FUNCTION SCALAR ASSEMBLY ',21318,'EOD',NULL,NULL,0 UNION ALL
select 'FUNCTION SCALAR INLINE SQL ',21321,'EOD',NULL,NULL,0 UNION ALL
select 'PARTITION SCHEME',21328,'EOD',NULL,NULL,0 UNION ALL
select 'USER',21333,'EOD',NULL,NULL,0 UNION ALL
select 'CONTRACT',21571,'EOD',NULL,NULL,0 UNION ALL
select 'TRIGGER DATABASE',21572,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL TABLE',21573,'EOD',NULL,NULL,0 UNION ALL
select 'FUNCTION TABLE-VALUED ASSEMBLY ',21574,'EOD',NULL,NULL,0 UNION ALL
select 'INTERNAL TABLE',21577,'EOD',NULL,NULL,0 UNION ALL
select 'MESSAGE TYPE',21581,'EOD',NULL,NULL,0 UNION ALL
select 'ROUTE',21586,'EOD',NULL,NULL,0 UNION ALL
select 'STATISTICS',21587,'EOD',NULL,NULL,0 UNION ALL
select 'ASYMMETRIC KEY USER',21825,'EOD',NULL,NULL,0 UNION ALL
select 'CERTIFICATE USER',21827,'EOD',NULL,NULL,0 UNION ALL
select 'AUDIT',21828,'EOD',NULL,NULL,0 UNION ALL
select 'GROUP USER',21831,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL GROUP USER',21840,'EOD',NULL,NULL,0 UNION ALL
select 'SQL USER',21843,'EOD',NULL,NULL,0 UNION ALL
select 'WINDOWS USER',21847,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL USER',21848,'EOD',NULL,NULL,0 UNION ALL
select 'SERVICE',22099,'EOD',NULL,NULL,0 UNION ALL
select 'EXTERNAL SCRIPT QUERY',22597,'EOD',NULL,NULL,0 UNION ALL
select 'INDEX',22601,'EOD',NULL,NULL,0 UNION ALL
select 'LOGIN',22604,'EOD',NULL,NULL,0 UNION ALL
select 'XML SCHEMA COLLECTION',22611,'EOD',NULL,NULL,0 UNION ALL
select 'TYPE',22868,'EOD',NULL,NULL,0 UNION ALL
select 'SYSREMOTELOGINS TYPES',-1,'F  ',NULL,NULL,0 UNION ALL
select '',0,'F  ',NULL,NULL,0 UNION ALL
select 'trusted',1,'F  ',NULL,NULL,0 UNION ALL
select 'SYSREMOTELOGINS TYPES (UPDATE)',-1,'F_U',NULL,NULL,0 UNION ALL
select '',0,'F_U',NULL,NULL,0 UNION ALL
select 'trusted',16,'F_U',NULL,NULL,0 UNION ALL
select 'GENERAL MISC. STRINGS',0,'G  ',NULL,NULL,0 UNION ALL
select 'SQL Server Internal Table',0,'G  ',NULL,NULL,0 UNION ALL
select 'INDEX TYPES',0,'I  ',NULL,NULL,0 UNION ALL
select 'nonclustered',0,'I  ',NULL,NULL,0 UNION ALL
select 'ignore duplicate keys',1,'I  ',NULL,NULL,0 UNION ALL
select 'unique',2,'I  ',NULL,NULL,0 UNION ALL
select 'ignore duplicate rows',4,'I  ',NULL,NULL,0 UNION ALL
select 'clustered',16,'I  ',NULL,NULL,0 UNION ALL
select 'hypothetical',32,'I  ',NULL,NULL,0 UNION ALL
select 'statistics',64,'I  ',NULL,NULL,0 UNION ALL
select 'primary key',2048,'I  ',0,1,0 UNION ALL
select 'unique key',4096,'I  ',0,1,0 UNION ALL
select 'auto create',8388608,'I  ',NULL,NULL,0 UNION ALL
select 'stats no recompute',16777216,'I  ',NULL,NULL,0 UNION ALL
select 'COMPATIBLE TYPES',0,'J  ',NULL,NULL,0 UNION ALL
select 'binary',1,'J  ',45,NULL,0 UNION ALL
select 'varbinary',1,'J  ',37,NULL,0 UNION ALL
select 'bit',2,'J  ',50,NULL,0 UNION ALL
select 'char',3,'J  ',47,NULL,0 UNION ALL
select 'varchar',3,'J  ',39,NULL,0 UNION ALL
select 'datetime',4,'J  ',61,NULL,0 UNION ALL
select 'datetimn',4,'J  ',111,NULL,0 UNION ALL
select 'smalldatetime',4,'J  ',58,NULL,0 UNION ALL
select 'float',5,'J  ',62,NULL,0 UNION ALL
select 'floatn',5,'J  ',109,NULL,0 UNION ALL
select 'real',5,'J  ',59,NULL,0 UNION ALL
select 'int',6,'J  ',56,NULL,0 UNION ALL
select 'intn',6,'J  ',38,NULL,0 UNION ALL
select 'smallint',6,'J  ',52,NULL,0 UNION ALL
select 'tinyint',6,'J  ',48,NULL,0 UNION ALL
select 'money',7,'J  ',60,NULL,0 UNION ALL
select 'moneyn',7,'J  ',110,NULL,0 UNION ALL
select 'smallmoney',7,'J  ',122,NULL,0 UNION ALL
select 'SYSKEYS TYPES',0,'K  ',NULL,NULL,0 UNION ALL
select 'primary',1,'K  ',NULL,NULL,0 UNION ALL
select 'foreign',2,'K  ',NULL,NULL,0 UNION ALL
select 'common',3,'K  ',NULL,NULL,0 UNION ALL
select 'LOCK TYPES',0,'L  ',NULL,NULL,0 UNION ALL
select 'NULL',1,'L  ',NULL,NULL,0 UNION ALL
select 'Sch-S',2,'L  ',NULL,NULL,0 UNION ALL
select 'Sch-M',3,'L  ',NULL,NULL,0 UNION ALL
select 'S',4,'L  ',NULL,NULL,0 UNION ALL
select 'U',5,'L  ',NULL,NULL,0 UNION ALL
select 'X',6,'L  ',NULL,NULL,0 UNION ALL
select 'IS',7,'L  ',NULL,NULL,0 UNION ALL
select 'IU',8,'L  ',NULL,NULL,0 UNION ALL
select 'IX',9,'L  ',NULL,NULL,0 UNION ALL
select 'SIU',10,'L  ',NULL,NULL,0 UNION ALL
select 'SIX',11,'L  ',NULL,NULL,0 UNION ALL
select 'UIX',12,'L  ',NULL,NULL,0 UNION ALL
select 'BU',13,'L  ',NULL,NULL,0 UNION ALL
select 'RangeS-S',14,'L  ',NULL,NULL,0 UNION ALL
select 'RangeS-U',15,'L  ',NULL,NULL,0 UNION ALL
select 'RangeIn-Null',16,'L  ',NULL,NULL,0 UNION ALL
select 'RangeIn-S',17,'L  ',NULL,NULL,0 UNION ALL
select 'RangeIn-U',18,'L  ',NULL,NULL,0 UNION ALL
select 'RangeIn-X',19,'L  ',NULL,NULL,0 UNION ALL
select 'RangeX-S',20,'L  ',NULL,NULL,0 UNION ALL
select 'RangeX-U',21,'L  ',NULL,NULL,0 UNION ALL
select 'RangeX-X',22,'L  ',NULL,NULL,0 UNION ALL
select 'Arabic',1025,'LNG',NULL,NULL,0 UNION ALL
select 'Bulgarian',1026,'LNG',NULL,NULL,0 UNION ALL
select 'Traditional Chinese',1028,'LNG',NULL,NULL,0 UNION ALL
select 'Czech',1029,'LNG',NULL,NULL,0 UNION ALL
select 'Danish',1030,'LNG',NULL,NULL,0 UNION ALL
select 'German',1031,'LNG',NULL,NULL,0 UNION ALL
select 'Greek',1032,'LNG',NULL,NULL,0 UNION ALL
select 'English',1033,'LNG',NULL,NULL,0 UNION ALL
select 'Finnish',1035,'LNG',NULL,NULL,0 UNION ALL
select 'French',1036,'LNG',NULL,NULL,0 UNION ALL
select 'Hungarian',1038,'LNG',NULL,NULL,0 UNION ALL
select 'Italian',1040,'LNG',NULL,NULL,0 UNION ALL
select 'japanese',1041,'LNG',NULL,NULL,0 UNION ALL
select 'Korean',1042,'LNG',NULL,NULL,0 UNION ALL
select 'Dutch',1043,'LNG',NULL,NULL,0 UNION ALL
select 'Polish',1045,'LNG',NULL,NULL,0 UNION ALL
select 'Brazilian',1046,'LNG',NULL,NULL,0 UNION ALL
select 'Romanian',1048,'LNG',NULL,NULL,0 UNION ALL
select 'Russian',1049,'LNG',NULL,NULL,0 UNION ALL
select 'Croatian',1050,'LNG',NULL,NULL,0 UNION ALL
select 'Slovak',1051,'LNG',NULL,NULL,0 UNION ALL
select 'Swedish',1053,'LNG',NULL,NULL,0 UNION ALL
select 'Thai',1054,'LNG',NULL,NULL,0 UNION ALL
select 'Turkish',1055,'LNG',NULL,NULL,0 UNION ALL
select 'Slovenian',1060,'LNG',NULL,NULL,0 UNION ALL
select 'Estonian',1061,'LNG',NULL,NULL,0 UNION ALL
select 'Latvian',1062,'LNG',NULL,NULL,0 UNION ALL
select 'Lithuanian',1063,'LNG',NULL,NULL,0 UNION ALL
select 'Simplified Chinese',2052,'LNG',NULL,NULL,0 UNION ALL
select 'Norwegian',2068,'LNG',NULL,NULL,0 UNION ALL
select 'Portuguese',2070,'LNG',NULL,NULL,0 UNION ALL
select 'Spanish',3082,'LNG',NULL,NULL,0 UNION ALL
select 'LOCK OWNER',0,'LO ',NULL,NULL,0 UNION ALL
select 'Xact',1,'LO ',NULL,NULL,0 UNION ALL
select 'Crsr',2,'LO ',NULL,NULL,0 UNION ALL
select 'Sess',3,'LO ',NULL,NULL,0 UNION ALL
select 'STWS',4,'LO ',NULL,NULL,0 UNION ALL
select 'XTWS',5,'LO ',NULL,NULL,0 UNION ALL
select 'WFR',6,'LO ',NULL,NULL,0 UNION ALL
select 'LOCK RESOURCES',0,'LR ',NULL,NULL,0 UNION ALL
select 'NUL',1,'LR ',NULL,NULL,0 UNION ALL
select 'DB',2,'LR ',NULL,NULL,0 UNION ALL
select 'FIL',3,'LR ',NULL,NULL,0 UNION ALL
select 'TAB',5,'LR ',NULL,NULL,0 UNION ALL
select 'PAG',6,'LR ',NULL,NULL,0 UNION ALL
select 'KEY',7,'LR ',NULL,NULL,0 UNION ALL
select 'EXT',8,'LR ',NULL,NULL,0 UNION ALL
select 'RID',9,'LR ',NULL,NULL,0 UNION ALL
select 'APP',10,'LR ',NULL,NULL,0 UNION ALL
select 'MD',11,'LR ',NULL,NULL,0 UNION ALL
select 'HBT',12,'LR ',NULL,NULL,0 UNION ALL
select 'AU',13,'LR ',NULL,NULL,0 UNION ALL
select 'LOCK REQ STATUS',0,'LS ',NULL,NULL,0 UNION ALL
select 'GRANT',1,'LS ',NULL,NULL,0 UNION ALL
select 'CNVT',2,'LS ',NULL,NULL,0 UNION ALL
select 'WAIT',3,'LS ',NULL,NULL,0 UNION ALL
select 'RELN',4,'LS ',NULL,NULL,0 UNION ALL
select 'BLCKN',5,'LS ',NULL,NULL,0 UNION ALL
select 'OBJECT TYPES',0,'O  ',NULL,NULL,0 UNION ALL
select 'system table',1,'O  ',NULL,NULL,0 UNION ALL
select 'view',2,'O  ',NULL,NULL,0 UNION ALL
select 'user table',3,'O  ',NULL,NULL,0 UNION ALL
select 'stored procedure',4,'O  ',NULL,NULL,0 UNION ALL
select 'default',6,'O  ',NULL,NULL,0 UNION ALL
select 'rule',7,'O  ',NULL,NULL,0 UNION ALL
select 'trigger',8,'O  ',NULL,NULL,0 UNION ALL
select 'replication filter stored procedure',12,'O  ',NULL,NULL,0 UNION ALL
select 'AF: aggregate function',-1,'O9T',0,0,0 UNION ALL
select 'AP: application',-1,'O9T',0,0,0 UNION ALL
select 'C : check cns',-1,'O9T',0,0,0 UNION ALL
select 'D : default (maybe cns)',-1,'O9T',0,0,0 UNION ALL
select 'EC: edge cns',-1,'O9T',0,0,0 UNION ALL
select 'EN: event notification',-1,'O9T',0,0,0 UNION ALL
select 'F : foreign key cns',-1,'O9T',0,0,0 UNION ALL
select 'FN: scalar function',-1,'O9T',0,0,0 UNION ALL
select 'FS: assembly scalar function',-1,'O9T',0,0,0 UNION ALL
select 'FT: assembly table function',-1,'O9T',0,0,0 UNION ALL
select 'IF: inline function',-1,'O9T',0,0,0 UNION ALL
select 'IS: inline scalar function',-1,'O9T',0,0,0 UNION ALL
select 'IT: internal table',-1,'O9T',0,0,0 UNION ALL
select 'L : log',-1,'O9T',0,0,0 UNION ALL
select 'P : stored procedure',-1,'O9T',0,0,0 UNION ALL
select 'PC : assembly stored procedure',-1,'O9T',0,0,0 UNION ALL
select 'PK: primary key cns',-1,'O9T',0,0,0 UNION ALL
select 'R : rule',-1,'O9T',0,0,0 UNION ALL
select 'RF: replication filter proc',-1,'O9T',0,0,0 UNION ALL
select 'S : system table',-1,'O9T',0,0,0 UNION ALL
select 'SN: synonym',-1,'O9T',0,0,0 UNION ALL
select 'SO: sequence object',-1,'O9T',0,0,0 UNION ALL
select 'SQ: queue',-1,'O9T',0,0,0 UNION ALL
select 'TA: assembly trigger',-1,'O9T',0,0,0 UNION ALL
select 'TF: table function',-1,'O9T',0,0,0 UNION ALL
select 'TR: trigger',-1,'O9T',0,0,0 UNION ALL
select 'U : user table',-1,'O9T',0,0,0 UNION ALL
select 'UQ: unique key cns',-1,'O9T',0,0,0 UNION ALL
select 'V : view',-1,'O9T',0,0,0 UNION ALL
select 'X : extended stored proc',-1,'O9T',0,0,0 UNION ALL
select 'sysobjects.type, reports',0,'O9T',0,0,0 UNION ALL
select NULL,0,'P  ',1,1,0 UNION ALL
select NULL,1,'P  ',1,2,0 UNION ALL
select NULL,2,'P  ',1,4,0 UNION ALL
select NULL,3,'P  ',1,8,0 UNION ALL
select NULL,4,'P  ',1,16,0 UNION ALL
select NULL,5,'P  ',1,32,0 UNION ALL
select NULL,6,'P  ',1,64,0 UNION ALL
select NULL,7,'P  ',1,128,0 UNION ALL
select NULL,8,'P  ',2,1,0 UNION ALL
select NULL,9,'P  ',2,2,0 UNION ALL
select NULL,10,'P  ',2,4,0 UNION ALL
select NULL,11,'P  ',2,8,0 UNION ALL
select NULL,12,'P  ',2,16,0 UNION ALL
select NULL,13,'P  ',2,32,0 UNION ALL
select NULL,14,'P  ',2,64,0 UNION ALL
select NULL,15,'P  ',2,128,0 UNION ALL
select NULL,16,'P  ',3,1,0 UNION ALL
select NULL,17,'P  ',3,2,0 UNION ALL
select NULL,18,'P  ',3,4,0 UNION ALL
select NULL,19,'P  ',3,8,0 UNION ALL
select NULL,20,'P  ',3,16,0 UNION ALL
select NULL,21,'P  ',3,32,0 UNION ALL
select NULL,22,'P  ',3,64,0 UNION ALL
select NULL,23,'P  ',3,128,0 UNION ALL
select NULL,24,'P  ',4,1,0 UNION ALL
select NULL,25,'P  ',4,2,0 UNION ALL
select NULL,26,'P  ',4,4,0 UNION ALL
select NULL,27,'P  ',4,8,0 UNION ALL
select NULL,28,'P  ',4,16,0 UNION ALL
select NULL,29,'P  ',4,32,0 UNION ALL
select NULL,30,'P  ',4,64,0 UNION ALL
select NULL,31,'P  ',4,128,0 UNION ALL
select NULL,32,'P  ',5,1,0 UNION ALL
select NULL,33,'P  ',5,2,0 UNION ALL
select NULL,34,'P  ',5,4,0 UNION ALL
select NULL,35,'P  ',5,8,0 UNION ALL
select NULL,36,'P  ',5,16,0 UNION ALL
select NULL,37,'P  ',5,32,0 UNION ALL
select NULL,38,'P  ',5,64,0 UNION ALL
select NULL,39,'P  ',5,128,0 UNION ALL
select NULL,40,'P  ',6,1,0 UNION ALL
select NULL,41,'P  ',6,2,0 UNION ALL
select NULL,42,'P  ',6,4,0 UNION ALL
select NULL,43,'P  ',6,8,0 UNION ALL
select NULL,44,'P  ',6,16,0 UNION ALL
select NULL,45,'P  ',6,32,0 UNION ALL
select NULL,46,'P  ',6,64,0 UNION ALL
select NULL,47,'P  ',6,128,0 UNION ALL
select NULL,48,'P  ',7,1,0 UNION ALL
select NULL,49,'P  ',7,2,0 UNION ALL
select NULL,50,'P  ',7,4,0 UNION ALL
select NULL,51,'P  ',7,8,0 UNION ALL
select NULL,52,'P  ',7,16,0 UNION ALL
select NULL,53,'P  ',7,32,0 UNION ALL
select NULL,54,'P  ',7,64,0 UNION ALL
select NULL,55,'P  ',7,128,0 UNION ALL
select NULL,56,'P  ',8,1,0 UNION ALL
select NULL,57,'P  ',8,2,0 UNION ALL
select NULL,58,'P  ',8,4,0 UNION ALL
select NULL,59,'P  ',8,8,0 UNION ALL
select NULL,60,'P  ',8,16,0 UNION ALL
select NULL,61,'P  ',8,32,0 UNION ALL
select NULL,62,'P  ',8,64,0 UNION ALL
select NULL,63,'P  ',8,128,0 UNION ALL
select NULL,64,'P  ',9,1,0 UNION ALL
select NULL,65,'P  ',9,2,0 UNION ALL
select NULL,66,'P  ',9,4,0 UNION ALL
select NULL,67,'P  ',9,8,0 UNION ALL
select NULL,68,'P  ',9,16,0 UNION ALL
select NULL,69,'P  ',9,32,0 UNION ALL
select NULL,70,'P  ',9,64,0 UNION ALL
select NULL,71,'P  ',9,128,0 UNION ALL
select NULL,72,'P  ',10,1,0 UNION ALL
select NULL,73,'P  ',10,2,0 UNION ALL
select NULL,74,'P  ',10,4,0 UNION ALL
select NULL,75,'P  ',10,8,0 UNION ALL
select NULL,76,'P  ',10,16,0 UNION ALL
select NULL,77,'P  ',10,32,0 UNION ALL
select NULL,78,'P  ',10,64,0 UNION ALL
select NULL,79,'P  ',10,128,0 UNION ALL
select NULL,80,'P  ',11,1,0 UNION ALL
select NULL,81,'P  ',11,2,0 UNION ALL
select NULL,82,'P  ',11,4,0 UNION ALL
select NULL,83,'P  ',11,8,0 UNION ALL
select NULL,84,'P  ',11,16,0 UNION ALL
select NULL,85,'P  ',11,32,0 UNION ALL
select NULL,86,'P  ',11,64,0 UNION ALL
select NULL,87,'P  ',11,128,0 UNION ALL
select NULL,88,'P  ',12,1,0 UNION ALL
select NULL,89,'P  ',12,2,0 UNION ALL
select NULL,90,'P  ',12,4,0 UNION ALL
select NULL,91,'P  ',12,8,0 UNION ALL
select NULL,92,'P  ',12,16,0 UNION ALL
select NULL,93,'P  ',12,32,0 UNION ALL
select NULL,94,'P  ',12,64,0 UNION ALL
select NULL,95,'P  ',12,128,0 UNION ALL
select NULL,96,'P  ',13,1,0 UNION ALL
select NULL,97,'P  ',13,2,0 UNION ALL
select NULL,98,'P  ',13,4,0 UNION ALL
select NULL,99,'P  ',13,8,0 UNION ALL
select NULL,100,'P  ',13,16,0 UNION ALL
select NULL,101,'P  ',13,32,0 UNION ALL
select NULL,102,'P  ',13,64,0 UNION ALL
select NULL,103,'P  ',13,128,0 UNION ALL
select NULL,104,'P  ',14,1,0 UNION ALL
select NULL,105,'P  ',14,2,0 UNION ALL
select NULL,106,'P  ',14,4,0 UNION ALL
select NULL,107,'P  ',14,8,0 UNION ALL
select NULL,108,'P  ',14,16,0 UNION ALL
select NULL,109,'P  ',14,32,0 UNION ALL
select NULL,110,'P  ',14,64,0 UNION ALL
select NULL,111,'P  ',14,128,0 UNION ALL
select NULL,112,'P  ',15,1,0 UNION ALL
select NULL,113,'P  ',15,2,0 UNION ALL
select NULL,114,'P  ',15,4,0 UNION ALL
select NULL,115,'P  ',15,8,0 UNION ALL
select NULL,116,'P  ',15,16,0 UNION ALL
select NULL,117,'P  ',15,32,0 UNION ALL
select NULL,118,'P  ',15,64,0 UNION ALL
select NULL,119,'P  ',15,128,0 UNION ALL
select NULL,120,'P  ',16,1,0 UNION ALL
select NULL,121,'P  ',16,2,0 UNION ALL
select NULL,122,'P  ',16,4,0 UNION ALL
select NULL,123,'P  ',16,8,0 UNION ALL
select NULL,124,'P  ',16,16,0 UNION ALL
select NULL,125,'P  ',16,32,0 UNION ALL
select NULL,126,'P  ',16,64,0 UNION ALL
select NULL,127,'P  ',16,128,0 UNION ALL
select NULL,128,'P  ',17,1,0 UNION ALL
select NULL,129,'P  ',17,2,0 UNION ALL
select NULL,130,'P  ',17,4,0 UNION ALL
select NULL,131,'P  ',17,8,0 UNION ALL
select NULL,132,'P  ',17,16,0 UNION ALL
select NULL,133,'P  ',17,32,0 UNION ALL
select NULL,134,'P  ',17,64,0 UNION ALL
select NULL,135,'P  ',17,128,0 UNION ALL
select NULL,136,'P  ',18,1,0 UNION ALL
select NULL,137,'P  ',18,2,0 UNION ALL
select NULL,138,'P  ',18,4,0 UNION ALL
select NULL,139,'P  ',18,8,0 UNION ALL
select NULL,140,'P  ',18,16,0 UNION ALL
select NULL,141,'P  ',18,32,0 UNION ALL
select NULL,142,'P  ',18,64,0 UNION ALL
select NULL,143,'P  ',18,128,0 UNION ALL
select NULL,144,'P  ',19,1,0 UNION ALL
select NULL,145,'P  ',19,2,0 UNION ALL
select NULL,146,'P  ',19,4,0 UNION ALL
select NULL,147,'P  ',19,8,0 UNION ALL
select NULL,148,'P  ',19,16,0 UNION ALL
select NULL,149,'P  ',19,32,0 UNION ALL
select NULL,150,'P  ',19,64,0 UNION ALL
select NULL,151,'P  ',19,128,0 UNION ALL
select NULL,152,'P  ',20,1,0 UNION ALL
select NULL,153,'P  ',20,2,0 UNION ALL
select NULL,154,'P  ',20,4,0 UNION ALL
select NULL,155,'P  ',20,8,0 UNION ALL
select NULL,156,'P  ',20,16,0 UNION ALL
select NULL,157,'P  ',20,32,0 UNION ALL
select NULL,158,'P  ',20,64,0 UNION ALL
select NULL,159,'P  ',20,128,0 UNION ALL
select NULL,160,'P  ',21,1,0 UNION ALL
select NULL,161,'P  ',21,2,0 UNION ALL
select NULL,162,'P  ',21,4,0 UNION ALL
select NULL,163,'P  ',21,8,0 UNION ALL
select NULL,164,'P  ',21,16,0 UNION ALL
select NULL,165,'P  ',21,32,0 UNION ALL
select NULL,166,'P  ',21,64,0 UNION ALL
select NULL,167,'P  ',21,128,0 UNION ALL
select NULL,168,'P  ',22,1,0 UNION ALL
select NULL,169,'P  ',22,2,0 UNION ALL
select NULL,170,'P  ',22,4,0 UNION ALL
select NULL,171,'P  ',22,8,0 UNION ALL
select NULL,172,'P  ',22,16,0 UNION ALL
select NULL,173,'P  ',22,32,0 UNION ALL
select NULL,174,'P  ',22,64,0 UNION ALL
select NULL,175,'P  ',22,128,0 UNION ALL
select NULL,176,'P  ',23,1,0 UNION ALL
select NULL,177,'P  ',23,2,0 UNION ALL
select NULL,178,'P  ',23,4,0 UNION ALL
select NULL,179,'P  ',23,8,0 UNION ALL
select NULL,180,'P  ',23,16,0 UNION ALL
select NULL,181,'P  ',23,32,0 UNION ALL
select NULL,182,'P  ',23,64,0 UNION ALL
select NULL,183,'P  ',23,128,0 UNION ALL
select NULL,184,'P  ',24,1,0 UNION ALL
select NULL,185,'P  ',24,2,0 UNION ALL
select NULL,186,'P  ',24,4,0 UNION ALL
select NULL,187,'P  ',24,8,0 UNION ALL
select NULL,188,'P  ',24,16,0 UNION ALL
select NULL,189,'P  ',24,32,0 UNION ALL
select NULL,190,'P  ',24,64,0 UNION ALL
select NULL,191,'P  ',24,128,0 UNION ALL
select NULL,192,'P  ',25,1,0 UNION ALL
select NULL,193,'P  ',25,2,0 UNION ALL
select NULL,194,'P  ',25,4,0 UNION ALL
select NULL,195,'P  ',25,8,0 UNION ALL
select NULL,196,'P  ',25,16,0 UNION ALL
select NULL,197,'P  ',25,32,0 UNION ALL
select NULL,198,'P  ',25,64,0 UNION ALL
select NULL,199,'P  ',25,128,0 UNION ALL
select NULL,200,'P  ',26,1,0 UNION ALL
select NULL,201,'P  ',26,2,0 UNION ALL
select NULL,202,'P  ',26,4,0 UNION ALL
select NULL,203,'P  ',26,8,0 UNION ALL
select NULL,204,'P  ',26,16,0 UNION ALL
select NULL,205,'P  ',26,32,0 UNION ALL
select NULL,206,'P  ',26,64,0 UNION ALL
select NULL,207,'P  ',26,128,0 UNION ALL
select NULL,208,'P  ',27,1,0 UNION ALL
select NULL,209,'P  ',27,2,0 UNION ALL
select NULL,210,'P  ',27,4,0 UNION ALL
select NULL,211,'P  ',27,8,0 UNION ALL
select NULL,212,'P  ',27,16,0 UNION ALL
select NULL,213,'P  ',27,32,0 UNION ALL
select NULL,214,'P  ',27,64,0 UNION ALL
select NULL,215,'P  ',27,128,0 UNION ALL
select NULL,216,'P  ',28,1,0 UNION ALL
select NULL,217,'P  ',28,2,0 UNION ALL
select NULL,218,'P  ',28,4,0 UNION ALL
select NULL,219,'P  ',28,8,0 UNION ALL
select NULL,220,'P  ',28,16,0 UNION ALL
select NULL,221,'P  ',28,32,0 UNION ALL
select NULL,222,'P  ',28,64,0 UNION ALL
select NULL,223,'P  ',28,128,0 UNION ALL
select NULL,224,'P  ',29,1,0 UNION ALL
select NULL,225,'P  ',29,2,0 UNION ALL
select NULL,226,'P  ',29,4,0 UNION ALL
select NULL,227,'P  ',29,8,0 UNION ALL
select NULL,228,'P  ',29,16,0 UNION ALL
select NULL,229,'P  ',29,32,0 UNION ALL
select NULL,230,'P  ',29,64,0 UNION ALL
select NULL,231,'P  ',29,128,0 UNION ALL
select NULL,232,'P  ',30,1,0 UNION ALL
select NULL,233,'P  ',30,2,0 UNION ALL
select NULL,234,'P  ',30,4,0 UNION ALL
select NULL,235,'P  ',30,8,0 UNION ALL
select NULL,236,'P  ',30,16,0 UNION ALL
select NULL,237,'P  ',30,32,0 UNION ALL
select NULL,238,'P  ',30,64,0 UNION ALL
select NULL,239,'P  ',30,128,0 UNION ALL
select NULL,240,'P  ',31,1,0 UNION ALL
select NULL,241,'P  ',31,2,0 UNION ALL
select NULL,242,'P  ',31,4,0 UNION ALL
select NULL,243,'P  ',31,8,0 UNION ALL
select NULL,244,'P  ',31,16,0 UNION ALL
select NULL,245,'P  ',31,32,0 UNION ALL
select NULL,246,'P  ',31,64,0 UNION ALL
select NULL,247,'P  ',31,128,0 UNION ALL
select NULL,248,'P  ',32,1,0 UNION ALL
select NULL,249,'P  ',32,2,0 UNION ALL
select NULL,250,'P  ',32,4,0 UNION ALL
select NULL,251,'P  ',32,8,0 UNION ALL
select NULL,252,'P  ',32,16,0 UNION ALL
select NULL,253,'P  ',32,32,0 UNION ALL
select NULL,254,'P  ',32,64,0 UNION ALL
select NULL,255,'P  ',32,128,0 UNION ALL
select NULL,256,'P  ',33,1,0 UNION ALL
select NULL,257,'P  ',33,2,0 UNION ALL
select NULL,258,'P  ',33,4,0 UNION ALL
select NULL,259,'P  ',33,8,0 UNION ALL
select NULL,260,'P  ',33,16,0 UNION ALL
select NULL,261,'P  ',33,32,0 UNION ALL
select NULL,262,'P  ',33,64,0 UNION ALL
select NULL,263,'P  ',33,128,0 UNION ALL
select NULL,264,'P  ',34,1,0 UNION ALL
select NULL,265,'P  ',34,2,0 UNION ALL
select NULL,266,'P  ',34,4,0 UNION ALL
select NULL,267,'P  ',34,8,0 UNION ALL
select NULL,268,'P  ',34,16,0 UNION ALL
select NULL,269,'P  ',34,32,0 UNION ALL
select NULL,270,'P  ',34,64,0 UNION ALL
select NULL,271,'P  ',34,128,0 UNION ALL
select NULL,272,'P  ',35,1,0 UNION ALL
select NULL,273,'P  ',35,2,0 UNION ALL
select NULL,274,'P  ',35,4,0 UNION ALL
select NULL,275,'P  ',35,8,0 UNION ALL
select NULL,276,'P  ',35,16,0 UNION ALL
select NULL,277,'P  ',35,32,0 UNION ALL
select NULL,278,'P  ',35,64,0 UNION ALL
select NULL,279,'P  ',35,128,0 UNION ALL
select NULL,280,'P  ',36,1,0 UNION ALL
select NULL,281,'P  ',36,2,0 UNION ALL
select NULL,282,'P  ',36,4,0 UNION ALL
select NULL,283,'P  ',36,8,0 UNION ALL
select NULL,284,'P  ',36,16,0 UNION ALL
select NULL,285,'P  ',36,32,0 UNION ALL
select NULL,286,'P  ',36,64,0 UNION ALL
select NULL,287,'P  ',36,128,0 UNION ALL
select NULL,288,'P  ',37,1,0 UNION ALL
select NULL,289,'P  ',37,2,0 UNION ALL
select NULL,290,'P  ',37,4,0 UNION ALL
select NULL,291,'P  ',37,8,0 UNION ALL
select NULL,292,'P  ',37,16,0 UNION ALL
select NULL,293,'P  ',37,32,0 UNION ALL
select NULL,294,'P  ',37,64,0 UNION ALL
select NULL,295,'P  ',37,128,0 UNION ALL
select NULL,296,'P  ',38,1,0 UNION ALL
select NULL,297,'P  ',38,2,0 UNION ALL
select NULL,298,'P  ',38,4,0 UNION ALL
select NULL,299,'P  ',38,8,0 UNION ALL
select NULL,300,'P  ',38,16,0 UNION ALL
select NULL,301,'P  ',38,32,0 UNION ALL
select NULL,302,'P  ',38,64,0 UNION ALL
select NULL,303,'P  ',38,128,0 UNION ALL
select NULL,304,'P  ',39,1,0 UNION ALL
select NULL,305,'P  ',39,2,0 UNION ALL
select NULL,306,'P  ',39,4,0 UNION ALL
select NULL,307,'P  ',39,8,0 UNION ALL
select NULL,308,'P  ',39,16,0 UNION ALL
select NULL,309,'P  ',39,32,0 UNION ALL
select NULL,310,'P  ',39,64,0 UNION ALL
select NULL,311,'P  ',39,128,0 UNION ALL
select NULL,312,'P  ',40,1,0 UNION ALL
select NULL,313,'P  ',40,2,0 UNION ALL
select NULL,314,'P  ',40,4,0 UNION ALL
select NULL,315,'P  ',40,8,0 UNION ALL
select NULL,316,'P  ',40,16,0 UNION ALL
select NULL,317,'P  ',40,32,0 UNION ALL
select NULL,318,'P  ',40,64,0 UNION ALL
select NULL,319,'P  ',40,128,0 UNION ALL
select NULL,320,'P  ',41,1,0 UNION ALL
select NULL,321,'P  ',41,2,0 UNION ALL
select NULL,322,'P  ',41,4,0 UNION ALL
select NULL,323,'P  ',41,8,0 UNION ALL
select NULL,324,'P  ',41,16,0 UNION ALL
select NULL,325,'P  ',41,32,0 UNION ALL
select NULL,326,'P  ',41,64,0 UNION ALL
select NULL,327,'P  ',41,128,0 UNION ALL
select NULL,328,'P  ',42,1,0 UNION ALL
select NULL,329,'P  ',42,2,0 UNION ALL
select NULL,330,'P  ',42,4,0 UNION ALL
select NULL,331,'P  ',42,8,0 UNION ALL
select NULL,332,'P  ',42,16,0 UNION ALL
select NULL,333,'P  ',42,32,0 UNION ALL
select NULL,334,'P  ',42,64,0 UNION ALL
select NULL,335,'P  ',42,128,0 UNION ALL
select NULL,336,'P  ',43,1,0 UNION ALL
select NULL,337,'P  ',43,2,0 UNION ALL
select NULL,338,'P  ',43,4,0 UNION ALL
select NULL,339,'P  ',43,8,0 UNION ALL
select NULL,340,'P  ',43,16,0 UNION ALL
select NULL,341,'P  ',43,32,0 UNION ALL
select NULL,342,'P  ',43,64,0 UNION ALL
select NULL,343,'P  ',43,128,0 UNION ALL
select NULL,344,'P  ',44,1,0 UNION ALL
select NULL,345,'P  ',44,2,0 UNION ALL
select NULL,346,'P  ',44,4,0 UNION ALL
select NULL,347,'P  ',44,8,0 UNION ALL
select NULL,348,'P  ',44,16,0 UNION ALL
select NULL,349,'P  ',44,32,0 UNION ALL
select NULL,350,'P  ',44,64,0 UNION ALL
select NULL,351,'P  ',44,128,0 UNION ALL
select NULL,352,'P  ',45,1,0 UNION ALL
select NULL,353,'P  ',45,2,0 UNION ALL
select NULL,354,'P  ',45,4,0 UNION ALL
select NULL,355,'P  ',45,8,0 UNION ALL
select NULL,356,'P  ',45,16,0 UNION ALL
select NULL,357,'P  ',45,32,0 UNION ALL
select NULL,358,'P  ',45,64,0 UNION ALL
select NULL,359,'P  ',45,128,0 UNION ALL
select NULL,360,'P  ',46,1,0 UNION ALL
select NULL,361,'P  ',46,2,0 UNION ALL
select NULL,362,'P  ',46,4,0 UNION ALL
select NULL,363,'P  ',46,8,0 UNION ALL
select NULL,364,'P  ',46,16,0 UNION ALL
select NULL,365,'P  ',46,32,0 UNION ALL
select NULL,366,'P  ',46,64,0 UNION ALL
select NULL,367,'P  ',46,128,0 UNION ALL
select NULL,368,'P  ',47,1,0 UNION ALL
select NULL,369,'P  ',47,2,0 UNION ALL
select NULL,370,'P  ',47,4,0 UNION ALL
select NULL,371,'P  ',47,8,0 UNION ALL
select NULL,372,'P  ',47,16,0 UNION ALL
select NULL,373,'P  ',47,32,0 UNION ALL
select NULL,374,'P  ',47,64,0 UNION ALL
select NULL,375,'P  ',47,128,0 UNION ALL
select NULL,376,'P  ',48,1,0 UNION ALL
select NULL,377,'P  ',48,2,0 UNION ALL
select NULL,378,'P  ',48,4,0 UNION ALL
select NULL,379,'P  ',48,8,0 UNION ALL
select NULL,380,'P  ',48,16,0 UNION ALL
select NULL,381,'P  ',48,32,0 UNION ALL
select NULL,382,'P  ',48,64,0 UNION ALL
select NULL,383,'P  ',48,128,0 UNION ALL
select NULL,384,'P  ',49,1,0 UNION ALL
select NULL,385,'P  ',49,2,0 UNION ALL
select NULL,386,'P  ',49,4,0 UNION ALL
select NULL,387,'P  ',49,8,0 UNION ALL
select NULL,388,'P  ',49,16,0 UNION ALL
select NULL,389,'P  ',49,32,0 UNION ALL
select NULL,390,'P  ',49,64,0 UNION ALL
select NULL,391,'P  ',49,128,0 UNION ALL
select NULL,392,'P  ',50,1,0 UNION ALL
select NULL,393,'P  ',50,2,0 UNION ALL
select NULL,394,'P  ',50,4,0 UNION ALL
select NULL,395,'P  ',50,8,0 UNION ALL
select NULL,396,'P  ',50,16,0 UNION ALL
select NULL,397,'P  ',50,32,0 UNION ALL
select NULL,398,'P  ',50,64,0 UNION ALL
select NULL,399,'P  ',50,128,0 UNION ALL
select NULL,400,'P  ',51,1,0 UNION ALL
select NULL,401,'P  ',51,2,0 UNION ALL
select NULL,402,'P  ',51,4,0 UNION ALL
select NULL,403,'P  ',51,8,0 UNION ALL
select NULL,404,'P  ',51,16,0 UNION ALL
select NULL,405,'P  ',51,32,0 UNION ALL
select NULL,406,'P  ',51,64,0 UNION ALL
select NULL,407,'P  ',51,128,0 UNION ALL
select NULL,408,'P  ',52,1,0 UNION ALL
select NULL,409,'P  ',52,2,0 UNION ALL
select NULL,410,'P  ',52,4,0 UNION ALL
select NULL,411,'P  ',52,8,0 UNION ALL
select NULL,412,'P  ',52,16,0 UNION ALL
select NULL,413,'P  ',52,32,0 UNION ALL
select NULL,414,'P  ',52,64,0 UNION ALL
select NULL,415,'P  ',52,128,0 UNION ALL
select NULL,416,'P  ',53,1,0 UNION ALL
select NULL,417,'P  ',53,2,0 UNION ALL
select NULL,418,'P  ',53,4,0 UNION ALL
select NULL,419,'P  ',53,8,0 UNION ALL
select NULL,420,'P  ',53,16,0 UNION ALL
select NULL,421,'P  ',53,32,0 UNION ALL
select NULL,422,'P  ',53,64,0 UNION ALL
select NULL,423,'P  ',53,128,0 UNION ALL
select NULL,424,'P  ',54,1,0 UNION ALL
select NULL,425,'P  ',54,2,0 UNION ALL
select NULL,426,'P  ',54,4,0 UNION ALL
select NULL,427,'P  ',54,8,0 UNION ALL
select NULL,428,'P  ',54,16,0 UNION ALL
select NULL,429,'P  ',54,32,0 UNION ALL
select NULL,430,'P  ',54,64,0 UNION ALL
select NULL,431,'P  ',54,128,0 UNION ALL
select NULL,432,'P  ',55,1,0 UNION ALL
select NULL,433,'P  ',55,2,0 UNION ALL
select NULL,434,'P  ',55,4,0 UNION ALL
select NULL,435,'P  ',55,8,0 UNION ALL
select NULL,436,'P  ',55,16,0 UNION ALL
select NULL,437,'P  ',55,32,0 UNION ALL
select NULL,438,'P  ',55,64,0 UNION ALL
select NULL,439,'P  ',55,128,0 UNION ALL
select NULL,440,'P  ',56,1,0 UNION ALL
select NULL,441,'P  ',56,2,0 UNION ALL
select NULL,442,'P  ',56,4,0 UNION ALL
select NULL,443,'P  ',56,8,0 UNION ALL
select NULL,444,'P  ',56,16,0 UNION ALL
select NULL,445,'P  ',56,32,0 UNION ALL
select NULL,446,'P  ',56,64,0 UNION ALL
select NULL,447,'P  ',56,128,0 UNION ALL
select NULL,448,'P  ',57,1,0 UNION ALL
select NULL,449,'P  ',57,2,0 UNION ALL
select NULL,450,'P  ',57,4,0 UNION ALL
select NULL,451,'P  ',57,8,0 UNION ALL
select NULL,452,'P  ',57,16,0 UNION ALL
select NULL,453,'P  ',57,32,0 UNION ALL
select NULL,454,'P  ',57,64,0 UNION ALL
select NULL,455,'P  ',57,128,0 UNION ALL
select NULL,456,'P  ',58,1,0 UNION ALL
select NULL,457,'P  ',58,2,0 UNION ALL
select NULL,458,'P  ',58,4,0 UNION ALL
select NULL,459,'P  ',58,8,0 UNION ALL
select NULL,460,'P  ',58,16,0 UNION ALL
select NULL,461,'P  ',58,32,0 UNION ALL
select NULL,462,'P  ',58,64,0 UNION ALL
select NULL,463,'P  ',58,128,0 UNION ALL
select NULL,464,'P  ',59,1,0 UNION ALL
select NULL,465,'P  ',59,2,0 UNION ALL
select NULL,466,'P  ',59,4,0 UNION ALL
select NULL,467,'P  ',59,8,0 UNION ALL
select NULL,468,'P  ',59,16,0 UNION ALL
select NULL,469,'P  ',59,32,0 UNION ALL
select NULL,470,'P  ',59,64,0 UNION ALL
select NULL,471,'P  ',59,128,0 UNION ALL
select NULL,472,'P  ',60,1,0 UNION ALL
select NULL,473,'P  ',60,2,0 UNION ALL
select NULL,474,'P  ',60,4,0 UNION ALL
select NULL,475,'P  ',60,8,0 UNION ALL
select NULL,476,'P  ',60,16,0 UNION ALL
select NULL,477,'P  ',60,32,0 UNION ALL
select NULL,478,'P  ',60,64,0 UNION ALL
select NULL,479,'P  ',60,128,0 UNION ALL
select NULL,480,'P  ',61,1,0 UNION ALL
select NULL,481,'P  ',61,2,0 UNION ALL
select NULL,482,'P  ',61,4,0 UNION ALL
select NULL,483,'P  ',61,8,0 UNION ALL
select NULL,484,'P  ',61,16,0 UNION ALL
select NULL,485,'P  ',61,32,0 UNION ALL
select NULL,486,'P  ',61,64,0 UNION ALL
select NULL,487,'P  ',61,128,0 UNION ALL
select NULL,488,'P  ',62,1,0 UNION ALL
select NULL,489,'P  ',62,2,0 UNION ALL
select NULL,490,'P  ',62,4,0 UNION ALL
select NULL,491,'P  ',62,8,0 UNION ALL
select NULL,492,'P  ',62,16,0 UNION ALL
select NULL,493,'P  ',62,32,0 UNION ALL
select NULL,494,'P  ',62,64,0 UNION ALL
select NULL,495,'P  ',62,128,0 UNION ALL
select NULL,496,'P  ',63,1,0 UNION ALL
select NULL,497,'P  ',63,2,0 UNION ALL
select NULL,498,'P  ',63,4,0 UNION ALL
select NULL,499,'P  ',63,8,0 UNION ALL
select NULL,500,'P  ',63,16,0 UNION ALL
select NULL,501,'P  ',63,32,0 UNION ALL
select NULL,502,'P  ',63,64,0 UNION ALL
select NULL,503,'P  ',63,128,0 UNION ALL
select NULL,504,'P  ',64,1,0 UNION ALL
select NULL,505,'P  ',64,2,0 UNION ALL
select NULL,506,'P  ',64,4,0 UNION ALL
select NULL,507,'P  ',64,8,0 UNION ALL
select NULL,508,'P  ',64,16,0 UNION ALL
select NULL,509,'P  ',64,32,0 UNION ALL
select NULL,510,'P  ',64,64,0 UNION ALL
select NULL,511,'P  ',64,128,0 UNION ALL
select NULL,512,'P  ',65,1,0 UNION ALL
select NULL,513,'P  ',65,2,0 UNION ALL
select NULL,514,'P  ',65,4,0 UNION ALL
select NULL,515,'P  ',65,8,0 UNION ALL
select NULL,516,'P  ',65,16,0 UNION ALL
select NULL,517,'P  ',65,32,0 UNION ALL
select NULL,518,'P  ',65,64,0 UNION ALL
select NULL,519,'P  ',65,128,0 UNION ALL
select NULL,520,'P  ',66,1,0 UNION ALL
select NULL,521,'P  ',66,2,0 UNION ALL
select NULL,522,'P  ',66,4,0 UNION ALL
select NULL,523,'P  ',66,8,0 UNION ALL
select NULL,524,'P  ',66,16,0 UNION ALL
select NULL,525,'P  ',66,32,0 UNION ALL
select NULL,526,'P  ',66,64,0 UNION ALL
select NULL,527,'P  ',66,128,0 UNION ALL
select NULL,528,'P  ',67,1,0 UNION ALL
select NULL,529,'P  ',67,2,0 UNION ALL
select NULL,530,'P  ',67,4,0 UNION ALL
select NULL,531,'P  ',67,8,0 UNION ALL
select NULL,532,'P  ',67,16,0 UNION ALL
select NULL,533,'P  ',67,32,0 UNION ALL
select NULL,534,'P  ',67,64,0 UNION ALL
select NULL,535,'P  ',67,128,0 UNION ALL
select NULL,536,'P  ',68,1,0 UNION ALL
select NULL,537,'P  ',68,2,0 UNION ALL
select NULL,538,'P  ',68,4,0 UNION ALL
select NULL,539,'P  ',68,8,0 UNION ALL
select NULL,540,'P  ',68,16,0 UNION ALL
select NULL,541,'P  ',68,32,0 UNION ALL
select NULL,542,'P  ',68,64,0 UNION ALL
select NULL,543,'P  ',68,128,0 UNION ALL
select NULL,544,'P  ',69,1,0 UNION ALL
select NULL,545,'P  ',69,2,0 UNION ALL
select NULL,546,'P  ',69,4,0 UNION ALL
select NULL,547,'P  ',69,8,0 UNION ALL
select NULL,548,'P  ',69,16,0 UNION ALL
select NULL,549,'P  ',69,32,0 UNION ALL
select NULL,550,'P  ',69,64,0 UNION ALL
select NULL,551,'P  ',69,128,0 UNION ALL
select NULL,552,'P  ',70,1,0 UNION ALL
select NULL,553,'P  ',70,2,0 UNION ALL
select NULL,554,'P  ',70,4,0 UNION ALL
select NULL,555,'P  ',70,8,0 UNION ALL
select NULL,556,'P  ',70,16,0 UNION ALL
select NULL,557,'P  ',70,32,0 UNION ALL
select NULL,558,'P  ',70,64,0 UNION ALL
select NULL,559,'P  ',70,128,0 UNION ALL
select NULL,560,'P  ',71,1,0 UNION ALL
select NULL,561,'P  ',71,2,0 UNION ALL
select NULL,562,'P  ',71,4,0 UNION ALL
select NULL,563,'P  ',71,8,0 UNION ALL
select NULL,564,'P  ',71,16,0 UNION ALL
select NULL,565,'P  ',71,32,0 UNION ALL
select NULL,566,'P  ',71,64,0 UNION ALL
select NULL,567,'P  ',71,128,0 UNION ALL
select NULL,568,'P  ',72,1,0 UNION ALL
select NULL,569,'P  ',72,2,0 UNION ALL
select NULL,570,'P  ',72,4,0 UNION ALL
select NULL,571,'P  ',72,8,0 UNION ALL
select NULL,572,'P  ',72,16,0 UNION ALL
select NULL,573,'P  ',72,32,0 UNION ALL
select NULL,574,'P  ',72,64,0 UNION ALL
select NULL,575,'P  ',72,128,0 UNION ALL
select NULL,576,'P  ',73,1,0 UNION ALL
select NULL,577,'P  ',73,2,0 UNION ALL
select NULL,578,'P  ',73,4,0 UNION ALL
select NULL,579,'P  ',73,8,0 UNION ALL
select NULL,580,'P  ',73,16,0 UNION ALL
select NULL,581,'P  ',73,32,0 UNION ALL
select NULL,582,'P  ',73,64,0 UNION ALL
select NULL,583,'P  ',73,128,0 UNION ALL
select NULL,584,'P  ',74,1,0 UNION ALL
select NULL,585,'P  ',74,2,0 UNION ALL
select NULL,586,'P  ',74,4,0 UNION ALL
select NULL,587,'P  ',74,8,0 UNION ALL
select NULL,588,'P  ',74,16,0 UNION ALL
select NULL,589,'P  ',74,32,0 UNION ALL
select NULL,590,'P  ',74,64,0 UNION ALL
select NULL,591,'P  ',74,128,0 UNION ALL
select NULL,592,'P  ',75,1,0 UNION ALL
select NULL,593,'P  ',75,2,0 UNION ALL
select NULL,594,'P  ',75,4,0 UNION ALL
select NULL,595,'P  ',75,8,0 UNION ALL
select NULL,596,'P  ',75,16,0 UNION ALL
select NULL,597,'P  ',75,32,0 UNION ALL
select NULL,598,'P  ',75,64,0 UNION ALL
select NULL,599,'P  ',75,128,0 UNION ALL
select NULL,600,'P  ',76,1,0 UNION ALL
select NULL,601,'P  ',76,2,0 UNION ALL
select NULL,602,'P  ',76,4,0 UNION ALL
select NULL,603,'P  ',76,8,0 UNION ALL
select NULL,604,'P  ',76,16,0 UNION ALL
select NULL,605,'P  ',76,32,0 UNION ALL
select NULL,606,'P  ',76,64,0 UNION ALL
select NULL,607,'P  ',76,128,0 UNION ALL
select NULL,608,'P  ',77,1,0 UNION ALL
select NULL,609,'P  ',77,2,0 UNION ALL
select NULL,610,'P  ',77,4,0 UNION ALL
select NULL,611,'P  ',77,8,0 UNION ALL
select NULL,612,'P  ',77,16,0 UNION ALL
select NULL,613,'P  ',77,32,0 UNION ALL
select NULL,614,'P  ',77,64,0 UNION ALL
select NULL,615,'P  ',77,128,0 UNION ALL
select NULL,616,'P  ',78,1,0 UNION ALL
select NULL,617,'P  ',78,2,0 UNION ALL
select NULL,618,'P  ',78,4,0 UNION ALL
select NULL,619,'P  ',78,8,0 UNION ALL
select NULL,620,'P  ',78,16,0 UNION ALL
select NULL,621,'P  ',78,32,0 UNION ALL
select NULL,622,'P  ',78,64,0 UNION ALL
select NULL,623,'P  ',78,128,0 UNION ALL
select NULL,624,'P  ',79,1,0 UNION ALL
select NULL,625,'P  ',79,2,0 UNION ALL
select NULL,626,'P  ',79,4,0 UNION ALL
select NULL,627,'P  ',79,8,0 UNION ALL
select NULL,628,'P  ',79,16,0 UNION ALL
select NULL,629,'P  ',79,32,0 UNION ALL
select NULL,630,'P  ',79,64,0 UNION ALL
select NULL,631,'P  ',79,128,0 UNION ALL
select NULL,632,'P  ',80,1,0 UNION ALL
select NULL,633,'P  ',80,2,0 UNION ALL
select NULL,634,'P  ',80,4,0 UNION ALL
select NULL,635,'P  ',80,8,0 UNION ALL
select NULL,636,'P  ',80,16,0 UNION ALL
select NULL,637,'P  ',80,32,0 UNION ALL
select NULL,638,'P  ',80,64,0 UNION ALL
select NULL,639,'P  ',80,128,0 UNION ALL
select NULL,640,'P  ',81,1,0 UNION ALL
select NULL,641,'P  ',81,2,0 UNION ALL
select NULL,642,'P  ',81,4,0 UNION ALL
select NULL,643,'P  ',81,8,0 UNION ALL
select NULL,644,'P  ',81,16,0 UNION ALL
select NULL,645,'P  ',81,32,0 UNION ALL
select NULL,646,'P  ',81,64,0 UNION ALL
select NULL,647,'P  ',81,128,0 UNION ALL
select NULL,648,'P  ',82,1,0 UNION ALL
select NULL,649,'P  ',82,2,0 UNION ALL
select NULL,650,'P  ',82,4,0 UNION ALL
select NULL,651,'P  ',82,8,0 UNION ALL
select NULL,652,'P  ',82,16,0 UNION ALL
select NULL,653,'P  ',82,32,0 UNION ALL
select NULL,654,'P  ',82,64,0 UNION ALL
select NULL,655,'P  ',82,128,0 UNION ALL
select NULL,656,'P  ',83,1,0 UNION ALL
select NULL,657,'P  ',83,2,0 UNION ALL
select NULL,658,'P  ',83,4,0 UNION ALL
select NULL,659,'P  ',83,8,0 UNION ALL
select NULL,660,'P  ',83,16,0 UNION ALL
select NULL,661,'P  ',83,32,0 UNION ALL
select NULL,662,'P  ',83,64,0 UNION ALL
select NULL,663,'P  ',83,128,0 UNION ALL
select NULL,664,'P  ',84,1,0 UNION ALL
select NULL,665,'P  ',84,2,0 UNION ALL
select NULL,666,'P  ',84,4,0 UNION ALL
select NULL,667,'P  ',84,8,0 UNION ALL
select NULL,668,'P  ',84,16,0 UNION ALL
select NULL,669,'P  ',84,32,0 UNION ALL
select NULL,670,'P  ',84,64,0 UNION ALL
select NULL,671,'P  ',84,128,0 UNION ALL
select NULL,672,'P  ',85,1,0 UNION ALL
select NULL,673,'P  ',85,2,0 UNION ALL
select NULL,674,'P  ',85,4,0 UNION ALL
select NULL,675,'P  ',85,8,0 UNION ALL
select NULL,676,'P  ',85,16,0 UNION ALL
select NULL,677,'P  ',85,32,0 UNION ALL
select NULL,678,'P  ',85,64,0 UNION ALL
select NULL,679,'P  ',85,128,0 UNION ALL
select NULL,680,'P  ',86,1,0 UNION ALL
select NULL,681,'P  ',86,2,0 UNION ALL
select NULL,682,'P  ',86,4,0 UNION ALL
select NULL,683,'P  ',86,8,0 UNION ALL
select NULL,684,'P  ',86,16,0 UNION ALL
select NULL,685,'P  ',86,32,0 UNION ALL
select NULL,686,'P  ',86,64,0 UNION ALL
select NULL,687,'P  ',86,128,0 UNION ALL
select NULL,688,'P  ',87,1,0 UNION ALL
select NULL,689,'P  ',87,2,0 UNION ALL
select NULL,690,'P  ',87,4,0 UNION ALL
select NULL,691,'P  ',87,8,0 UNION ALL
select NULL,692,'P  ',87,16,0 UNION ALL
select NULL,693,'P  ',87,32,0 UNION ALL
select NULL,694,'P  ',87,64,0 UNION ALL
select NULL,695,'P  ',87,128,0 UNION ALL
select NULL,696,'P  ',88,1,0 UNION ALL
select NULL,697,'P  ',88,2,0 UNION ALL
select NULL,698,'P  ',88,4,0 UNION ALL
select NULL,699,'P  ',88,8,0 UNION ALL
select NULL,700,'P  ',88,16,0 UNION ALL
select NULL,701,'P  ',88,32,0 UNION ALL
select NULL,702,'P  ',88,64,0 UNION ALL
select NULL,703,'P  ',88,128,0 UNION ALL
select NULL,704,'P  ',89,1,0 UNION ALL
select NULL,705,'P  ',89,2,0 UNION ALL
select NULL,706,'P  ',89,4,0 UNION ALL
select NULL,707,'P  ',89,8,0 UNION ALL
select NULL,708,'P  ',89,16,0 UNION ALL
select NULL,709,'P  ',89,32,0 UNION ALL
select NULL,710,'P  ',89,64,0 UNION ALL
select NULL,711,'P  ',89,128,0 UNION ALL
select NULL,712,'P  ',90,1,0 UNION ALL
select NULL,713,'P  ',90,2,0 UNION ALL
select NULL,714,'P  ',90,4,0 UNION ALL
select NULL,715,'P  ',90,8,0 UNION ALL
select NULL,716,'P  ',90,16,0 UNION ALL
select NULL,717,'P  ',90,32,0 UNION ALL
select NULL,718,'P  ',90,64,0 UNION ALL
select NULL,719,'P  ',90,128,0 UNION ALL
select NULL,720,'P  ',91,1,0 UNION ALL
select NULL,721,'P  ',91,2,0 UNION ALL
select NULL,722,'P  ',91,4,0 UNION ALL
select NULL,723,'P  ',91,8,0 UNION ALL
select NULL,724,'P  ',91,16,0 UNION ALL
select NULL,725,'P  ',91,32,0 UNION ALL
select NULL,726,'P  ',91,64,0 UNION ALL
select NULL,727,'P  ',91,128,0 UNION ALL
select NULL,728,'P  ',92,1,0 UNION ALL
select NULL,729,'P  ',92,2,0 UNION ALL
select NULL,730,'P  ',92,4,0 UNION ALL
select NULL,731,'P  ',92,8,0 UNION ALL
select NULL,732,'P  ',92,16,0 UNION ALL
select NULL,733,'P  ',92,32,0 UNION ALL
select NULL,734,'P  ',92,64,0 UNION ALL
select NULL,735,'P  ',92,128,0 UNION ALL
select NULL,736,'P  ',93,1,0 UNION ALL
select NULL,737,'P  ',93,2,0 UNION ALL
select NULL,738,'P  ',93,4,0 UNION ALL
select NULL,739,'P  ',93,8,0 UNION ALL
select NULL,740,'P  ',93,16,0 UNION ALL
select NULL,741,'P  ',93,32,0 UNION ALL
select NULL,742,'P  ',93,64,0 UNION ALL
select NULL,743,'P  ',93,128,0 UNION ALL
select NULL,744,'P  ',94,1,0 UNION ALL
select NULL,745,'P  ',94,2,0 UNION ALL
select NULL,746,'P  ',94,4,0 UNION ALL
select NULL,747,'P  ',94,8,0 UNION ALL
select NULL,748,'P  ',94,16,0 UNION ALL
select NULL,749,'P  ',94,32,0 UNION ALL
select NULL,750,'P  ',94,64,0 UNION ALL
select NULL,751,'P  ',94,128,0 UNION ALL
select NULL,752,'P  ',95,1,0 UNION ALL
select NULL,753,'P  ',95,2,0 UNION ALL
select NULL,754,'P  ',95,4,0 UNION ALL
select NULL,755,'P  ',95,8,0 UNION ALL
select NULL,756,'P  ',95,16,0 UNION ALL
select NULL,757,'P  ',95,32,0 UNION ALL
select NULL,758,'P  ',95,64,0 UNION ALL
select NULL,759,'P  ',95,128,0 UNION ALL
select NULL,760,'P  ',96,1,0 UNION ALL
select NULL,761,'P  ',96,2,0 UNION ALL
select NULL,762,'P  ',96,4,0 UNION ALL
select NULL,763,'P  ',96,8,0 UNION ALL
select NULL,764,'P  ',96,16,0 UNION ALL
select NULL,765,'P  ',96,32,0 UNION ALL
select NULL,766,'P  ',96,64,0 UNION ALL
select NULL,767,'P  ',96,128,0 UNION ALL
select NULL,768,'P  ',97,1,0 UNION ALL
select NULL,769,'P  ',97,2,0 UNION ALL
select NULL,770,'P  ',97,4,0 UNION ALL
select NULL,771,'P  ',97,8,0 UNION ALL
select NULL,772,'P  ',97,16,0 UNION ALL
select NULL,773,'P  ',97,32,0 UNION ALL
select NULL,774,'P  ',97,64,0 UNION ALL
select NULL,775,'P  ',97,128,0 UNION ALL
select NULL,776,'P  ',98,1,0 UNION ALL
select NULL,777,'P  ',98,2,0 UNION ALL
select NULL,778,'P  ',98,4,0 UNION ALL
select NULL,779,'P  ',98,8,0 UNION ALL
select NULL,780,'P  ',98,16,0 UNION ALL
select NULL,781,'P  ',98,32,0 UNION ALL
select NULL,782,'P  ',98,64,0 UNION ALL
select NULL,783,'P  ',98,128,0 UNION ALL
select NULL,784,'P  ',99,1,0 UNION ALL
select NULL,785,'P  ',99,2,0 UNION ALL
select NULL,786,'P  ',99,4,0 UNION ALL
select NULL,787,'P  ',99,8,0 UNION ALL
select NULL,788,'P  ',99,16,0 UNION ALL
select NULL,789,'P  ',99,32,0 UNION ALL
select NULL,790,'P  ',99,64,0 UNION ALL
select NULL,791,'P  ',99,128,0 UNION ALL
select NULL,792,'P  ',100,1,0 UNION ALL
select NULL,793,'P  ',100,2,0 UNION ALL
select NULL,794,'P  ',100,4,0 UNION ALL
select NULL,795,'P  ',100,8,0 UNION ALL
select NULL,796,'P  ',100,16,0 UNION ALL
select NULL,797,'P  ',100,32,0 UNION ALL
select NULL,798,'P  ',100,64,0 UNION ALL
select NULL,799,'P  ',100,128,0 UNION ALL
select NULL,800,'P  ',101,1,0 UNION ALL
select NULL,801,'P  ',101,2,0 UNION ALL
select NULL,802,'P  ',101,4,0 UNION ALL
select NULL,803,'P  ',101,8,0 UNION ALL
select NULL,804,'P  ',101,16,0 UNION ALL
select NULL,805,'P  ',101,32,0 UNION ALL
select NULL,806,'P  ',101,64,0 UNION ALL
select NULL,807,'P  ',101,128,0 UNION ALL
select NULL,808,'P  ',102,1,0 UNION ALL
select NULL,809,'P  ',102,2,0 UNION ALL
select NULL,810,'P  ',102,4,0 UNION ALL
select NULL,811,'P  ',102,8,0 UNION ALL
select NULL,812,'P  ',102,16,0 UNION ALL
select NULL,813,'P  ',102,32,0 UNION ALL
select NULL,814,'P  ',102,64,0 UNION ALL
select NULL,815,'P  ',102,128,0 UNION ALL
select NULL,816,'P  ',103,1,0 UNION ALL
select NULL,817,'P  ',103,2,0 UNION ALL
select NULL,818,'P  ',103,4,0 UNION ALL
select NULL,819,'P  ',103,8,0 UNION ALL
select NULL,820,'P  ',103,16,0 UNION ALL
select NULL,821,'P  ',103,32,0 UNION ALL
select NULL,822,'P  ',103,64,0 UNION ALL
select NULL,823,'P  ',103,128,0 UNION ALL
select NULL,824,'P  ',104,1,0 UNION ALL
select NULL,825,'P  ',104,2,0 UNION ALL
select NULL,826,'P  ',104,4,0 UNION ALL
select NULL,827,'P  ',104,8,0 UNION ALL
select NULL,828,'P  ',104,16,0 UNION ALL
select NULL,829,'P  ',104,32,0 UNION ALL
select NULL,830,'P  ',104,64,0 UNION ALL
select NULL,831,'P  ',104,128,0 UNION ALL
select NULL,832,'P  ',105,1,0 UNION ALL
select NULL,833,'P  ',105,2,0 UNION ALL
select NULL,834,'P  ',105,4,0 UNION ALL
select NULL,835,'P  ',105,8,0 UNION ALL
select NULL,836,'P  ',105,16,0 UNION ALL
select NULL,837,'P  ',105,32,0 UNION ALL
select NULL,838,'P  ',105,64,0 UNION ALL
select NULL,839,'P  ',105,128,0 UNION ALL
select NULL,840,'P  ',106,1,0 UNION ALL
select NULL,841,'P  ',106,2,0 UNION ALL
select NULL,842,'P  ',106,4,0 UNION ALL
select NULL,843,'P  ',106,8,0 UNION ALL
select NULL,844,'P  ',106,16,0 UNION ALL
select NULL,845,'P  ',106,32,0 UNION ALL
select NULL,846,'P  ',106,64,0 UNION ALL
select NULL,847,'P  ',106,128,0 UNION ALL
select NULL,848,'P  ',107,1,0 UNION ALL
select NULL,849,'P  ',107,2,0 UNION ALL
select NULL,850,'P  ',107,4,0 UNION ALL
select NULL,851,'P  ',107,8,0 UNION ALL
select NULL,852,'P  ',107,16,0 UNION ALL
select NULL,853,'P  ',107,32,0 UNION ALL
select NULL,854,'P  ',107,64,0 UNION ALL
select NULL,855,'P  ',107,128,0 UNION ALL
select NULL,856,'P  ',108,1,0 UNION ALL
select NULL,857,'P  ',108,2,0 UNION ALL
select NULL,858,'P  ',108,4,0 UNION ALL
select NULL,859,'P  ',108,8,0 UNION ALL
select NULL,860,'P  ',108,16,0 UNION ALL
select NULL,861,'P  ',108,32,0 UNION ALL
select NULL,862,'P  ',108,64,0 UNION ALL
select NULL,863,'P  ',108,128,0 UNION ALL
select NULL,864,'P  ',109,1,0 UNION ALL
select NULL,865,'P  ',109,2,0 UNION ALL
select NULL,866,'P  ',109,4,0 UNION ALL
select NULL,867,'P  ',109,8,0 UNION ALL
select NULL,868,'P  ',109,16,0 UNION ALL
select NULL,869,'P  ',109,32,0 UNION ALL
select NULL,870,'P  ',109,64,0 UNION ALL
select NULL,871,'P  ',109,128,0 UNION ALL
select NULL,872,'P  ',110,1,0 UNION ALL
select NULL,873,'P  ',110,2,0 UNION ALL
select NULL,874,'P  ',110,4,0 UNION ALL
select NULL,875,'P  ',110,8,0 UNION ALL
select NULL,876,'P  ',110,16,0 UNION ALL
select NULL,877,'P  ',110,32,0 UNION ALL
select NULL,878,'P  ',110,64,0 UNION ALL
select NULL,879,'P  ',110,128,0 UNION ALL
select NULL,880,'P  ',111,1,0 UNION ALL
select NULL,881,'P  ',111,2,0 UNION ALL
select NULL,882,'P  ',111,4,0 UNION ALL
select NULL,883,'P  ',111,8,0 UNION ALL
select NULL,884,'P  ',111,16,0 UNION ALL
select NULL,885,'P  ',111,32,0 UNION ALL
select NULL,886,'P  ',111,64,0 UNION ALL
select NULL,887,'P  ',111,128,0 UNION ALL
select NULL,888,'P  ',112,1,0 UNION ALL
select NULL,889,'P  ',112,2,0 UNION ALL
select NULL,890,'P  ',112,4,0 UNION ALL
select NULL,891,'P  ',112,8,0 UNION ALL
select NULL,892,'P  ',112,16,0 UNION ALL
select NULL,893,'P  ',112,32,0 UNION ALL
select NULL,894,'P  ',112,64,0 UNION ALL
select NULL,895,'P  ',112,128,0 UNION ALL
select NULL,896,'P  ',113,1,0 UNION ALL
select NULL,897,'P  ',113,2,0 UNION ALL
select NULL,898,'P  ',113,4,0 UNION ALL
select NULL,899,'P  ',113,8,0 UNION ALL
select NULL,900,'P  ',113,16,0 UNION ALL
select NULL,901,'P  ',113,32,0 UNION ALL
select NULL,902,'P  ',113,64,0 UNION ALL
select NULL,903,'P  ',113,128,0 UNION ALL
select NULL,904,'P  ',114,1,0 UNION ALL
select NULL,905,'P  ',114,2,0 UNION ALL
select NULL,906,'P  ',114,4,0 UNION ALL
select NULL,907,'P  ',114,8,0 UNION ALL
select NULL,908,'P  ',114,16,0 UNION ALL
select NULL,909,'P  ',114,32,0 UNION ALL
select NULL,910,'P  ',114,64,0 UNION ALL
select NULL,911,'P  ',114,128,0 UNION ALL
select NULL,912,'P  ',115,1,0 UNION ALL
select NULL,913,'P  ',115,2,0 UNION ALL
select NULL,914,'P  ',115,4,0 UNION ALL
select NULL,915,'P  ',115,8,0 UNION ALL
select NULL,916,'P  ',115,16,0 UNION ALL
select NULL,917,'P  ',115,32,0 UNION ALL
select NULL,918,'P  ',115,64,0 UNION ALL
select NULL,919,'P  ',115,128,0 UNION ALL
select NULL,920,'P  ',116,1,0 UNION ALL
select NULL,921,'P  ',116,2,0 UNION ALL
select NULL,922,'P  ',116,4,0 UNION ALL
select NULL,923,'P  ',116,8,0 UNION ALL
select NULL,924,'P  ',116,16,0 UNION ALL
select NULL,925,'P  ',116,32,0 UNION ALL
select NULL,926,'P  ',116,64,0 UNION ALL
select NULL,927,'P  ',116,128,0 UNION ALL
select NULL,928,'P  ',117,1,0 UNION ALL
select NULL,929,'P  ',117,2,0 UNION ALL
select NULL,930,'P  ',117,4,0 UNION ALL
select NULL,931,'P  ',117,8,0 UNION ALL
select NULL,932,'P  ',117,16,0 UNION ALL
select NULL,933,'P  ',117,32,0 UNION ALL
select NULL,934,'P  ',117,64,0 UNION ALL
select NULL,935,'P  ',117,128,0 UNION ALL
select NULL,936,'P  ',118,1,0 UNION ALL
select NULL,937,'P  ',118,2,0 UNION ALL
select NULL,938,'P  ',118,4,0 UNION ALL
select NULL,939,'P  ',118,8,0 UNION ALL
select NULL,940,'P  ',118,16,0 UNION ALL
select NULL,941,'P  ',118,32,0 UNION ALL
select NULL,942,'P  ',118,64,0 UNION ALL
select NULL,943,'P  ',118,128,0 UNION ALL
select NULL,944,'P  ',119,1,0 UNION ALL
select NULL,945,'P  ',119,2,0 UNION ALL
select NULL,946,'P  ',119,4,0 UNION ALL
select NULL,947,'P  ',119,8,0 UNION ALL
select NULL,948,'P  ',119,16,0 UNION ALL
select NULL,949,'P  ',119,32,0 UNION ALL
select NULL,950,'P  ',119,64,0 UNION ALL
select NULL,951,'P  ',119,128,0 UNION ALL
select NULL,952,'P  ',120,1,0 UNION ALL
select NULL,953,'P  ',120,2,0 UNION ALL
select NULL,954,'P  ',120,4,0 UNION ALL
select NULL,955,'P  ',120,8,0 UNION ALL
select NULL,956,'P  ',120,16,0 UNION ALL
select NULL,957,'P  ',120,32,0 UNION ALL
select NULL,958,'P  ',120,64,0 UNION ALL
select NULL,959,'P  ',120,128,0 UNION ALL
select NULL,960,'P  ',121,1,0 UNION ALL
select NULL,961,'P  ',121,2,0 UNION ALL
select NULL,962,'P  ',121,4,0 UNION ALL
select NULL,963,'P  ',121,8,0 UNION ALL
select NULL,964,'P  ',121,16,0 UNION ALL
select NULL,965,'P  ',121,32,0 UNION ALL
select NULL,966,'P  ',121,64,0 UNION ALL
select NULL,967,'P  ',121,128,0 UNION ALL
select NULL,968,'P  ',122,1,0 UNION ALL
select NULL,969,'P  ',122,2,0 UNION ALL
select NULL,970,'P  ',122,4,0 UNION ALL
select NULL,971,'P  ',122,8,0 UNION ALL
select NULL,972,'P  ',122,16,0 UNION ALL
select NULL,973,'P  ',122,32,0 UNION ALL
select NULL,974,'P  ',122,64,0 UNION ALL
select NULL,975,'P  ',122,128,0 UNION ALL
select NULL,976,'P  ',123,1,0 UNION ALL
select NULL,977,'P  ',123,2,0 UNION ALL
select NULL,978,'P  ',123,4,0 UNION ALL
select NULL,979,'P  ',123,8,0 UNION ALL
select NULL,980,'P  ',123,16,0 UNION ALL
select NULL,981,'P  ',123,32,0 UNION ALL
select NULL,982,'P  ',123,64,0 UNION ALL
select NULL,983,'P  ',123,128,0 UNION ALL
select NULL,984,'P  ',124,1,0 UNION ALL
select NULL,985,'P  ',124,2,0 UNION ALL
select NULL,986,'P  ',124,4,0 UNION ALL
select NULL,987,'P  ',124,8,0 UNION ALL
select NULL,988,'P  ',124,16,0 UNION ALL
select NULL,989,'P  ',124,32,0 UNION ALL
select NULL,990,'P  ',124,64,0 UNION ALL
select NULL,991,'P  ',124,128,0 UNION ALL
select NULL,992,'P  ',125,1,0 UNION ALL
select NULL,993,'P  ',125,2,0 UNION ALL
select NULL,994,'P  ',125,4,0 UNION ALL
select NULL,995,'P  ',125,8,0 UNION ALL
select NULL,996,'P  ',125,16,0 UNION ALL
select NULL,997,'P  ',125,32,0 UNION ALL
select NULL,998,'P  ',125,64,0 UNION ALL
select NULL,999,'P  ',125,128,0 UNION ALL
select NULL,1000,'P  ',126,1,0 UNION ALL
select NULL,1001,'P  ',126,2,0 UNION ALL
select NULL,1002,'P  ',126,4,0 UNION ALL
select NULL,1003,'P  ',126,8,0 UNION ALL
select NULL,1004,'P  ',126,16,0 UNION ALL
select NULL,1005,'P  ',126,32,0 UNION ALL
select NULL,1006,'P  ',126,64,0 UNION ALL
select NULL,1007,'P  ',126,128,0 UNION ALL
select NULL,1008,'P  ',127,1,0 UNION ALL
select NULL,1009,'P  ',127,2,0 UNION ALL
select NULL,1010,'P  ',127,4,0 UNION ALL
select NULL,1011,'P  ',127,8,0 UNION ALL
select NULL,1012,'P  ',127,16,0 UNION ALL
select NULL,1013,'P  ',127,32,0 UNION ALL
select NULL,1014,'P  ',127,64,0 UNION ALL
select NULL,1015,'P  ',127,128,0 UNION ALL
select NULL,1016,'P  ',128,1,0 UNION ALL
select NULL,1017,'P  ',128,2,0 UNION ALL
select NULL,1018,'P  ',128,4,0 UNION ALL
select NULL,1019,'P  ',128,8,0 UNION ALL
select NULL,1020,'P  ',128,16,0 UNION ALL
select NULL,1021,'P  ',128,32,0 UNION ALL
select NULL,1022,'P  ',128,64,0 UNION ALL
select NULL,1023,'P  ',128,128,0 UNION ALL
select NULL,1024,'P  ',129,1,0 UNION ALL
select NULL,1025,'P  ',129,2,0 UNION ALL
select NULL,1026,'P  ',129,4,0 UNION ALL
select NULL,1027,'P  ',129,8,0 UNION ALL
select NULL,1028,'P  ',129,16,0 UNION ALL
select NULL,1029,'P  ',129,32,0 UNION ALL
select NULL,1030,'P  ',129,64,0 UNION ALL
select NULL,1031,'P  ',129,128,0 UNION ALL
select NULL,1032,'P  ',130,1,0 UNION ALL
select NULL,1033,'P  ',130,2,0 UNION ALL
select NULL,1034,'P  ',130,4,0 UNION ALL
select NULL,1035,'P  ',130,8,0 UNION ALL
select NULL,1036,'P  ',130,16,0 UNION ALL
select NULL,1037,'P  ',130,32,0 UNION ALL
select NULL,1038,'P  ',130,64,0 UNION ALL
select NULL,1039,'P  ',130,128,0 UNION ALL
select NULL,1040,'P  ',131,1,0 UNION ALL
select NULL,1041,'P  ',131,2,0 UNION ALL
select NULL,1042,'P  ',131,4,0 UNION ALL
select NULL,1043,'P  ',131,8,0 UNION ALL
select NULL,1044,'P  ',131,16,0 UNION ALL
select NULL,1045,'P  ',131,32,0 UNION ALL
select NULL,1046,'P  ',131,64,0 UNION ALL
select NULL,1047,'P  ',131,128,0 UNION ALL
select NULL,1048,'P  ',132,1,0 UNION ALL
select NULL,1049,'P  ',132,2,0 UNION ALL
select NULL,1050,'P  ',132,4,0 UNION ALL
select NULL,1051,'P  ',132,8,0 UNION ALL
select NULL,1052,'P  ',132,16,0 UNION ALL
select NULL,1053,'P  ',132,32,0 UNION ALL
select NULL,1054,'P  ',132,64,0 UNION ALL
select NULL,1055,'P  ',132,128,0 UNION ALL
select NULL,1056,'P  ',133,1,0 UNION ALL
select NULL,1057,'P  ',133,2,0 UNION ALL
select NULL,1058,'P  ',133,4,0 UNION ALL
select NULL,1059,'P  ',133,8,0 UNION ALL
select NULL,1060,'P  ',133,16,0 UNION ALL
select NULL,1061,'P  ',133,32,0 UNION ALL
select NULL,1062,'P  ',133,64,0 UNION ALL
select NULL,1063,'P  ',133,128,0 UNION ALL
select NULL,1064,'P  ',134,1,0 UNION ALL
select NULL,1065,'P  ',134,2,0 UNION ALL
select NULL,1066,'P  ',134,4,0 UNION ALL
select NULL,1067,'P  ',134,8,0 UNION ALL
select NULL,1068,'P  ',134,16,0 UNION ALL
select NULL,1069,'P  ',134,32,0 UNION ALL
select NULL,1070,'P  ',134,64,0 UNION ALL
select NULL,1071,'P  ',134,128,0 UNION ALL
select NULL,1072,'P  ',135,1,0 UNION ALL
select NULL,1073,'P  ',135,2,0 UNION ALL
select NULL,1074,'P  ',135,4,0 UNION ALL
select NULL,1075,'P  ',135,8,0 UNION ALL
select NULL,1076,'P  ',135,16,0 UNION ALL
select NULL,1077,'P  ',135,32,0 UNION ALL
select NULL,1078,'P  ',135,64,0 UNION ALL
select NULL,1079,'P  ',135,128,0 UNION ALL
select NULL,1080,'P  ',136,1,0 UNION ALL
select NULL,1081,'P  ',136,2,0 UNION ALL
select NULL,1082,'P  ',136,4,0 UNION ALL
select NULL,1083,'P  ',136,8,0 UNION ALL
select NULL,1084,'P  ',136,16,0 UNION ALL
select NULL,1085,'P  ',136,32,0 UNION ALL
select NULL,1086,'P  ',136,64,0 UNION ALL
select NULL,1087,'P  ',136,128,0 UNION ALL
select NULL,1088,'P  ',137,1,0 UNION ALL
select NULL,1089,'P  ',137,2,0 UNION ALL
select NULL,1090,'P  ',137,4,0 UNION ALL
select NULL,1091,'P  ',137,8,0 UNION ALL
select NULL,1092,'P  ',137,16,0 UNION ALL
select NULL,1093,'P  ',137,32,0 UNION ALL
select NULL,1094,'P  ',137,64,0 UNION ALL
select NULL,1095,'P  ',137,128,0 UNION ALL
select NULL,1096,'P  ',138,1,0 UNION ALL
select NULL,1097,'P  ',138,2,0 UNION ALL
select NULL,1098,'P  ',138,4,0 UNION ALL
select NULL,1099,'P  ',138,8,0 UNION ALL
select NULL,1100,'P  ',138,16,0 UNION ALL
select NULL,1101,'P  ',138,32,0 UNION ALL
select NULL,1102,'P  ',138,64,0 UNION ALL
select NULL,1103,'P  ',138,128,0 UNION ALL
select NULL,1104,'P  ',139,1,0 UNION ALL
select NULL,1105,'P  ',139,2,0 UNION ALL
select NULL,1106,'P  ',139,4,0 UNION ALL
select NULL,1107,'P  ',139,8,0 UNION ALL
select NULL,1108,'P  ',139,16,0 UNION ALL
select NULL,1109,'P  ',139,32,0 UNION ALL
select NULL,1110,'P  ',139,64,0 UNION ALL
select NULL,1111,'P  ',139,128,0 UNION ALL
select NULL,1112,'P  ',140,1,0 UNION ALL
select NULL,1113,'P  ',140,2,0 UNION ALL
select NULL,1114,'P  ',140,4,0 UNION ALL
select NULL,1115,'P  ',140,8,0 UNION ALL
select NULL,1116,'P  ',140,16,0 UNION ALL
select NULL,1117,'P  ',140,32,0 UNION ALL
select NULL,1118,'P  ',140,64,0 UNION ALL
select NULL,1119,'P  ',140,128,0 UNION ALL
select NULL,1120,'P  ',141,1,0 UNION ALL
select NULL,1121,'P  ',141,2,0 UNION ALL
select NULL,1122,'P  ',141,4,0 UNION ALL
select NULL,1123,'P  ',141,8,0 UNION ALL
select NULL,1124,'P  ',141,16,0 UNION ALL
select NULL,1125,'P  ',141,32,0 UNION ALL
select NULL,1126,'P  ',141,64,0 UNION ALL
select NULL,1127,'P  ',141,128,0 UNION ALL
select NULL,1128,'P  ',142,1,0 UNION ALL
select NULL,1129,'P  ',142,2,0 UNION ALL
select NULL,1130,'P  ',142,4,0 UNION ALL
select NULL,1131,'P  ',142,8,0 UNION ALL
select NULL,1132,'P  ',142,16,0 UNION ALL
select NULL,1133,'P  ',142,32,0 UNION ALL
select NULL,1134,'P  ',142,64,0 UNION ALL
select NULL,1135,'P  ',142,128,0 UNION ALL
select NULL,1136,'P  ',143,1,0 UNION ALL
select NULL,1137,'P  ',143,2,0 UNION ALL
select NULL,1138,'P  ',143,4,0 UNION ALL
select NULL,1139,'P  ',143,8,0 UNION ALL
select NULL,1140,'P  ',143,16,0 UNION ALL
select NULL,1141,'P  ',143,32,0 UNION ALL
select NULL,1142,'P  ',143,64,0 UNION ALL
select NULL,1143,'P  ',143,128,0 UNION ALL
select NULL,1144,'P  ',144,1,0 UNION ALL
select NULL,1145,'P  ',144,2,0 UNION ALL
select NULL,1146,'P  ',144,4,0 UNION ALL
select NULL,1147,'P  ',144,8,0 UNION ALL
select NULL,1148,'P  ',144,16,0 UNION ALL
select NULL,1149,'P  ',144,32,0 UNION ALL
select NULL,1150,'P  ',144,64,0 UNION ALL
select NULL,1151,'P  ',144,128,0 UNION ALL
select NULL,1152,'P  ',145,1,0 UNION ALL
select NULL,1153,'P  ',145,2,0 UNION ALL
select NULL,1154,'P  ',145,4,0 UNION ALL
select NULL,1155,'P  ',145,8,0 UNION ALL
select NULL,1156,'P  ',145,16,0 UNION ALL
select NULL,1157,'P  ',145,32,0 UNION ALL
select NULL,1158,'P  ',145,64,0 UNION ALL
select NULL,1159,'P  ',145,128,0 UNION ALL
select NULL,1160,'P  ',146,1,0 UNION ALL
select NULL,1161,'P  ',146,2,0 UNION ALL
select NULL,1162,'P  ',146,4,0 UNION ALL
select NULL,1163,'P  ',146,8,0 UNION ALL
select NULL,1164,'P  ',146,16,0 UNION ALL
select NULL,1165,'P  ',146,32,0 UNION ALL
select NULL,1166,'P  ',146,64,0 UNION ALL
select NULL,1167,'P  ',146,128,0 UNION ALL
select NULL,1168,'P  ',147,1,0 UNION ALL
select NULL,1169,'P  ',147,2,0 UNION ALL
select NULL,1170,'P  ',147,4,0 UNION ALL
select NULL,1171,'P  ',147,8,0 UNION ALL
select NULL,1172,'P  ',147,16,0 UNION ALL
select NULL,1173,'P  ',147,32,0 UNION ALL
select NULL,1174,'P  ',147,64,0 UNION ALL
select NULL,1175,'P  ',147,128,0 UNION ALL
select NULL,1176,'P  ',148,1,0 UNION ALL
select NULL,1177,'P  ',148,2,0 UNION ALL
select NULL,1178,'P  ',148,4,0 UNION ALL
select NULL,1179,'P  ',148,8,0 UNION ALL
select NULL,1180,'P  ',148,16,0 UNION ALL
select NULL,1181,'P  ',148,32,0 UNION ALL
select NULL,1182,'P  ',148,64,0 UNION ALL
select NULL,1183,'P  ',148,128,0 UNION ALL
select NULL,1184,'P  ',149,1,0 UNION ALL
select NULL,1185,'P  ',149,2,0 UNION ALL
select NULL,1186,'P  ',149,4,0 UNION ALL
select NULL,1187,'P  ',149,8,0 UNION ALL
select NULL,1188,'P  ',149,16,0 UNION ALL
select NULL,1189,'P  ',149,32,0 UNION ALL
select NULL,1190,'P  ',149,64,0 UNION ALL
select NULL,1191,'P  ',149,128,0 UNION ALL
select NULL,1192,'P  ',150,1,0 UNION ALL
select NULL,1193,'P  ',150,2,0 UNION ALL
select NULL,1194,'P  ',150,4,0 UNION ALL
select NULL,1195,'P  ',150,8,0 UNION ALL
select NULL,1196,'P  ',150,16,0 UNION ALL
select NULL,1197,'P  ',150,32,0 UNION ALL
select NULL,1198,'P  ',150,64,0 UNION ALL
select NULL,1199,'P  ',150,128,0 UNION ALL
select NULL,1200,'P  ',151,1,0 UNION ALL
select NULL,1201,'P  ',151,2,0 UNION ALL
select NULL,1202,'P  ',151,4,0 UNION ALL
select NULL,1203,'P  ',151,8,0 UNION ALL
select NULL,1204,'P  ',151,16,0 UNION ALL
select NULL,1205,'P  ',151,32,0 UNION ALL
select NULL,1206,'P  ',151,64,0 UNION ALL
select NULL,1207,'P  ',151,128,0 UNION ALL
select NULL,1208,'P  ',152,1,0 UNION ALL
select NULL,1209,'P  ',152,2,0 UNION ALL
select NULL,1210,'P  ',152,4,0 UNION ALL
select NULL,1211,'P  ',152,8,0 UNION ALL
select NULL,1212,'P  ',152,16,0 UNION ALL
select NULL,1213,'P  ',152,32,0 UNION ALL
select NULL,1214,'P  ',152,64,0 UNION ALL
select NULL,1215,'P  ',152,128,0 UNION ALL
select NULL,1216,'P  ',153,1,0 UNION ALL
select NULL,1217,'P  ',153,2,0 UNION ALL
select NULL,1218,'P  ',153,4,0 UNION ALL
select NULL,1219,'P  ',153,8,0 UNION ALL
select NULL,1220,'P  ',153,16,0 UNION ALL
select NULL,1221,'P  ',153,32,0 UNION ALL
select NULL,1222,'P  ',153,64,0 UNION ALL
select NULL,1223,'P  ',153,128,0 UNION ALL
select NULL,1224,'P  ',154,1,0 UNION ALL
select NULL,1225,'P  ',154,2,0 UNION ALL
select NULL,1226,'P  ',154,4,0 UNION ALL
select NULL,1227,'P  ',154,8,0 UNION ALL
select NULL,1228,'P  ',154,16,0 UNION ALL
select NULL,1229,'P  ',154,32,0 UNION ALL
select NULL,1230,'P  ',154,64,0 UNION ALL
select NULL,1231,'P  ',154,128,0 UNION ALL
select NULL,1232,'P  ',155,1,0 UNION ALL
select NULL,1233,'P  ',155,2,0 UNION ALL
select NULL,1234,'P  ',155,4,0 UNION ALL
select NULL,1235,'P  ',155,8,0 UNION ALL
select NULL,1236,'P  ',155,16,0 UNION ALL
select NULL,1237,'P  ',155,32,0 UNION ALL
select NULL,1238,'P  ',155,64,0 UNION ALL
select NULL,1239,'P  ',155,128,0 UNION ALL
select NULL,1240,'P  ',156,1,0 UNION ALL
select NULL,1241,'P  ',156,2,0 UNION ALL
select NULL,1242,'P  ',156,4,0 UNION ALL
select NULL,1243,'P  ',156,8,0 UNION ALL
select NULL,1244,'P  ',156,16,0 UNION ALL
select NULL,1245,'P  ',156,32,0 UNION ALL
select NULL,1246,'P  ',156,64,0 UNION ALL
select NULL,1247,'P  ',156,128,0 UNION ALL
select NULL,1248,'P  ',157,1,0 UNION ALL
select NULL,1249,'P  ',157,2,0 UNION ALL
select NULL,1250,'P  ',157,4,0 UNION ALL
select NULL,1251,'P  ',157,8,0 UNION ALL
select NULL,1252,'P  ',157,16,0 UNION ALL
select NULL,1253,'P  ',157,32,0 UNION ALL
select NULL,1254,'P  ',157,64,0 UNION ALL
select NULL,1255,'P  ',157,128,0 UNION ALL
select NULL,1256,'P  ',158,1,0 UNION ALL
select NULL,1257,'P  ',158,2,0 UNION ALL
select NULL,1258,'P  ',158,4,0 UNION ALL
select NULL,1259,'P  ',158,8,0 UNION ALL
select NULL,1260,'P  ',158,16,0 UNION ALL
select NULL,1261,'P  ',158,32,0 UNION ALL
select NULL,1262,'P  ',158,64,0 UNION ALL
select NULL,1263,'P  ',158,128,0 UNION ALL
select NULL,1264,'P  ',159,1,0 UNION ALL
select NULL,1265,'P  ',159,2,0 UNION ALL
select NULL,1266,'P  ',159,4,0 UNION ALL
select NULL,1267,'P  ',159,8,0 UNION ALL
select NULL,1268,'P  ',159,16,0 UNION ALL
select NULL,1269,'P  ',159,32,0 UNION ALL
select NULL,1270,'P  ',159,64,0 UNION ALL
select NULL,1271,'P  ',159,128,0 UNION ALL
select NULL,1272,'P  ',160,1,0 UNION ALL
select NULL,1273,'P  ',160,2,0 UNION ALL
select NULL,1274,'P  ',160,4,0 UNION ALL
select NULL,1275,'P  ',160,8,0 UNION ALL
select NULL,1276,'P  ',160,16,0 UNION ALL
select NULL,1277,'P  ',160,32,0 UNION ALL
select NULL,1278,'P  ',160,64,0 UNION ALL
select NULL,1279,'P  ',160,128,0 UNION ALL
select NULL,1280,'P  ',161,1,0 UNION ALL
select NULL,1281,'P  ',161,2,0 UNION ALL
select NULL,1282,'P  ',161,4,0 UNION ALL
select NULL,1283,'P  ',161,8,0 UNION ALL
select NULL,1284,'P  ',161,16,0 UNION ALL
select NULL,1285,'P  ',161,32,0 UNION ALL
select NULL,1286,'P  ',161,64,0 UNION ALL
select NULL,1287,'P  ',161,128,0 UNION ALL
select NULL,1288,'P  ',162,1,0 UNION ALL
select NULL,1289,'P  ',162,2,0 UNION ALL
select NULL,1290,'P  ',162,4,0 UNION ALL
select NULL,1291,'P  ',162,8,0 UNION ALL
select NULL,1292,'P  ',162,16,0 UNION ALL
select NULL,1293,'P  ',162,32,0 UNION ALL
select NULL,1294,'P  ',162,64,0 UNION ALL
select NULL,1295,'P  ',162,128,0 UNION ALL
select NULL,1296,'P  ',163,1,0 UNION ALL
select NULL,1297,'P  ',163,2,0 UNION ALL
select NULL,1298,'P  ',163,4,0 UNION ALL
select NULL,1299,'P  ',163,8,0 UNION ALL
select NULL,1300,'P  ',163,16,0 UNION ALL
select NULL,1301,'P  ',163,32,0 UNION ALL
select NULL,1302,'P  ',163,64,0 UNION ALL
select NULL,1303,'P  ',163,128,0 UNION ALL
select NULL,1304,'P  ',164,1,0 UNION ALL
select NULL,1305,'P  ',164,2,0 UNION ALL
select NULL,1306,'P  ',164,4,0 UNION ALL
select NULL,1307,'P  ',164,8,0 UNION ALL
select NULL,1308,'P  ',164,16,0 UNION ALL
select NULL,1309,'P  ',164,32,0 UNION ALL
select NULL,1310,'P  ',164,64,0 UNION ALL
select NULL,1311,'P  ',164,128,0 UNION ALL
select NULL,1312,'P  ',165,1,0 UNION ALL
select NULL,1313,'P  ',165,2,0 UNION ALL
select NULL,1314,'P  ',165,4,0 UNION ALL
select NULL,1315,'P  ',165,8,0 UNION ALL
select NULL,1316,'P  ',165,16,0 UNION ALL
select NULL,1317,'P  ',165,32,0 UNION ALL
select NULL,1318,'P  ',165,64,0 UNION ALL
select NULL,1319,'P  ',165,128,0 UNION ALL
select NULL,1320,'P  ',166,1,0 UNION ALL
select NULL,1321,'P  ',166,2,0 UNION ALL
select NULL,1322,'P  ',166,4,0 UNION ALL
select NULL,1323,'P  ',166,8,0 UNION ALL
select NULL,1324,'P  ',166,16,0 UNION ALL
select NULL,1325,'P  ',166,32,0 UNION ALL
select NULL,1326,'P  ',166,64,0 UNION ALL
select NULL,1327,'P  ',166,128,0 UNION ALL
select NULL,1328,'P  ',167,1,0 UNION ALL
select NULL,1329,'P  ',167,2,0 UNION ALL
select NULL,1330,'P  ',167,4,0 UNION ALL
select NULL,1331,'P  ',167,8,0 UNION ALL
select NULL,1332,'P  ',167,16,0 UNION ALL
select NULL,1333,'P  ',167,32,0 UNION ALL
select NULL,1334,'P  ',167,64,0 UNION ALL
select NULL,1335,'P  ',167,128,0 UNION ALL
select NULL,1336,'P  ',168,1,0 UNION ALL
select NULL,1337,'P  ',168,2,0 UNION ALL
select NULL,1338,'P  ',168,4,0 UNION ALL
select NULL,1339,'P  ',168,8,0 UNION ALL
select NULL,1340,'P  ',168,16,0 UNION ALL
select NULL,1341,'P  ',168,32,0 UNION ALL
select NULL,1342,'P  ',168,64,0 UNION ALL
select NULL,1343,'P  ',168,128,0 UNION ALL
select NULL,1344,'P  ',169,1,0 UNION ALL
select NULL,1345,'P  ',169,2,0 UNION ALL
select NULL,1346,'P  ',169,4,0 UNION ALL
select NULL,1347,'P  ',169,8,0 UNION ALL
select NULL,1348,'P  ',169,16,0 UNION ALL
select NULL,1349,'P  ',169,32,0 UNION ALL
select NULL,1350,'P  ',169,64,0 UNION ALL
select NULL,1351,'P  ',169,128,0 UNION ALL
select NULL,1352,'P  ',170,1,0 UNION ALL
select NULL,1353,'P  ',170,2,0 UNION ALL
select NULL,1354,'P  ',170,4,0 UNION ALL
select NULL,1355,'P  ',170,8,0 UNION ALL
select NULL,1356,'P  ',170,16,0 UNION ALL
select NULL,1357,'P  ',170,32,0 UNION ALL
select NULL,1358,'P  ',170,64,0 UNION ALL
select NULL,1359,'P  ',170,128,0 UNION ALL
select NULL,1360,'P  ',171,1,0 UNION ALL
select NULL,1361,'P  ',171,2,0 UNION ALL
select NULL,1362,'P  ',171,4,0 UNION ALL
select NULL,1363,'P  ',171,8,0 UNION ALL
select NULL,1364,'P  ',171,16,0 UNION ALL
select NULL,1365,'P  ',171,32,0 UNION ALL
select NULL,1366,'P  ',171,64,0 UNION ALL
select NULL,1367,'P  ',171,128,0 UNION ALL
select NULL,1368,'P  ',172,1,0 UNION ALL
select NULL,1369,'P  ',172,2,0 UNION ALL
select NULL,1370,'P  ',172,4,0 UNION ALL
select NULL,1371,'P  ',172,8,0 UNION ALL
select NULL,1372,'P  ',172,16,0 UNION ALL
select NULL,1373,'P  ',172,32,0 UNION ALL
select NULL,1374,'P  ',172,64,0 UNION ALL
select NULL,1375,'P  ',172,128,0 UNION ALL
select NULL,1376,'P  ',173,1,0 UNION ALL
select NULL,1377,'P  ',173,2,0 UNION ALL
select NULL,1378,'P  ',173,4,0 UNION ALL
select NULL,1379,'P  ',173,8,0 UNION ALL
select NULL,1380,'P  ',173,16,0 UNION ALL
select NULL,1381,'P  ',173,32,0 UNION ALL
select NULL,1382,'P  ',173,64,0 UNION ALL
select NULL,1383,'P  ',173,128,0 UNION ALL
select NULL,1384,'P  ',174,1,0 UNION ALL
select NULL,1385,'P  ',174,2,0 UNION ALL
select NULL,1386,'P  ',174,4,0 UNION ALL
select NULL,1387,'P  ',174,8,0 UNION ALL
select NULL,1388,'P  ',174,16,0 UNION ALL
select NULL,1389,'P  ',174,32,0 UNION ALL
select NULL,1390,'P  ',174,64,0 UNION ALL
select NULL,1391,'P  ',174,128,0 UNION ALL
select NULL,1392,'P  ',175,1,0 UNION ALL
select NULL,1393,'P  ',175,2,0 UNION ALL
select NULL,1394,'P  ',175,4,0 UNION ALL
select NULL,1395,'P  ',175,8,0 UNION ALL
select NULL,1396,'P  ',175,16,0 UNION ALL
select NULL,1397,'P  ',175,32,0 UNION ALL
select NULL,1398,'P  ',175,64,0 UNION ALL
select NULL,1399,'P  ',175,128,0 UNION ALL
select NULL,1400,'P  ',176,1,0 UNION ALL
select NULL,1401,'P  ',176,2,0 UNION ALL
select NULL,1402,'P  ',176,4,0 UNION ALL
select NULL,1403,'P  ',176,8,0 UNION ALL
select NULL,1404,'P  ',176,16,0 UNION ALL
select NULL,1405,'P  ',176,32,0 UNION ALL
select NULL,1406,'P  ',176,64,0 UNION ALL
select NULL,1407,'P  ',176,128,0 UNION ALL
select NULL,1408,'P  ',177,1,0 UNION ALL
select NULL,1409,'P  ',177,2,0 UNION ALL
select NULL,1410,'P  ',177,4,0 UNION ALL
select NULL,1411,'P  ',177,8,0 UNION ALL
select NULL,1412,'P  ',177,16,0 UNION ALL
select NULL,1413,'P  ',177,32,0 UNION ALL
select NULL,1414,'P  ',177,64,0 UNION ALL
select NULL,1415,'P  ',177,128,0 UNION ALL
select NULL,1416,'P  ',178,1,0 UNION ALL
select NULL,1417,'P  ',178,2,0 UNION ALL
select NULL,1418,'P  ',178,4,0 UNION ALL
select NULL,1419,'P  ',178,8,0 UNION ALL
select NULL,1420,'P  ',178,16,0 UNION ALL
select NULL,1421,'P  ',178,32,0 UNION ALL
select NULL,1422,'P  ',178,64,0 UNION ALL
select NULL,1423,'P  ',178,128,0 UNION ALL
select NULL,1424,'P  ',179,1,0 UNION ALL
select NULL,1425,'P  ',179,2,0 UNION ALL
select NULL,1426,'P  ',179,4,0 UNION ALL
select NULL,1427,'P  ',179,8,0 UNION ALL
select NULL,1428,'P  ',179,16,0 UNION ALL
select NULL,1429,'P  ',179,32,0 UNION ALL
select NULL,1430,'P  ',179,64,0 UNION ALL
select NULL,1431,'P  ',179,128,0 UNION ALL
select NULL,1432,'P  ',180,1,0 UNION ALL
select NULL,1433,'P  ',180,2,0 UNION ALL
select NULL,1434,'P  ',180,4,0 UNION ALL
select NULL,1435,'P  ',180,8,0 UNION ALL
select NULL,1436,'P  ',180,16,0 UNION ALL
select NULL,1437,'P  ',180,32,0 UNION ALL
select NULL,1438,'P  ',180,64,0 UNION ALL
select NULL,1439,'P  ',180,128,0 UNION ALL
select NULL,1440,'P  ',181,1,0 UNION ALL
select NULL,1441,'P  ',181,2,0 UNION ALL
select NULL,1442,'P  ',181,4,0 UNION ALL
select NULL,1443,'P  ',181,8,0 UNION ALL
select NULL,1444,'P  ',181,16,0 UNION ALL
select NULL,1445,'P  ',181,32,0 UNION ALL
select NULL,1446,'P  ',181,64,0 UNION ALL
select NULL,1447,'P  ',181,128,0 UNION ALL
select NULL,1448,'P  ',182,1,0 UNION ALL
select NULL,1449,'P  ',182,2,0 UNION ALL
select NULL,1450,'P  ',182,4,0 UNION ALL
select NULL,1451,'P  ',182,8,0 UNION ALL
select NULL,1452,'P  ',182,16,0 UNION ALL
select NULL,1453,'P  ',182,32,0 UNION ALL
select NULL,1454,'P  ',182,64,0 UNION ALL
select NULL,1455,'P  ',182,128,0 UNION ALL
select NULL,1456,'P  ',183,1,0 UNION ALL
select NULL,1457,'P  ',183,2,0 UNION ALL
select NULL,1458,'P  ',183,4,0 UNION ALL
select NULL,1459,'P  ',183,8,0 UNION ALL
select NULL,1460,'P  ',183,16,0 UNION ALL
select NULL,1461,'P  ',183,32,0 UNION ALL
select NULL,1462,'P  ',183,64,0 UNION ALL
select NULL,1463,'P  ',183,128,0 UNION ALL
select NULL,1464,'P  ',184,1,0 UNION ALL
select NULL,1465,'P  ',184,2,0 UNION ALL
select NULL,1466,'P  ',184,4,0 UNION ALL
select NULL,1467,'P  ',184,8,0 UNION ALL
select NULL,1468,'P  ',184,16,0 UNION ALL
select NULL,1469,'P  ',184,32,0 UNION ALL
select NULL,1470,'P  ',184,64,0 UNION ALL
select NULL,1471,'P  ',184,128,0 UNION ALL
select NULL,1472,'P  ',185,1,0 UNION ALL
select NULL,1473,'P  ',185,2,0 UNION ALL
select NULL,1474,'P  ',185,4,0 UNION ALL
select NULL,1475,'P  ',185,8,0 UNION ALL
select NULL,1476,'P  ',185,16,0 UNION ALL
select NULL,1477,'P  ',185,32,0 UNION ALL
select NULL,1478,'P  ',185,64,0 UNION ALL
select NULL,1479,'P  ',185,128,0 UNION ALL
select NULL,1480,'P  ',186,1,0 UNION ALL
select NULL,1481,'P  ',186,2,0 UNION ALL
select NULL,1482,'P  ',186,4,0 UNION ALL
select NULL,1483,'P  ',186,8,0 UNION ALL
select NULL,1484,'P  ',186,16,0 UNION ALL
select NULL,1485,'P  ',186,32,0 UNION ALL
select NULL,1486,'P  ',186,64,0 UNION ALL
select NULL,1487,'P  ',186,128,0 UNION ALL
select NULL,1488,'P  ',187,1,0 UNION ALL
select NULL,1489,'P  ',187,2,0 UNION ALL
select NULL,1490,'P  ',187,4,0 UNION ALL
select NULL,1491,'P  ',187,8,0 UNION ALL
select NULL,1492,'P  ',187,16,0 UNION ALL
select NULL,1493,'P  ',187,32,0 UNION ALL
select NULL,1494,'P  ',187,64,0 UNION ALL
select NULL,1495,'P  ',187,128,0 UNION ALL
select NULL,1496,'P  ',188,1,0 UNION ALL
select NULL,1497,'P  ',188,2,0 UNION ALL
select NULL,1498,'P  ',188,4,0 UNION ALL
select NULL,1499,'P  ',188,8,0 UNION ALL
select NULL,1500,'P  ',188,16,0 UNION ALL
select NULL,1501,'P  ',188,32,0 UNION ALL
select NULL,1502,'P  ',188,64,0 UNION ALL
select NULL,1503,'P  ',188,128,0 UNION ALL
select NULL,1504,'P  ',189,1,0 UNION ALL
select NULL,1505,'P  ',189,2,0 UNION ALL
select NULL,1506,'P  ',189,4,0 UNION ALL
select NULL,1507,'P  ',189,8,0 UNION ALL
select NULL,1508,'P  ',189,16,0 UNION ALL
select NULL,1509,'P  ',189,32,0 UNION ALL
select NULL,1510,'P  ',189,64,0 UNION ALL
select NULL,1511,'P  ',189,128,0 UNION ALL
select NULL,1512,'P  ',190,1,0 UNION ALL
select NULL,1513,'P  ',190,2,0 UNION ALL
select NULL,1514,'P  ',190,4,0 UNION ALL
select NULL,1515,'P  ',190,8,0 UNION ALL
select NULL,1516,'P  ',190,16,0 UNION ALL
select NULL,1517,'P  ',190,32,0 UNION ALL
select NULL,1518,'P  ',190,64,0 UNION ALL
select NULL,1519,'P  ',190,128,0 UNION ALL
select NULL,1520,'P  ',191,1,0 UNION ALL
select NULL,1521,'P  ',191,2,0 UNION ALL
select NULL,1522,'P  ',191,4,0 UNION ALL
select NULL,1523,'P  ',191,8,0 UNION ALL
select NULL,1524,'P  ',191,16,0 UNION ALL
select NULL,1525,'P  ',191,32,0 UNION ALL
select NULL,1526,'P  ',191,64,0 UNION ALL
select NULL,1527,'P  ',191,128,0 UNION ALL
select NULL,1528,'P  ',192,1,0 UNION ALL
select NULL,1529,'P  ',192,2,0 UNION ALL
select NULL,1530,'P  ',192,4,0 UNION ALL
select NULL,1531,'P  ',192,8,0 UNION ALL
select NULL,1532,'P  ',192,16,0 UNION ALL
select NULL,1533,'P  ',192,32,0 UNION ALL
select NULL,1534,'P  ',192,64,0 UNION ALL
select NULL,1535,'P  ',192,128,0 UNION ALL
select NULL,1536,'P  ',193,1,0 UNION ALL
select NULL,1537,'P  ',193,2,0 UNION ALL
select NULL,1538,'P  ',193,4,0 UNION ALL
select NULL,1539,'P  ',193,8,0 UNION ALL
select NULL,1540,'P  ',193,16,0 UNION ALL
select NULL,1541,'P  ',193,32,0 UNION ALL
select NULL,1542,'P  ',193,64,0 UNION ALL
select NULL,1543,'P  ',193,128,0 UNION ALL
select NULL,1544,'P  ',194,1,0 UNION ALL
select NULL,1545,'P  ',194,2,0 UNION ALL
select NULL,1546,'P  ',194,4,0 UNION ALL
select NULL,1547,'P  ',194,8,0 UNION ALL
select NULL,1548,'P  ',194,16,0 UNION ALL
select NULL,1549,'P  ',194,32,0 UNION ALL
select NULL,1550,'P  ',194,64,0 UNION ALL
select NULL,1551,'P  ',194,128,0 UNION ALL
select NULL,1552,'P  ',195,1,0 UNION ALL
select NULL,1553,'P  ',195,2,0 UNION ALL
select NULL,1554,'P  ',195,4,0 UNION ALL
select NULL,1555,'P  ',195,8,0 UNION ALL
select NULL,1556,'P  ',195,16,0 UNION ALL
select NULL,1557,'P  ',195,32,0 UNION ALL
select NULL,1558,'P  ',195,64,0 UNION ALL
select NULL,1559,'P  ',195,128,0 UNION ALL
select NULL,1560,'P  ',196,1,0 UNION ALL
select NULL,1561,'P  ',196,2,0 UNION ALL
select NULL,1562,'P  ',196,4,0 UNION ALL
select NULL,1563,'P  ',196,8,0 UNION ALL
select NULL,1564,'P  ',196,16,0 UNION ALL
select NULL,1565,'P  ',196,32,0 UNION ALL
select NULL,1566,'P  ',196,64,0 UNION ALL
select NULL,1567,'P  ',196,128,0 UNION ALL
select NULL,1568,'P  ',197,1,0 UNION ALL
select NULL,1569,'P  ',197,2,0 UNION ALL
select NULL,1570,'P  ',197,4,0 UNION ALL
select NULL,1571,'P  ',197,8,0 UNION ALL
select NULL,1572,'P  ',197,16,0 UNION ALL
select NULL,1573,'P  ',197,32,0 UNION ALL
select NULL,1574,'P  ',197,64,0 UNION ALL
select NULL,1575,'P  ',197,128,0 UNION ALL
select NULL,1576,'P  ',198,1,0 UNION ALL
select NULL,1577,'P  ',198,2,0 UNION ALL
select NULL,1578,'P  ',198,4,0 UNION ALL
select NULL,1579,'P  ',198,8,0 UNION ALL
select NULL,1580,'P  ',198,16,0 UNION ALL
select NULL,1581,'P  ',198,32,0 UNION ALL
select NULL,1582,'P  ',198,64,0 UNION ALL
select NULL,1583,'P  ',198,128,0 UNION ALL
select NULL,1584,'P  ',199,1,0 UNION ALL
select NULL,1585,'P  ',199,2,0 UNION ALL
select NULL,1586,'P  ',199,4,0 UNION ALL
select NULL,1587,'P  ',199,8,0 UNION ALL
select NULL,1588,'P  ',199,16,0 UNION ALL
select NULL,1589,'P  ',199,32,0 UNION ALL
select NULL,1590,'P  ',199,64,0 UNION ALL
select NULL,1591,'P  ',199,128,0 UNION ALL
select NULL,1592,'P  ',200,1,0 UNION ALL
select NULL,1593,'P  ',200,2,0 UNION ALL
select NULL,1594,'P  ',200,4,0 UNION ALL
select NULL,1595,'P  ',200,8,0 UNION ALL
select NULL,1596,'P  ',200,16,0 UNION ALL
select NULL,1597,'P  ',200,32,0 UNION ALL
select NULL,1598,'P  ',200,64,0 UNION ALL
select NULL,1599,'P  ',200,128,0 UNION ALL
select NULL,1600,'P  ',201,1,0 UNION ALL
select NULL,1601,'P  ',201,2,0 UNION ALL
select NULL,1602,'P  ',201,4,0 UNION ALL
select NULL,1603,'P  ',201,8,0 UNION ALL
select NULL,1604,'P  ',201,16,0 UNION ALL
select NULL,1605,'P  ',201,32,0 UNION ALL
select NULL,1606,'P  ',201,64,0 UNION ALL
select NULL,1607,'P  ',201,128,0 UNION ALL
select NULL,1608,'P  ',202,1,0 UNION ALL
select NULL,1609,'P  ',202,2,0 UNION ALL
select NULL,1610,'P  ',202,4,0 UNION ALL
select NULL,1611,'P  ',202,8,0 UNION ALL
select NULL,1612,'P  ',202,16,0 UNION ALL
select NULL,1613,'P  ',202,32,0 UNION ALL
select NULL,1614,'P  ',202,64,0 UNION ALL
select NULL,1615,'P  ',202,128,0 UNION ALL
select NULL,1616,'P  ',203,1,0 UNION ALL
select NULL,1617,'P  ',203,2,0 UNION ALL
select NULL,1618,'P  ',203,4,0 UNION ALL
select NULL,1619,'P  ',203,8,0 UNION ALL
select NULL,1620,'P  ',203,16,0 UNION ALL
select NULL,1621,'P  ',203,32,0 UNION ALL
select NULL,1622,'P  ',203,64,0 UNION ALL
select NULL,1623,'P  ',203,128,0 UNION ALL
select NULL,1624,'P  ',204,1,0 UNION ALL
select NULL,1625,'P  ',204,2,0 UNION ALL
select NULL,1626,'P  ',204,4,0 UNION ALL
select NULL,1627,'P  ',204,8,0 UNION ALL
select NULL,1628,'P  ',204,16,0 UNION ALL
select NULL,1629,'P  ',204,32,0 UNION ALL
select NULL,1630,'P  ',204,64,0 UNION ALL
select NULL,1631,'P  ',204,128,0 UNION ALL
select NULL,1632,'P  ',205,1,0 UNION ALL
select NULL,1633,'P  ',205,2,0 UNION ALL
select NULL,1634,'P  ',205,4,0 UNION ALL
select NULL,1635,'P  ',205,8,0 UNION ALL
select NULL,1636,'P  ',205,16,0 UNION ALL
select NULL,1637,'P  ',205,32,0 UNION ALL
select NULL,1638,'P  ',205,64,0 UNION ALL
select NULL,1639,'P  ',205,128,0 UNION ALL
select NULL,1640,'P  ',206,1,0 UNION ALL
select NULL,1641,'P  ',206,2,0 UNION ALL
select NULL,1642,'P  ',206,4,0 UNION ALL
select NULL,1643,'P  ',206,8,0 UNION ALL
select NULL,1644,'P  ',206,16,0 UNION ALL
select NULL,1645,'P  ',206,32,0 UNION ALL
select NULL,1646,'P  ',206,64,0 UNION ALL
select NULL,1647,'P  ',206,128,0 UNION ALL
select NULL,1648,'P  ',207,1,0 UNION ALL
select NULL,1649,'P  ',207,2,0 UNION ALL
select NULL,1650,'P  ',207,4,0 UNION ALL
select NULL,1651,'P  ',207,8,0 UNION ALL
select NULL,1652,'P  ',207,16,0 UNION ALL
select NULL,1653,'P  ',207,32,0 UNION ALL
select NULL,1654,'P  ',207,64,0 UNION ALL
select NULL,1655,'P  ',207,128,0 UNION ALL
select NULL,1656,'P  ',208,1,0 UNION ALL
select NULL,1657,'P  ',208,2,0 UNION ALL
select NULL,1658,'P  ',208,4,0 UNION ALL
select NULL,1659,'P  ',208,8,0 UNION ALL
select NULL,1660,'P  ',208,16,0 UNION ALL
select NULL,1661,'P  ',208,32,0 UNION ALL
select NULL,1662,'P  ',208,64,0 UNION ALL
select NULL,1663,'P  ',208,128,0 UNION ALL
select NULL,1664,'P  ',209,1,0 UNION ALL
select NULL,1665,'P  ',209,2,0 UNION ALL
select NULL,1666,'P  ',209,4,0 UNION ALL
select NULL,1667,'P  ',209,8,0 UNION ALL
select NULL,1668,'P  ',209,16,0 UNION ALL
select NULL,1669,'P  ',209,32,0 UNION ALL
select NULL,1670,'P  ',209,64,0 UNION ALL
select NULL,1671,'P  ',209,128,0 UNION ALL
select NULL,1672,'P  ',210,1,0 UNION ALL
select NULL,1673,'P  ',210,2,0 UNION ALL
select NULL,1674,'P  ',210,4,0 UNION ALL
select NULL,1675,'P  ',210,8,0 UNION ALL
select NULL,1676,'P  ',210,16,0 UNION ALL
select NULL,1677,'P  ',210,32,0 UNION ALL
select NULL,1678,'P  ',210,64,0 UNION ALL
select NULL,1679,'P  ',210,128,0 UNION ALL
select NULL,1680,'P  ',211,1,0 UNION ALL
select NULL,1681,'P  ',211,2,0 UNION ALL
select NULL,1682,'P  ',211,4,0 UNION ALL
select NULL,1683,'P  ',211,8,0 UNION ALL
select NULL,1684,'P  ',211,16,0 UNION ALL
select NULL,1685,'P  ',211,32,0 UNION ALL
select NULL,1686,'P  ',211,64,0 UNION ALL
select NULL,1687,'P  ',211,128,0 UNION ALL
select NULL,1688,'P  ',212,1,0 UNION ALL
select NULL,1689,'P  ',212,2,0 UNION ALL
select NULL,1690,'P  ',212,4,0 UNION ALL
select NULL,1691,'P  ',212,8,0 UNION ALL
select NULL,1692,'P  ',212,16,0 UNION ALL
select NULL,1693,'P  ',212,32,0 UNION ALL
select NULL,1694,'P  ',212,64,0 UNION ALL
select NULL,1695,'P  ',212,128,0 UNION ALL
select NULL,1696,'P  ',213,1,0 UNION ALL
select NULL,1697,'P  ',213,2,0 UNION ALL
select NULL,1698,'P  ',213,4,0 UNION ALL
select NULL,1699,'P  ',213,8,0 UNION ALL
select NULL,1700,'P  ',213,16,0 UNION ALL
select NULL,1701,'P  ',213,32,0 UNION ALL
select NULL,1702,'P  ',213,64,0 UNION ALL
select NULL,1703,'P  ',213,128,0 UNION ALL
select NULL,1704,'P  ',214,1,0 UNION ALL
select NULL,1705,'P  ',214,2,0 UNION ALL
select NULL,1706,'P  ',214,4,0 UNION ALL
select NULL,1707,'P  ',214,8,0 UNION ALL
select NULL,1708,'P  ',214,16,0 UNION ALL
select NULL,1709,'P  ',214,32,0 UNION ALL
select NULL,1710,'P  ',214,64,0 UNION ALL
select NULL,1711,'P  ',214,128,0 UNION ALL
select NULL,1712,'P  ',215,1,0 UNION ALL
select NULL,1713,'P  ',215,2,0 UNION ALL
select NULL,1714,'P  ',215,4,0 UNION ALL
select NULL,1715,'P  ',215,8,0 UNION ALL
select NULL,1716,'P  ',215,16,0 UNION ALL
select NULL,1717,'P  ',215,32,0 UNION ALL
select NULL,1718,'P  ',215,64,0 UNION ALL
select NULL,1719,'P  ',215,128,0 UNION ALL
select NULL,1720,'P  ',216,1,0 UNION ALL
select NULL,1721,'P  ',216,2,0 UNION ALL
select NULL,1722,'P  ',216,4,0 UNION ALL
select NULL,1723,'P  ',216,8,0 UNION ALL
select NULL,1724,'P  ',216,16,0 UNION ALL
select NULL,1725,'P  ',216,32,0 UNION ALL
select NULL,1726,'P  ',216,64,0 UNION ALL
select NULL,1727,'P  ',216,128,0 UNION ALL
select NULL,1728,'P  ',217,1,0 UNION ALL
select NULL,1729,'P  ',217,2,0 UNION ALL
select NULL,1730,'P  ',217,4,0 UNION ALL
select NULL,1731,'P  ',217,8,0 UNION ALL
select NULL,1732,'P  ',217,16,0 UNION ALL
select NULL,1733,'P  ',217,32,0 UNION ALL
select NULL,1734,'P  ',217,64,0 UNION ALL
select NULL,1735,'P  ',217,128,0 UNION ALL
select NULL,1736,'P  ',218,1,0 UNION ALL
select NULL,1737,'P  ',218,2,0 UNION ALL
select NULL,1738,'P  ',218,4,0 UNION ALL
select NULL,1739,'P  ',218,8,0 UNION ALL
select NULL,1740,'P  ',218,16,0 UNION ALL
select NULL,1741,'P  ',218,32,0 UNION ALL
select NULL,1742,'P  ',218,64,0 UNION ALL
select NULL,1743,'P  ',218,128,0 UNION ALL
select NULL,1744,'P  ',219,1,0 UNION ALL
select NULL,1745,'P  ',219,2,0 UNION ALL
select NULL,1746,'P  ',219,4,0 UNION ALL
select NULL,1747,'P  ',219,8,0 UNION ALL
select NULL,1748,'P  ',219,16,0 UNION ALL
select NULL,1749,'P  ',219,32,0 UNION ALL
select NULL,1750,'P  ',219,64,0 UNION ALL
select NULL,1751,'P  ',219,128,0 UNION ALL
select NULL,1752,'P  ',220,1,0 UNION ALL
select NULL,1753,'P  ',220,2,0 UNION ALL
select NULL,1754,'P  ',220,4,0 UNION ALL
select NULL,1755,'P  ',220,8,0 UNION ALL
select NULL,1756,'P  ',220,16,0 UNION ALL
select NULL,1757,'P  ',220,32,0 UNION ALL
select NULL,1758,'P  ',220,64,0 UNION ALL
select NULL,1759,'P  ',220,128,0 UNION ALL
select NULL,1760,'P  ',221,1,0 UNION ALL
select NULL,1761,'P  ',221,2,0 UNION ALL
select NULL,1762,'P  ',221,4,0 UNION ALL
select NULL,1763,'P  ',221,8,0 UNION ALL
select NULL,1764,'P  ',221,16,0 UNION ALL
select NULL,1765,'P  ',221,32,0 UNION ALL
select NULL,1766,'P  ',221,64,0 UNION ALL
select NULL,1767,'P  ',221,128,0 UNION ALL
select NULL,1768,'P  ',222,1,0 UNION ALL
select NULL,1769,'P  ',222,2,0 UNION ALL
select NULL,1770,'P  ',222,4,0 UNION ALL
select NULL,1771,'P  ',222,8,0 UNION ALL
select NULL,1772,'P  ',222,16,0 UNION ALL
select NULL,1773,'P  ',222,32,0 UNION ALL
select NULL,1774,'P  ',222,64,0 UNION ALL
select NULL,1775,'P  ',222,128,0 UNION ALL
select NULL,1776,'P  ',223,1,0 UNION ALL
select NULL,1777,'P  ',223,2,0 UNION ALL
select NULL,1778,'P  ',223,4,0 UNION ALL
select NULL,1779,'P  ',223,8,0 UNION ALL
select NULL,1780,'P  ',223,16,0 UNION ALL
select NULL,1781,'P  ',223,32,0 UNION ALL
select NULL,1782,'P  ',223,64,0 UNION ALL
select NULL,1783,'P  ',223,128,0 UNION ALL
select NULL,1784,'P  ',224,1,0 UNION ALL
select NULL,1785,'P  ',224,2,0 UNION ALL
select NULL,1786,'P  ',224,4,0 UNION ALL
select NULL,1787,'P  ',224,8,0 UNION ALL
select NULL,1788,'P  ',224,16,0 UNION ALL
select NULL,1789,'P  ',224,32,0 UNION ALL
select NULL,1790,'P  ',224,64,0 UNION ALL
select NULL,1791,'P  ',224,128,0 UNION ALL
select NULL,1792,'P  ',225,1,0 UNION ALL
select NULL,1793,'P  ',225,2,0 UNION ALL
select NULL,1794,'P  ',225,4,0 UNION ALL
select NULL,1795,'P  ',225,8,0 UNION ALL
select NULL,1796,'P  ',225,16,0 UNION ALL
select NULL,1797,'P  ',225,32,0 UNION ALL
select NULL,1798,'P  ',225,64,0 UNION ALL
select NULL,1799,'P  ',225,128,0 UNION ALL
select NULL,1800,'P  ',226,1,0 UNION ALL
select NULL,1801,'P  ',226,2,0 UNION ALL
select NULL,1802,'P  ',226,4,0 UNION ALL
select NULL,1803,'P  ',226,8,0 UNION ALL
select NULL,1804,'P  ',226,16,0 UNION ALL
select NULL,1805,'P  ',226,32,0 UNION ALL
select NULL,1806,'P  ',226,64,0 UNION ALL
select NULL,1807,'P  ',226,128,0 UNION ALL
select NULL,1808,'P  ',227,1,0 UNION ALL
select NULL,1809,'P  ',227,2,0 UNION ALL
select NULL,1810,'P  ',227,4,0 UNION ALL
select NULL,1811,'P  ',227,8,0 UNION ALL
select NULL,1812,'P  ',227,16,0 UNION ALL
select NULL,1813,'P  ',227,32,0 UNION ALL
select NULL,1814,'P  ',227,64,0 UNION ALL
select NULL,1815,'P  ',227,128,0 UNION ALL
select NULL,1816,'P  ',228,1,0 UNION ALL
select NULL,1817,'P  ',228,2,0 UNION ALL
select NULL,1818,'P  ',228,4,0 UNION ALL
select NULL,1819,'P  ',228,8,0 UNION ALL
select NULL,1820,'P  ',228,16,0 UNION ALL
select NULL,1821,'P  ',228,32,0 UNION ALL
select NULL,1822,'P  ',228,64,0 UNION ALL
select NULL,1823,'P  ',228,128,0 UNION ALL
select NULL,1824,'P  ',229,1,0 UNION ALL
select NULL,1825,'P  ',229,2,0 UNION ALL
select NULL,1826,'P  ',229,4,0 UNION ALL
select NULL,1827,'P  ',229,8,0 UNION ALL
select NULL,1828,'P  ',229,16,0 UNION ALL
select NULL,1829,'P  ',229,32,0 UNION ALL
select NULL,1830,'P  ',229,64,0 UNION ALL
select NULL,1831,'P  ',229,128,0 UNION ALL
select NULL,1832,'P  ',230,1,0 UNION ALL
select NULL,1833,'P  ',230,2,0 UNION ALL
select NULL,1834,'P  ',230,4,0 UNION ALL
select NULL,1835,'P  ',230,8,0 UNION ALL
select NULL,1836,'P  ',230,16,0 UNION ALL
select NULL,1837,'P  ',230,32,0 UNION ALL
select NULL,1838,'P  ',230,64,0 UNION ALL
select NULL,1839,'P  ',230,128,0 UNION ALL
select NULL,1840,'P  ',231,1,0 UNION ALL
select NULL,1841,'P  ',231,2,0 UNION ALL
select NULL,1842,'P  ',231,4,0 UNION ALL
select NULL,1843,'P  ',231,8,0 UNION ALL
select NULL,1844,'P  ',231,16,0 UNION ALL
select NULL,1845,'P  ',231,32,0 UNION ALL
select NULL,1846,'P  ',231,64,0 UNION ALL
select NULL,1847,'P  ',231,128,0 UNION ALL
select NULL,1848,'P  ',232,1,0 UNION ALL
select NULL,1849,'P  ',232,2,0 UNION ALL
select NULL,1850,'P  ',232,4,0 UNION ALL
select NULL,1851,'P  ',232,8,0 UNION ALL
select NULL,1852,'P  ',232,16,0 UNION ALL
select NULL,1853,'P  ',232,32,0 UNION ALL
select NULL,1854,'P  ',232,64,0 UNION ALL
select NULL,1855,'P  ',232,128,0 UNION ALL
select NULL,1856,'P  ',233,1,0 UNION ALL
select NULL,1857,'P  ',233,2,0 UNION ALL
select NULL,1858,'P  ',233,4,0 UNION ALL
select NULL,1859,'P  ',233,8,0 UNION ALL
select NULL,1860,'P  ',233,16,0 UNION ALL
select NULL,1861,'P  ',233,32,0 UNION ALL
select NULL,1862,'P  ',233,64,0 UNION ALL
select NULL,1863,'P  ',233,128,0 UNION ALL
select NULL,1864,'P  ',234,1,0 UNION ALL
select NULL,1865,'P  ',234,2,0 UNION ALL
select NULL,1866,'P  ',234,4,0 UNION ALL
select NULL,1867,'P  ',234,8,0 UNION ALL
select NULL,1868,'P  ',234,16,0 UNION ALL
select NULL,1869,'P  ',234,32,0 UNION ALL
select NULL,1870,'P  ',234,64,0 UNION ALL
select NULL,1871,'P  ',234,128,0 UNION ALL
select NULL,1872,'P  ',235,1,0 UNION ALL
select NULL,1873,'P  ',235,2,0 UNION ALL
select NULL,1874,'P  ',235,4,0 UNION ALL
select NULL,1875,'P  ',235,8,0 UNION ALL
select NULL,1876,'P  ',235,16,0 UNION ALL
select NULL,1877,'P  ',235,32,0 UNION ALL
select NULL,1878,'P  ',235,64,0 UNION ALL
select NULL,1879,'P  ',235,128,0 UNION ALL
select NULL,1880,'P  ',236,1,0 UNION ALL
select NULL,1881,'P  ',236,2,0 UNION ALL
select NULL,1882,'P  ',236,4,0 UNION ALL
select NULL,1883,'P  ',236,8,0 UNION ALL
select NULL,1884,'P  ',236,16,0 UNION ALL
select NULL,1885,'P  ',236,32,0 UNION ALL
select NULL,1886,'P  ',236,64,0 UNION ALL
select NULL,1887,'P  ',236,128,0 UNION ALL
select NULL,1888,'P  ',237,1,0 UNION ALL
select NULL,1889,'P  ',237,2,0 UNION ALL
select NULL,1890,'P  ',237,4,0 UNION ALL
select NULL,1891,'P  ',237,8,0 UNION ALL
select NULL,1892,'P  ',237,16,0 UNION ALL
select NULL,1893,'P  ',237,32,0 UNION ALL
select NULL,1894,'P  ',237,64,0 UNION ALL
select NULL,1895,'P  ',237,128,0 UNION ALL
select NULL,1896,'P  ',238,1,0 UNION ALL
select NULL,1897,'P  ',238,2,0 UNION ALL
select NULL,1898,'P  ',238,4,0 UNION ALL
select NULL,1899,'P  ',238,8,0 UNION ALL
select NULL,1900,'P  ',238,16,0 UNION ALL
select NULL,1901,'P  ',238,32,0 UNION ALL
select NULL,1902,'P  ',238,64,0 UNION ALL
select NULL,1903,'P  ',238,128,0 UNION ALL
select NULL,1904,'P  ',239,1,0 UNION ALL
select NULL,1905,'P  ',239,2,0 UNION ALL
select NULL,1906,'P  ',239,4,0 UNION ALL
select NULL,1907,'P  ',239,8,0 UNION ALL
select NULL,1908,'P  ',239,16,0 UNION ALL
select NULL,1909,'P  ',239,32,0 UNION ALL
select NULL,1910,'P  ',239,64,0 UNION ALL
select NULL,1911,'P  ',239,128,0 UNION ALL
select NULL,1912,'P  ',240,1,0 UNION ALL
select NULL,1913,'P  ',240,2,0 UNION ALL
select NULL,1914,'P  ',240,4,0 UNION ALL
select NULL,1915,'P  ',240,8,0 UNION ALL
select NULL,1916,'P  ',240,16,0 UNION ALL
select NULL,1917,'P  ',240,32,0 UNION ALL
select NULL,1918,'P  ',240,64,0 UNION ALL
select NULL,1919,'P  ',240,128,0 UNION ALL
select NULL,1920,'P  ',241,1,0 UNION ALL
select NULL,1921,'P  ',241,2,0 UNION ALL
select NULL,1922,'P  ',241,4,0 UNION ALL
select NULL,1923,'P  ',241,8,0 UNION ALL
select NULL,1924,'P  ',241,16,0 UNION ALL
select NULL,1925,'P  ',241,32,0 UNION ALL
select NULL,1926,'P  ',241,64,0 UNION ALL
select NULL,1927,'P  ',241,128,0 UNION ALL
select NULL,1928,'P  ',242,1,0 UNION ALL
select NULL,1929,'P  ',242,2,0 UNION ALL
select NULL,1930,'P  ',242,4,0 UNION ALL
select NULL,1931,'P  ',242,8,0 UNION ALL
select NULL,1932,'P  ',242,16,0 UNION ALL
select NULL,1933,'P  ',242,32,0 UNION ALL
select NULL,1934,'P  ',242,64,0 UNION ALL
select NULL,1935,'P  ',242,128,0 UNION ALL
select NULL,1936,'P  ',243,1,0 UNION ALL
select NULL,1937,'P  ',243,2,0 UNION ALL
select NULL,1938,'P  ',243,4,0 UNION ALL
select NULL,1939,'P  ',243,8,0 UNION ALL
select NULL,1940,'P  ',243,16,0 UNION ALL
select NULL,1941,'P  ',243,32,0 UNION ALL
select NULL,1942,'P  ',243,64,0 UNION ALL
select NULL,1943,'P  ',243,128,0 UNION ALL
select NULL,1944,'P  ',244,1,0 UNION ALL
select NULL,1945,'P  ',244,2,0 UNION ALL
select NULL,1946,'P  ',244,4,0 UNION ALL
select NULL,1947,'P  ',244,8,0 UNION ALL
select NULL,1948,'P  ',244,16,0 UNION ALL
select NULL,1949,'P  ',244,32,0 UNION ALL
select NULL,1950,'P  ',244,64,0 UNION ALL
select NULL,1951,'P  ',244,128,0 UNION ALL
select NULL,1952,'P  ',245,1,0 UNION ALL
select NULL,1953,'P  ',245,2,0 UNION ALL
select NULL,1954,'P  ',245,4,0 UNION ALL
select NULL,1955,'P  ',245,8,0 UNION ALL
select NULL,1956,'P  ',245,16,0 UNION ALL
select NULL,1957,'P  ',245,32,0 UNION ALL
select NULL,1958,'P  ',245,64,0 UNION ALL
select NULL,1959,'P  ',245,128,0 UNION ALL
select NULL,1960,'P  ',246,1,0 UNION ALL
select NULL,1961,'P  ',246,2,0 UNION ALL
select NULL,1962,'P  ',246,4,0 UNION ALL
select NULL,1963,'P  ',246,8,0 UNION ALL
select NULL,1964,'P  ',246,16,0 UNION ALL
select NULL,1965,'P  ',246,32,0 UNION ALL
select NULL,1966,'P  ',246,64,0 UNION ALL
select NULL,1967,'P  ',246,128,0 UNION ALL
select NULL,1968,'P  ',247,1,0 UNION ALL
select NULL,1969,'P  ',247,2,0 UNION ALL
select NULL,1970,'P  ',247,4,0 UNION ALL
select NULL,1971,'P  ',247,8,0 UNION ALL
select NULL,1972,'P  ',247,16,0 UNION ALL
select NULL,1973,'P  ',247,32,0 UNION ALL
select NULL,1974,'P  ',247,64,0 UNION ALL
select NULL,1975,'P  ',247,128,0 UNION ALL
select NULL,1976,'P  ',248,1,0 UNION ALL
select NULL,1977,'P  ',248,2,0 UNION ALL
select NULL,1978,'P  ',248,4,0 UNION ALL
select NULL,1979,'P  ',248,8,0 UNION ALL
select NULL,1980,'P  ',248,16,0 UNION ALL
select NULL,1981,'P  ',248,32,0 UNION ALL
select NULL,1982,'P  ',248,64,0 UNION ALL
select NULL,1983,'P  ',248,128,0 UNION ALL
select NULL,1984,'P  ',249,1,0 UNION ALL
select NULL,1985,'P  ',249,2,0 UNION ALL
select NULL,1986,'P  ',249,4,0 UNION ALL
select NULL,1987,'P  ',249,8,0 UNION ALL
select NULL,1988,'P  ',249,16,0 UNION ALL
select NULL,1989,'P  ',249,32,0 UNION ALL
select NULL,1990,'P  ',249,64,0 UNION ALL
select NULL,1991,'P  ',249,128,0 UNION ALL
select NULL,1992,'P  ',250,1,0 UNION ALL
select NULL,1993,'P  ',250,2,0 UNION ALL
select NULL,1994,'P  ',250,4,0 UNION ALL
select NULL,1995,'P  ',250,8,0 UNION ALL
select NULL,1996,'P  ',250,16,0 UNION ALL
select NULL,1997,'P  ',250,32,0 UNION ALL
select NULL,1998,'P  ',250,64,0 UNION ALL
select NULL,1999,'P  ',250,128,0 UNION ALL
select NULL,2000,'P  ',251,1,0 UNION ALL
select NULL,2001,'P  ',251,2,0 UNION ALL
select NULL,2002,'P  ',251,4,0 UNION ALL
select NULL,2003,'P  ',251,8,0 UNION ALL
select NULL,2004,'P  ',251,16,0 UNION ALL
select NULL,2005,'P  ',251,32,0 UNION ALL
select NULL,2006,'P  ',251,64,0 UNION ALL
select NULL,2007,'P  ',251,128,0 UNION ALL
select NULL,2008,'P  ',252,1,0 UNION ALL
select NULL,2009,'P  ',252,2,0 UNION ALL
select NULL,2010,'P  ',252,4,0 UNION ALL
select NULL,2011,'P  ',252,8,0 UNION ALL
select NULL,2012,'P  ',252,16,0 UNION ALL
select NULL,2013,'P  ',252,32,0 UNION ALL
select NULL,2014,'P  ',252,64,0 UNION ALL
select NULL,2015,'P  ',252,128,0 UNION ALL
select NULL,2016,'P  ',253,1,0 UNION ALL
select NULL,2017,'P  ',253,2,0 UNION ALL
select NULL,2018,'P  ',253,4,0 UNION ALL
select NULL,2019,'P  ',253,8,0 UNION ALL
select NULL,2020,'P  ',253,16,0 UNION ALL
select NULL,2021,'P  ',253,32,0 UNION ALL
select NULL,2022,'P  ',253,64,0 UNION ALL
select NULL,2023,'P  ',253,128,0 UNION ALL
select NULL,2024,'P  ',254,1,0 UNION ALL
select NULL,2025,'P  ',254,2,0 UNION ALL
select NULL,2026,'P  ',254,4,0 UNION ALL
select NULL,2027,'P  ',254,8,0 UNION ALL
select NULL,2028,'P  ',254,16,0 UNION ALL
select NULL,2029,'P  ',254,32,0 UNION ALL
select NULL,2030,'P  ',254,64,0 UNION ALL
select NULL,2031,'P  ',254,128,0 UNION ALL
select NULL,2032,'P  ',255,1,0 UNION ALL
select NULL,2033,'P  ',255,2,0 UNION ALL
select NULL,2034,'P  ',255,4,0 UNION ALL
select NULL,2035,'P  ',255,8,0 UNION ALL
select NULL,2036,'P  ',255,16,0 UNION ALL
select NULL,2037,'P  ',255,32,0 UNION ALL
select NULL,2038,'P  ',255,64,0 UNION ALL
select NULL,2039,'P  ',255,128,0 UNION ALL
select NULL,2040,'P  ',256,1,0 UNION ALL
select NULL,2041,'P  ',256,2,0 UNION ALL
select NULL,2042,'P  ',256,4,0 UNION ALL
select NULL,2043,'P  ',256,8,0 UNION ALL
select NULL,2044,'P  ',256,16,0 UNION ALL
select NULL,2045,'P  ',256,32,0 UNION ALL
select NULL,2046,'P  ',256,64,0 UNION ALL
select NULL,2047,'P  ',256,128,0 UNION ALL
select ' (rpt)',-32768,'R  ',NULL,NULL,0 UNION ALL
select '',0,'R  ',NULL,NULL,0 UNION ALL
select 'REPORT TYPES',0,'R  ',NULL,NULL,0 UNION ALL
select 'SF LOCK TYPES',0,'SFL',NULL,NULL,0 UNION ALL
select 'Extent Lock - Exclusive',8,'SFL',NULL,NULL,0 UNION ALL
select 'Extent Lock - Update',9,'SFL',NULL,NULL,0 UNION ALL
select 'Extent Lock - Next',11,'SFL',NULL,NULL,0 UNION ALL
select 'Extent Lock - Previous',12,'SFL',NULL,NULL,0 UNION ALL
select '@@OPTIONS',0,'SOP',NULL,NULL,0 UNION ALL
select 'disable_def_cnst_check',1,'SOP',NULL,NULL,1 UNION ALL
select 'implicit_transactions',2,'SOP',NULL,NULL,1 UNION ALL
select 'cursor_close_on_commit',4,'SOP',NULL,NULL,1 UNION ALL
select 'ansi_warnings',8,'SOP',NULL,NULL,1 UNION ALL
select 'ansi_padding',16,'SOP',NULL,NULL,1 UNION ALL
select 'ansi_nulls',32,'SOP',NULL,NULL,1 UNION ALL
select 'arithabort',64,'SOP',NULL,NULL,1 UNION ALL
select 'arithignore',128,'SOP',NULL,NULL,1 UNION ALL
select 'quoted_identifier',256,'SOP',NULL,NULL,1 UNION ALL
select 'nocount',512,'SOP',NULL,NULL,1 UNION ALL
select 'ansi_null_dflt_on',1024,'SOP',NULL,NULL,1 UNION ALL
select 'ansi_null_dflt_off',2048,'SOP',NULL,NULL,1 UNION ALL
select 'concat_null_yields_null',4096,'SOP',NULL,NULL,1 UNION ALL
select 'numeric_roundabort',8192,'SOP',NULL,NULL,1 UNION ALL
select 'xact_abort',16384,'SOP',NULL,NULL,1 UNION ALL
select 'sysadmin',16,'SRV',0,NULL,0 UNION ALL
select 'System Administrators',16,'SRV',-1,NULL,0 UNION ALL
select 'Security Administrators',32,'SRV',-1,NULL,0 UNION ALL
select 'securityadmin',32,'SRV',0,NULL,0 UNION ALL
select 'Server Administrators',64,'SRV',-1,NULL,0 UNION ALL
select 'serveradmin',64,'SRV',0,NULL,0 UNION ALL
select 'Setup Administrators',128,'SRV',-1,NULL,0 UNION ALL
select 'setupadmin',128,'SRV',0,NULL,0 UNION ALL
select 'Process Administrators',256,'SRV',-1,NULL,0 UNION ALL
select 'processadmin',256,'SRV',0,NULL,0 UNION ALL
select 'Disk Administrators',512,'SRV',-1,NULL,0 UNION ALL
select 'diskadmin',512,'SRV',0,NULL,0 UNION ALL
select 'Database Creators',1024,'SRV',-1,NULL,0 UNION ALL
select 'dbcreator',1024,'SRV',0,NULL,0 UNION ALL
select 'Bulk Insert Administrators',4096,'SRV',-1,NULL,0 UNION ALL
select 'bulkadmin',4096,'SRV',0,NULL,0 UNION ALL
select 'SYSPROTECTS.ACTION',0,'T  ',NULL,NULL,0 UNION ALL
select 'References',26,'T  ',NULL,NULL,0 UNION ALL
select 'Create Function',178,'T  ',NULL,NULL,0 UNION ALL
select 'Select',193,'T  ',NULL,NULL,0 UNION ALL
select 'Insert',195,'T  ',NULL,NULL,0 UNION ALL
select 'Delete',196,'T  ',NULL,NULL,0 UNION ALL
select 'Update',197,'T  ',NULL,NULL,0 UNION ALL
select 'Create Table',198,'T  ',NULL,NULL,0 UNION ALL
select 'Create Database',203,'T  ',NULL,NULL,0 UNION ALL
select 'Grant_WGO',204,'T  ',NULL,NULL,0 UNION ALL
select 'Grant',205,'T  ',NULL,NULL,0 UNION ALL
select 'Deny',206,'T  ',NULL,NULL,0 UNION ALL
select 'Create View',207,'T  ',NULL,NULL,0 UNION ALL
select 'Create Procedure',222,'T  ',NULL,NULL,0 UNION ALL
select 'Execute',224,'T  ',NULL,NULL,0 UNION ALL
select 'Backup Database',228,'T  ',NULL,NULL,0 UNION ALL
select 'Create Default',233,'T  ',NULL,NULL,0 UNION ALL
select 'Backup Transaction',235,'T  ',NULL,NULL,0 UNION ALL
select 'Create Rule',236,'T  ',NULL,NULL,0 UNION ALL
select 'SYSDEVICES STATUS',0,'V  ',NULL,NULL,0 UNION ALL
select 'default disk',1,'V  ',NULL,NULL,0 UNION ALL
select 'physical disk',2,'V  ',NULL,NULL,0 UNION ALL
select 'logical disk',4,'V  ',NULL,NULL,0 UNION ALL
select 'backup device',16,'V  ',NULL,NULL,0 UNION ALL
select 'serial writes',32,'V  ',NULL,NULL,0 UNION ALL
select 'read only',4096,'V  ',0,1,0 UNION ALL
select 'deferred',8192,'V  ',0,1,0;

 --[/noformat] 
----
// end::sql_modules_definition[]


