= [docs].[RepoObject_Adoc]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--AntoraReferencedList:
:ExistsProperty--AntoraReferencingList:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_IndexPatternColumnDatatype:
:ExistsProperty--pk_IndexPatternColumnName:
:ExistsProperty--pk_IndexSemanticGroup:
:ExistsProperty--ReferencedObjectList:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
D5E0B563-4291-EB11-84F2-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
912722304
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-11 12:09:59
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-RepoObject_guid]]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObject_gross.adoc#column-RepoObject_guid[repo.RepoObject_gross.RepoObject_guid]
--

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_guid[docs.RepoObject_Adoc_T.RepoObject_guid]
--


[[column-AdocContent]]
=== AdocContent

[cols="d,m,m,m,m,d"]
|===
|
|AdocContent
|nvarchar(max)
|NOT NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-AdocContent[docs.RepoObject_Adoc_T.AdocContent]
--


[[column-is_DocsOutput]]
=== is_DocsOutput

[cols="d,m,m,m,m,d"]
|===
|
|is_DocsOutput
|int
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-is_DocsOutput[docs.RepoObject_Adoc_T.is_DocsOutput]
--


[[column-PropertyCount]]
=== PropertyCount

[cols="d,m,m,m,m,d"]
|===
|
|PropertyCount
|int
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-PropertyCount[docs.RepoObject_Adoc_T.PropertyCount]
--


[[column-RepoObject_fullname]]
=== RepoObject_fullname

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_fullname
|nvarchar(261)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_fullname[docs.RepoObject_Adoc_T.RepoObject_fullname]
--


[[column-RepoObject_fullname2]]
=== RepoObject_fullname2

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_fullname2
|nvarchar(257)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_fullname2[docs.RepoObject_Adoc_T.RepoObject_fullname2]
--


[[column-RepoObject_schema_name]]
=== RepoObject_schema_name

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_schema_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_schema_name[docs.RepoObject_Adoc_T.RepoObject_schema_name]
--


[[column-SysObject_fullname]]
=== SysObject_fullname

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_fullname
|nvarchar(261)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_fullname[docs.RepoObject_Adoc_T.SysObject_fullname]
--


[[column-SysObject_fullname2]]
=== SysObject_fullname2

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_fullname2
|nvarchar(257)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_fullname2[docs.RepoObject_Adoc_T.SysObject_fullname2]
--


[[column-SysObject_schema_name]]
=== SysObject_schema_name

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_schema_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_schema_name[docs.RepoObject_Adoc_T.SysObject_schema_name]
--


[[column-SysObject_type]]
=== SysObject_type

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_type
|char(2)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_type[docs.RepoObject_Adoc_T.SysObject_type]
--


[[column-SysObject_type_name]]
=== SysObject_type_name

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_type_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_type_name[docs.RepoObject_Adoc_T.SysObject_type_name]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-RepoObject_guid>>*
|uniqueidentifier
|NOT NULL
|
|












// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-AdocContent>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-is_DocsOutput>>
|int
|NULL
|
|

|
|<<column-PropertyCount>>
|int
|NULL
|
|

|
|<<column-RepoObject_fullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-RepoObject_fullname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-RepoObject_schema_name>>
|nvarchar(128)
|NULL
|
|

|
|<<column-SysObject_fullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-SysObject_fullname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-SysObject_schema_name>>
|nvarchar(128)
|NULL
|
|

|
|<<column-SysObject_type>>
|char(2)
|NULL
|
|

|
|<<column-SysObject_type_name>>
|nvarchar(128)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-PK_RepoObject_Adoc]]
=== PK_RepoObject_Adoc

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_repoobject_guid[RepoObject_guid]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::AdocUspSteps[]

// end::AdocUspSteps[]


== example1

// tag::example1[]

// end::example1[]


== example2

// tag::example2[]

// end::example2[]


== example3

// tag::example3[]

// end::example3[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_RepoObject_guid[]

// end::usp_persistence_RepoObject_guid[]


== UspExamples

// tag::UspExamples[]

// end::UspExamples[]


== UspParameters

// tag::UspParameters[]

// end::UspParameters[]


== persistence_source_RepoObject_xref

// tag::persistence_source_RepoObject_xref[]

// end::persistence_source_RepoObject_xref[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::MS_Description[]

// end::MS_Description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_RepoObject_fullname[]

// end::persistence_source_RepoObject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_RepoObject_fullname2[]

// end::persistence_source_RepoObject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_RepoObject_guid[]

// end::persistence_source_RepoObject_guid[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== example4

// tag::example4[]

// end::example4[]


== example5

// tag::example5[]

// end::example5[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== AntoraReferencedList

// tag::AntoraReferencedList[]
* xref:docs.RepoObject_ColumnList.adoc[]
* xref:docs.RepoObject_IndexList_T.adoc[]
* xref:docs.RepoObject_ParameterList.adoc[]
* xref:repo.RepoObject_gross.adoc[]
* xref:repo.RepoObjectProperty.adoc[]
* xref:repo.RepoObjectProperty_cross.adoc[]
// end::AntoraReferencedList[]


== AntoraReferencingList

// tag::AntoraReferencingList[]
* xref:docs.RepoObject_Adoc_T.adoc[]
* xref:docs.usp_PERSIST_RepoObject_Adoc_T.adoc[]
// end::AntoraReferencingList[]


== pk_index_guid

// tag::pk_index_guid[]
C28818B0-CA97-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_IndexPatternColumnDatatype[]
uniqueidentifier
// end::pk_IndexPatternColumnDatatype[]


== pk_IndexPatternColumnName

// tag::pk_IndexPatternColumnName[]
RepoObject_guid
// end::pk_IndexPatternColumnName[]


== pk_IndexSemanticGroup

// tag::pk_IndexSemanticGroup[]
RepoObject_guid
// end::pk_IndexSemanticGroup[]


== ReferencedObjectList

// tag::ReferencedObjectList[]
* [repo].[RepoObject_gross]
* [repo].[RepoObjectProperty]
// end::ReferencedObjectList[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----




/*
todo - direkt oder Åber extended properties
- Index List
- referencing
- referenced
*/
CREATE VIEW [docs].[RepoObject_Adoc]
AS
SELECT ro.[RepoObject_guid]
 , [is_DocsOutput] = MAX(ro.[is_DocsOutput])
 , RepoObject_fullname = MAX(ro.RepoObject_fullname)
 , RepoObject_fullname2 = MAX(ro.RepoObject_fullname2)
 , [RepoObject_schema_name] = MAX([RepoObject_schema_name])
 , SysObject_fullname = MAX(ro.SysObject_fullname)
 , SysObject_fullname2 = MAX(ro.SysObject_fullname2)
 , [SysObject_schema_name] = MAX([SysObject_schema_name])
 , SysObject_type = MAX(ro.SysObject_type)
 , SysObject_type_name = MAX(ro.SysObject_type_name)
 , AdocContent = CONCAT (
  '= '
  , MAX(ro.SysObject_fullname)
  , CHAR(13)
  , CHAR(10)
  --
  , CHAR(13)
  , CHAR(10)
  , '== existing_properties'
  , CHAR(13)
  , CHAR(10)
  , CHAR(13)
  , CHAR(10)
  , '// tag::existing_properties[]'
  , CHAR(13)
  , CHAR(10)
  , STRING_AGG(CONCAT (
    CAST('' AS NVARCHAR(max))
    , CASE 
     WHEN NOT rop.[property_nvarchar] IS NULL
      THEN ':ExistsProperty--' + rop.[property_name] + ':' + CHAR(13) + CHAR(10)
     ELSE ''
     END
    ), '') WITHIN GROUP (
    ORDER BY rop.[property_name]
    )
   , CASE 
    WHEN max(ro.sql_modules_antora) <> ''
     THEN ':ExistsProperty--sql_modules_definition:' + CHAR(13) + CHAR(10)
    END
   , CASE 
    WHEN max(ro.SysObject_type) IN (
      'U'
      , 'V'
      )
     THEN ':ExistsProperty--FK:' + CHAR(13) + CHAR(10)
    END
   , CASE 
    WHEN max(ilist.AntoraIndexList) <> ''
     THEN ':ExistsProperty--AntoraIndexList:' + CHAR(13) + CHAR(10)
    END
   , CASE 
    WHEN max(parlist.AntoraParameterList) <> ''
     THEN ':ExistsProperty--AntoraParameterList:' + CHAR(13) + CHAR(10)
    END
   , CASE 
    WHEN max(ro.SysObject_type) IN (
      'U'
      , 'V'
      , 'IF'
      )
     THEN ':ExistsProperty--Columns:' + CHAR(13) + CHAR(10)
    END
   , '// end::existing_properties[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== RepoObject_guid'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::RepoObject_guid[]'
   , CHAR(13)
   , CHAR(10)
   , ro.[RepoObject_guid]
   , CHAR(13)
   , CHAR(10)
   , '// end::RepoObject_guid[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== SysObject_type'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::SysObject_type[]'
   , CHAR(13)
   , CHAR(10)
   , MAX(ro.SysObject_type)
   , CHAR(13)
   , CHAR(10)
   , '// end::SysObject_type[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== SysObject_type_name'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::SysObject_type_name[]'
   , CHAR(13)
   , CHAR(10)
   , MAX(ro.SysObject_type_name)
   , CHAR(13)
   , CHAR(10)
   , '// end::SysObject_type_name[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== SysObject_id'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::SysObject_id[]'
   , CHAR(13)
   , CHAR(10)
   , max(ro.SysObject_id)
   , CHAR(13)
   , CHAR(10)
   , '// end::SysObject_id[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== SysObject_modify_date'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::SysObject_modify_date[]'
   , CHAR(13)
   , CHAR(10)
   , CONVERT(NVARCHAR(20), max(ro.SysObject_modify_date), 120)
   , CHAR(13)
   , CHAR(10)
   , '// end::SysObject_modify_date[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== AntoraColumnDetails'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::AntoraColumnDetails[]'
   , CHAR(13)
   , CHAR(10)
   , max(clist.AntoraColumnDetails)
   , CHAR(13)
   , CHAR(10)
   , '// end::AntoraColumnDetails[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== AntoraPkColumnTableRows'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::AntoraPkColumnTableRows[]'
   , CHAR(13)
   , CHAR(10)
   , max(clist.AntoraPkColumnTableRows)
   , CHAR(13)
   , CHAR(10)
   , '// end::AntoraPkColumnTableRows[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== AntoraNonPkColumnTableRows'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::AntoraNonPkColumnTableRows[]'
   , CHAR(13)
   , CHAR(10)
   , max(clist.AntoraNonPkColumnTableRows)
   , CHAR(13)
   , CHAR(10)
   , '// end::AntoraNonPkColumnTableRows[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== AntoraIndexList'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::AntoraIndexList[]'
   , CHAR(13)
   , CHAR(10)
   , max(ilist.AntoraIndexList)
   , CHAR(13)
   , CHAR(10)
   , '// end::AntoraIndexList[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== AntoraParameterList'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::AntoraParameterList[]'
   , CHAR(13)
   , CHAR(10)
   , max(parlist.AntoraParameterList)
   , CHAR(13)
   , CHAR(10)
   , '// end::AntoraParameterList[]'
   , CHAR(13)
   , CHAR(10)
   ----
   --, CHAR(13)
   --, CHAR(10)
   --, '== pk_index_guid'
   --, CHAR(13)
   --, CHAR(10)
   --, CHAR(13)
   --, CHAR(10)
   --, '// tag::pk_index_guid[]'
   --, CHAR(13)
   --, CHAR(10)
   --, max(ro.pk_index_guid)
   --, CHAR(13)
   --, CHAR(10)
   --, '// end::pk_index_guid[]'
   --, CHAR(13)
   --, CHAR(10)
   ----
   --, CHAR(13)
   --, CHAR(10)
   --, '== pk_IndexPatternColumnDatatype'
   --, CHAR(13)
   --, CHAR(10)
   --, CHAR(13)
   --, CHAR(10)
   --, '// tag::pk_IndexPatternColumnDatatype[]'
   --, CHAR(13)
   --, CHAR(10)
   --, max(ro.pk_IndexPatternColumnDatatype)
   --, CHAR(13)
   --, CHAR(10)
   --, '// end::pk_IndexPatternColumnDatatype[]'
   --, CHAR(13)
   --, CHAR(10)
   ----
   --, CHAR(13)
   --, CHAR(10)
   --, '== pk_IndexPatternColumnName'
   --, CHAR(13)
   --, CHAR(10)
   --, CHAR(13)
   --, CHAR(10)
   --, '// tag::pk_IndexPatternColumnName[]'
   --, CHAR(13)
   --, CHAR(10)
   --, max(ro.pk_IndexPatternColumnName)
   --, CHAR(13)
   --, CHAR(10)
   --, '// end::pk_IndexPatternColumnName[]'
   --, CHAR(13)
   --, CHAR(10)
   ----
   --, CHAR(13)
   --, CHAR(10)
   --, '== pk_IndexSemanticGroup'
   --, CHAR(13)
   --, CHAR(10)
   --, CHAR(13)
   --, CHAR(10)
   --, '// tag::pk_IndexSemanticGroup[]'
   --, CHAR(13)
   --, CHAR(10)
   --, max(ro.pk_IndexSemanticGroup)
   --, CHAR(13)
   --, CHAR(10)
   --, '// end::pk_IndexSemanticGroup[]'
   --, CHAR(13)
   --, CHAR(10)
   --
   --
   --
   --, CHAR(13)
   --, CHAR(10)
   --, '== CreateColumnList'
   --, CHAR(13)
   --, CHAR(10)
   --, CHAR(13)
   --, CHAR(10)
   --, '// tag::CreateColumnList[]'
   --, CHAR(13)
   --, CHAR(10)
   --, max(ro.CreateColumnList)
   --, CHAR(13)
   --, CHAR(10)
   --, '// end::CreateColumnList[]'
   --, CHAR(13)
   --, CHAR(10)
   ----
   --, CHAR(13)
   --, CHAR(10)
   --, '== DbmlColumnList'
   --, CHAR(13)
   --, CHAR(10)
   --, CHAR(13)
   --, CHAR(10)
   --, '// tag::DbmlColumnList[]'
   --, CHAR(13)
   --, CHAR(10)
   --, max(ro.DbmlColumnList)
   --, CHAR(13)
   --, CHAR(10)
   --, '// end::DbmlColumnList[]'
   --, CHAR(13)
   --, CHAR(10)
   --
   ,
   --CASE 
   -- WHEN COUNT(DISTINCT rop.property_name) > 1
   --  THEN 
   STRING_AGG(CONCAT (
     CAST('' AS NVARCHAR(max))
     , CHAR(13)
     , CHAR(10)
     , '== '
     , rop_cross.[property_name]
     , CHAR(13)
     , CHAR(10)
     , CHAR(13)
     , CHAR(10)
     , '// tag::'
     , rop_cross.[property_name]
     , '[]'
     , CHAR(13)
     , CHAR(10)
     , rop.[property_nvarchar]
     , CHAR(13)
     , CHAR(10)
     , '// end::'
     , rop_cross.[property_name]
     , '[]'
     , CHAR(13)
     , CHAR(10)
     ), CHAR(13) + CHAR(10)) WITHIN
  GROUP (
    ORDER BY rop.[property_name]
    )
   --END
   --
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
   , '== sql_modules_definition'
   , CHAR(13)
   , CHAR(10)
   , CHAR(13)
   , CHAR(10)
   , '// tag::sql_modules_definition[]'
   , CHAR(13)
   , CHAR(10)
   , '[source,sql]'
   , CHAR(13)
   , CHAR(10)
   , '----'
   , CHAR(13)
   , CHAR(10)
   , max(ro.sql_modules_antora)
   , CHAR(13)
   , CHAR(10)
   , '----'
   , CHAR(13)
   , CHAR(10)
   , '// end::sql_modules_definition[]'
   , CHAR(13)
   , CHAR(10)
   --
   , CHAR(13)
   , CHAR(10)
  )
 , PropertyCount = COUNT(DISTINCT rop.property_name)
FROM [repo].[RepoObject_gross] ro
LEFT JOIN [repo].[RepoObjectProperty_cross] rop_cross
 ON rop_cross.RepoObject_guid = ro.RepoObject_guid
LEFT JOIN [repo].[RepoObjectProperty] rop
 ON rop.RepoObject_guid = rop_cross.RepoObject_guid
  AND rop.[property_name] = rop_cross.[property_name]
--AND NOT rop.[property_nvarchar] IS NULL
LEFT JOIN [docs].[RepoObject_ColumnList] clist
 ON clist.RepoObject_guid = ro.RepoObject_guid
LEFT JOIN [docs].[RepoObject_IndexList_T] ilist
 ON ilist.RepoObject_guid = ro.RepoObject_guid
LEFT JOIN [docs].[RepoObject_ParameterList] parlist
 ON parlist.RepoObject_guid = ro.RepoObject_guid
GROUP BY ro.[RepoObject_guid]

----
// end::sql_modules_definition[]


