= [docs].[RepoObject_Adoc]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--pk_indexsemanticgroup:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
D5E0B563-4291-EB11-84F2-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1874821741
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-15 17:29:48
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-RepoObject_guid]]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObject_gross.adoc#column-RepoObject_guid[repo.RepoObject_gross.RepoObject_guid]
--

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_guid[docs.RepoObject_Adoc_T.RepoObject_guid]
--


[[column-AdocContent]]
=== AdocContent

[cols="d,m,m,m,m,d"]
|===
|
|AdocContent
|nvarchar(max)
|NOT NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-AdocContent[docs.RepoObject_Adoc_T.AdocContent]
--


[[column-is_DocsOutput]]
=== is_DocsOutput

[cols="d,m,m,m,m,d"]
|===
|
|is_DocsOutput
|int
|NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObject_gross.adoc#column-is_DocsOutput[repo.RepoObject_gross.is_DocsOutput]
--

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-is_DocsOutput[docs.RepoObject_Adoc_T.is_DocsOutput]
--


[[column-PropertyCount]]
=== PropertyCount

[cols="d,m,m,m,m,d"]
|===
|
|PropertyCount
|int
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-PropertyCount[docs.RepoObject_Adoc_T.PropertyCount]
--


[[column-RepoObject_fullname]]
=== RepoObject_fullname

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_fullname
|nvarchar(261)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_fullname[docs.RepoObject_Adoc_T.RepoObject_fullname]
--


[[column-RepoObject_fullname2]]
=== RepoObject_fullname2

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_fullname2
|nvarchar(257)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_fullname2[docs.RepoObject_Adoc_T.RepoObject_fullname2]
--


[[column-RepoObject_schema_name]]
=== RepoObject_schema_name

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_schema_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-RepoObject_schema_name[docs.RepoObject_Adoc_T.RepoObject_schema_name]
--


[[column-SysObject_fullname]]
=== SysObject_fullname

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_fullname
|nvarchar(261)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_fullname[docs.RepoObject_Adoc_T.SysObject_fullname]
--


[[column-SysObject_fullname2]]
=== SysObject_fullname2

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_fullname2
|nvarchar(257)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_fullname2[docs.RepoObject_Adoc_T.SysObject_fullname2]
--


[[column-SysObject_schema_name]]
=== SysObject_schema_name

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_schema_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_schema_name[docs.RepoObject_Adoc_T.SysObject_schema_name]
--


[[column-SysObject_type]]
=== SysObject_type

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_type
|char(2)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_type[docs.RepoObject_Adoc_T.SysObject_type]
--


[[column-SysObject_type_name]]
=== SysObject_type_name

[cols="d,m,m,m,m,d"]
|===
|
|SysObject_type_name
|nvarchar(128)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Adoc_T.adoc#column-SysObject_type_name[docs.RepoObject_Adoc_T.SysObject_type_name]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-RepoObject_guid>>*
|uniqueidentifier
|NOT NULL
|
|












// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-AdocContent>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-is_DocsOutput>>
|int
|NULL
|
|

|
|<<column-PropertyCount>>
|int
|NULL
|
|

|
|<<column-RepoObject_fullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-RepoObject_fullname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-RepoObject_schema_name>>
|nvarchar(128)
|NULL
|
|

|
|<<column-SysObject_fullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-SysObject_fullname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-SysObject_schema_name>>
|nvarchar(128)
|NULL
|
|

|
|<<column-SysObject_type>>
|char(2)
|NULL
|
|

|
|<<column-SysObject_type_name>>
|nvarchar(128)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-PK_RepoObject_Adoc]]
=== PK_RepoObject_Adoc

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_repoobject_guid[RepoObject_guid]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:docs.RepoObject_ColumnList.adoc[]
* xref:docs.RepoObject_IndexList_T.adoc[]
* xref:docs.RepoObject_ParameterList.adoc[]
* xref:repo.RepoObject_gross.adoc[]
* xref:repo.RepoObjectProperty.adoc[]
* xref:repo.RepoObjectProperty_cross.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.RepoObject_Adoc_T.adoc[]
* xref:docs.usp_PERSIST_RepoObject_Adoc_T.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]
C28818B0-CA97-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid
// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]
RepoObject_guid
// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [docs].[RepoObject_ColumnList]
* [docs].[RepoObject_IndexList_T]
* [docs].[RepoObject_ParameterList]
* [repo].[RepoObject_gross]
* [repo].[RepoObjectProperty]
* [repo].[RepoObjectProperty_cross]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----

/*
todo - direkt oder Åber extended properties
- Index List
- referencing
- referenced
*/
CREATE View [docs].[RepoObject_Adoc]
As
Select
    ro.RepoObject_guid
  , is_DocsOutput          = Max ( ro.is_DocsOutput )
  , RepoObject_fullname    = Max ( ro.RepoObject_fullname )
  , RepoObject_fullname2   = Max ( ro.RepoObject_fullname2 )
  , RepoObject_schema_name = Max ( RepoObject_schema_name )
  , SysObject_fullname     = Max ( ro.SysObject_fullname )
  , SysObject_fullname2    = Max ( ro.SysObject_fullname2 )
  , SysObject_schema_name  = Max ( SysObject_schema_name )
  , SysObject_type         = Max ( ro.SysObject_type )
  , SysObject_type_name    = Max ( ro.SysObject_type_name )
  , AdocContent            = Concat (
                                        '= '
                                      , Max ( ro.SysObject_fullname )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== existing_properties'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::existing_properties[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , String_Agg (
                                                       Concat (
                                                                  Cast('' As NVarchar(Max))
                                                                , Case
                                                                      When Not rop.property_nvarchar Is Null
                                                                          Then
                                                                          ':ExistsProperty--' + Lower ( rop.property_name ) + ':'
                                                                          + Char ( 13 ) + Char ( 10 )
                                                                      Else
                                                                          ''
                                                                  End
                                                              )
                                                     , ''
                                                   ) Within Group(Order By
                                                                      rop_cross.property_name)
                                      , Case
                                            When Max ( ro.sql_modules_antora ) <> ''
                                                Then
                                                ':ExistsProperty--sql_modules_definition:' + Char ( 13 ) + Char ( 10 )
                                        End
                                      , Case
                                            When Max ( ro.SysObject_type ) In
                                            ( 'U', 'V' )
                                                Then
                                                ':ExistsProperty--FK:' + Char ( 13 ) + Char ( 10 )
                                        End
                                      , Case
                                            When Max ( ilist.AntoraIndexList ) <> ''
                                                Then
                                                ':ExistsProperty--AntoraIndexList:' + Char ( 13 ) + Char ( 10 )
                                        End
                                      , Case
                                            When Max ( parlist.AntoraParameterList ) <> ''
                                                Then
                                                ':ExistsProperty--AntoraParameterList:' + Char ( 13 ) + Char ( 10 )
                                        End
                                      , Case
                                            When Max ( ro.SysObject_type ) In
                                            ( 'U', 'V', 'IF' )
                                                Then
                                                ':ExistsProperty--Columns:' + Char ( 13 ) + Char ( 10 )
                                        End
                                      , '// end::existing_properties[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== RepoObject_guid'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::RepoObject_guid[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , ro.RepoObject_guid
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::RepoObject_guid[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== SysObject_type'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::SysObject_type[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Max ( ro.SysObject_type )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::SysObject_type[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== SysObject_type_name'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::SysObject_type_name[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Max ( ro.SysObject_type_name )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::SysObject_type_name[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== SysObject_id'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::SysObject_id[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Max ( ro.SysObject_id )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::SysObject_id[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== SysObject_modify_date'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::SysObject_modify_date[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Convert ( NVarchar(20), Max ( ro.SysObject_modify_date ), 120 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::SysObject_modify_date[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== AntoraColumnDetails'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::AntoraColumnDetails[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Max ( clist.AntoraColumnDetails )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::AntoraColumnDetails[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== AntoraPkColumnTableRows'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::AntoraPkColumnTableRows[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Max ( clist.AntoraPkColumnTableRows )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::AntoraPkColumnTableRows[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== AntoraNonPkColumnTableRows'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::AntoraNonPkColumnTableRows[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Max ( clist.AntoraNonPkColumnTableRows )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::AntoraNonPkColumnTableRows[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== AntoraIndexList'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::AntoraIndexList[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Max ( ilist.AntoraIndexList )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::AntoraIndexList[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== AntoraParameterList'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::AntoraParameterList[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Max ( parlist.AntoraParameterList )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::AntoraParameterList[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , String_Agg (
                                                       Concat (
                                                                  Cast('' As NVarchar(Max))
                                                                , Char ( 13 )
                                                                , Char ( 10 )
                                                                , '== '
                                                                , rop_cross.property_name
                                                                , Char ( 13 )
                                                                , Char ( 10 )
                                                                , Char ( 13 )
                                                                , Char ( 10 )
                                                                , '// tag::'
                                                                , Lower ( rop_cross.property_name )
                                                                , '[]'
                                                                , Char ( 13 )
                                                                , Char ( 10 )
                                                                , rop.property_nvarchar
                                                                , Char ( 13 )
                                                                , Char ( 10 )
                                                                , '// end::'
                                                                , Lower ( rop_cross.property_name )
                                                                , '[]'
                                                                , Char ( 13 )
                                                                , Char ( 10 )
                                                              )
                                                     , Char ( 13 ) + Char ( 10 )
                                                   ) Within Group(Order By
                                                                      rop_cross.property_name)
                                      --END
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '== sql_modules_definition'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// tag::sql_modules_definition[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '[source,sql]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '----'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , Max ( ro.sql_modules_antora )
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '----'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      , '// end::sql_modules_definition[]'
                                      , Char ( 13 )
                                      , Char ( 10 )
                                      --
                                      , Char ( 13 )
                                      , Char ( 10 )
                                    )
  , PropertyCount          = Count ( Distinct rop.property_name )
From
    repo.RepoObject_gross             ro
    Left Join
        repo.RepoObjectProperty_cross rop_cross
            On
            rop_cross.RepoObject_guid = ro.RepoObject_guid

    Left Join
        repo.RepoObjectProperty       rop
            On
            rop.RepoObject_guid       = rop_cross.RepoObject_guid
            And rop.property_name     = rop_cross.property_name
    --AND NOT rop.[property_nvarchar] IS NULL

    Left Join
        docs.RepoObject_ColumnList    clist
            On
            clist.RepoObject_guid     = ro.RepoObject_guid

    Left Join
        docs.RepoObject_IndexList_T   ilist
            On
            ilist.RepoObject_guid     = ro.RepoObject_guid

    Left Join
        docs.RepoObject_ParameterList parlist
            On
            parlist.RepoObject_guid   = ro.RepoObject_guid
Group By
    ro.RepoObject_guid;

----
// end::sql_modules_definition[]


