= [docs].[RepoObject_ColumnList]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
9F8B79D5-B993-EB11-84F2-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1346819860
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-14 19:26:25
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-RepoObject_guid]]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObjectColumn_gross.adoc#column-RepoObject_guid[repo.RepoObjectColumn_gross.RepoObject_guid]
--


[[column-AntoraColumnDetails]]
=== AntoraColumnDetails

[cols="d,m,m,m,m,d"]
|===
|
|AntoraColumnDetails
|nvarchar(max)
|NULL
|
|
|===


[[column-AntoraNonPkColumnTableRows]]
=== AntoraNonPkColumnTableRows

[cols="d,m,m,m,m,d"]
|===
|
|AntoraNonPkColumnTableRows
|nvarchar(max)
|NULL
|
|
|===


[[column-AntoraPkColumnTableRows]]
=== AntoraPkColumnTableRows

[cols="d,m,m,m,m,d"]
|===
|
|AntoraPkColumnTableRows
|nvarchar(max)
|NULL
|
|
|===


[[column-PlantumlNonPkEntityColumns]]
=== PlantumlNonPkEntityColumns

[cols="d,m,m,m,m,d"]
|===
|
|PlantumlNonPkEntityColumns
|nvarchar(max)
|NULL
|
|
|===


[[column-PlantumlPkEntityColumns]]
=== PlantumlPkEntityColumns

[cols="d,m,m,m,m,d"]
|===
|
|PlantumlPkEntityColumns
|nvarchar(max)
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-RepoObject_guid>>*
|uniqueidentifier
|NOT NULL
|
|






// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-AntoraColumnDetails>>
|nvarchar(max)
|NULL
|
|

|
|<<column-AntoraNonPkColumnTableRows>>
|nvarchar(max)
|NULL
|
|

|
|<<column-AntoraPkColumnTableRows>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PlantumlNonPkEntityColumns>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PlantumlPkEntityColumns>>
|nvarchar(max)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-PK_RepoObject_ColumnList]]
=== PK_RepoObject_ColumnList

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_no_group[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:repo.RepoObjectColumn_gross.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.RepoObject_Adoc.adoc[]
* xref:docs.RepoObject_Plantuml_Entity.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]
E88818B0-CA97-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid
// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObjectColumn_gross]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----


/*
alternative columns sort order for documentation:
- PK
- columns by name
*/
CREATE View [docs].[RepoObject_ColumnList]
As
Select
    roc.RepoObject_guid
  , AntoraColumnDetails        = String_Agg (
                                                Concat (
                                                           --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                                           Cast('' As NVarchar(Max))
                                                         , '[[column-'
                                                         , roc.RepoObjectColumn_name
                                                         , ']]'
                                                         , Char ( 13 ) + Char ( 10 )
                                                         , '=== '
                                                         , roc.RepoObjectColumn_name
                                                         , Char ( 13 ) + Char ( 10 )
                                                         , Char ( 13 ) + Char ( 10 )
                                                         , '[cols="d,m,m,m,m,d"]'
                                                         , Char ( 13 ) + Char ( 10 )
                                                         , '|==='
                                                         , Char ( 13 ) + Char ( 10 )
                                                         , Concat (
                                                                      '|'
                                                                    , roc.index_column_id
                                                                    , Char ( 13 ) + Char ( 10 )
                                                                    , '|'
                                                                    , Iif(roc.is_index_primary_key = 1, '*', '')
                                                                    , roc.RepoObjectColumn_name
                                                                    , Iif(roc.is_index_primary_key = 1, '*', '')
                                                                    , Char ( 13 ) + Char ( 10 )
                                                                    , '|'
                                                                    , roc.Repo_user_type_fullname
                                                                    , Char ( 13 ) + Char ( 10 )
                                                                    , '|'
                                                                    , Iif(Repo_is_nullable = 0, 'NOT NULL', 'NULL')
                                                                    , Char ( 13 ) + Char ( 10 )
                                                                    , '|'
                                                                    , Iif(roc.Repo_is_identity = 1
                                                                        , '(' + Cast(roc.Repo_seed_value As NVarchar(4000))
                                                                          + ','
                                                                          + Cast(roc.Repo_increment_value As NVarchar(4000))
                                                                          + ')'
                                                                        , Null)
                                                                    , Char ( 13 ) + Char ( 10 )
                                                                    , '|'
                                                                    , Iif(roc.Repo_is_computed = 1
                                                                   , Iif(roc.Repo_is_persisted = 1, 'Persisted', 'Calc')
                                                                   , Null)
                                                                    , Char ( 13 ) + Char ( 10 )
                                                                  )
                                                         , '|==='
                                                         , Char ( 13 ) + Char ( 10 )
                                                         , Char ( 13 ) + Char ( 10 )
                                                         , Case
                                                               When roc.Property_ms_description <> ''
                                                                   Then
                                                                   Concat (
                                                                              '.Description'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '--'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , roc.Property_ms_description
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '--'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                          )
                                                           End
                                                         , Case
                                                               When roc.Repo_default_definition <> ''
                                                                   Then
                                                                   Concat (
                                                                              '.Default: '
                                                                            , roc.Repo_default_name
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '....'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , roc.Repo_default_definition
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '....'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                          )
                                                           End
                                                         , Case
                                                               When roc.Repo_definition <> ''
                                                                   Then
                                                                   Concat (
                                                                              '.Definition'
                                                                            , Iif(roc.Repo_is_persisted = 1
                                                                           , ' (PERSISTED)'
                                                                           , Null)
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '....'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , roc.Repo_definition
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '....'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                          )
                                                           End
                                                         , Case
                                                               When roc.has_get_referenced_issue = 1
                                                                   Then
                                                                   Concat (
                                                                              '.has_get_referenced_issue'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '....'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , roc.has_get_referenced_issue
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '....'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                          )
                                                           End
                                                         , Case
                                                               When roc.AntoraReferencedColumnList <> ''
                                                                   Then
                                                                   Concat (
                                                                              '.Referenced Columns'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '--'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , roc.AntoraReferencedColumnList
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '--'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                          )
                                                           End
                                                         , Case
                                                               When roc.AntoraReferencingColumnList <> ''
                                                                   Then
                                                                   Concat (
                                                                              '.Referencing Columns'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '--'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , roc.AntoraReferencingColumnList
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '--'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                          )
                                                           End
                                                       )
                                              , Char ( 13 ) + Char ( 10 )
                                            ) Within Group(Order By
                                                               roc.is_index_primary_key Desc
                                                             , roc.index_column_id
                                                             , roc.Repo_is_computed
                                                             , roc.RepoObjectColumn_name)
  , AntoraPkColumnTableRows    = String_Agg (
                                                Concat (
                                                           --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                                           Cast('' As NVarchar(Max))
                                                         , Case
                                                               When roc.is_index_primary_key = 1
                                                                   Then
                                                                   Concat (
                                                                              '|'
                                                                            , roc.index_column_id
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '|'
                                                                            , '*'
                                                                            , '<<column-'
                                                                            , roc.RepoObjectColumn_name
                                                                            , '>>'
                                                                            , '*'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '|'
                                                                            , roc.Repo_user_type_fullname
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '|'
                                                                            , Iif(Repo_is_nullable = 0, 'NOT NULL', 'NULL')
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '|'
                                                                            , Iif(roc.Repo_is_identity = 1
                                                                                , '('
                                                                                  + Cast(roc.Repo_seed_value As NVarchar(4000))
                                                                                  + ','
                                                                                  + Cast(roc.Repo_increment_value As NVarchar(4000))
                                                                                  + ')'
                                                                                , Null)
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '|'
                                                                            , Iif(roc.Repo_is_computed = 1
                                                                               , Iif(roc.Repo_is_persisted = 1
                                                                                     , 'Persisted'
                                                                                     , 'Calc')
                                                                               , Null)
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                          )
                                                           End
                                                       )
                                              , Char ( 13 ) + Char ( 10 )
                                            ) Within Group(Order By
                                                               roc.is_index_primary_key Desc
                                                             , roc.index_column_id
                                                             , roc.Repo_is_computed
                                                             , roc.RepoObjectColumn_name)
  , AntoraNonPkColumnTableRows = String_Agg (
                                                Concat (
                                                           --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                                           Cast('' As NVarchar(Max))
                                                         , Case
                                                               When IsNull ( roc.is_index_primary_key, 0 ) = 0
                                                                   Then
                                                                   Concat (
                                                                              '|'
                                                                            --, roc.[index_column_id]
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '|'
                                                                            , '<<column-'
                                                                            , roc.RepoObjectColumn_name
                                                                            , '>>'
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '|'
                                                                            , roc.Repo_user_type_fullname
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '|'
                                                                            , Iif(Repo_is_nullable = 0
                                                                                  , 'NOT NULL'
                                                                                  , 'NULL')
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '|'
                                                                            , Iif(roc.Repo_is_identity = 1
                                                                                , '('
                                                                                  + Cast(roc.Repo_seed_value As NVarchar(4000))
                                                                                  + ','
                                                                                  + Cast(roc.Repo_increment_value As NVarchar(4000))
                                                                                  + ')'
                                                                                , Null)
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                            , '|'
                                                                            , Iif(roc.Repo_is_computed = 1
                                                                                  , Iif(roc.Repo_is_persisted = 1
                                                                                        , 'Persisted'
                                                                                        , 'Calc')
                                                                                  , Null)
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                          )
                                                           End
                                                       )
                                              , Char ( 13 ) + Char ( 10 )
                                            ) Within Group(Order By
                                                               roc.is_index_primary_key Desc
                                                             , roc.index_column_id
                                                             , roc.Repo_is_computed
                                                             , roc.RepoObjectColumn_name)
  , PlantumlPkEntityColumns    = String_Agg (
                                                Concat (
                                                           Cast('' As NVarchar(Max))
                                                         , Case
                                                               When roc.is_index_primary_key = 1
                                                                   Then
                                                                   Concat (
                                                                              '  '
                                                                            --* to identify mandatory attributes
                                                                            , Iif(Repo_is_nullable = 0, '* ', Null)
                                                                            --{static}  => underline, {abstract} => italic
                                                                            , Case
                                                                                  When roc.Repo_is_computed = 1
                                                                                      Then
                                                                                      Iif(roc.Repo_is_persisted = 1
                                                                                       , '{static} '
                                                                                       , '{abstract} ')
                                                                              End
                                                                            --PK in bold
                                                                            , '**'
                                                                            , roc.RepoObjectColumn_name
                                                                            , '**'
                                                                            , ' : '
                                                                            , roc.Repo_user_type_fullname
                                                                            --, CASE 
                                                                            -- WHEN roc.[Repo_is_computed] = 1
                                                                            --  THEN ' <<calc' + IIF(roc.[Repo_is_persisted] = 1, ' (Persisted)', '') + '>>'
                                                                            -- END
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                          )
                                                           End
                                                       )
                                              , ''
                                            ) Within Group(Order By
                                                               roc.is_index_primary_key Desc
                                                             , roc.index_column_id
                                                             , roc.Repo_is_computed
                                                             , roc.RepoObjectColumn_name)
  , PlantumlNonPkEntityColumns = String_Agg (
                                                Concat (
                                                           Cast('' As NVarchar(Max))
                                                         , Case
                                                               When IsNull ( roc.is_index_primary_key, 0 ) = 0
                                                                   Then
                                                                   Concat (
                                                                              '  '
                                                                            --* to identify mandatory attributes
                                                                            , Iif(Repo_is_nullable = 0, '* ', Null)
                                                                            --{static}  => underline, {abstract} => italic
                                                                            , Case
                                                                                  When roc.Repo_is_computed = 1
                                                                                      Then
                                                                                      Iif(roc.Repo_is_persisted = 1
                                                                                          , '{static} '
                                                                                          , '{abstract} ')
                                                                              End
                                                                            , roc.RepoObjectColumn_name
                                                                            , ' : '
                                                                            , roc.Repo_user_type_fullname
                                                                            --, CASE 
                                                                            -- WHEN roc.[Repo_is_computed] = 1
                                                                            --  THEN ' <<calc' + IIF(roc.[Repo_is_persisted] = 1, ' (Persisted)', '') + '>>'
                                                                            -- END
                                                                            , Char ( 13 ) + Char ( 10 )
                                                                          )
                                                           End
                                                       )
                                              , ''
                                            ) Within Group(Order By
                                                               roc.is_index_primary_key Desc
                                                             , roc.index_column_id
                                                             , roc.Repo_is_computed
                                                             , roc.RepoObjectColumn_name)
From
    repo.RepoObjectColumn_gross As roc
Where
    --not [is_query_plan_expression], these are not real columms
    roc.is_query_plan_expression Is Null
    --we need the datatype, or it should be computed
    And
    (
        Not roc.Repo_user_type_fullname Is Null
        Or roc.Repo_is_computed = 1
    )
Group By
    roc.RepoObject_guid;

----
// end::sql_modules_definition[]


