= [docs].[RepoObject_Plantuml]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--pk_indexsemanticgroup:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
F20B29C2-E595-EB11-84F4-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1506820430
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-14 23:11:39
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-RepoObject_guid]]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObject_gross.adoc#column-RepoObject_guid[repo.RepoObject_gross.RepoObject_guid]
--

.Referencing Columns
--
* xref:docs.RepoObject_Plantuml_T.adoc#column-RepoObject_guid[docs.RepoObject_Plantuml_T.RepoObject_guid]
--


[[column-ColRefList]]
=== ColRefList

[cols="d,m,m,m,m,d"]
|===
|
|ColRefList
|nvarchar(max)
|NULL
|
|
|===

.Referenced Columns
--
* xref:docs.RepoObject_Plantuml_ColRefList.adoc#column-ColRefList[docs.RepoObject_Plantuml_ColRefList.ColRefList]
--

.Referencing Columns
--
* xref:docs.RepoObject_Plantuml_T.adoc#column-ColRefList[docs.RepoObject_Plantuml_T.ColRefList]
--


[[column-ObjectRefList]]
=== ObjectRefList

[cols="d,m,m,m,m,d"]
|===
|
|ObjectRefList
|nvarchar(max)
|NULL
|
|
|===

.Referenced Columns
--
* xref:docs.RepoObject_Plantuml_ObjectRefList.adoc#column-ObjectRefList[docs.RepoObject_Plantuml_ObjectRefList.ObjectRefList]
* xref:
* xref:
--

.Referencing Columns
--
* xref:docs.RepoObject_Plantuml_T.adoc#column-ObjectRefList[docs.RepoObject_Plantuml_T.ObjectRefList]
--


[[column-ObjectRefList_0_30]]
=== ObjectRefList_0_30

[cols="d,m,m,m,m,d"]
|===
|
|ObjectRefList_0_30
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:
--


[[column-ObjectRefList_30_0]]
=== ObjectRefList_30_0

[cols="d,m,m,m,m,d"]
|===
|
|ObjectRefList_30_0
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:
--


[[column-PlantumlEntity_0_30_ObjectRef]]
=== PlantumlEntity_0_30_ObjectRef

[cols="d,m,m,m,m,d"]
|===
|
|PlantumlEntity_0_30_ObjectRef
|nvarchar(max)
|NOT NULL
|
|
|===

.Referencing Columns
--
* xref:
--


[[column-PlantumlEntity_1_1_ColRef]]
=== PlantumlEntity_1_1_ColRef

[cols="d,m,m,m,m,d"]
|===
|
|PlantumlEntity_1_1_ColRef
|nvarchar(max)
|NOT NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Plantuml_T.adoc#column-PlantumlEntity_1_1_ColRef[docs.RepoObject_Plantuml_T.PlantumlEntity_1_1_ColRef]
--


[[column-PlantumlEntity_1_1_FkRef]]
=== PlantumlEntity_1_1_FkRef

[cols="d,m,m,m,m,d"]
|===
|
|PlantumlEntity_1_1_FkRef
|nvarchar(max)
|NOT NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Plantuml_T.adoc#column-PlantumlEntity_1_1_FkRef[docs.RepoObject_Plantuml_T.PlantumlEntity_1_1_FkRef]
--


[[column-PlantumlEntity_1_1_ObjectRef]]
=== PlantumlEntity_1_1_ObjectRef

[cols="d,m,m,m,m,d"]
|===
|
|PlantumlEntity_1_1_ObjectRef
|nvarchar(max)
|NOT NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Plantuml_T.adoc#column-PlantumlEntity_1_1_ObjectRef[docs.RepoObject_Plantuml_T.PlantumlEntity_1_1_ObjectRef]
--


[[column-PlantumlEntity_30_0_ObjectRef]]
=== PlantumlEntity_30_0_ObjectRef

[cols="d,m,m,m,m,d"]
|===
|
|PlantumlEntity_30_0_ObjectRef
|nvarchar(max)
|NOT NULL
|
|
|===

.Referencing Columns
--
* xref:
--


[[column-PumlEntityList]]
=== PumlEntityList

[cols="d,m,m,m,m,d"]
|===
|
|PumlEntityList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_Plantuml_T.adoc#column-PumlEntityList[docs.RepoObject_Plantuml_T.PumlEntityList]
--


[[column-PumlEntityList_0_30]]
=== PumlEntityList_0_30

[cols="d,m,m,m,m,d"]
|===
|
|PumlEntityList_0_30
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:
--


[[column-PumlEntityList_30_0]]
=== PumlEntityList_30_0

[cols="d,m,m,m,m,d"]
|===
|
|PumlEntityList_30_0
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:
--


[[column-RepoObject_fullname2]]
=== RepoObject_fullname2

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_fullname2
|nvarchar(257)
|NOT NULL
|
|
|===

.Description
--
(concat([RepoObject_schema_name],'.',[RepoObject_name]))
--

.Referenced Columns
--
* xref:repo.RepoObject_gross.adoc#column-RepoObject_fullname2[repo.RepoObject_gross.RepoObject_fullname2]
--

.Referencing Columns
--
* xref:docs.RepoObject_Plantuml_T.adoc#column-RepoObject_fullname2[docs.RepoObject_Plantuml_T.RepoObject_fullname2]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-RepoObject_guid>>*
|uniqueidentifier
|NOT NULL
|
|














// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-ColRefList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-ObjectRefList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-ObjectRefList_0_30>>
|nvarchar(max)
|NULL
|
|

|
|<<column-ObjectRefList_30_0>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PlantumlEntity_0_30_ObjectRef>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-PlantumlEntity_1_1_ColRef>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-PlantumlEntity_1_1_FkRef>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-PlantumlEntity_1_1_ObjectRef>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-PlantumlEntity_30_0_ObjectRef>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-PumlEntityList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PumlEntityList_0_30>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PumlEntityList_30_0>>
|nvarchar(max)
|NULL
|
|

|
|<<column-RepoObject_fullname2>>
|nvarchar(257)
|NOT NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-PK_RepoObject_Plantuml]]
=== PK_RepoObject_Plantuml

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_repoobject_guid[RepoObject_guid]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:config.ftv_get_parameter_value.adoc[]
* xref:docs.ftv_RepoObject_Reference_PlantUml_EntityRefList.adoc[]
* xref:docs.RepoObject_Plantuml_ColRefList.adoc[]
* xref:docs.RepoObject_PlantUml_FkRefList.adoc[]
* xref:docs.RepoObject_Plantuml_ObjectRefList.adoc[]
* xref:.adoc[]
* xref:.adoc[]
* xref:docs.RepoObject_PlantUml_PumlEntityFkList.adoc[]
* xref:repo.RepoObject_gross.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.RepoObject_Plantuml_T.adoc[]
* xref:docs.usp_PERSIST_RepoObject_Plantuml_T.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]
C18818B0-CA97-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid
// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]
RepoObject_guid
// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [config].[ftv_get_parameter_value]
* [docs].[ftv_RepoObject_Reference_PlantUml_EntityRefList]
* [docs].[RepoObject_Plantuml_ColRefList]
* [docs].[RepoObject_PlantUml_FkRefList]
* [docs].[RepoObject_Plantuml_ObjectRefList]
* [docs].[RepoObject_Plantuml_ObjectRefList_0_30]
* [docs].[RepoObject_Plantuml_ObjectRefList_30_0]
* [docs].[RepoObject_PlantUml_PumlEntityFkList]
* [repo].[RepoObject_gross]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----



CREATE View [docs].[RepoObject_Plantuml]
As
Select
    ro.RepoObject_guid
  , ro.RepoObject_fullname2
  , elist_1_1.PumlEntityList
  , elist_0_30.PumlEntityList     As PumlEntityList_0_30
  , elist_30_0.PumlEntityList     As PumlEntityList_30_0
  , clist.ColRefList
  , olist_1_1.ObjectRefList
  , olist_0_30.ObjectRefList      As ObjectRefList_0_30
  , olist_30_0.ObjectRefList      As ObjectRefList_30_0
  , PlantumlEntity_1_1_ColRef     = Concat (
                                               'left to right direction'
                                             , Char ( 13 ) + Char ( 10 )
                                             , 'hide circle'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '''avoide "." issues:'
                                             , Char ( 13 ) + Char ( 10 )
                                             , 'set namespaceSeparator none'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                             , skin.Parameter_value__result_nvarchar
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                             , elist_1_1.PumlEntityList
                                             , Char ( 13 ) + Char ( 10 )
                                             , olist_1_1.ObjectRefList
                                             , Char ( 13 ) + Char ( 10 )
                                             , clist.ColRefList
                                           )
  , PlantumlEntity_1_1_ObjectRef  = Concat (
                                               'left to right direction'
                                             , Char ( 13 ) + Char ( 10 )
                                             , 'hide circle'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '''avoide "." issues:'
                                             , Char ( 13 ) + Char ( 10 )
                                             , 'set namespaceSeparator none'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                             , skin.Parameter_value__result_nvarchar
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                             , elist_1_1.PumlEntityOnlyPkList
                                             , Char ( 13 ) + Char ( 10 )
                                             , olist_1_1.ObjectRefList
                                           )
  , PlantumlEntity_0_30_ObjectRef = Concat (
                                               '''Left to right direction'
                                             , Char ( 13 ) + Char ( 10 )
                                             , 'hide circle'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '''avoide "." issues:'
                                             , Char ( 13 ) + Char ( 10 )
                                             , 'set namespaceSeparator none'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                             , skin.Parameter_value__result_nvarchar
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                             , elist_0_30.PumlEntityOnlyPkList
                                             , Char ( 13 ) + Char ( 10 )
                                             , olist_0_30.ObjectRefList
                                           )
  , PlantumlEntity_30_0_ObjectRef = Concat (
                                               '''Left to right direction'
                                             , Char ( 13 ) + Char ( 10 )
                                             , 'hide circle'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '''avoide "." issues:'
                                             , Char ( 13 ) + Char ( 10 )
                                             , 'set namespaceSeparator none'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                             , skin.Parameter_value__result_nvarchar
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                             , elist_30_0.PumlEntityOnlyPkList
                                             , Char ( 13 ) + Char ( 10 )
                                             , olist_30_0.ObjectRefList
                                           )
  , PlantumlEntity_1_1_FkRef      = Concat (
                                               'Left to right direction'
                                             , Char ( 13 ) + Char ( 10 )
                                             , 'hide circle'
                                             , Char ( 13 ) + Char ( 10 )
                                             , '''avoide "." issues:'
                                             , Char ( 13 ) + Char ( 10 )
                                             , 'set namespaceSeparator none'
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                             , skin.Parameter_value__result_nvarchar
                                             , Char ( 13 ) + Char ( 10 )
                                             , Char ( 13 ) + Char ( 10 )
                                             , EntityFkList.PumlEntityFkList
                                             , Char ( 13 ) + Char ( 10 )
                                             , FkRefList.FkRefList
                                           )
From
    repo.RepoObject_gross                                                                         As ro
    Left Join
        docs.RepoObject_Plantuml_ColRefList                                                       As clist
            On
            clist.RepoObject_guid = ro.RepoObject_guid

    Left Join
        docs.RepoObject_Plantuml_ObjectRefList                                                    As olist_1_1
            On
            olist_1_1.RepoObject_guid = ro.RepoObject_guid

    Left Join
        docs.RepoObject_Plantuml_ObjectRefList_0_30                                               As olist_0_30
            On
            olist_0_30.RepoObject_guid = ro.RepoObject_guid

    Left Join
        docs.RepoObject_Plantuml_ObjectRefList_30_0                                               As olist_30_0
            On
            olist_30_0.RepoObject_guid = ro.RepoObject_guid
    Cross Apply docs.ftv_RepoObject_Reference_PlantUml_EntityRefList ( ro.RepoObject_guid, 1, 1 ) As elist_1_1
    Cross Apply docs.ftv_RepoObject_Reference_PlantUml_EntityRefList ( ro.RepoObject_guid, 30, 0 ) As elist_30_0
    Cross Apply docs.ftv_RepoObject_Reference_PlantUml_EntityRefList ( ro.RepoObject_guid, 0, 30 ) As elist_0_30
    Left Join
        docs.RepoObject_PlantUml_PumlEntityFkList                            As EntityFkList
            On
            EntityFkList.RepoObject_guid = ro.RepoObject_guid

    Left Join
        docs.RepoObject_PlantUml_FkRefList                                   As FkRefList
            On
            FkRefList.RepoObject_guid = ro.RepoObject_guid
    Cross Join config.ftv_get_parameter_value ( 'puml_skinparam_class', '' ) As skin;

----
// end::sql_modules_definition[]


