= [docs].[RepoObject_ColumnList]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--AntoraReferencedList:
:ExistsProperty--AntoraReferencingList:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_IndexPatternColumnDatatype:
:ExistsProperty--pk_IndexPatternColumnName:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
9F8B79D5-B993-EB11-84F2-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1856725667
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-05 09:42:32
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-RepoObject_guid]]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObjectColumn_gross.adoc#column-RepoObject_guid[repo.RepoObjectColumn_gross.RepoObject_guid]
--


[[column-AntoraColumnDetails]]
=== AntoraColumnDetails

[cols="d,m,m,m,m,d"]
|===
|
|AntoraColumnDetails
|nvarchar(max)
|NULL
|
|
|===


[[column-AntoraNonPkColumnTableRows]]
=== AntoraNonPkColumnTableRows

[cols="d,m,m,m,m,d"]
|===
|
|AntoraNonPkColumnTableRows
|nvarchar(max)
|NULL
|
|
|===


[[column-AntoraPkColumnTableRows]]
=== AntoraPkColumnTableRows

[cols="d,m,m,m,m,d"]
|===
|
|AntoraPkColumnTableRows
|nvarchar(max)
|NULL
|
|
|===


[[column-PlantumlNonPkEntityColumns]]
=== PlantumlNonPkEntityColumns

[cols="d,m,m,m,m,d"]
|===
|
|PlantumlNonPkEntityColumns
|nvarchar(max)
|NULL
|
|
|===


[[column-PlantumlPkEntityColumns]]
=== PlantumlPkEntityColumns

[cols="d,m,m,m,m,d"]
|===
|
|PlantumlPkEntityColumns
|nvarchar(max)
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-RepoObject_guid>>*
|uniqueidentifier
|NOT NULL
|
|






// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-AntoraColumnDetails>>
|nvarchar(max)
|NULL
|
|

|
|<<column-AntoraNonPkColumnTableRows>>
|nvarchar(max)
|NULL
|
|

|
|<<column-AntoraPkColumnTableRows>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PlantumlNonPkEntityColumns>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PlantumlPkEntityColumns>>
|nvarchar(max)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-PK_RepoObject_ColumnList]]
=== PK_RepoObject_ColumnList

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_no_group[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== example1

// tag::example1[]

// end::example1[]


== example2

// tag::example2[]

// end::example2[]


== example3

// tag::example3[]

// end::example3[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_RepoObject_guid[]

// end::usp_persistence_RepoObject_guid[]


== UspExamples

// tag::UspExamples[]

// end::UspExamples[]


== UspParameters

// tag::UspParameters[]

// end::UspParameters[]


== persistence_source_RepoObject_xref

// tag::persistence_source_RepoObject_xref[]

// end::persistence_source_RepoObject_xref[]


== pk_IndexSemanticGroup

// tag::pk_IndexSemanticGroup[]

// end::pk_IndexSemanticGroup[]


== ReferencedObjectList

// tag::ReferencedObjectList[]

// end::ReferencedObjectList[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::MS_Description[]

// end::MS_Description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_RepoObject_fullname[]

// end::persistence_source_RepoObject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_RepoObject_fullname2[]

// end::persistence_source_RepoObject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_RepoObject_guid[]

// end::persistence_source_RepoObject_guid[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== example4

// tag::example4[]

// end::example4[]


== example5

// tag::example5[]

// end::example5[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== AdocUspSteps

// tag::AdocUspSteps[]

// end::AdocUspSteps[]


== AntoraReferencedList

// tag::AntoraReferencedList[]
* xref:repo.RepoObjectColumn_gross.adoc[]
// end::AntoraReferencedList[]


== AntoraReferencingList

// tag::AntoraReferencingList[]
* xref:docs.RepoObject_Adoc.adoc[]
* xref:docs.RepoObject_Plantuml_Entity.adoc[]
// end::AntoraReferencingList[]


== pk_index_guid

// tag::pk_index_guid[]
E88818B0-CA97-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_IndexPatternColumnDatatype[]
uniqueidentifier
// end::pk_IndexPatternColumnDatatype[]


== pk_IndexPatternColumnName

// tag::pk_IndexPatternColumnName[]
RepoObject_guid
// end::pk_IndexPatternColumnName[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----

/*
alternative columns sort order for documentation:
- PK
- columns by name
*/
CREATE VIEW [docs].[RepoObject_ColumnList]
AS
SELECT roc.[RepoObject_guid]
 , AntoraColumnDetails = String_Agg(CONCAT (
   --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
   CAST('' AS NVARCHAR(MAX))
   , '[[column-'
   , roc.[RepoObjectColumn_name]
   , ']]'
   , CHAR(13) + CHAR(10)
   , '=== '
   , roc.[RepoObjectColumn_name]
   , CHAR(13) + CHAR(10)
   , CHAR(13) + CHAR(10)
   , '[cols="d,m,m,m,m,d"]'
   , CHAR(13) + CHAR(10)
   , '|==='
   , CHAR(13) + CHAR(10)
   , CONCAT (
    '|'
    , roc.[index_column_id]
    , CHAR(13) + CHAR(10)
    , '|'
    , IIF(roc.[is_index_primary_key] = 1, '*', '')
    , roc.[RepoObjectColumn_name]
    , IIF(roc.[is_index_primary_key] = 1, '*', '')
    , CHAR(13) + CHAR(10)
    , '|'
    , roc.[Repo_user_type_fullname]
    , CHAR(13) + CHAR(10)
    , '|'
    , IIF([Repo_is_nullable] = 0, 'NOT NULL', 'NULL')
    , CHAR(13) + CHAR(10)
    , '|'
    , IIF(roc.[Repo_is_identity] = 1, '(' + CAST(roc.[Repo_seed_value] AS NVARCHAR(4000)) + ',' + CAST(roc.[Repo_increment_value] AS NVARCHAR(4000)) + ')', NULL)
    , CHAR(13) + CHAR(10)
    , '|'
    , IIF(roc.[Repo_is_computed] = 1, IIF(roc.[Repo_is_persisted] = 1, 'Persisted', 'Calc'), NULL)
    , CHAR(13) + CHAR(10)
    )
   , '|==='
   , CHAR(13) + CHAR(10)
   , CHAR(13) + CHAR(10)
   , CASE 
    WHEN roc.[Property_ms_description] <> ''
     THEN CONCAT (
       '.Description'
       , CHAR(13) + CHAR(10)
       , '....'
       , CHAR(13) + CHAR(10)
       , roc.[Property_ms_description]
       , CHAR(13) + CHAR(10)
       , '....'
       , CHAR(13) + CHAR(10)
       , CHAR(13) + CHAR(10)
       )
    END
   , CASE 
    WHEN roc.[Repo_default_definition] <> ''
     THEN CONCAT (
       '.Default: '
       , roc.[Repo_default_name]
       , CHAR(13) + CHAR(10)
       , '....'
       , CHAR(13) + CHAR(10)
       , roc.[Repo_default_definition]
       , CHAR(13) + CHAR(10)
       , '....'
       , CHAR(13) + CHAR(10)
       , CHAR(13) + CHAR(10)
       )
    END
   , CASE 
    WHEN roc.[Repo_definition] <> ''
     THEN CONCAT (
       '.Definition'
       , IIF(roc.[Repo_is_persisted] = 1, ' (PERSISTED)', NULL)
       , CHAR(13) + CHAR(10)
       , '....'
       , CHAR(13) + CHAR(10)
       , roc.[Repo_definition]
       , CHAR(13) + CHAR(10)
       , '....'
       , CHAR(13) + CHAR(10)
       , CHAR(13) + CHAR(10)
       )
    END
   , CASE 
    WHEN roc.[has_get_referenced_issue] = 1
     THEN CONCAT (
       '.has_get_referenced_issue'
       , CHAR(13) + CHAR(10)
       , '....'
       , CHAR(13) + CHAR(10)
       , roc.[has_get_referenced_issue]
       , CHAR(13) + CHAR(10)
       , '....'
       , CHAR(13) + CHAR(10)
       , CHAR(13) + CHAR(10)
       )
    END
   , CASE 
    WHEN roc.[AntoraReferencedColumnList] <> ''
     THEN CONCAT (
       '.Referenced Columns'
       , CHAR(13) + CHAR(10)
       , '--'
       , CHAR(13) + CHAR(10)
       , roc.[AntoraReferencedColumnList]
       , CHAR(13) + CHAR(10)
       , '--'
       , CHAR(13) + CHAR(10)
       , CHAR(13) + CHAR(10)
       )
    END
   , CASE 
    WHEN roc.[AntoraReferencingColumnList] <> ''
     THEN CONCAT (
       '.Referencing Columns'
       , CHAR(13) + CHAR(10)
       , '--'
       , CHAR(13) + CHAR(10)
       , roc.[AntoraReferencingColumnList]
       , CHAR(13) + CHAR(10)
       , '--'
       , CHAR(13) + CHAR(10)
       , CHAR(13) + CHAR(10)
       )
    END
   ), CHAR(13) + CHAR(10)) WITHIN
GROUP (
  ORDER BY roc.[is_index_primary_key] DESC
   , roc.[index_column_id]
   , roc.[Repo_is_computed]
   , roc.[RepoObjectColumn_name]
  )
 , AntoraPkColumnTableRows = String_Agg(CONCAT (
   --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
   CAST('' AS NVARCHAR(MAX))
   , CASE 
    WHEN roc.[is_index_primary_key] = 1
     THEN CONCAT (
       '|'
       , roc.[index_column_id]
       , CHAR(13) + CHAR(10)
       , '|'
       , '*'
       , '<<column-'
       , roc.[RepoObjectColumn_name]
       , '>>'
       , '*'
       , CHAR(13) + CHAR(10)
       , '|'
       , roc.[Repo_user_type_fullname]
       , CHAR(13) + CHAR(10)
       , '|'
       , IIF([Repo_is_nullable] = 0, 'NOT NULL', 'NULL')
       , CHAR(13) + CHAR(10)
       , '|'
       , IIF(roc.[Repo_is_identity] = 1, '(' + CAST(roc.[Repo_seed_value] AS NVARCHAR(4000)) + ',' + CAST(roc.[Repo_increment_value] AS NVARCHAR(4000)) + ')', NULL)
       , CHAR(13) + CHAR(10)
       , '|'
       , IIF(roc.[Repo_is_computed] = 1, IIF(roc.[Repo_is_persisted] = 1, 'Persisted', 'Calc'), NULL)
       , CHAR(13) + CHAR(10)
       )
    END
   ), CHAR(13) + CHAR(10)) WITHIN
GROUP (
  ORDER BY roc.[is_index_primary_key] DESC
   , roc.[index_column_id]
   , roc.[Repo_is_computed]
   , roc.[RepoObjectColumn_name]
  )
 , AntoraNonPkColumnTableRows = String_Agg(CONCAT (
   --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
   CAST('' AS NVARCHAR(MAX))
   , CASE 
    WHEN ISNULL(roc.[is_index_primary_key], 0) = 0
     THEN CONCAT (
       '|'
       --, roc.[index_column_id]
       , CHAR(13) + CHAR(10)
       , '|'
       , '<<column-'
       , roc.[RepoObjectColumn_name]
       , '>>'
       , CHAR(13) + CHAR(10)
       , '|'
       , roc.[Repo_user_type_fullname]
       , CHAR(13) + CHAR(10)
       , '|'
       , IIF([Repo_is_nullable] = 0, 'NOT NULL', 'NULL')
       , CHAR(13) + CHAR(10)
       , '|'
       , IIF(roc.[Repo_is_identity] = 1, '(' + CAST(roc.[Repo_seed_value] AS NVARCHAR(4000)) + ',' + CAST(roc.[Repo_increment_value] AS NVARCHAR(4000)) + ')', NULL)
       , CHAR(13) + CHAR(10)
       , '|'
       , IIF(roc.[Repo_is_computed] = 1, IIF(roc.[Repo_is_persisted] = 1, 'Persisted', 'Calc'), NULL)
       , CHAR(13) + CHAR(10)
       )
    END
   ), CHAR(13) + CHAR(10)) WITHIN
GROUP (
  ORDER BY roc.[is_index_primary_key] DESC
   , roc.[index_column_id]
   , roc.[Repo_is_computed]
   , roc.[RepoObjectColumn_name]
  )
 , PlantumlPkEntityColumns = String_Agg(CONCAT (
   CAST('' AS NVARCHAR(MAX))
   , CASE 
    WHEN roc.[is_index_primary_key] = 1
     THEN CONCAT (
       '  '
       --* to identify mandatory attributes
       , IIF([Repo_is_nullable] = 0, '* ', NULL)
       --{static}  => underline, {abstract} => italic
       , CASE 
        WHEN roc.[Repo_is_computed] = 1
         THEN IIF(roc.[Repo_is_persisted] = 1, '{static} ', '{abstract} ')
        END
       --PK in bold
       , '**'
       , roc.[RepoObjectColumn_name]
       , '**'
       , ' : '
       , roc.[Repo_user_type_fullname]
       --, CASE 
       -- WHEN roc.[Repo_is_computed] = 1
       --  THEN ' <<calc' + IIF(roc.[Repo_is_persisted] = 1, ' (Persisted)', '') + '>>'
       -- END
       , CHAR(13) + CHAR(10)
       )
    END
   ), '') WITHIN
GROUP (
  ORDER BY roc.[is_index_primary_key] DESC
   , roc.[index_column_id]
   , roc.[Repo_is_computed]
   , roc.[RepoObjectColumn_name]
  )
 , PlantumlNonPkEntityColumns = String_Agg(CONCAT (
   CAST('' AS NVARCHAR(MAX))
   , CASE 
    WHEN ISNULL(roc.[is_index_primary_key], 0) = 0
     THEN CONCAT (
       '  '
       --* to identify mandatory attributes
       , IIF([Repo_is_nullable] = 0, '* ', NULL)
       --{static}  => underline, {abstract} => italic
       , CASE 
        WHEN roc.[Repo_is_computed] = 1
         THEN IIF(roc.[Repo_is_persisted] = 1, '{static} ', '{abstract} ')
        END
       , roc.[RepoObjectColumn_name]
       , ' : '
       , roc.[Repo_user_type_fullname]
       --, CASE 
       -- WHEN roc.[Repo_is_computed] = 1
       --  THEN ' <<calc' + IIF(roc.[Repo_is_persisted] = 1, ' (Persisted)', '') + '>>'
       -- END
       , CHAR(13) + CHAR(10)
       )
    END
   ), '') WITHIN
GROUP (
  ORDER BY roc.[is_index_primary_key] DESC
   , roc.[index_column_id]
   , roc.[Repo_is_computed]
   , roc.[RepoObjectColumn_name]
  )
FROM [repo].[RepoObjectColumn_gross] AS roc
WHERE
 --not [is_query_plan_expression], these are not real columms
 roc.[is_query_plan_expression] IS NULL
 --we need the datatype, or it should be computed
 AND (
  NOT roc.[Repo_user_type_fullname] IS NULL
  OR roc.Repo_is_computed = 1
  )
GROUP BY roc.[RepoObject_guid]

----
// end::sql_modules_definition[]


