= [docs].[RepoObject_IndexList]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6FE2B548-5E96-EB11-84F4-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1938821969
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-13 19:02:39
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-RepoObject_guid]]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_IndexList_T.adoc#column-RepoObject_guid[docs.RepoObject_IndexList_T.RepoObject_guid]
--


[[column-AntoraIndexList]]
=== AntoraIndexList

[cols="d,m,m,m,m,d"]
|===
|
|AntoraIndexList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_IndexList_T.adoc#column-AntoraIndexList[docs.RepoObject_IndexList_T.AntoraIndexList]
--


[[column-PumlIndexList]]
=== PumlIndexList

[cols="d,m,m,m,m,d"]
|===
|
|PumlIndexList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:docs.RepoObject_IndexList_T.adoc#column-PumlIndexList[docs.RepoObject_IndexList_T.PumlIndexList]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-RepoObject_guid>>*
|uniqueidentifier
|NULL
|
|



// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-AntoraIndexList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PumlIndexList>>
|nvarchar(max)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-PK_RepoObject_IndexList]]
=== PK_RepoObject_IndexList

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_no_group[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:repo.ForeignKey_gross.adoc[]
* xref:repo.Index_gross.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:docs.RepoObject_IndexList_T.adoc[]
* xref:docs.usp_PERSIST_RepoObject_IndexList_T.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]
FF97B507-1799-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
RepoObject_guid
// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[ForeignKey_gross]
* [repo].[Index_gross]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----
Create View docs.RepoObject_IndexList
As
Select
    ix.parent_RepoObject_guid As RepoObject_guid
  , AntoraIndexList           = String_Agg (
                                               Concat (
                                                          --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                                          Cast('' As NVarchar(Max))
                                                        , Char ( 13 ) + Char ( 10 )
                                                        , '[[index-'
                                                        , ix.index_name
                                                        , ']]'
                                                        , Char ( 13 ) + Char ( 10 )
                                                        , '=== '
                                                        , ix.index_name
                                                        , Char ( 13 ) + Char ( 10 )
                                                        , Char ( 13 ) + Char ( 10 )
                                                        , '* IndexSemanticGroup: ' + 'xref:index/IndexSemanticGroup.adoc#_'
                                                          + Replace (
                                                                        Replace (
                                                                                    Replace (
                                                                                                Lower ( IsNull (
                                                                                                                   ix.IndexSemanticGroup
                                                                                                                 , 'no_group'
                                                                                                               )
                                                                                                      )
                                                                                              , ' '
                                                                                              , '_'
                                                                                            )
                                                                                  , '__'
                                                                                  , '_'
                                                                                )
                                                                      , '__'
                                                                      , '_'
                                                                    ) + '[' + IsNull ( ix.IndexSemanticGroup, 'no_group' ) + ']'
                                                        , Char ( 13 ) + Char ( 10 )
                                                        , '+' + Char ( 13 ) + Char ( 10 )
                                                        , '--' + Char ( 13 ) + Char ( 10 )
                                                        , AntoraIndexColumnList
                                                        , Char ( 13 ) + Char ( 10 )
                                                        , '--' + Char ( 13 ) + Char ( 10 )
                                                        , '* PK, Unique, Real: '
                                                        , is_index_primary_key
                                                        , ', '
                                                        , is_index_unique
                                                        , ', '
                                                        , is_index_real
                                                        , Char ( 13 ) + Char ( 10 )
                                                        , '* ' + fk.referenced_AntoraXref + Char ( 13 ) + Char ( 10 )
                                                        , Iif(ix.is_index_disabled = 1
                                                    , '* is disabled' + Char ( 13 ) + Char ( 10 )
                                                    , Null)
                                                      )
                                             , Char ( 13 ) + Char ( 10 )
                                           ) Within Group(Order By
                                                              ix.is_index_primary_key Desc
                                                            , ix.is_index_unique Desc
                                                            , ix.index_name)
  , PumlIndexList             = String_Agg (
                                               Concat (
                                                          Cast('' As NVarchar(Max))
                                                        , Iif(is_index_real = 0, '- ', Null)
                                                        , Iif(is_index_primary_key = 1, '**', Null)
                                                        , ix.index_name
                                                        , Iif(is_index_primary_key = 1, '**', Null)
                                                        , Char ( 13 ) + Char ( 10 )
                                                        , '{' + ix.IndexSemanticGroup + '}'
                                                        , Char ( 13 ) + Char ( 10 )
                                                        , '..'
                                                        , Char ( 13 ) + Char ( 10 )
                                                        , PumlIndexColumnList
                                                      )
                                             , Char ( 13 ) + Char ( 10 ) + '--' + Char ( 13 ) + Char ( 10 )
                                           ) Within Group(Order By
                                                              ix.is_index_primary_key Desc
                                                            , ix.is_index_unique Desc
                                                            , ix.index_name)
From
    repo.Index_gross          As ix
    Left Join
        repo.ForeignKey_gross fk
            On
            fk.referencing_index_guid = ix.index_guid
Group By
    ix.parent_RepoObject_guid;

----
// end::sql_modules_definition[]


