= [repo].[ftv_GeneratorUspStep_sql]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--AntoraReferencedList:
:ExistsProperty--AntoraReferencingList:
:ExistsProperty--ReferencedObjectList:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
3590291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
IF
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
inline function
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
882102183
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-03-03 15:01:53
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-Number]]
=== Number

[cols="d,m,m,m,m,d"]
|===
|
|Number
|int
|NOT NULL
|
|
|===


[[column-SqlStep]]
=== SqlStep

[cols="d,m,m,m,m,d"]
|===
|
|SqlStep
|nvarchar(max)
|NOT NULL
|
|
|===


[[column-Statement]]
=== Statement

[cols="d,m,m,m,m,d"]
|===
|
|Statement
|nvarchar(max)
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]



// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-Number>>
|int
|NOT NULL
|
|

|
|<<column-SqlStep>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-Statement>>
|nvarchar(max)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]
* @usp_id (int)
* @number (int)
* @usp_has_logging (tinyint)
* @required_Begin_count (int)
* @required_End_count (int)
* @is_required_ELSE (tinyint)
// end::AntoraParameterList[]

== persistence_source_RepoObject_xref

// tag::persistence_source_RepoObject_xref[]

// end::persistence_source_RepoObject_xref[]


== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_IndexPatternColumnDatatype[]

// end::pk_IndexPatternColumnDatatype[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_RepoObject_fullname[]

// end::persistence_source_RepoObject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_RepoObject_fullname2[]

// end::persistence_source_RepoObject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_RepoObject_guid[]

// end::persistence_source_RepoObject_guid[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::MS_Description[]

// end::MS_Description[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== example4

// tag::example4[]

// end::example4[]


== example5

// tag::example5[]

// end::example5[]


== has_history

// tag::has_history[]

// end::has_history[]


== example1

// tag::example1[]

// end::example1[]


== example2

// tag::example2[]

// end::example2[]


== example3

// tag::example3[]

// end::example3[]


== AdocUspSteps

// tag::AdocUspSteps[]

// end::AdocUspSteps[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_RepoObject_guid[]

// end::usp_persistence_RepoObject_guid[]


== UspExamples

// tag::UspExamples[]

// end::UspExamples[]


== UspParameters

// tag::UspParameters[]

// end::UspParameters[]


== pk_IndexPatternColumnName

// tag::pk_IndexPatternColumnName[]

// end::pk_IndexPatternColumnName[]


== pk_IndexSemanticGroup

// tag::pk_IndexSemanticGroup[]

// end::pk_IndexSemanticGroup[]


== AntoraReferencedList

// tag::AntoraReferencedList[]
* xref:repo.GeneratorUspStep.adoc[]
// end::AntoraReferencedList[]


== AntoraReferencingList

// tag::AntoraReferencingList[]
* xref:repo.GeneratorUspStep_Sql.adoc[]
// end::AntoraReferencingList[]


== ReferencedObjectList

// tag::ReferencedObjectList[]
* [repo].[GeneratorUspStep]
// end::ReferencedObjectList[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----

CREATE FUNCTION [repo].[ftv_GeneratorUspStep_sql] (
 @usp_id INT
 , @number INT
 , @usp_has_logging TINYINT = 0
 , @required_Begin_count INT = 0 --how many "BEGIN" should be added in front of statement (required in condition blocks)
 , @required_End_count INT = 0 --how many "END" should be added at the of statement (required in condition blocks)
 , @is_required_ELSE TINYINT = 0 --"ELSE" should be added in front of statement (required in condition blocks)
 )
RETURNS TABLE
AS
RETURN (
  SELECT
   --
   SqlStep =
   --
   CONCAT (
    CAST('' AS NVARCHAR(max))
    , '/*'
    , (
     SELECT [Number]
      , [Parent_Number]
      , [Name]
      , [has_logging]
      , [is_condition]
      , [is_inactive]
      , [is_SubProcedure]
      , [log_source_object]
      , [log_target_object]
      , [log_flag_InsertUpdateDelete]
      , [info_01]
      , [info_02]
      , [info_03]
      , [info_04]
      , [info_05]
      , [info_06]
      , [info_07]
      , [info_08]
      , [info_09]
     FOR json path
      , ROOT('ReportUspStep')
     )
    , '*/'
    , CHAR(13)
    , CHAR(10)
    , CASE @is_required_ELSE
     WHEN 1
      THEN 'ELSE' + CHAR(13) + CHAR(10)
     END
    , REPLICATE('BEGIN' + CHAR(13) + CHAR(10), @required_Begin_count)
    , CASE 
     WHEN [is_SubProcedure] = 1
      THEN
       --no logging
       CONCAT (
        'EXEC '
        , [Statement]
        , CHAR(13)
        , CHAR(10)
        , '--add your own parameters'
        , CASE 
         WHEN NOT [info_01] IS NULL
          THEN CONCAT (
            CHAR(13)
            , CHAR(10)
            , '  '
            , '@'
            , [info_01]
            )
         END
        , CASE 
         WHEN NOT [info_02] IS NULL
          THEN CONCAT (
            CHAR(13)
            , CHAR(10)
            , '  '
            , ','
            , '@'
            , [info_02]
            )
         END
        , CASE 
         WHEN NOT [info_03] IS NULL
          THEN CONCAT (
            CHAR(13)
            , CHAR(10)
            , '  '
            , ','
            , '@'
            , [info_03]
            )
         END
        , CASE 
         WHEN NOT [info_04] IS NULL
          THEN CONCAT (
            CHAR(13)
            , CHAR(10)
            , '  '
            , ','
            , '@'
            , [info_04]
            )
         END
        , CASE 
         WHEN NOT [info_05] IS NULL
          THEN CONCAT (
            CHAR(13)
            , CHAR(10)
            , '  '
            , ','
            , '@'
            , [info_05]
            )
         END
        , CASE 
         WHEN NOT [info_06] IS NULL
          THEN CONCAT (
            CHAR(13)
            , CHAR(10)
            , '  '
            , ','
            , '@'
            , [info_06]
            )
         END
        , CASE 
         WHEN NOT [info_07] IS NULL
          THEN CONCAT (
            CHAR(13)
            , CHAR(10)
            , '  '
            , ','
            , '@'
            , [info_07]
            )
         END
        , CASE 
         WHEN NOT [info_08] IS NULL
          THEN CONCAT (
            CHAR(13)
            , CHAR(10)
            , '  '
            , ','
            , '@'
            , [info_08]
            )
         END
        , CASE 
         WHEN NOT [info_09] IS NULL
          THEN CONCAT (
            CHAR(13)
            , CHAR(10)
            , '  '
            , ','
            , '@'
            , [info_09]
            )
         END
        , CASE 
         WHEN @usp_has_logging = 1
          THEN CONCAT (
            ''
            , CASE 
             WHEN NOT [info_01] IS NULL
              OR NOT [info_02] IS NULL
              OR NOT [info_03] IS NULL
              OR NOT [info_04] IS NULL
              OR NOT [info_05] IS NULL
              OR NOT [info_06] IS NULL
              OR NOT [info_07] IS NULL
              OR NOT [info_08] IS NULL
              OR NOT [info_09] IS NULL
              THEN CONCAT (
                CHAR(13)
                , CHAR(10)
                , ','
                )
             END
            , CHAR(13)
            , CHAR(10)
            , '--logging parameters'
            , CHAR(13)
            , CHAR(10)
            , ' @execution_instance_guid = @execution_instance_guid'
            , CHAR(13)
            , CHAR(10)
            , ' , @ssis_execution_id = @ssis_execution_id'
            , CHAR(13)
            , CHAR(10)
            , ' , @sub_execution_id = @sub_execution_id'
            , CHAR(13)
            , CHAR(10)
            , ' , @parent_execution_log_id = @current_execution_log_id'
            )
         END
        , CHAR(13)
        , CHAR(10)
        )
     WHEN [is_condition] = 1
      THEN
       --no logging
       CONCAT (
        'IF '
        , [Statement]
        )
     ELSE
      --other statements
      CONCAT (
       ''
       , 'PRINT CONCAT(''usp_id;Number;Parent_Number: '','
       , [usp_id]
       , ','';'','
       , [Number]
       , ','';'','
       , CASE 
        WHEN NOT [Parent_Number] IS NULL
         THEN CAST([Parent_Number] AS VARCHAR(50))
        ELSE 'NULL'
        END
       , ');'
       , CHAR(13)
       , CHAR(10)
       , CHAR(13)
       , CHAR(10)
       , [Statement]
       --logging depending on parameter @usp_has_logging
       , CASE 
        WHEN @usp_has_logging = 1
         AND [has_logging] = 1
         THEN CONCAT (
           ''
           , CHAR(13)
           , CHAR(10)
           , CHAR(13)
           , CHAR(10)
           , '-- Logging START --'
           , CHAR(13)
           , CHAR(10)
           , 'SET @rows = @@ROWCOUNT'
           , CHAR(13)
           , CHAR(10)
           , 'SET @step_id = @step_id + 1'
           --, char(13), char(10), 'SET @step_name = ''', [Name], ''''
           , CHAR(13)
           , CHAR(10)
           , 'SET @step_name = '
           , CASE 
            WHEN NOT [Name] IS NULL
             THEN '''' + REPLACE([Name], '''', '''''') + ''''
            ELSE 'NULL'
            END
           , CHAR(13)
           , CHAR(10)
           , 'SET @source_object = '
           , CASE 
            WHEN NOT [log_source_object] IS NULL
             THEN '''' + [log_source_object] + ''''
            ELSE 'NULL'
            END
           , CHAR(13)
           , CHAR(10)
           , 'SET @target_object = '
           , CASE 
            WHEN NOT [log_target_object] IS NULL
             THEN '''' + [log_target_object] + ''''
            ELSE 'NULL'
            END
           , CHAR(13)
           , CHAR(10)
           , CHAR(13)
           , CHAR(10)
           , 'EXEC repo.usp_ExecutionLog_insert '
           , CHAR(13)
           , CHAR(10)
           , ' @execution_instance_guid = @execution_instance_guid'
           , CHAR(13)
           , CHAR(10)
           , ' , @ssis_execution_id = @ssis_execution_id'
           , CHAR(13)
           , CHAR(10)
           , ' , @sub_execution_id = @sub_execution_id'
           , CHAR(13)
           , CHAR(10)
           , ' , @parent_execution_log_id = @parent_execution_log_id'
           , CHAR(13)
           , CHAR(10)
           , ' , @current_execution_guid = @current_execution_guid'
           , CHAR(13)
           , CHAR(10)
           , ' , @proc_id = @proc_id'
           , CHAR(13)
           , CHAR(10)
           , ' , @proc_schema_name = @proc_schema_name'
           , CHAR(13)
           , CHAR(10)
           , ' , @proc_name = @proc_name'
           , CHAR(13)
           , CHAR(10)
           , ' , @event_info = @event_info'
           , CHAR(13)
           , CHAR(10)
           , ' , @step_id = @step_id'
           , CHAR(13)
           , CHAR(10)
           , ' , @step_name = @step_name'
           , CHAR(13)
           , CHAR(10)
           , ' , @source_object = @source_object'
           , CHAR(13)
           , CHAR(10)
           , ' , @target_object = @target_object'
           , CHAR(13)
           , CHAR(10)
           , CASE [log_flag_InsertUpdateDelete]
            WHEN 'I'
             THEN ' , @inserted = @rows'
            WHEN 'U'
             THEN ' , @updated = @rows'
            WHEN 'D'
             THEN ' , @deleted = @rows'
            END
           , CASE 
            WHEN NOT [info_01] IS NULL
             THEN CONCAT (
               CHAR(13)
               , CHAR(10)
               , ' , @info_01 = '''
               , [info_01]
               , ''''
               )
            END
           , CASE 
            WHEN NOT [info_02] IS NULL
             THEN CONCAT (
               CHAR(13)
               , CHAR(10)
               , ' , @info_01 = '''
               , [info_02]
               , ''''
               )
            END
           , CASE 
            WHEN NOT [info_03] IS NULL
             THEN CONCAT (
               CHAR(13)
               , CHAR(10)
               , ' , @info_01 = '''
               , [info_03]
               , ''''
               )
            END
           , CASE 
            WHEN NOT [info_04] IS NULL
             THEN CONCAT (
               CHAR(13)
               , CHAR(10)
               , ' , @info_01 = '''
               , [info_04]
               , ''''
               )
            END
           , CASE 
            WHEN NOT [info_05] IS NULL
             THEN CONCAT (
               CHAR(13)
               , CHAR(10)
               , ' , @info_01 = '''
               , [info_05]
               , ''''
               )
            END
           , CASE 
            WHEN NOT [info_06] IS NULL
             THEN CONCAT (
               CHAR(13)
               , CHAR(10)
               , ' , @info_01 = '''
               , [info_06]
               , ''''
               )
            END
           , CASE 
            WHEN NOT [info_07] IS NULL
             THEN CONCAT (
               CHAR(13)
               , CHAR(10)
               , ' , @info_01 = '''
               , [info_07]
               , ''''
               )
            END
           , CASE 
            WHEN NOT [info_08] IS NULL
             THEN CONCAT (
               CHAR(13)
               , CHAR(10)
               , ' , @info_01 = '''
               , [info_08]
               , ''''
               )
            END
           , CASE 
            WHEN NOT [info_09] IS NULL
             THEN CONCAT (
               CHAR(13)
               , CHAR(10)
               , ' , @info_01 = '''
               , [info_09]
               , ''''
               )
            END
           , CHAR(13)
           , CHAR(10)
           , '-- Logging END --'
           --, char(13), char(10)
           )
        END
       )
     END
    , REPLICATE(CHAR(13) + CHAR(10) + 'END;', @required_End_count)
    , CHAR(13)
    , CHAR(10)
    )
   , Number
   , [Statement]
  FROM [repo].[GeneratorUspStep] s
  WHERE s.[usp_id] = @usp_id
   AND s.Number = @number
  )

----
// end::sql_modules_definition[]


