= [repo].[ftv_RepoObject_ReferenceTree_referenced]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--exampleusage:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
63CDA946-459D-EB11-84F6-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
IF
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
inline function
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
175339689
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-14 16:16:01
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-Referenced_Depth]]
=== Referenced_Depth

[cols="d,m,m,m,m,d"]
|===
|
|Referenced_Depth
|int
|NULL
|
|
|===


[[column-Referenced_fullname]]
=== Referenced_fullname

[cols="d,m,m,m,m,d"]
|===
|
|Referenced_fullname
|nvarchar(261)
|NULL
|
|
|===


[[column-Referenced_fullname2]]
=== Referenced_fullname2

[cols="d,m,m,m,m,d"]
|===
|
|Referenced_fullname2
|nvarchar(257)
|NULL
|
|
|===


[[column-Referenced_guid]]
=== Referenced_guid

[cols="d,m,m,m,m,d"]
|===
|
|Referenced_guid
|uniqueidentifier
|NULL
|
|
|===


[[column-Referenced_type]]
=== Referenced_type

[cols="d,m,m,m,m,d"]
|===
|
|Referenced_type
|char(2)
|NULL
|
|
|===


[[column-Referencing_Depth]]
=== Referencing_Depth

[cols="d,m,m,m,m,d"]
|===
|
|Referencing_Depth
|int
|NULL
|
|
|===


[[column-Referencing_fullname]]
=== Referencing_fullname

[cols="d,m,m,m,m,d"]
|===
|
|Referencing_fullname
|nvarchar(261)
|NULL
|
|
|===


[[column-Referencing_fullname2]]
=== Referencing_fullname2

[cols="d,m,m,m,m,d"]
|===
|
|Referencing_fullname2
|nvarchar(257)
|NULL
|
|
|===


[[column-Referencing_guid]]
=== Referencing_guid

[cols="d,m,m,m,m,d"]
|===
|
|Referencing_guid
|uniqueidentifier
|NULL
|
|
|===


[[column-Referencing_type]]
=== Referencing_type

[cols="d,m,m,m,m,d"]
|===
|
|Referencing_type
|char(2)
|NULL
|
|
|===


[[column-RepoObject_guid]]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]











// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-Referenced_Depth>>
|int
|NULL
|
|

|
|<<column-Referenced_fullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-Referenced_fullname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-Referenced_guid>>
|uniqueidentifier
|NULL
|
|

|
|<<column-Referenced_type>>
|char(2)
|NULL
|
|

|
|<<column-Referencing_Depth>>
|int
|NULL
|
|

|
|<<column-Referencing_fullname>>
|nvarchar(261)
|NULL
|
|

|
|<<column-Referencing_fullname2>>
|nvarchar(257)
|NULL
|
|

|
|<<column-Referencing_guid>>
|uniqueidentifier
|NULL
|
|

|
|<<column-Referencing_type>>
|char(2)
|NULL
|
|

|
|<<column-RepoObject_guid>>
|uniqueidentifier
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]
* @RepoObject_guid (uniqueidentifier)
* @Referenced_Depth (int)
* @Referencing_Depth (int)
// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:graph.RepoObject_ReferencingReferenced.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

DECLARE @RepoObject_guid uniqueidentifier

SET @RepoObject_guid = (SELECT RepoObject_guid from [repo].[RepoObject] where RepoObject_fullname = '[repo].[RepoObject_gross]')

SELECT *
FROM [repo].[ftv_RepoObject_ReferenceTree_referenced](@RepoObject_guid, DEFAULT, DEFAULT)
ORDER BY [Referenced_Depth]
 , [Referencing_Depth]

SELECT *
FROM [repo].[ftv_RepoObject_ReferenceTree_referenced](@RepoObject_guid, 1, 1)
ORDER BY [Referenced_Depth]
 , [Referencing_Depth]

SELECT *
FROM [repo].[ftv_RepoObject_ReferenceTree_referenced](@RepoObject_guid, 0, 6)
ORDER BY [Referenced_Depth]
 , [Referencing_Depth]

SELECT *
FROM [repo].[ftv_RepoObject_ReferenceTree_referenced](@RepoObject_guid, 100, 100)
ORDER BY [Referenced_Depth]
 , [Referencing_Depth]
// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [graph].[RepoObject_ReferencingReferenced]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----

/*
--Duplicates are possible, if exists alternative path between objects with different depth
--to elimenate them, exclude Referenced_Depth and Referencing_Depth and use DISTINCT


<<property_start>>exampleUsage
DECLARE @RepoObject_guid uniqueidentifier

SET @RepoObject_guid = (SELECT RepoObject_guid from [repo].[RepoObject] where RepoObject_fullname = '[repo].[RepoObject_gross]')

SELECT *
FROM [repo].[ftv_RepoObject_ReferenceTree_referenced](@RepoObject_guid, DEFAULT, DEFAULT)
ORDER BY [Referenced_Depth]
 , [Referencing_Depth]

SELECT *
FROM [repo].[ftv_RepoObject_ReferenceTree_referenced](@RepoObject_guid, 1, 1)
ORDER BY [Referenced_Depth]
 , [Referencing_Depth]

SELECT *
FROM [repo].[ftv_RepoObject_ReferenceTree_referenced](@RepoObject_guid, 0, 6)
ORDER BY [Referenced_Depth]
 , [Referencing_Depth]

SELECT *
FROM [repo].[ftv_RepoObject_ReferenceTree_referenced](@RepoObject_guid, 100, 100)
ORDER BY [Referenced_Depth]
 , [Referencing_Depth]
<<property_end>>


*/
create Function [repo].[ftv_RepoObject_ReferenceTree_referenced]
(
    @RepoObject_guid   UniqueIdentifier
  , @Referenced_Depth  Int = 0
  , @Referencing_Depth Int = 0 --has no effect
)
Returns Table
As
Return
(
    --trees are recursive to get parent child relations
    With
    tree_referenced
    As
        (
        Select
            FirstNode.*
          , 1 As Referenced_Depth
          , 0 As Referencing_Depth
        From
            graph.RepoObject_ReferencingReferenced As FirstNode
        --INNER JOIN [config].[type] t1
        -- ON t1.[type] = FirstNode.Referenced_type
        --INNER JOIN [config].[type] t2
        -- ON t2.[type] = FirstNode.Referencing_type
        Where
            Referencing_guid = @RepoObject_guid
            And 1            <= @Referenced_Depth
        --AND t1.[is_DocsOutput] = 1
        --AND t2.[is_DocsOutput] = 1
        Union All
        Select
            child.*
          , Referenced_Depth = parent.Referenced_Depth + 1
          , 0
        From
            graph.RepoObject_ReferencingReferenced As child
            Inner Join
                tree_referenced                    As parent
                    On
                    child.Referencing_guid = parent.Referenced_guid
        --INNER JOIN [config].[type] t1
        -- ON t1.[type] = child.Referenced_type
        ----INNER JOIN [config].[type] t2
        ---- ON t2.[type] = child.Referencing_type
        Where
            parent.Referenced_Depth < @Referenced_Depth
        --AND t1.[is_DocsOutput] = 1
        ----AND t2.[is_DocsOutput] = 1
        )
  --,
  --  tree_referencing
  --  As
  --      (
  --      Select
  --          FirstNode.*
  --        , 0 As Referenced_Depth
  --        , 1 As Referencing_Depth
  --      From
  --          graph.RepoObject_ReferencingReferenced As FirstNode
  --      --INNER JOIN [config].[type] t1
  --      -- ON t1.[type] = FirstNode.Referenced_type
  --      --INNER JOIN [config].[type] t2
  --      -- ON t2.[type] = FirstNode.Referencing_type
  --      Where
  --          Referenced_guid = @RepoObject_guid
  --          And 1           <= @Referencing_Depth
  --      --AND t1.[is_DocsOutput] = 1
  --      --AND t2.[is_DocsOutput] = 1
  --      Union All
  --      Select
  --          child.*
  --        , 0
  --        , Referencing_Depth = parent.Referencing_Depth + 1
  --      From
  --          graph.RepoObject_ReferencingReferenced As child
  --          Inner Join
  --              tree_referencing                   As parent
  --                  On
  --                  child.Referenced_guid = parent.Referencing_guid
  --      ----INNER JOIN [config].[type] t1
  --      ---- ON t1.[type] = child.Referenced_type
  --      --INNER JOIN [config].[type] t2
  --      -- ON t2.[type] = child.Referencing_type
  --      Where
  --          parent.Referencing_Depth < @Referencing_Depth
  --      ----AND t1.[is_DocsOutput] = 1
  --      --AND t2.[is_DocsOutput] = 1
  --      )
    Select
        *
      , @RepoObject_guid As RepoObject_guid
    From
        tree_referenced
    --Union
    --Select
    --    *
    --  , @RepoObject_guid As RepoObject_guid
    --From
    --    tree_referencing
);
----
// end::sql_modules_definition[]


