= [repo].[usp_RepoObjectSource_QueryPlan]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
8F90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1746105261
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-13 19:02:46
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]
* @execution_instance_guid (uniqueidentifier)
* @ssis_execution_id (bigint)
* @sub_execution_id (int)
* @parent_execution_log_id (bigint)
// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:logs.usp_ExecutionLog_insert.adoc[]
* xref:repo.ftv_query_plan_extract_source.adoc[]
* xref:repo.RepoObject.adoc[]
* xref:repo.RepoObject_gross.adoc[]
* xref:repo.RepoObjectColumn.adoc[]
* xref:repo.RepoObjectSource_QueryPlan.adoc[]
* xref:repo.SysObjectColumn_QueryPlanExpression.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:repo.usp_main.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [logs].[usp_ExecutionLog_insert]
* [repo].[ftv_query_plan_extract_source]
* [repo].[RepoObject]
* [repo].[RepoObject_gross]
* [repo].[RepoObjectColumn]
* [repo].[RepoObjectSource_QueryPlan]
* [repo].[SysObjectColumn_QueryPlanExpression]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----

/*
references on column level
target: repo.RepoObjectSource__QueryPlan
source: query plan analysis of the execution of a query like
`Vselect top (1) * into #foo from (SELECT * FROM sss.aaa)`

First update query plan and write them into repo.RepoObject_QueryPlan
then analyse the query plans and update results into 

EXEC [repo].[usp_RepoObject__update_SysObject_query_plan]
EXEC [repo].[usp_RepoObjectSource_from_query_plan__update]

some query plans can't be extracted, some can be extracted but not analyzed
in this case mark the RepoObject in repo.RepoObject
SET [has_execution_plan_issue] = 1

*/
CREATE Procedure [repo].[usp_RepoObjectSource_QueryPlan]
    -- some optional parameters, used for logging
    @execution_instance_guid UniqueIdentifier = Null --SSIS system variable ExecutionInstanceGUID could be used, but other any other guid
  , @ssis_execution_id       BigInt           = Null --only SSIS system variable ServerExecutionID should be used, or any other consistent number system, do not mix
  , @sub_execution_id        Int              = Null
  , @parent_execution_log_id BigInt           = Null
As
Declare
    @current_execution_log_id BigInt
  , @current_execution_guid   UniqueIdentifier = NewId ()
  , @source_object            NVarchar(261)    = Null
  , @target_object            NVarchar(261)    = Null
  , @proc_id                  Int              = @@ProcId
  , @proc_schema_name         NVarchar(128)    = Object_Schema_Name ( @@ProcId )
  , @proc_name                NVarchar(128)    = Object_Name ( @@ProcId )
  , @event_info               NVarchar(Max)
  , @step_id                  Int              = 0
  , @step_name                NVarchar(1000)   = Null
  , @rows                     Int;

Set @event_info =
(
    Select
        event_info
    From
        sys.dm_exec_input_buffer ( @@Spid, Current_Request_Id ())
);

If @execution_instance_guid Is Null
    Set @execution_instance_guid = NewId ();

--SET @rows = @@ROWCOUNT;
Set @step_id = @step_id + 1;
Set @step_name = N'start';
Set @source_object = Null;
Set @target_object = Null;

Exec logs.usp_ExecutionLog_insert
    @execution_instance_guid = @execution_instance_guid
  , @ssis_execution_id = @ssis_execution_id
  , @sub_execution_id = @sub_execution_id
  , @parent_execution_log_id = @parent_execution_log_id
  , @current_execution_guid = @current_execution_guid
  , @proc_id = @proc_id
  , @proc_schema_name = @proc_schema_name
  , @proc_name = @proc_name
  , @event_info = @event_info
  , @step_id = @step_id
  , @step_name = @step_name
  , @source_object = @source_object
  , @target_object = @target_object
  , @inserted = Null
  , @updated = Null
  , @deleted = Null
  , @info_01 = Null
  , @info_02 = Null
  , @info_03 = Null
  , @info_04 = Null
  , @info_05 = Null
  , @info_06 = Null
  , @info_07 = Null
  , @info_08 = Null
  , @info_09 = Null
  , @execution_log_id = @current_execution_log_id Output;

--
----START
--
Declare @message NVarchar(1000);

-- delete outdated entries, which need to be analyzed again
Delete From
repo.RepoObjectSource_QueryPlan
From
    repo.RepoObject_gross As ro
    Inner Join
        repo.RepoObjectSource_QueryPlan
            On
            ro.RepoObject_guid                 = repo.RepoObjectSource_QueryPlan.RepoObject_guid
            And ro.SysObject_query_executed_dt > repo.RepoObjectSource_QueryPlan.SysObject_query_executed_dt;

Set @rows = @@RowCount;
Set @step_id = @step_id + 1;
Set @step_name = N'DELETE outdated entries, which need to be analyzed again';
Set @source_object = N'[repo].[RepoObject]';
Set @target_object = N'[repo].[RepoObjectSource__query_plan]';

Exec logs.usp_ExecutionLog_insert
    @execution_instance_guid = @execution_instance_guid
  , @ssis_execution_id = @ssis_execution_id
  , @sub_execution_id = @sub_execution_id
  , @parent_execution_log_id = @parent_execution_log_id
  , @current_execution_guid = @current_execution_guid
  , @proc_id = @proc_id
  , @proc_schema_name = @proc_schema_name
  , @proc_name = @proc_name
  , @event_info = @event_info
  , @step_id = @step_id
  , @step_name = @step_name
  , @source_object = @source_object
  , @target_object = @target_object
  , @inserted = Null
  , @updated = Null
  , @deleted = @rows
  , @info_01 = Null
  , @info_02 = Null
  , @info_03 = Null
  , @info_04 = Null
  , @info_05 = Null
  , @info_06 = Null
  , @info_07 = Null
  , @info_08 = Null
  , @info_09 = Null;

Declare object_cursor Cursor Local Fast_Forward For
--
Select
    ro.RepoObject_guid
  , ro.SysObject_fullname
--, [ro].[SysObject_query_executed_dt]
--, [ro].SysObject_query_plan
From
    repo.RepoObject_gross As ro
Where
    Not ro.SysObject_query_plan Is Null
    --only views
    And ro.SysObject_type                         = 'V'
    --exclude objects with has_execution_plan_issue
    And IsNull ( ro.has_execution_plan_issue, 0 ) = 0
    And Not Exists
(
    Select
        RepoObject_guid
    From
        repo.RepoObjectSource_QueryPlan As TFilter
    Where
        ro.RepoObject_guid                 = TFilter.RepoObject_guid
        And ro.SysObject_query_executed_dt = TFilter.SysObject_query_executed_dt
)
Order By
    ro.RepoObject_guid;

Declare
    @RepoObject_guid    UniqueIdentifier
  , @SysObject_fullname NVarchar(500);

--, @SysObject_query_executed_dt datetime
--, @SysObject_query_plan xml
Open object_cursor;

Fetch Next From object_cursor
Into
    @RepoObject_guid
  , @SysObject_fullname;

--, @SysObject_query_executed_dt, @SysObject_query_plan
While @@Fetch_Status <> -1
Begin
    If @@Fetch_Status <> -2
    Begin
        --information about the current RepoObject in case of error
        --some query plans can't be extracted, some can be extracted but not analyzed
        --in this case mark the RepoObject in repo.RepoObject
        --SET [has_execution_plan_issue] = 1
        Print Concat ( @RepoObject_guid, ' ', @SysObject_fullname );

        Begin Try
            Insert Into repo.RepoObjectSource_QueryPlan
            (
                RepoObject_guid
              , SysObject_query_executed_dt
              , target_column_name
              , source_server_name
              , source_database_name
              , source_schema_name
              , source_table_name
              , source_column_name
              , const_value
              , target_column_info
              , source_column_info
              , const_info
            )
            Select
                ro.RepoObject_guid
              , ro.SysObject_query_executed_dt
              , sc.target_column_name
              , sc.source_server_name
              , sc.source_database_name
              , sc.source_schema_name
              , sc.source_table_name
              , sc.source_column_name
              , sc.const_value
              , sc.target_column_info
              , sc.source_column_info
              , sc.const_info
            From
                repo.RepoObject_gross                                                   As ro
                Cross Apply repo.ftv_query_plan_extract_source ( SysObject_query_plan ) As sc
            Where
                ro.RepoObject_guid = @RepoObject_guid
            Option ( MaxRecursion 100 );

            --WHERE  NOT [ro].[SysObject_query_plan] IS NULL
            --       AND NOT EXISTS
            --(
            --    SELECT
            --           [RepoObject_guid]
            --    FROM
            --         [repo].[RepoObjectSource_from_query_plan] AS [TFilter]
            --    WHERE  [ro].[RepoObject_guid] = [TFilter].[RepoObject_guid]
            --           AND [ro].[SysObject_query_executed_dt] = [TFilter].[SysObject_query_executed_dt]
            --) OPTION(
            --         MAXRECURSION 20)
            Set @rows = @@RowCount;
            Set @message = Null;
        End Try
        Begin Catch
            Set @rows = 0;
            Set @message = N'CATCH - can not analyze query plan';

            Update
                ro
            Set
                has_execution_plan_issue = 1
            From
                repo.RepoObject As ro
            Where
                ro.RepoObject_guid = @RepoObject_guid;
        End Catch;

        Set @step_id = @step_id + 1;
        Set @step_name = N'CROSS APPLY repo.ftv_query_plan_extract_source(SysObject_query_plan)';
        Set @source_object = N'[repo].[RepoObject]';
        Set @target_object = N'[repo].[RepoObjectSource__query_plan]';

        Exec logs.usp_ExecutionLog_insert
            @execution_instance_guid = @execution_instance_guid
          , @ssis_execution_id = @ssis_execution_id
          , @sub_execution_id = @sub_execution_id
          , @parent_execution_log_id = @parent_execution_log_id
          , @current_execution_guid = @current_execution_guid
          , @proc_id = @proc_id
          , @proc_schema_name = @proc_schema_name
          , @proc_name = @proc_name
          , @event_info = @event_info
          , @step_id = @step_id
          , @step_name = @step_name
          , @source_object = @source_object
          , @target_object = @target_object
          , @inserted = @rows
          , @updated = Null
          , @deleted = Null
          , @info_01 = @RepoObject_guid
          , @info_02 = @SysObject_fullname
          , @info_03 = @message
          , @info_04 = Null
          , @info_05 = Null
          , @info_06 = Null
          , @info_07 = Null
          , @info_08 = Null
          , @info_09 = Null;
    End;

    Fetch Next From object_cursor
    Into
        @RepoObject_guid
      , @SysObject_fullname;
--, @SysObject_query_executed_dt, @SysObject_query_plan
End;

Close object_cursor;
Deallocate object_cursor;

Insert Into repo.RepoObjectColumn
(
    RepoObject_guid
  , SysObjectColumn_name
  , SysObjectColumn_column_id
  , is_query_plan_expression
)
Select
    RepoObject_guid
  , SysObjectColumn_name
  , SysObjectColumn_column_id
  , 1 As is_query_plan_expression
From
    repo.SysObjectColumn_QueryPlanExpression As T1
Where
    Not Exists
(
    Select
        SysObjectColumn_name
    From
        repo.RepoObjectColumn As roc
    Where
        roc.RepoObject_guid          = T1.RepoObject_guid
        And roc.SysObjectColumn_name = T1.SysObjectColumn_name
);

Set @rows = @@RowCount;
Set @step_id = @step_id + 1;
Set @step_name = N'INSERT missing';
Set @source_object = N'[repo].[SysObjectColumn__query_plan_expression]';
Set @target_object = N'[repo].[RepoObjectColumn]';

Exec logs.usp_ExecutionLog_insert
    @execution_instance_guid = @execution_instance_guid
  , @ssis_execution_id = @ssis_execution_id
  , @sub_execution_id = @sub_execution_id
  , @parent_execution_log_id = @parent_execution_log_id
  , @current_execution_guid = @current_execution_guid
  , @proc_id = @proc_id
  , @proc_schema_name = @proc_schema_name
  , @proc_name = @proc_name
  , @event_info = @event_info
  , @step_id = @step_id
  , @step_name = @step_name
  , @source_object = @source_object
  , @target_object = @target_object
  , @inserted = @rows
  , @updated = Null
  , @deleted = Null
  , @info_01 = Null
  , @info_02 = Null
  , @info_03 = Null
  , @info_04 = Null
  , @info_05 = Null
  , @info_06 = Null
  , @info_07 = Null
  , @info_08 = Null
  , @info_09 = Null;

Delete
roc
From
    repo.RepoObjectColumn As roc
Where
    is_query_plan_expression = 1
    And Not Exists
(
    Select
        SysObjectColumn_name
    From
        repo.SysObjectColumn_QueryPlanExpression As T1
    Where
        roc.RepoObject_guid          = T1.RepoObject_guid
        And roc.SysObjectColumn_name = T1.SysObjectColumn_name
);

Set @rows = @@RowCount;
Set @step_id = @step_id + 1;
Set @step_name = N'DELETE not existing';
Set @source_object = N'[repo].[SysObjectColumn__query_plan_expression]';
Set @target_object = N'[repo].[RepoObjectColumn]';

Exec logs.usp_ExecutionLog_insert
    @execution_instance_guid = @execution_instance_guid
  , @ssis_execution_id = @ssis_execution_id
  , @sub_execution_id = @sub_execution_id
  , @parent_execution_log_id = @parent_execution_log_id
  , @current_execution_guid = @current_execution_guid
  , @proc_id = @proc_id
  , @proc_schema_name = @proc_schema_name
  , @proc_name = @proc_name
  , @event_info = @event_info
  , @step_id = @step_id
  , @step_name = @step_name
  , @source_object = @source_object
  , @target_object = @target_object
  , @inserted = Null
  , @updated = Null
  , @deleted = @rows
  , @info_01 = Null
  , @info_02 = Null
  , @info_03 = Null
  , @info_04 = Null
  , @info_05 = Null
  , @info_06 = Null
  , @info_07 = Null
  , @info_08 = Null
  , @info_09 = Null;

--
--END
--
--SET @rows = @@ROWCOUNT;
Set @step_id = @step_id + 1;
Set @step_name = N'end';
Set @source_object = Null;
Set @target_object = Null;

Exec logs.usp_ExecutionLog_insert
    @execution_instance_guid = @execution_instance_guid
  , @ssis_execution_id = @ssis_execution_id
  , @sub_execution_id = @sub_execution_id
  , @parent_execution_log_id = @parent_execution_log_id
  , @current_execution_guid = @current_execution_guid
  , @proc_id = @proc_id
  , @proc_schema_name = @proc_schema_name
  , @proc_name = @proc_name
  , @event_info = @event_info
  , @step_id = @step_id
  , @step_name = @step_name
  , @source_object = @source_object
  , @target_object = @target_object
  , @inserted = Null
  , @updated = Null
  , @deleted = Null
  , @info_01 = Null
  , @info_02 = Null
  , @info_03 = Null
  , @info_04 = Null
  , @info_05 = Null
  , @info_06 = Null
  , @info_07 = Null
  , @info_08 = Null
  , @info_09 = Null;
----
// end::sql_modules_definition[]


