= [repo].[Index_ColumList]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--has_execution_plan_issue:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6890291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1202819347
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-13 19:02:38
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-index_guid]]
=== index_guid

[cols="d,m,m,m,m,d"]
|===
|1
|*index_guid*
|uniqueidentifier
|NULL
|
|
|===

.Referenced Columns
--
* xref:repo.IndexColumn_union.adoc#column-index_guid[repo.IndexColumn_union.index_guid]
--


[[column-AntoraIndexColumnList]]
=== AntoraIndexColumnList

[cols="d,m,m,m,m,d"]
|===
|
|AntoraIndexColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.Index_gross.adoc#column-AntoraIndexColumnList[repo.Index_gross.AntoraIndexColumnList]
--


[[column-ColumnList]]
=== ColumnList

[cols="d,m,m,m,m,d"]
|===
|
|ColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.Index_gross.adoc#column-ColumnList[repo.Index_gross.ColumnList]
--


[[column-ConstraintColumnList]]
=== ConstraintColumnList

[cols="d,m,m,m,m,d"]
|===
|
|ConstraintColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.Index_gross.adoc#column-ConstraintColumnList[repo.Index_gross.ConstraintColumnList]
--


[[column-DbmlIndexColumnList]]
=== DbmlIndexColumnList

[cols="d,m,m,m,m,d"]
|===
|
|DbmlIndexColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.Index_gross.adoc#column-DbmlIndexColumnList[repo.Index_gross.DbmlIndexColumnList]
--


[[column-PersistenceWhereColumnList]]
=== PersistenceWhereColumnList

[cols="d,m,m,m,m,d"]
|===
|
|PersistenceWhereColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.Index_gross.adoc#column-PersistenceWhereColumnList[repo.Index_gross.PersistenceWhereColumnList]
--


[[column-PumlIndexColumnList]]
=== PumlIndexColumnList

[cols="d,m,m,m,m,d"]
|===
|
|PumlIndexColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.Index_gross.adoc#column-PumlIndexColumnList[repo.Index_gross.PumlIndexColumnList]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-index_guid>>*
|uniqueidentifier
|NULL
|
|







// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-AntoraIndexColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-ColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-ConstraintColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-DbmlIndexColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PersistenceWhereColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PumlIndexColumnList>>
|nvarchar(max)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-PK_Index_ColumList]]
=== PK_Index_ColumList

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_no_group[no_group]
+
--
* <<column-index_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:repo.IndexColumn_union.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:repo.Index_gross.adoc[]
* xref:repo.Index_SqlConstraint_PkUq.adoc[]
* xref:uspgenerator.GeneratorUspStep_Persistence.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]
1
// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]
678AA10A-AB97-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
uniqueidentifier
// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
index_guid
// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[IndexColumn_union]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----
Create View repo.Index_ColumList
As
Select
    col.index_guid
  , AntoraIndexColumnList      = String_Agg (
                                                Concat (
                                                           Cast(N'' As NVarchar(Max))
                                                         , '* <<column-' + col.SysObject_column_name + '>>; '
                                                         , col.SysObject_column_user_type_fullname
                                                       )
                                              , Char ( 13 ) + Char ( 10 )
                                            ) Within Group(Order By
                                                               col.index_column_id)
  --ColumnList doesn't contain Asc and Desc
  , ColumnList                 = String_Agg (
                                                Concat (
                                                           --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                                           Cast(' ' As NVarchar(Max)), QuoteName ( col.SysObject_column_name )
                                                       )
                                              , ','
                                            ) Within Group(Order By
                                                               col.index_column_id)
  --ConstraintColumnList contains Asc and Desc
  , ConstraintColumnList       = String_Agg (
                                                Concat (
                                                           --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                                           Cast(' ' As NVarchar(Max))
                                                         , QuoteName ( col.SysObject_column_name )
                                                         , Case col.is_descending_key
                                                               When 1
                                                                   Then
                                                                   ' DESC'
                                                               Else
                                                                   ' ASC'
                                                           End
                                                       )
                                              , ','
                                            ) Within Group(Order By
                                                               col.index_column_id)
  , DbmlIndexColumnList        = String_Agg (
                                                Concat (
                                                           --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                                           Cast(' ' As NVarchar(Max))
                                                         , QuoteName ( col.SysObject_column_name, '"' )
                                                       )
                                              , ','
                                            ) Within Group(Order By
                                                               col.index_column_id)
  , PersistenceWhereColumnList = Stuff (
                                           String_Agg (
                                                          Concat (
                                                                     --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
                                                                     Cast('AND T.' As NVarchar(Max))
                                                                   , QuoteName ( col.SysObject_column_name )
                                                                   , ' = S.'
                                                                   , QuoteName ( col.SysObject_column_name )
                                                                   , Char ( 13 )
                                                                   , Char ( 10 )
                                                                 )
                                                        , ''
                                                      ) Within Group(Order By
                                                                         col.index_column_id)
                                         , 1
                                         , 4
                                         , Null
                                       )
  , PumlIndexColumnList        = String_Agg (
                                                Concat (
                                                           Cast(N'' As NVarchar(Max))
                                                         , col.SysObject_column_name + '; '
                                                         , col.SysObject_column_user_type_fullname
                                                       )
                                              , Char ( 13 ) + Char ( 10 )
                                            ) Within Group(Order By
                                                               col.index_column_id)
From
    repo.IndexColumn_union As col
Group By
    col.index_guid;

----
// end::sql_modules_definition[]


