= [repo].[RepoObject_ColumnList]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--AntoraReferencedList:
:ExistsProperty--AntoraReferencingList:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_IndexPatternColumnDatatype:
:ExistsProperty--pk_IndexPatternColumnName:
:ExistsProperty--ReferencedObjectList:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6F90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1490104349
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-02 13:14:29
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-RepoObject_guid]]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|1
|*RepoObject_guid*
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObjectColumn_gross.adoc#column-RepoObject_guid[repo.RepoObjectColumn_gross.RepoObject_guid]
--


[[column-CreateColumnList]]
=== CreateColumnList

[cols="d,m,m,m,m,d"]
|===
|
|CreateColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.RepoObject_gross.adoc#column-CreateColumnList[repo.RepoObject_gross.CreateColumnList]
--


[[column-DbmlColumnList]]
=== DbmlColumnList

[cols="d,m,m,m,m,d"]
|===
|
|DbmlColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.RepoObject_gross.adoc#column-DbmlColumnList[repo.RepoObject_gross.DbmlColumnList]
--


[[column-PersistenceCompareColumnList]]
=== PersistenceCompareColumnList

[cols="d,m,m,m,m,d"]
|===
|
|PersistenceCompareColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.RepoObject_gross.adoc#column-PersistenceCompareColumnList[repo.RepoObject_gross.PersistenceCompareColumnList]
--


[[column-PersistenceInsertColumnList]]
=== PersistenceInsertColumnList

[cols="d,m,m,m,m,d"]
|===
|
|PersistenceInsertColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.RepoObject_gross.adoc#column-PersistenceInsertColumnList[repo.RepoObject_gross.PersistenceInsertColumnList]
--


[[column-PersistenceUpdateColumnList]]
=== PersistenceUpdateColumnList

[cols="d,m,m,m,m,d"]
|===
|
|PersistenceUpdateColumnList
|nvarchar(max)
|NULL
|
|
|===

.Referencing Columns
--
* xref:repo.RepoObject_gross.adoc#column-PersistenceUpdateColumnList[repo.RepoObject_gross.PersistenceUpdateColumnList]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-RepoObject_guid>>*
|uniqueidentifier
|NOT NULL
|
|






// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-CreateColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-DbmlColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PersistenceCompareColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PersistenceInsertColumnList>>
|nvarchar(max)
|NULL
|
|

|
|<<column-PersistenceUpdateColumnList>>
|nvarchar(max)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-PK_RepoObject_ColumnList]]
=== PK_RepoObject_ColumnList

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_no_group[no_group]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 1, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::AdocUspSteps[]

// end::AdocUspSteps[]


== pk_IndexSemanticGroup

// tag::pk_IndexSemanticGroup[]

// end::pk_IndexSemanticGroup[]


== example1

// tag::example1[]

// end::example1[]


== example2

// tag::example2[]

// end::example2[]


== example3

// tag::example3[]

// end::example3[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_RepoObject_guid[]

// end::usp_persistence_RepoObject_guid[]


== UspExamples

// tag::UspExamples[]

// end::UspExamples[]


== UspParameters

// tag::UspParameters[]

// end::UspParameters[]


== persistence_source_RepoObject_xref

// tag::persistence_source_RepoObject_xref[]

// end::persistence_source_RepoObject_xref[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::MS_Description[]

// end::MS_Description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_RepoObject_fullname[]

// end::persistence_source_RepoObject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_RepoObject_fullname2[]

// end::persistence_source_RepoObject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_RepoObject_guid[]

// end::persistence_source_RepoObject_guid[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== example4

// tag::example4[]

// end::example4[]


== example5

// tag::example5[]

// end::example5[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== AntoraReferencedList

// tag::AntoraReferencedList[]
* xref:repo.RepoObjectColumn_gross.adoc[]
// end::AntoraReferencedList[]


== AntoraReferencingList

// tag::AntoraReferencingList[]
* xref:repo.RepoObject_gross.adoc[]
* xref:repo.RepoObject_SqlCreateTable.adoc[]
// end::AntoraReferencingList[]


== pk_index_guid

// tag::pk_index_guid[]
D58818B0-CA97-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_IndexPatternColumnDatatype[]
uniqueidentifier
// end::pk_IndexPatternColumnDatatype[]


== pk_IndexPatternColumnName

// tag::pk_IndexPatternColumnName[]
RepoObject_guid
// end::pk_IndexPatternColumnName[]


== ReferencedObjectList

// tag::ReferencedObjectList[]
* [repo].[RepoObjectColumn_gross]
// end::ReferencedObjectList[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----

CREATE VIEW [repo].[RepoObject_ColumnList]
AS
SELECT roc.[RepoObject_guid]
 , CreateColumnList = String_Agg(CONCAT (
   --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
   CAST('' AS NVARCHAR(MAX))
   , QuoteName(roc.[RepoObjectColumn_name])
   , ' '
   , CASE roc.Repo_is_computed
    WHEN 1
     THEN CONCAT (
       'AS '
       , roc.Repo_definition
       , CASE 
        WHEN roc.Repo_is_persisted = 1
         THEN ' PERSISTED'
        END
       )
    ELSE CONCAT (
      roc.[Repo_user_type_fullname]
      --CONSTRAINT
      --DEFAULT
      , CASE 
       WHEN roc.[Repo_default_name] <> ''
        AND IsNull(roc.[Repo_default_is_system_named], 0) = 0
        THEN CONCAT (
          ' CONSTRAINT '
          , roc.[Repo_default_name]
          )
       END
      --
      , CASE 
       WHEN roc.[Repo_default_definition] <> ''
        THEN CONCAT (
          ' DEFAULT '
          , roc.[Repo_default_definition]
          )
       END
      --temporal table columns
      , CASE roc.[Repo_generated_always_type]
       WHEN 1
        THEN ' GENERATED ALWAYS AS ROW START'
       WHEN 2
        THEN ' GENERATED ALWAYS AS ROW END'
       END
      --IDENTITY
      --, CASE roc.Repo_is_identity
      -- WHEN 1
      --  THEN ' IDENTITY ' + CASE 
      --    WHEN NOT roc.[Repo_seed_value] IS NULL
      --     AND NOT roc.[Repo_increment_value] IS NULL
      --     THEN CONCAT (
      --       '('
      --       , CAST(roc.[Repo_seed_value] AS NVARCHAR(max))
      --       , ', '
      --       , CAST(roc.[Repo_increment_value] AS NVARCHAR(max))
      --       , ')'
      --       )
      --    END
      -- END
      , CASE roc.[Repo_is_identity]
       WHEN 1
        THEN CONCAT (
          ' IDENTITY ('
          , IsNull(CAST(roc.[Repo_seed_value] AS NVARCHAR(MAX)), '1')
          , ', '
          , IsNull(CAST(roc.[Repo_increment_value] AS NVARCHAR(MAX)), '1')
          , ')'
          )
       END
      , CASE 
       WHEN roc.[Repo_is_nullable] = 0
        OR roc.[Repo_generated_always_type] >= 1
        THEN ' NOT'
       END
      , ' NULL '
      )
    END
   , CHAR(13)
   , CHAR(10)
   ), ', ') WITHIN
GROUP (
  ORDER BY roc.RepoObjectColumn_column_id
  )
 , DbmlColumnList = String_Agg(CONCAT (
   --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
   CAST('' AS NVARCHAR(MAX))
   , QUOTENAME(roc.[RepoObjectColumn_name], '"')
   , ' '
   , roc.[Repo_user_type_fullname]
   , ' '
   , '['
   --null or not null
   , CASE 
    WHEN roc.[Repo_is_nullable] = 0
     OR roc.[Repo_generated_always_type] >= 1
     THEN 'not'
    END
   , ' null'
   --primary key or pk
   , CASE 
    WHEN roc.[is_index_primary_key] = 1
     THEN ', pk'
    END
   --unique
   --default: some_value
   --Attention: 
   --number value starts blank: default: 123 or default: 123.456
   --string value starts with single quotes: default: 'some string value'
   --expression value is wrapped with parenthesis: default: `now() - interval '5 days'`
   --boolean (true/false/null): default: false or default: null
   --
   , CASE 
    WHEN roc.[Repo_default_definition] <> ''
     THEN CONCAT (
       ', default: '
       , QUOTENAME(roc.[Repo_default_definition], '`')
       )
    END
   --increment
   , CASE roc.[Repo_is_identity]
    WHEN 1
     THEN ', increment'
    END
   --note: 'string to add notes'
   , CASE 
    WHEN NOT roc.Property_ms_description IS NULL
     THEN ', Note: ''''''' + CHAR(13) + CHAR(10) + REPLACE(REPLACE(roc.Property_ms_description, '\', '\\'), '''''''', '\''''''') + CHAR(13) + CHAR(10) + ''''''''
    END
   , ']'
   ), CHAR(13) + CHAR(10)) WITHIN
GROUP (
  ORDER BY roc.RepoObjectColumn_column_id
  )
 , PersistenceCompareColumnList = STUFF(String_Agg(CONCAT (
    --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
    CAST('' AS NVARCHAR(MAX))
    , ''
    , CASE 
     WHEN
      --source should exists
      NOT roc.[persistence_source_RepoObjectColumn_guid] IS NULL
      AND IsNull(roc.[is_persistence_no_include], 0) = 0
      AND IsNull(roc.[is_persistence_no_check], 0) = 0
      AND IsNull(roc.is_query_plan_expression, 0) = 0
      AND roc.Repo_generated_always_type = 0
      AND roc.Repo_is_computed = 0
      AND roc.Repo_is_identity = 0
      --do not compare PK
      --issue: if the source column is marked as PK but the target column is not marked as PK, then this column is included
      --to avoid this we would need to analyze also the source column properties
      --or we could set [is_persistence_no_check] = 1
      AND roc.[is_index_primary_key] IS NULL
      THEN CONCAT (
        'OR T.'
        , QuoteName(roc.[RepoObjectColumn_name])
        , ' <> S.'
        , QuoteName(roc.[RepoObjectColumn_name])
        , CASE 
         WHEN roc.Repo_is_nullable = 1
          THEN CONCAT (
            ' OR (S.'
            , QuoteName(roc.[RepoObjectColumn_name])
            , ' IS NULL AND NOT T.'
            , QuoteName(roc.[RepoObjectColumn_name])
            , ' IS NULL)'
            , ' OR (NOT S.'
            , QuoteName(roc.[RepoObjectColumn_name])
            , ' IS NULL AND T.'
            , QuoteName(roc.[RepoObjectColumn_name])
            , ' IS NULL)'
            )
         END
        , CHAR(13)
        , CHAR(10)
        )
     END
    ), '') WITHIN GROUP (
   ORDER BY roc.RepoObjectColumn_column_id
   ), 1, 3, '   ')
 , PersistenceInsertColumnList = STUFF(String_Agg(CONCAT (
    --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
    CAST('' AS NVARCHAR(MAX))
    , ''
    , CASE 
     WHEN
      --source should exists
      NOT roc.[persistence_source_RepoObjectColumn_guid] IS NULL
      AND IsNull(roc.[is_persistence_no_include], 0) = 0
      AND IsNull(roc.is_query_plan_expression, 0) = 0
      AND roc.Repo_generated_always_type = 0
      AND roc.Repo_is_computed = 0
      AND roc.Repo_is_identity = 0
      THEN CONCAT (
        ', '
        , QuoteName(roc.[RepoObjectColumn_name])
        , CHAR(13)
        , CHAR(10)
        )
     END
    ), '') WITHIN GROUP (
   ORDER BY roc.RepoObjectColumn_column_id
   ), 1, 2, '  ')
 , PersistenceUpdateColumnList = STUFF(String_Agg(CONCAT (
    --we need to convert to first argument nvarchar(max) to avoid the limit of 8000 byte
    CAST('' AS NVARCHAR(MAX))
    , ''
    , CASE 
     WHEN
      --source should exists
      NOT roc.[persistence_source_RepoObjectColumn_guid] IS NULL
      AND IsNull(roc.[is_persistence_no_include], 0) = 0
      AND IsNull(roc.[is_persistence_no_check], 0) = 0
      AND IsNull(roc.is_query_plan_expression, 0) = 0
      AND roc.Repo_generated_always_type = 0
      AND roc.Repo_is_computed = 0
      AND roc.Repo_is_identity = 0
      THEN CONCAT (
        ', T.'
        , QuoteName(roc.[RepoObjectColumn_name])
        , ' = S.'
        , QuoteName(roc.[RepoObjectColumn_name])
        , CHAR(13)
        , CHAR(10)
        )
     END
    ), '') WITHIN GROUP (
   ORDER BY roc.RepoObjectColumn_column_id
   ), 1, 2, '  ')
FROM [repo].[RepoObjectColumn_gross] AS roc
WHERE
 --not [is_query_plan_expression], these are not real columms
 roc.[is_query_plan_expression] IS NULL
 --we need the datatype, or it should be computed
 AND (
  NOT roc.[Repo_user_type_fullname] IS NULL
  OR roc.Repo_is_computed = 1
  )
GROUP BY roc.[RepoObject_guid]

----
// end::sql_modules_definition[]


