= [repo].[usp_generate_merge]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--sql_modules_definition:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
FCAFBA8C-AD72-EB11-84E3-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1575676661
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-02-19 12:37:43
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::AdocUspSteps[]

// end::AdocUspSteps[]


== AntoraReferencedList

// tag::AntoraReferencedList[]

// end::AntoraReferencedList[]


== AntoraReferencingList

// tag::AntoraReferencingList[]

// end::AntoraReferencingList[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_RepoObject_guid[]

// end::usp_persistence_RepoObject_guid[]


== UspExamples

// tag::UspExamples[]

// end::UspExamples[]


== UspParameters

// tag::UspParameters[]

// end::UspParameters[]


== pk_IndexPatternColumnName

// tag::pk_IndexPatternColumnName[]

// end::pk_IndexPatternColumnName[]


== pk_IndexSemanticGroup

// tag::pk_IndexSemanticGroup[]

// end::pk_IndexSemanticGroup[]


== ReferencedObjectList

// tag::ReferencedObjectList[]

// end::ReferencedObjectList[]


== persistence_source_RepoObject_xref

// tag::persistence_source_RepoObject_xref[]

// end::persistence_source_RepoObject_xref[]


== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_IndexPatternColumnDatatype[]

// end::pk_IndexPatternColumnDatatype[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_RepoObject_fullname[]

// end::persistence_source_RepoObject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_RepoObject_fullname2[]

// end::persistence_source_RepoObject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_RepoObject_guid[]

// end::persistence_source_RepoObject_guid[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::MS_Description[]

// end::MS_Description[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== example4

// tag::example4[]

// end::example4[]


== example5

// tag::example5[]

// end::example5[]


== has_history

// tag::has_history[]

// end::has_history[]


== example1

// tag::example1[]

// end::example1[]


== example2

// tag::example2[]

// end::example2[]


== example3

// tag::example3[]

// end::example3[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----
/*
create the procedure sp_generate_merge in master database
details: https://github.com/readyroll/generate-sql-merge

issue in orignal procedure with sql_variant content!

this will create sql statements to merge data into a target table
these scrpits can be included in database projects to use in post deployment scripts in DACPAC

https://documentation.red-gate.com/rr1/key-concepts/data-population/static-data#StaticData-offline

ATTENTION:
for sql_variant type the procedure generates wrong code:
[repo].[Parameter]
[repo].[RepoObjectColumnProperty]
[repo].[RepoObjectProperty]

*/

CREATE   procedure [repo].[usp_generate_merge]
AS

--issues with sql_variant
EXEC sp_generate_merge @table_name = 'Parameter', @schema = 'repo', @debug_mode = 1

EXEC sp_generate_merge @table_name = 'GeneratorUsp', @schema = 'repo', @debug_mode = 1
EXEC sp_generate_merge @table_name = 'GeneratorUspParameter', @schema = 'repo', @debug_mode = 1
EXEC sp_generate_merge @table_name = 'GeneratorUspStep', @schema = 'repo', @debug_mode = 1

--todo: store and get all columns in extended properties
/*
TITLE: Microsoft SQL Server Management Studio
------------------------------

Unable to show XML. The following error happened:
Unexpected end of file while parsing PI has occurred. Line 162, position 154777.

One solution is to increase the number of characters retrieved from the server for XML data. To change this setting, on the Tools menu, click Options.

------------------------------
BUTTONS:

OK
------------------------------


Menu > Tools > Options > Query Results > Results to Grid > XML Data
default is 2 MB, set to unlimited

But this can crash SSMS

*/
EXEC sp_generate_merge @table_name = 'RepoObject', @schema = 'repo', @debug_mode = 1
--todo: store and get all columns in extended properties
EXEC sp_generate_merge @table_name = 'RepoObject_persistence', @schema = 'repo', @debug_mode = 1
-- RepoObject_SqlModules can be easy restored using the python script SqlParser.py
EXEC sp_generate_merge @table_name = 'RepoObject_SqlModules', @schema = 'repo', @debug_mode = 1

----not required, get properties using [repo].[usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate]
----issues with sql_variant
--EXEC sp_generate_merge @table_name = 'RepoObjectProperty', @schema = 'repo', @debug_mode = 1

EXEC sp_generate_merge @table_name = 'RepoObjectColumn', @schema = 'repo', @debug_mode = 1
----not required, get properties using [repo].[usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate]
----issues with sql_variant
--EXEC sp_generate_merge @table_name = 'RepoObjectColumnProperty', @schema = 'repo', @debug_mode = 1

----currently only the SqlParser data is used
--EXEC sp_generate_merge @table_name = 'RepoObjectSource_FirstResultSet', @schema = 'repo', @debug_mode = 1
--EXEC sp_generate_merge @table_name = 'RepoObjectSource_QueryPlan', @schema = 'repo', @debug_mode = 1

EXEC sp_generate_merge @table_name = 'Index_virtual', @schema = 'repo', @debug_mode = 1
EXEC sp_generate_merge @table_name = 'IndexColumn_virtual', @schema = 'repo', @debug_mode = 1
EXEC sp_generate_merge @table_name = 'Index_Settings', @schema = 'repo', @debug_mode = 1

EXEC sp_generate_merge @table_name = 'ProcedureInstance', @schema = 'repo', @debug_mode = 1
EXEC sp_generate_merge @table_name = 'ProcedureInstanceDependency', @schema = 'repo', @debug_mode = 1
EXEC sp_generate_merge @table_name = 'Workflow', @schema = 'repo', @debug_mode = 1
EXEC sp_generate_merge @table_name = 'WorkflowStep', @schema = 'repo', @debug_mode = 1

----
// end::sql_modules_definition[]


