= [repo].[usp_Index_virtual_InsertUpdate]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--AntoraReferencedList:
:ExistsProperty--AntoraReferencingList:
:ExistsProperty--ReferencedObjectList:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
A190291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1890105774
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-09 00:29:48
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]
* @RepoObject_guid (uniqueidentifier)
* @RepoObject_fullname (nvarchar(261))
* @RepoObject_fullname2 (nvarchar(257))
* @IndexPatternColumnName (nvarchar(4000))
* @index_name (nvarchar(128))
* @index_type (tinyint)
* @is_index_disabled (bit)
* @is_index_primary_key (bit)
* @is_index_unique (bit)
* @execution_instance_guid (uniqueidentifier)
* @ssis_execution_id (bigint)
* @sub_execution_id (int)
* @parent_execution_log_id (bigint)
// end::AntoraParameterList[]

== AdocUspSteps

// tag::AdocUspSteps[]

// end::AdocUspSteps[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::MS_Description[]

// end::MS_Description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_RepoObject_fullname[]

// end::persistence_source_RepoObject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_RepoObject_fullname2[]

// end::persistence_source_RepoObject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_RepoObject_guid[]

// end::persistence_source_RepoObject_guid[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== example4

// tag::example4[]

// end::example4[]


== example5

// tag::example5[]

// end::example5[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== example1

// tag::example1[]

// end::example1[]


== example2

// tag::example2[]

// end::example2[]


== example3

// tag::example3[]

// end::example3[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_RepoObject_guid[]

// end::usp_persistence_RepoObject_guid[]


== UspExamples

// tag::UspExamples[]

// end::UspExamples[]


== UspParameters

// tag::UspParameters[]

// end::UspParameters[]


== persistence_source_RepoObject_xref

// tag::persistence_source_RepoObject_xref[]

// end::persistence_source_RepoObject_xref[]


== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_IndexPatternColumnDatatype[]

// end::pk_IndexPatternColumnDatatype[]


== pk_IndexPatternColumnName

// tag::pk_IndexPatternColumnName[]

// end::pk_IndexPatternColumnName[]


== pk_IndexSemanticGroup

// tag::pk_IndexSemanticGroup[]

// end::pk_IndexSemanticGroup[]


== AntoraReferencedList

// tag::AntoraReferencedList[]
* xref:repo.Index_gross.adoc[]
* xref:repo.Index_virtual.adoc[]
* xref:repo.IndexColumn_virtual.adoc[]
* xref:repo.RepoObject.adoc[]
* xref:repo.RepoObjectColumn.adoc[]
* xref:repo.usp_ExecutionLog_insert.adoc[]
// end::AntoraReferencedList[]


== AntoraReferencingList

// tag::AntoraReferencingList[]
* xref:repo.usp_Index_ForeignKey.adoc[]
// end::AntoraReferencingList[]


== ReferencedObjectList

// tag::ReferencedObjectList[]
* [repo].[Index_gross]
* [repo].[Index_virtual]
* [repo].[IndexColumn_virtual]
* [repo].[RepoObject]
* [repo].[RepoObjectColumn]
* [repo].[usp_ExecutionLog_insert]
// end::ReferencedObjectList[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----

/*
Index will be inserted (updated) into repo.[Index_virtual]
but it will not be visible in [repo].[Index_gross]
until it was also included into [repo].[Index_Settings]
and after inserting a new index there could be duplicates for the same columns which needs to be removed again

That's why it is required run (this also happens in [repo].[usp_main])

EXEC [repo].[usp_Index_finish]

--test:
EXEC repo.usp_Index_virtual_InsertUpdate 
 @RepoObject_fullname = '[dbo].[view_1]'
 , @IndexPatternColumnName = 'aaa_id,bbb'

EXEC repo.usp_Index_virtual_InsertUpdate 
 @RepoObject_fullname2 = 'dbo.view_1'
 , @IndexPatternColumnName = 'aaa_id'
 , @is_index_primary_key = 1

EXEC repo.usp_Index_virtual_InsertUpdate 
 @RepoObject_fullname = '[repo].[RepoObjectColumn_gross]'
 , @IndexPatternColumnName = 'RepoObjectColumn_guid'
 , @is_index_primary_key = 1

EXEC repo.usp_Index_virtual_InsertUpdate 
 @RepoObject_fullname = '[graph].[RepoObjectColumn_S]'
 , @IndexPatternColumnName = 'RepoObjectColumn_guid'
 , @is_index_primary_key = 1

EXEC [repo].[usp_Index_finish]



index_type

Type of index:
0 = Heap
1 = Clustered
2 = Nonclustered
3 = XML
4 = Spatial
5 = Clustered columnstore index. Applies to: SQL Server 2014 (12.x) and later.
6 = Nonclustered columnstore index. Applies to: SQL Server 2012 (11.x) and later.
7 = Nonclustered hash index. Applies to: SQL Server 2014 (12.x) and later.
*/
CREATE PROCEDURE [repo].[usp_Index_virtual_InsertUpdate] @RepoObject_guid UNIQUEIDENTIFIER = NULL --if @RepoObject_guid is NULL, then @RepoObject_fullname is used
 , @RepoObject_fullname NVARCHAR(261) = NULL --will be used to find matching @RepoObject_guid, if @RepoObject_guid is NULL; use [schema].[TableOrView]
 , @RepoObject_fullname2 NVARCHAR(257) = NULL --will be used to find matching @RepoObject_guid, if @RepoObject_guid is NULL; use schema.TableOrView
 , @IndexPatternColumnName NVARCHAR(4000) = NULL --a semicolon separated list to define the Index, for example 'aaa;bbb;ccc'
 , @index_name NVARCHAR(128) = NULL
 , @index_type TINYINT = 2 --1 Clustered, 2 Nonclustered
 , @is_index_disabled BIT = 0
 , @is_index_primary_key BIT = 0
 , @is_index_unique BIT = 0
 -- some optional parameters, used for logging
 , @execution_instance_guid UNIQUEIDENTIFIER = NULL --SSIS system variable ExecutionInstanceGUID could be used, but other any other guid
 , @ssis_execution_id BIGINT = NULL --only SSIS system variable ServerExecutionID should be used, or any other consistent number system, do not mix
 , @sub_execution_id INT = NULL
 , @parent_execution_log_id BIGINT = NULL
AS
DECLARE @current_execution_log_id BIGINT
 , @current_execution_guid UNIQUEIDENTIFIER = NEWID()
 , @source_object NVARCHAR(261) = NULL
 , @target_object NVARCHAR(261) = NULL
 , @proc_id INT = @@procid
 , @proc_schema_name NVARCHAR(128) = OBJECT_SCHEMA_NAME(@@procid)
 , @proc_name NVARCHAR(128) = OBJECT_NAME(@@procid)
 , @event_info NVARCHAR(MAX)
 , @step_id INT = 0
 , @step_name NVARCHAR(1000) = NULL
 , @rows INT

SET @event_info = (
  SELECT [event_info]
  FROM sys.dm_exec_input_buffer(@@spid, CURRENT_REQUEST_ID())
  )

IF @execution_instance_guid IS NULL
 SET @execution_instance_guid = NEWID();
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1
SET @step_name = 'start'
SET @source_object = NULL
SET @target_object = NULL

EXEC repo.usp_ExecutionLog_insert @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = NULL
 , @updated = NULL
 , @deleted = NULL
 , @info_01 = NULL
 , @info_02 = NULL
 , @info_03 = NULL
 , @info_04 = NULL
 , @info_05 = NULL
 , @info_06 = NULL
 , @info_07 = NULL
 , @info_08 = NULL
 , @info_09 = NULL
 , @execution_log_id = @current_execution_log_id OUTPUT
 , @parameter_01 = @RepoObject_guid
 , @parameter_02 = @RepoObject_fullname
 , @parameter_03 = @RepoObject_fullname2
 , @parameter_04 = @IndexPatternColumnName
 , @parameter_05 = @index_name
 , @parameter_06 = @index_type
 , @parameter_07 = @is_index_disabled
 , @parameter_08 = @is_index_primary_key
 , @parameter_09 = @is_index_unique

--
----START
--
DECLARE @index_guid UNIQUEIDENTIFIER

IF @RepoObject_guid IS NULL
 SET @RepoObject_guid = (
   SELECT [RepoObject_guid]
   FROM [repo].[RepoObject]
   WHERE [RepoObject_fullname] = @RepoObject_fullname
   )

IF @RepoObject_guid IS NULL
 SET @RepoObject_guid = (
   SELECT [RepoObject_guid]
   FROM [repo].[RepoObject]
   WHERE [RepoObject_fullname2] = @RepoObject_fullname2
   )

--check existence of @RepoObject_guid
IF NOT EXISTS (
  SELECT 1
  FROM [repo].[RepoObject]
  WHERE [RepoObject_guid] = @RepoObject_guid
  )
BEGIN
 SET @step_name = CONCAT (
   'RepoObject_guid does not exist;'
   , @RepoObject_guid
   , ';'
   , @RepoObject_fullname
   );

 THROW 51001
  , @step_name
  , 1;
END

--try to find existing index
SET @index_guid = (
  SELECT [index_guid]
  FROM [repo].[Index_gross]
  WHERE [parent_RepoObject_guid] = @RepoObject_guid
   AND [IndexPatternColumnName] = @IndexPatternColumnName
  )

--update existing [Index_virtual]
--Attention, a new inserted index into repo.[Index_virtual] will be available only after `EXEC [repo].[usp_Index_finish]`
IF NOT @index_guid IS NULL
BEGIN
 PRINT 'Update existing Index'

 UPDATE iv
 SET [index_name] = ISNULL(@index_name, [iv].[index_name])
  , [index_type] = @index_type
  , [is_index_disabled] = @is_index_disabled
  , [is_index_primary_key] = @is_index_primary_key
  , [is_index_unique] = IIF(@is_index_primary_key = 1, 1, @is_index_unique)
 FROM [repo].[Index_virtual] [iv]
 WHERE [iv].[index_guid] = @index_guid
END
ELSE
BEGIN
 PRINT 'Insert new Index'

 DECLARE @table TABLE ([guid] UNIQUEIDENTIFIER)

 ----make sure the @table table is empty
 --DELETE @table
 INSERT INTO repo.[Index_virtual] (
  [parent_RepoObject_guid]
  , [index_name]
  , [index_type]
  , [is_index_disabled]
  , [is_index_primary_key]
  , [is_index_unique]
  )
 OUTPUT [INSERTED].[index_guid]
 INTO @table
 SELECT @RepoObject_guid
  , @index_name
  , @index_type
  , @is_index_disabled
  , @is_index_primary_key
  , IIF(@is_index_primary_key = 1, 1, @is_index_unique)

 SET @index_guid = (
   SELECT [guid]
   FROM @table
   )

 /*
--test to get the string_split in the right order:

DECLARE @IndexPatternColumnName NVARCHAR(max) = 'z; y; aaa;bbb;ccc ddd; eee;fff ;ggg'

--there is no garantee to get the strings in the right order, but "normally" it works
--the result for ASC or DESC is the same
--https://feedback.azure.com/forums/908035-sql-server/suggestions/32902852-add-row-position-column-to-string-split
SELECT TRIM(value) AS index_column_name
 , row_number() OVER (
  ORDER BY (
    SELECT NULL
    )
  ) AS [index_column_id]
FROM STRING_SPLIT(@IndexPatternColumnName, ',')

*/
 --todo: concept to insert [is_descending_key]
 --or update manually if required
 INSERT INTO [repo].[IndexColumn_virtual] (
  [index_guid]
  , [index_column_id]
  , [RepoObjectColumn_guid]
  , [is_descending_key]
  )
 SELECT @index_guid
  , [ColTable].[index_column_id]
  , [roc].[RepoObjectColumn_guid]
  , 0
 FROM (
  SELECT TRIM(value) AS [index_column_name]
   , ROW_NUMBER() OVER (
    ORDER BY (
      SELECT NULL
      )
    ) AS [index_column_id]
  FROM STRING_SPLIT(@IndexPatternColumnName, ',')
  ) AS ColTable
 LEFT JOIN [repo].[RepoObjectColumn] AS roc
  ON roc.RepoObject_guid = @RepoObject_guid
   AND roc.RepoObjectColumn_name = index_column_name

 SET @rows = @@ROWCOUNT;
 SET @step_id = @step_id + 1;
 SET @step_name = 'INSERT Index Columns'
 SET @source_object = '[repo].[RepoObjectColumn]'
 SET @target_object = '[repo].[IndexColumn_virtual]'

 EXEC repo.usp_ExecutionLog_insert @execution_instance_guid = @execution_instance_guid
  , @ssis_execution_id = @ssis_execution_id
  , @sub_execution_id = @sub_execution_id
  , @parent_execution_log_id = @parent_execution_log_id
  , @current_execution_guid = @current_execution_guid
  , @proc_id = @proc_id
  , @proc_schema_name = @proc_schema_name
  , @proc_name = @proc_name
  , @event_info = @event_info
  , @step_id = @step_id
  , @step_name = @step_name
  , @source_object = @source_object
  , @target_object = @target_object
  , @inserted = @rows
  , @updated = NULL
  , @deleted = NULL
  , @info_01 = NULL
  , @info_02 = NULL
  , @info_03 = NULL
  , @info_04 = NULL
  , @info_05 = NULL
  , @info_06 = NULL
  , @info_07 = NULL
  , @info_08 = NULL
  , @info_09 = NULL
END

--if @is_index_primary_key = 1 then mark other indexes as is_index_primary_key = 0
IF @is_index_primary_key = 1
BEGIN
 PRINT 'set [is_index_primary_key] = 0 (for other index of same [parent_RepoObject_guid])'

 UPDATE iv
 SET [is_index_primary_key] = 0
 FROM [repo].[Index_virtual] [iv]
 INNER JOIN [repo].[Index_gross] [ig]
  ON [ig].[index_guid] = [iv].[index_guid]
 WHERE [iv].[is_index_primary_key] = 1
  AND [iv].[parent_RepoObject_guid] = @RepoObject_guid
  AND [ig].[IndexPatternColumnName] <> @IndexPatternColumnName
END

--
--
--END
--
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1;
SET @step_name = 'end'
SET @source_object = NULL
SET @target_object = NULL

EXEC repo.usp_ExecutionLog_insert @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = NULL
 , @updated = NULL
 , @deleted = NULL
 , @info_01 = NULL
 , @info_02 = NULL
 , @info_03 = NULL
 , @info_04 = NULL
 , @info_05 = NULL
 , @info_06 = NULL
 , @info_07 = NULL
 , @info_08 = NULL
 , @info_09 = NULL

----
// end::sql_modules_definition[]


