= [repo].[usp_main]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--AdocUspSteps:
:ExistsProperty--AntoraReferencedList:
:ExistsProperty--MS_Description:
:ExistsProperty--ReferencedObjectList:
:ExistsProperty--UspExamples:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
6BCBC49C-3862-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
462624691
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-11 13:27:43
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]
* @execution_instance_guid (uniqueidentifier)
* @ssis_execution_id (bigint)
* @sub_execution_id (int)
* @parent_execution_log_id (bigint)
// end::AntoraParameterList[]

== persistence_source_RepoObject_xref

// tag::persistence_source_RepoObject_xref[]

// end::persistence_source_RepoObject_xref[]


== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_IndexPatternColumnDatatype[]

// end::pk_IndexPatternColumnDatatype[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_RepoObject_fullname[]

// end::persistence_source_RepoObject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_RepoObject_fullname2[]

// end::persistence_source_RepoObject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_RepoObject_guid[]

// end::persistence_source_RepoObject_guid[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== example4

// tag::example4[]

// end::example4[]


== example5

// tag::example5[]

// end::example5[]


== has_history

// tag::has_history[]

// end::has_history[]


== example1

// tag::example1[]

// end::example1[]


== example2

// tag::example2[]

// end::example2[]


== example3

// tag::example3[]

// end::example3[]


== UspParameters

// tag::UspParameters[]

// end::UspParameters[]


== pk_IndexPatternColumnName

// tag::pk_IndexPatternColumnName[]

// end::pk_IndexPatternColumnName[]


== pk_IndexSemanticGroup

// tag::pk_IndexSemanticGroup[]

// end::pk_IndexSemanticGroup[]


== AntoraReferencingList

// tag::AntoraReferencingList[]

// end::AntoraReferencingList[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_RepoObject_guid[]

// end::usp_persistence_RepoObject_guid[]


== AdocUspSteps

// tag::AdocUspSteps[]
.Steps in [repo].[usp_main]
[cols="d,15a,d"]
|===
|Number|Name (Action, Source, Target)|Parent

|210
|
*[repo].[usp_sync_guid]*

* `EXEC [repo].[usp_sync_guid]`

|

|300
|
*(select [repo].[fs_get_parameter_value]('main enable usp_RepoObjectSource_FirstResultSet', DEFAULT)) = 1*

* `IF (select [repo].[fs_get_parameter_value]('main enable usp_RepoObjectSource_FirstResultSet', DEFAULT)) = 1`

|

|310
|
*[repo].[usp_RepoObjectSource_FirstResultSet]*

* `EXEC [repo].[usp_RepoObjectSource_FirstResultSet]
--This can take a very long time`

|300

|400
|
*(select [repo].[fs_get_parameter_value]('main enable usp_RepoObject_update_SysObjectQueryPlan', DEFAULT)) = 1*

* `IF (select [repo].[fs_get_parameter_value]('main enable usp_RepoObject_update_SysObjectQueryPlan', DEFAULT)) = 1`

|

|410
|
*[repo].[usp_RepoObject_update_SysObjectQueryPlan]*

* `EXEC [repo].[usp_RepoObject_update_SysObjectQueryPlan]
--This can take a very long time`

|400

|500
|
*(select [repo].[fs_get_parameter_value]('main enable usp_RepoObjectSource_QueryPlan', DEFAULT)) = 1*

* `IF (select [repo].[fs_get_parameter_value]('main enable usp_RepoObjectSource_QueryPlan', DEFAULT)) = 1`

|

|510
|
*[repo].[usp_RepoObjectSource_QueryPlan]
--This can take a very long time*

* `EXEC [repo].[usp_RepoObjectSource_QueryPlan]
--This can take a very long time`

|500

|610
|
*[repo].[usp_update_Referencing_Count]*

* `EXEC [repo].[usp_update_Referencing_Count]`

|

|710
|
*[repo].[usp_index_inheritance]*

* `EXEC [repo].[usp_index_inheritance]
--todo:
--should or could be executed several times until no new indexes are inherited`

|

|720
|
*[repo].[usp_Index_ForeignKey]*

* `EXEC [repo].[usp_Index_ForeignKey]`

|

|810
|
*[repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]*

* `EXEC [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]
--This must happen later than the index logic, because the PK can change there. And this affects the order of the columns.`

|

|910
|
*[repo].[usp_GeneratorUsp_insert_update_persistence]*

* `EXEC [repo].[usp_GeneratorUsp_insert_update_persistence]
--RepoObjectColumn_column_id is required and should be updated before`

|

|2110
|
*MERGE [graph].[ReferencedObject]*

* u
* [repo].[RepoObject_reference_union]
* [graph].[ReferencedObject]

|

|2120
|
*MERGE [graph].[ReferencingObject]*

* u
* [repo].[RepoObject_reference_union]
* [graph].[ReferencingObject]

|

|2210
|
*MERGE [graph].[ReferencedObjectColumn]*

* u
* [repo].[RepoObjectColumn_reference_union]
* [graph].[ReferencedObjectColumn]

|

|2220
|
*MERGE [graph].[ReferencingObjectColumn]*

* u
* [repo].[RepoObjectColumn_reference_union]
* [graph].[ReferencingObjectColumn]

|
|===

// end::AdocUspSteps[]


== AntoraReferencedList

// tag::AntoraReferencedList[]
* xref:graph.ReferencedObject.adoc[]
* xref:graph.ReferencedObjectColumn.adoc[]
* xref:graph.ReferencingObject.adoc[]
* xref:graph.ReferencingObjectColumn.adoc[]
* xref:graph.RepoObject.adoc[]
* xref:graph.RepoObjectColumn.adoc[]
* xref:repo.fs_get_parameter_value.adoc[]
* xref:repo.RepoObject_reference_union.adoc[]
* xref:repo.RepoObjectColumn_reference_union.adoc[]
* xref:repo.usp_ExecutionLog_insert.adoc[]
* xref:repo.usp_GeneratorUsp_insert_update_persistence.adoc[]
* xref:repo.usp_Index_ForeignKey.adoc[]
* xref:repo.usp_index_inheritance.adoc[]
* xref:repo.usp_RepoObject_update_SysObjectQueryPlan.adoc[]
* xref:repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id.adoc[]
* xref:repo.usp_RepoObjectSource_FirstResultSet.adoc[]
* xref:repo.usp_RepoObjectSource_QueryPlan.adoc[]
* xref:repo.usp_sync_guid.adoc[]
* xref:repo.usp_update_Referencing_Count.adoc[]
// end::AntoraReferencedList[]


== MS_Description

// tag::MS_Description[]
main procedure

this central procedure must be executed regularly

* to synchronize the repository with the database
* for index processing
** combination of real and virtual indexes
** virtual and real foreign key
** code generation and updates for persistence procedures
* references and data lineage
* inheritance of properties

* should be called very often
* see xref:sqldb:repo.usp_main.adoc#_procdure_steps[Procedure steps] for details.
* use links in xref:sqldb:repo.usp_main.adoc#_referenced_objects[Referenced objects] to get details of called sub procedures
// end::MS_Description[]


== ReferencedObjectList

// tag::ReferencedObjectList[]
* [graph].[ReferencedObject]
* [graph].[ReferencedObjectColumn]
* [graph].[ReferencingObject]
* [graph].[ReferencingObjectColumn]
* [graph].[RepoObject]
* [graph].[RepoObjectColumn]
* [repo].[fs_get_parameter_value]
* [repo].[RepoObject_reference_union]
* [repo].[RepoObjectColumn_reference_union]
* [repo].[usp_ExecutionLog_insert]
* [repo].[usp_GeneratorUsp_insert_update_persistence]
* [repo].[usp_Index_ForeignKey]
* [repo].[usp_index_inheritance]
* [repo].[usp_RepoObject_update_SysObjectQueryPlan]
* [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]
* [repo].[usp_RepoObjectSource_FirstResultSet]
* [repo].[usp_RepoObjectSource_QueryPlan]
* [repo].[usp_sync_guid]
* [repo].[usp_update_Referencing_Count]
// end::ReferencedObjectList[]


== UspExamples

// tag::UspExamples[]
EXEC [repo].[usp_main]
// end::UspExamples[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----
CREATE   PROCEDURE [repo].[usp_main]
----keep the code between logging parameters and "START" unchanged!
---- parameters, used for logging; you don't need to care about them, but you can use them, wenn calling from SSIS or in your workflow to log the context of the procedure call
  @execution_instance_guid UNIQUEIDENTIFIER = NULL --SSIS system variable ExecutionInstanceGUID could be used, any other unique guid is also fine. If NULL, then NEWID() is used to create one
, @ssis_execution_id BIGINT = NULL --only SSIS system variable ServerExecutionID should be used, or any other consistent number system, do not mix different number systems
, @sub_execution_id INT = NULL --in case you log some sub_executions, for example in SSIS loops or sub packages
, @parent_execution_log_id BIGINT = NULL --in case a sup procedure is called, the @current_execution_log_id of the parent procedure should be propagated here. It allowes call stack analyzing
AS
DECLARE
 --
   @current_execution_log_id BIGINT --this variable should be filled only once per procedure call, it contains the first logging call for the step 'start'.
 , @current_execution_guid UNIQUEIDENTIFIER = NEWID() --a unique guid for any procedure call. It should be propagated to sub procedures using "@parent_execution_log_id = @current_execution_log_id"
 , @source_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @target_object NVARCHAR(261) = NULL --use it like '[schema].[object]', this allows data flow vizualizatiuon (include square brackets)
 , @proc_id INT = @@procid
 , @proc_schema_name NVARCHAR(128) = OBJECT_SCHEMA_NAME(@@procid) --schema ande name of the current procedure should be automatically logged
 , @proc_name NVARCHAR(128) = OBJECT_NAME(@@procid)               --schema ande name of the current procedure should be automatically logged
 , @event_info NVARCHAR(MAX)
 , @step_id INT = 0
 , @step_name NVARCHAR(1000) = NULL
 , @rows INT

--[event_info] get's only the information about the "outer" calling process
--wenn the procedure calls sub procedures, the [event_info] will not change
SET @event_info = (
  SELECT [event_info]
  FROM sys.dm_exec_input_buffer(@@spid, CURRENT_REQUEST_ID())
  )

IF @execution_instance_guid IS NULL
 SET @execution_instance_guid = NEWID();
--
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1
SET @step_name = 'start'
SET @source_object = NULL
SET @target_object = NULL

EXEC repo.usp_ExecutionLog_insert
 --these parameters should be the same for all logging execution
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 --the following parameters are individual for each call
 , @step_id = @step_id --@step_id should be incremented before each call
 , @step_name = @step_name --assign individual step names for each call
 --only the "start" step should return the log id into @current_execution_log_id
 --all other calls should not overwrite @current_execution_log_id
 , @execution_log_id = @current_execution_log_id OUTPUT
----you can log the content of your own parameters, do this only in the start-step
----data type is sql_variant

--
PRINT '[repo].[usp_main]'
--keep the code between logging parameters and "START" unchanged!
--
----START
--
----- start here with your own code
--
/*{"ReportUspStep":[{"Number":210,"Name":"[repo].[usp_sync_guid]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [repo].[usp_sync_guid]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":300,"Name":"(select [repo].[fs_get_parameter_value]('main enable usp_RepoObjectSource_FirstResultSet', DEFAULT)) = 1","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0}]}*/
IF (select [repo].[fs_get_parameter_value]('main enable usp_RepoObjectSource_FirstResultSet', DEFAULT)) = 1

/*{"ReportUspStep":[{"Number":310,"Parent_Number":300,"Name":"[repo].[usp_RepoObjectSource_FirstResultSet]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
BEGIN
EXEC [repo].[usp_RepoObjectSource_FirstResultSet]
--This can take a very long time
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id

END;

/*{"ReportUspStep":[{"Number":400,"Name":"(select [repo].[fs_get_parameter_value]('main enable usp_RepoObject_update_SysObjectQueryPlan', DEFAULT)) = 1","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0}]}*/
IF (select [repo].[fs_get_parameter_value]('main enable usp_RepoObject_update_SysObjectQueryPlan', DEFAULT)) = 1

/*{"ReportUspStep":[{"Number":410,"Parent_Number":400,"Name":"[repo].[usp_RepoObject_update_SysObjectQueryPlan]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
BEGIN
EXEC [repo].[usp_RepoObject_update_SysObjectQueryPlan]
--This can take a very long time
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id

END;

/*{"ReportUspStep":[{"Number":500,"Name":"(select [repo].[fs_get_parameter_value]('main enable usp_RepoObjectSource_QueryPlan', DEFAULT)) = 1","has_logging":0,"is_condition":1,"is_inactive":0,"is_SubProcedure":0}]}*/
IF (select [repo].[fs_get_parameter_value]('main enable usp_RepoObjectSource_QueryPlan', DEFAULT)) = 1

/*{"ReportUspStep":[{"Number":510,"Parent_Number":500,"Name":"[repo].[usp_RepoObjectSource_QueryPlan]\r\n--This can take a very long time","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
BEGIN
EXEC [repo].[usp_RepoObjectSource_QueryPlan]
--This can take a very long time
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id

END;

/*{"ReportUspStep":[{"Number":610,"Name":"[repo].[usp_update_Referencing_Count]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [repo].[usp_update_Referencing_Count]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":710,"Name":"[repo].[usp_index_inheritance]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [repo].[usp_index_inheritance]
--todo:
--should or could be executed several times until no new indexes are inherited
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":720,"Name":"[repo].[usp_Index_ForeignKey]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [repo].[usp_Index_ForeignKey]
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":810,"Name":"[repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [repo].[usp_RepoObjectColumn_update_RepoObjectColumn_column_id]
--This must happen later than the index logic, because the PK can change there. And this affects the order of the columns.
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":910,"Name":"[repo].[usp_GeneratorUsp_insert_update_persistence]","has_logging":0,"is_condition":0,"is_inactive":0,"is_SubProcedure":1}]}*/
EXEC [repo].[usp_GeneratorUsp_insert_update_persistence]
--RepoObjectColumn_column_id is required and should be updated before
--add your own parameters
--logging parameters
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @current_execution_log_id


/*{"ReportUspStep":[{"Number":2110,"Name":"MERGE [graph].[ReferencedObject]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[repo].[RepoObject_reference_union]","log_target_object":"[graph].[ReferencedObject]","log_flag_InsertUpdateDelete":"u"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',2,';',2110,';',NULL);

MERGE [graph].[ReferencedObject]
USING (
 (
  SELECT DISTINCT
   --
   [referencing_RepoObject_guid]
   , [referenced_RepoObject_guid]
  FROM [repo].[RepoObject_reference_union]
  ) AS S
 --
 JOIN [graph].[RepoObject] referencing
  ON S.[referencing_RepoObject_guid] = referencing.[RepoObject_guid]
 JOIN [graph].[RepoObject] referenced
  ON S.[referenced_RepoObject_guid] = referenced.[RepoObject_guid]
 )
 ON MATCH(referencing - (ReferencedObject) - > referenced)
WHEN NOT MATCHED BY TARGET
 THEN
  INSERT (
   $FROM_ID
   , $TO_ID
   )
  VALUES (
   referencing.$NODE_ID
   , referenced.$NODE_ID
   )
WHEN NOT MATCHED BY SOURCE
 THEN
  DELETE
OUTPUT deleted.*
 , $ACTION
 , inserted.*;

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'MERGE [graph].[ReferencedObject]'
SET @source_object = '[repo].[RepoObject_reference_union]'
SET @target_object = '[graph].[ReferencedObject]'

EXEC repo.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @updated = @rows
-- Logging END --

/*{"ReportUspStep":[{"Number":2120,"Name":"MERGE [graph].[ReferencingObject]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[repo].[RepoObject_reference_union]","log_target_object":"[graph].[ReferencingObject]","log_flag_InsertUpdateDelete":"u"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',2,';',2120,';',NULL);

MERGE [graph].[ReferencingObject]
USING (
 (
  SELECT DISTINCT
   --
   [referencing_RepoObject_guid]
   , [referenced_RepoObject_guid]
  FROM [repo].[RepoObject_reference_union]
  ) AS S
 --
 JOIN [graph].[RepoObject] referencing
  ON S.[referencing_RepoObject_guid] = referencing.[RepoObject_guid]
 JOIN [graph].[RepoObject] referenced
  ON S.[referenced_RepoObject_guid] = referenced.[RepoObject_guid]
 )
 ON MATCH(referenced - (ReferencingObject) - > referencing)
WHEN NOT MATCHED BY TARGET
 THEN
  INSERT (
   $FROM_ID
   , $TO_ID
   )
  VALUES (
   referenced.$NODE_ID
   , referencing.$NODE_ID
   )
WHEN NOT MATCHED BY SOURCE
 THEN
  DELETE
OUTPUT deleted.*
 , $ACTION
 , inserted.*;

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'MERGE [graph].[ReferencingObject]'
SET @source_object = '[repo].[RepoObject_reference_union]'
SET @target_object = '[graph].[ReferencingObject]'

EXEC repo.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @updated = @rows
-- Logging END --

/*{"ReportUspStep":[{"Number":2210,"Name":"MERGE [graph].[ReferencedObjectColumn]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[repo].[RepoObjectColumn_reference_union]","log_target_object":"[graph].[ReferencedObjectColumn]","log_flag_InsertUpdateDelete":"u"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',2,';',2210,';',NULL);

MERGE [graph].[ReferencedObjectColumn]
USING (
 (
  SELECT DISTINCT
   --
   [referencing_RepoObjectColumn_guid]
   , [referenced_RepoObjectColumn_guid]
  FROM [repo].[RepoObjectColumn_reference_union]
  where not [referencing_RepoObjectColumn_guid] is null
  and not [referenced_RepoObjectColumn_guid] is null
  ) AS S
 --
 JOIN [graph].[RepoObjectColumn] referencing
  ON S.[referencing_RepoObjectColumn_guid] = referencing.[RepoObjectColumn_guid]
 JOIN [graph].[RepoObjectColumn] referenced
  ON S.[referenced_RepoObjectColumn_guid] = referenced.[RepoObjectColumn_guid]
 )
 ON MATCH(referencing - (ReferencedObjectColumn) - > referenced)
WHEN NOT MATCHED BY TARGET
 THEN
  INSERT (
   $FROM_ID
   , $TO_ID
   )
  VALUES (
   referencing.$NODE_ID
   , referenced.$NODE_ID
   )
WHEN NOT MATCHED BY SOURCE
 THEN
  DELETE
OUTPUT deleted.*
 , $ACTION
 , inserted.*;

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'MERGE [graph].[ReferencedObjectColumn]'
SET @source_object = '[repo].[RepoObjectColumn_reference_union]'
SET @target_object = '[graph].[ReferencedObjectColumn]'

EXEC repo.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @updated = @rows
-- Logging END --

/*{"ReportUspStep":[{"Number":2220,"Name":"MERGE [graph].[ReferencingObjectColumn]","has_logging":1,"is_condition":0,"is_inactive":0,"is_SubProcedure":0,"log_source_object":"[repo].[RepoObjectColumn_reference_union]","log_target_object":"[graph].[ReferencingObjectColumn]","log_flag_InsertUpdateDelete":"u"}]}*/
PRINT CONCAT('usp_id;Number;Parent_Number: ',2,';',2220,';',NULL);

MERGE [graph].[ReferencingObjectColumn]
USING (
 (
  SELECT DISTINCT
   --
   [referencing_RepoObjectColumn_guid]
   , [referenced_RepoObjectColumn_guid]
  FROM [repo].[RepoObjectColumn_reference_union]
  where not [referencing_RepoObjectColumn_guid] is null
  and not [referenced_RepoObjectColumn_guid] is null
  ) AS S
 --
 JOIN [graph].[RepoObjectColumn] referencing
  ON S.[referencing_RepoObjectColumn_guid] = referencing.[RepoObjectColumn_guid]
 JOIN [graph].[RepoObjectColumn] referenced
  ON S.[referenced_RepoObjectColumn_guid] = referenced.[RepoObjectColumn_guid]
 )
 ON MATCH(referenced - (ReferencingObjectColumn) - > referencing)
WHEN NOT MATCHED BY TARGET
 THEN
  INSERT (
   $FROM_ID
   , $TO_ID
   )
  VALUES (
   referenced.$NODE_ID
   , referencing.$NODE_ID
   )
WHEN NOT MATCHED BY SOURCE
 THEN
  DELETE
OUTPUT deleted.*
 , $ACTION
 , inserted.*;

-- Logging START --
SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'MERGE [graph].[ReferencingObjectColumn]'
SET @source_object = '[repo].[RepoObjectColumn_reference_union]'
SET @target_object = '[graph].[ReferencingObjectColumn]'

EXEC repo.usp_ExecutionLog_insert 
 @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @updated = @rows
-- Logging END --

--
--finish your own code here
--keep the code between "END" and the end of the procedure unchanged!
--
--END
--
--SET @rows = @@ROWCOUNT
SET @step_id = @step_id + 1
SET @step_name = 'end'
SET @source_object = NULL
SET @target_object = NULL

EXEC repo.usp_ExecutionLog_insert
   @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object


----
// end::sql_modules_definition[]


