= [repo].[RepoObjectProperty_Collect_source_ROGross]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
B6FE9885-EA9D-EB11-84F6-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
351340316
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-15 15:50:42
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-property_name]]
=== property_name

[cols="d,m,m,m,m,d"]
|===
|
|property_name
|varchar(39)
|NOT NULL
|
|
|===


[[column-property_value]]
=== property_value

[cols="d,m,m,m,m,d"]
|===
|
|property_value
|sql_variant
|NULL
|
|
|===


[[column-RepoObject_guid]]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|
|===

.Referenced Columns
--
* xref:repo.RepoObject_gross.adoc#column-RepoObject_guid[repo.RepoObject_gross.RepoObject_guid]
--


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]



// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-property_name>>
|varchar(39)
|NOT NULL
|
|

|
|<<column-property_value>>
|sql_variant
|NULL
|
|

|
|<<column-RepoObject_guid>>
|uniqueidentifier
|NOT NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-idx_RepoObjectProperty_Collect_source_ROGross__1]]
=== idx_RepoObjectProperty_Collect_source_ROGross__1

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_repoobject_guid[RepoObject_guid]
+
--
* <<column-RepoObject_guid>>; uniqueidentifier
--
* PK, Unique, Real: 0, 0, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:repo.RepoObject_gross.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:repo.usp_RepoObjectProperty_collect.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObject_gross]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----

CREATE View repo.RepoObjectProperty_Collect_source_ROGross
As
Select
    ro.RepoObject_guid
  , property_name  = p_names.property_name
  , property_value = Case p_names.property_name
                         When 'pk_index_guid'
                             Then
                             Cast(ro.pk_index_guid As Sql_Variant)
                         When 'pk_IndexPatternColumnDatatype'
                             Then
                             Cast(ro.pk_IndexPatternColumnDatatype As Sql_Variant)
                         When 'pk_IndexPatternColumnName'
                             Then
                             Cast(ro.pk_IndexPatternColumnName As Sql_Variant)
                         When 'pk_IndexSemanticGroup'
                             Then
                             Cast(ro.pk_IndexSemanticGroup As Sql_Variant)
                         When 'is_repo_managed'
                             Then
                             Cast(ro.is_repo_managed As Sql_Variant)
                         When 'usp_persistence_RepoObject_guid'
                             Then
                             Cast(ro.usp_persistence_RepoObject_guid As Sql_Variant)
                         When 'persistence_source_RepoObject_guid'
                             Then
                             Cast(ro.persistence_source_RepoObject_guid As Sql_Variant)
                         When 'persistence_source_RepoObject_fullname'
                             Then
                             Cast(ro.persistence_source_RepoObject_fullname As Sql_Variant)
                         When 'persistence_source_RepoObject_fullname2'
                             Then
                             Cast(ro.persistence_source_RepoObject_fullname2 As Sql_Variant)
                         When 'persistence_source_RepoObject_xref'
                             Then
                             Cast(ro.persistence_source_RepoObject_xref As Sql_Variant)
                         When 'has_history'
                             Then
                             Cast(ro.has_history As Sql_Variant)
                         When 'has_history_columns'
                             Then
                             Cast(ro.has_history_columns As Sql_Variant)
                         When 'is_persistence'
                             Then
                             Cast(ro.is_persistence As Sql_Variant)
                         When 'is_persistence_check_duplicate_per_pk'
                             Then
                             Cast(ro.is_persistence_check_duplicate_per_pk As Sql_Variant)
                         When 'is_persistence_check_for_empty_source'
                             Then
                             Cast(ro.is_persistence_check_for_empty_source As Sql_Variant)
                         When 'is_persistence_delete_missing'
                             Then
                             Cast(ro.is_persistence_delete_missing As Sql_Variant)
                         When 'is_persistence_delete_changed'
                             Then
                             Cast(ro.is_persistence_delete_changed As Sql_Variant)
                         When 'is_persistence_insert'
                             Then
                             Cast(ro.is_persistence_insert As Sql_Variant)
                         When 'is_persistence_truncate'
                             Then
                             Cast(ro.is_persistence_truncate As Sql_Variant)
                         When 'is_persistence_update_changed'
                             Then
                             Cast(ro.is_persistence_update_changed As Sql_Variant)
                         When 'history_schema_name'
                             Then
                             Cast(ro.history_schema_name As Sql_Variant)
                         When 'history_table_name'
                             Then
                             Cast(ro.history_table_name As Sql_Variant)
                         When 'AntoraReferencedList'
                             Then
                             Cast(Cast(ro.AntoraReferencedList As NVarchar(4000)) As Sql_Variant)
                         When 'AntoraReferencingList'
                             Then
                             Cast(Cast(ro.AntoraReferencingList As NVarchar(4000)) As Sql_Variant)
                         When 'has_execution_plan_issue'
                             Then
                             Cast(Cast(ro.has_execution_plan_issue As NVarchar(4000)) As Sql_Variant)
                         When 'has_get_referenced_issue'
                             Then
                             Cast(Cast(ro.has_get_referenced_issue As NVarchar(4000)) As Sql_Variant)
                     End
From
    repo.RepoObject_gross ro
    Cross Join
    (
        Values
            ( 'pk_index_guid' )
          , ( 'pk_IndexPatternColumnDatatype' )
          , ( 'pk_IndexPatternColumnName' )
          , ( 'pk_IndexSemanticGroup' )
          , ( 'is_repo_managed' )
          , ( 'usp_persistence_RepoObject_guid' )
          , ( 'persistence_source_RepoObject_guid' )
          , ( 'persistence_source_RepoObject_fullname' )
          , ( 'persistence_source_RepoObject_fullname2' )
          , ( 'persistence_source_RepoObject_xref' )
          , ( 'has_history' )
          , ( 'has_history_columns' )
          , ( 'is_persistence' )
          , ( 'is_persistence_check_duplicate_per_pk' )
          , ( 'is_persistence_check_for_empty_source' )
          , ( 'is_persistence_delete_missing' )
          , ( 'is_persistence_delete_changed' )
          , ( 'is_persistence_insert' )
          , ( 'is_persistence_truncate' )
          , ( 'is_persistence_update_changed' )
          , ( 'history_schema_name' )
          , ( 'history_table_name' )
          , ( 'AntoraReferencedList' )
          , ( 'AntoraReferencingList' )
          , ( 'has_execution_plan_issue' )
          , ( 'has_get_referenced_issue' )
    )                     p_names ( property_name )
Where
    Not RepoObject_guid Is Null;

----
// end::sql_modules_definition[]


