= [repo].[usp_RepoObjectSource_FirstResultSet]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--AntoraReferencedList:
:ExistsProperty--AntoraReferencingList:
:ExistsProperty--ReferencedObjectList:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
9390291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
P 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
stored procedure
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1778105375
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-08 15:44:26
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]

// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]

// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]
* @execution_instance_guid (uniqueidentifier)
* @ssis_execution_id (bigint)
* @sub_execution_id (int)
* @parent_execution_log_id (bigint)
// end::AntoraParameterList[]

== AdocUspSteps

// tag::AdocUspSteps[]

// end::AdocUspSteps[]


== example1

// tag::example1[]

// end::example1[]


== example2

// tag::example2[]

// end::example2[]


== example3

// tag::example3[]

// end::example3[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_RepoObject_guid[]

// end::usp_persistence_RepoObject_guid[]


== UspExamples

// tag::UspExamples[]

// end::UspExamples[]


== UspParameters

// tag::UspParameters[]

// end::UspParameters[]


== persistence_source_RepoObject_xref

// tag::persistence_source_RepoObject_xref[]

// end::persistence_source_RepoObject_xref[]


== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_IndexPatternColumnDatatype[]

// end::pk_IndexPatternColumnDatatype[]


== pk_IndexPatternColumnName

// tag::pk_IndexPatternColumnName[]

// end::pk_IndexPatternColumnName[]


== pk_IndexSemanticGroup

// tag::pk_IndexSemanticGroup[]

// end::pk_IndexSemanticGroup[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::MS_Description[]

// end::MS_Description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_RepoObject_fullname[]

// end::persistence_source_RepoObject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_RepoObject_fullname2[]

// end::persistence_source_RepoObject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_RepoObject_guid[]

// end::persistence_source_RepoObject_guid[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== example4

// tag::example4[]

// end::example4[]


== example5

// tag::example5[]

// end::example5[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== AntoraReferencedList

// tag::AntoraReferencedList[]
* xref:repo.RepoObject.adoc[]
* xref:repo.RepoObject_gross.adoc[]
* xref:repo.RepoObjectSource_FirstResultSet.adoc[]
* xref:repo.usp_ExecutionLog_insert.adoc[]
// end::AntoraReferencedList[]


== AntoraReferencingList

// tag::AntoraReferencingList[]
* xref:repo.usp_main.adoc[]
// end::AntoraReferencingList[]


== ReferencedObjectList

// tag::ReferencedObjectList[]
* [repo].[RepoObject]
* [repo].[RepoObject_gross]
* [repo].[RepoObjectSource_FirstResultSet]
* [repo].[usp_ExecutionLog_insert]
// end::ReferencedObjectList[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----
/*
references on column level
target: repo.RepoObjectSource
source: sys.dm_exec_describe_first_result_set


sometimes required
truncate table [repo].[RepoObjectSource__dm_exec_describe_first_result_set]
*/
CREATE PROCEDURE [repo].[usp_RepoObjectSource_FirstResultSet]
 -- some optional parameters, used for logging
 @execution_instance_guid UNIQUEIDENTIFIER = NULL --SSIS system variable ExecutionInstanceGUID could be used, but other any other guid
 , @ssis_execution_id BIGINT = NULL --only SSIS system variable ServerExecutionID should be used, or any other consistent number system, do not mix
 , @sub_execution_id INT = NULL
 , @parent_execution_log_id BIGINT = NULL
AS
DECLARE @current_execution_log_id BIGINT
 , @current_execution_guid UNIQUEIDENTIFIER = NEWID()
 , @source_object NVARCHAR(261) = NULL
 , @target_object NVARCHAR(261) = NULL
 , @proc_id INT = @@procid
 , @proc_schema_name NVARCHAR(128) = OBJECT_SCHEMA_NAME(@@procid)
 , @proc_name NVARCHAR(128) = OBJECT_NAME(@@procid)
 , @event_info NVARCHAR(MAX)
 , @step_id INT = 0
 , @step_name NVARCHAR(1000) = NULL
 , @rows INT

SET @event_info = (
  SELECT [event_info]
  FROM sys.dm_exec_input_buffer(@@spid, CURRENT_REQUEST_ID())
  )

IF @execution_instance_guid IS NULL
 SET @execution_instance_guid = NEWID();
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1
SET @step_name = 'start'

--SET @source_object = NULL
--SET @target_object = NULL
EXEC repo.usp_ExecutionLog_insert @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = NULL
 , @updated = NULL
 , @deleted = NULL
 , @info_01 = NULL
 , @info_02 = NULL
 , @info_03 = NULL
 , @info_04 = NULL
 , @info_05 = NULL
 , @info_06 = NULL
 , @info_07 = NULL
 , @info_08 = NULL
 , @info_09 = NULL
 , @execution_log_id = @current_execution_log_id OUTPUT;

--
----START
--
----Make sure that the metadata is up to date
--EXEC repo.usp_sync_guid
--     @execution_instance_guid = @execution_instance_guid
--   , @ssis_execution_id = @ssis_execution_id
--   , @sub_execution_id = @sub_execution_id
--   , @parent_execution_log_id = @current_execution_log_id
--delete FROM repo.RepoObjectSource where query_sql was updated
DELETE
FROM repo.RepoObjectSource_FirstResultSet
FROM [repo].[RepoObjectSource_FirstResultSet]
LEFT OUTER JOIN [repo].[RepoObject] AS [ro]
 ON [repo].[RepoObjectSource_FirstResultSet].[RepoObject_guid] = [ro].[RepoObject_guid]
WHERE [repo].[RepoObjectSource_FirstResultSet].[created_dt] < [ro].[SysObject_modify_date]
 OR [ro].[SysObject_modify_date] IS NULL
 --wrong inserts from prev execution
 OR [target_column_name] IS NULL

SET @rows = @@rowcount;
SET @step_id = @step_id + 1
SET @step_name = 'DELETE modified after last created:dt'
SET @source_object = NULL
SET @target_object = '[repo].[RepoObjectSource_FirstResultSet]'

EXEC repo.usp_ExecutionLog_insert @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = NULL
 , @updated = NULL
 , @deleted = @rows
 , @info_01 = NULL
 , @info_02 = NULL
 , @info_03 = NULL
 , @info_04 = NULL
 , @info_05 = NULL
 , @info_06 = NULL
 , @info_07 = NULL
 , @info_08 = NULL
 , @info_09 = NULL

INSERT INTO repo.RepoObjectSource_FirstResultSet (
 [RepoObject_guid]
 , [column_ordinal]
 , [target_column_name]
 , [system_type_id]
 , [system_type_name]
 , [source_server_name]
 , [source_database_name]
 , [source_schema_name]
 , [source_table_name]
 , [source_column_name]
 , [is_hidden]
 , [created_dt]
 )
SELECT [ro_filtered].[RepoObject_guid]
 , [ref].[column_ordinal]
 , [ref].[name]
 , [ref].[system_type_id]
 , [ref].[system_type_name]
 , [ref].[source_server]
 , [ref].[source_database]
 , [ref].[source_schema]
 , [ref].[source_table]
 , [ref].[source_column]
 , [ref].[is_hidden]
 , GETDATE() AS [created_dt]
FROM (
 SELECT [ro].[RepoObject_guid]
  , [ro].[SysObject_query_sql]
 FROM repo.RepoObject_gross AS ro
 LEFT JOIN (
  SELECT [RepoObject_guid]
   , MIN([created_dt]) AS [created_dt_min]
  FROM repo.RepoObjectSource_FirstResultSet AS ros
  GROUP BY [RepoObject_guid]
  ) AS ros
  ON ro.RepoObject_guid = ros.RepoObject_guid
 WHERE NOT [ro].[SysObject_query_sql] IS NULL
  --only tables and views
  AND [ro].[SysObject_type] IN (
   'U'
   , 'V'
   )
  AND (
   [ros].[created_dt_min] IS NULL
   OR [ro].[SysObject_modify_date] IS NULL
   OR [ros].[created_dt_min] < [ro].[SysObject_modify_date]
   )
 ) AS ro_filtered
CROSS APPLY
 --schema sys should be OK here because SysObject_query_sql has a full qualified query including database_name 
 sys.dm_exec_describe_first_result_set(ro_filtered.SysObject_query_sql, NULL, 1) AS ref
WHERE
 --skip invalid entries
 NOT [ref].[name] IS NULL

SET @rows = @@rowcount;
SET @step_id = @step_id + 1
SET @step_name = 'CROSS APPLY sys.dm_exec_describe_first_result_set(ro_filtered.SysObject_query_sql , NULL , 1)'
SET @source_object = '[repo].[RepoObject]'
SET @target_object = '[repo].[RepoObjectSource_FirstResultSet]'

EXEC repo.usp_ExecutionLog_insert @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = @rows
 , @updated = NULL
 , @deleted = NULL
 , @info_01 = NULL
 , @info_02 = NULL
 , @info_03 = NULL
 , @info_04 = NULL
 , @info_05 = NULL
 , @info_06 = NULL
 , @info_07 = NULL
 , @info_08 = NULL
 , @info_09 = NULL

--
--END
--
--SET @rows = @@ROWCOUNT;
SET @step_id = @step_id + 1;
SET @step_name = 'end'
SET @source_object = NULL
SET @target_object = NULL

EXEC repo.usp_ExecutionLog_insert @execution_instance_guid = @execution_instance_guid
 , @ssis_execution_id = @ssis_execution_id
 , @sub_execution_id = @sub_execution_id
 , @parent_execution_log_id = @parent_execution_log_id
 , @current_execution_guid = @current_execution_guid
 , @proc_id = @proc_id
 , @proc_schema_name = @proc_schema_name
 , @proc_name = @proc_name
 , @event_info = @event_info
 , @step_id = @step_id
 , @step_name = @step_name
 , @source_object = @source_object
 , @target_object = @target_object
 , @inserted = NULL
 , @updated = NULL
 , @deleted = NULL
 , @info_01 = NULL
 , @info_02 = NULL
 , @info_03 = NULL
 , @info_04 = NULL
 , @info_05 = NULL
 , @info_06 = NULL
 , @info_07 = NULL
 , @info_08 = NULL
 , @info_09 = NULL
----
// end::sql_modules_definition[]


