= [uspgenerator].[GeneratorUspStep_Persistence_IsInactive_setpoint]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
7F90291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1554820601
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-13 19:59:19
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-usp_id]]
=== usp_id

[cols="d,m,m,m,m,d"]
|===
|1
|*usp_id*
|int
|NOT NULL
|
|
|===


[[column-is_inactive]]
=== is_inactive

[cols="d,m,m,m,m,d"]
|===
|
|is_inactive
|int
|NOT NULL
|
|
|===


[[column-Number]]
=== Number

[cols="d,m,m,m,m,d"]
|===
|
|Number
|int
|NOT NULL
|
|
|===


[[column-source_pk_index_guid]]
=== source_pk_index_guid

[cols="d,m,m,m,m,d"]
|===
|
|source_pk_index_guid
|uniqueidentifier
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-usp_id>>*
|int
|NOT NULL
|
|




// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-is_inactive>>
|int
|NOT NULL
|
|

|
|<<column-Number>>
|int
|NOT NULL
|
|

|
|<<column-source_pk_index_guid>>
|uniqueidentifier
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-PK_GeneratorUspStep_Persistence_IsInactive_setpoint]]
=== PK_GeneratorUspStep_Persistence_IsInactive_setpoint

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_no_group[no_group]
+
--
* <<column-usp_id>>; int
--
* PK, Unique, Real: 1, 1, 0


[[index-UK_GeneratorUspStep_Persistence_IsInactive_setpoint__2]]
=== UK_GeneratorUspStep_Persistence_IsInactive_setpoint__2

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_no_group[no_group]
+
--
* <<column-usp_id>>; int
* <<column-Number>>; int
--
* PK, Unique, Real: 0, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:repo.RepoObject_gross.adoc[]
* xref:uspgenerator.GeneratorUsp.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:uspgenerator.usp_GeneratorUsp_insert_update_persistence.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]
363BB439-0796-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
int
// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
usp_id
// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[RepoObject_gross]
* [uspgenerator].[GeneratorUsp]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----
CREATE View [uspgenerator].GeneratorUspStep_Persistence_IsInactive_setpoint
As
With
ro_u
As
    (
    Select
        u.id               As usp_id
      , u.usp_schema
      , u.usp_name
      , ro.is_persistence_check_duplicate_per_pk
      , ro.is_persistence_check_for_empty_source
      , ro.is_persistence_delete_missing
      , ro.is_persistence_delete_changed
      , ro.is_persistence_insert
      , ro.is_persistence_truncate
      , ro.is_persistence_update_changed
      , ro_s.pk_index_guid As source_pk_index_guid
    From
        repo.RepoObject_gross     As ro
        Inner Join
            [uspgenerator].GeneratorUsp     As u
                On
                ro.RepoObject_schema_name   = u.usp_schema
                And ro.usp_persistence_name = u.usp_name

        Left Join
            repo.RepoObject_gross As ro_s
                On
                ro_s.RepoObject_guid        = ro.persistence_source_RepoObject_guid
    )
Select
    --check for empty source
    usp_id
  , Number              = 100
  , is_inactive         = Case is_persistence_check_for_empty_source
                              When 1
                                  Then
                                  0
                              Else
                                  1
                          End
  , source_pk_index_guid -- required only for debugging
From
    ro_u
Union All
Select
    --check duplicate per PK
    --also check existing PK
    usp_id
  , Number              = 300
  , is_inactive         = Case
                              When is_persistence_check_duplicate_per_pk = 1
                                   And Not ( source_pk_index_guid Is Null )
                                  Then
                                  0
                              Else
                                  1
                          End
  , source_pk_index_guid
From
    ro_u
Union All
Select
    --truncate persistence target
    usp_id
  , Number              = 400
  , is_inactive         = Case is_persistence_truncate
                              When 1
                                  Then
                                  0
                              Else
                                  1
                          End
  , source_pk_index_guid
From
    ro_u
Union All
Select
    --delete persistence target missing in source
    --also do not delete if truncate, because there is nothing to delete after truncate
    --also check existing PK
    usp_id
  , Number              = 500
  , is_inactive         = Case
                              When is_persistence_truncate = 1
                                   Or is_persistence_delete_missing = 0
                                   Or source_pk_index_guid Is Null
                                  Then
                                  1
                              Else
                                  0
                          End
  , source_pk_index_guid
From
    ro_u
Union All
Select
    --delete persistence target changed
    --also do not delete if truncate, because there is nothing to delete after truncate
    --also check existing PK
    usp_id
  , Number              = 550
  , is_inactive         = Case
                              When is_persistence_truncate = 1
                                   Or is_persistence_delete_changed = 0
                                   Or source_pk_index_guid Is Null
                                  Then
                                  1
                              Else
                                  0
                          End
  , source_pk_index_guid
From
    ro_u
Union All
Select
    --update changed
    --also du not update after deleting changed or after truncate, because there is nothing to update
    --also check existing PK
    usp_id
  , Number              = 600
  , is_inactive         = Case
                              When is_persistence_truncate = 1
                                   Or is_persistence_delete_changed = 1
                                   Or is_persistence_update_changed = 0
                                   Or source_pk_index_guid Is Null
                                  Then
                                  1
                              Else
                                  0
                          End
  , source_pk_index_guid
From
    ro_u
Union All
Select
    --insert missing
    --don't do this, if 'insert all' (in case of truncate)
    --also check existing PK
    usp_id
  , Number              = 700
  , is_inactive         = Case
                              When is_persistence_insert = 1
                                   And Not is_persistence_truncate = 1
                                   And Not ( source_pk_index_guid Is Null )
                                  Then
                                  0
                              Else
                                  1
                          End
  , source_pk_index_guid
From
    ro_u
Union All
Select
    --insert all
    --only in combination with truncate
    --possible enhancement: maybe some delete all is required, if truncate is not possible?
    usp_id
  , Number              = 800
  , is_inactive         = Case
                              When is_persistence_truncate = 1
                                   And is_persistence_insert = 1
                                  Then
                                  0
                              Else
                                  1
                          End
  , source_pk_index_guid
From
    ro_u;

----
// end::sql_modules_definition[]


