= [uspgenerator].[ftv_GeneratorUspStep_sql]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--AntoraParameterList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
3590291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
IF
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
inline function
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
882102183
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-13 19:59:19
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-Number]]
=== Number

[cols="d,m,m,m,m,d"]
|===
|
|Number
|int
|NOT NULL
|
|
|===


[[column-SqlStep]]
=== SqlStep

[cols="d,m,m,m,m,d"]
|===
|
|SqlStep
|nvarchar(max)
|NOT NULL
|
|
|===


[[column-Statement]]
=== Statement

[cols="d,m,m,m,m,d"]
|===
|
|Statement
|nvarchar(max)
|NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]



// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]
|
|<<column-Number>>
|int
|NOT NULL
|
|

|
|<<column-SqlStep>>
|nvarchar(max)
|NOT NULL
|
|

|
|<<column-Statement>>
|nvarchar(max)
|NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]
* @usp_id (int)
* @number (int)
* @usp_has_logging (tinyint)
* @required_Begin_count (int)
* @required_End_count (int)
* @is_required_ELSE (tinyint)
// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:uspgenerator.GeneratorUspStep.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:uspgenerator.GeneratorUspStep_Sql.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]

// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]

// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]

// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [uspgenerator].[GeneratorUspStep]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----
CREATE Function [uspgenerator].ftv_GeneratorUspStep_sql
(
    @usp_id               Int
  , @number               Int
  , @usp_has_logging      TinyInt = 0
  , @required_Begin_count Int     = 0 --how many "BEGIN" should be added in front of statement (required in condition blocks)
  , @required_End_count   Int     = 0 --how many "END" should be added at the of statement (required in condition blocks)
  , @is_required_ELSE     TinyInt = 0 --"ELSE" should be added in front of statement (required in condition blocks)
)
Returns Table
As
Return
(
    Select
        --
        SqlStep =
        --
        Concat (
                   Cast('' As NVarchar(Max))
                 , '/*'
                 , (
                       Select
                           Number
                         , Parent_Number
                         , Name
                         , has_logging
                         , is_condition
                         , is_inactive
                         , is_SubProcedure
                         , log_source_object
                         , log_target_object
                         , log_flag_InsertUpdateDelete
                         , info_01
                         , info_02
                         , info_03
                         , info_04
                         , info_05
                         , info_06
                         , info_07
                         , info_08
                         , info_09
                       For Json Path, Root('ReportUspStep')
                   )
                 , '*/'
                 , Char ( 13 ) + Char ( 10 )
                 , Case @is_required_ELSE
                       When 1
                           Then
                           'ELSE' + Char ( 13 ) + Char ( 10 )
                   End
                 , Replicate ( 'BEGIN' + Char ( 13 ) + Char ( 10 ), @required_Begin_count )
                 , Case
                       When is_SubProcedure = 1
                           Then
                           --no logging
                           Concat (
                                      'EXEC '
                                    , Statement
                                    , Char ( 13 ) + Char ( 10 )
                                    , '--add your own parameters'
                                    , Case
                                          When Not info_01 Is Null
                                              Then
                                              Concat ( Char ( 13 ) + Char ( 10 ), '  ', '@', info_01 )
                                      End
                                    , Case
                                          When Not info_02 Is Null
                                              Then
                                              Concat ( Char ( 13 ) + Char ( 10 ), '  ', ',', '@', info_02 )
                                      End
                                    , Case
                                          When Not info_03 Is Null
                                              Then
                                              Concat ( Char ( 13 ) + Char ( 10 ), '  ', ',', '@', info_03 )
                                      End
                                    , Case
                                          When Not info_04 Is Null
                                              Then
                                              Concat ( Char ( 13 ) + Char ( 10 ), '  ', ',', '@', info_04 )
                                      End
                                    , Case
                                          When Not info_05 Is Null
                                              Then
                                              Concat ( Char ( 13 ) + Char ( 10 ), '  ', ',', '@', info_05 )
                                      End
                                    , Case
                                          When Not info_06 Is Null
                                              Then
                                              Concat ( Char ( 13 ) + Char ( 10 ), '  ', ',', '@', info_06 )
                                      End
                                    , Case
                                          When Not info_07 Is Null
                                              Then
                                              Concat ( Char ( 13 ) + Char ( 10 ), '  ', ',', '@', info_07 )
                                      End
                                    , Case
                                          When Not info_08 Is Null
                                              Then
                                              Concat ( Char ( 13 ) + Char ( 10 ), '  ', ',', '@', info_08 )
                                      End
                                    , Case
                                          When Not info_09 Is Null
                                              Then
                                              Concat ( Char ( 13 ) + Char ( 10 ), '  ', ',', '@', info_09 )
                                      End
                                    , Case
                                          When @usp_has_logging = 1
                                              Then
                                              Concat (
                                                         ''
                                                       , Case
                                                             When Not info_01 Is Null
                                                                  Or Not info_02 Is Null
                                                                  Or Not info_03 Is Null
                                                                  Or Not info_04 Is Null
                                                                  Or Not info_05 Is Null
                                                                  Or Not info_06 Is Null
                                                                  Or Not info_07 Is Null
                                                                  Or Not info_08 Is Null
                                                                  Or Not info_09 Is Null
                                                                 Then
                                                                 Concat ( Char ( 13 ) + Char ( 10 ), ',' )
                                                         End
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , '--logging parameters'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' @execution_instance_guid = @execution_instance_guid'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @ssis_execution_id = @ssis_execution_id'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @sub_execution_id = @sub_execution_id'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @parent_execution_log_id = @current_execution_log_id'
                                                     )
                                      End
                                    , Char ( 13 ) + Char ( 10 )
                                  )
                       When is_condition = 1
                           Then
                           --no logging
                           Concat ( 'IF ', Statement )
                       Else
                           --other statements
                           Concat (
                                      ''
                                    , 'PRINT CONCAT(''usp_id;Number;Parent_Number: '','
                                    , usp_id
                                    , ','';'','
                                    , Number
                                    , ','';'','
                                    , Case
                                          When Not Parent_Number Is Null
                                              Then
                                              Cast(Parent_Number As Varchar(50))
                                          Else
                                              'NULL'
                                      End
                                    , ');'
                                    , Char ( 13 ) + Char ( 10 )
                                    , Char ( 13 ) + Char ( 10 )
                                    , Statement
                                    --logging depending on parameter @usp_has_logging
                                    , Case
                                          When @usp_has_logging = 1
                                               And has_logging = 1
                                              Then
                                              Concat (
                                                         ''
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , '-- Logging START --'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , 'SET @rows = @@ROWCOUNT'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , 'SET @step_id = @step_id + 1'
                                                       --, char(13), char(10), 'SET @step_name = ''', [Name], ''''
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , 'SET @step_name = '
                                                       , Case
                                                             When Not Name Is Null
                                                                 Then
                                                                 '''' + Replace ( Name, '''', '''''' ) + ''''
                                                             Else
                                                                 'NULL'
                                                         End
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , 'SET @source_object = '
                                                       , Case
                                                             When Not log_source_object Is Null
                                                                 Then
                                                                 '''' + log_source_object + ''''
                                                             Else
                                                                 'NULL'
                                                         End
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , 'SET @target_object = '
                                                       , Case
                                                             When Not log_target_object Is Null
                                                                 Then
                                                                 '''' + log_target_object + ''''
                                                             Else
                                                                 'NULL'
                                                         End
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , 'EXEC logs.usp_ExecutionLog_insert '
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' @execution_instance_guid = @execution_instance_guid'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @ssis_execution_id = @ssis_execution_id'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @sub_execution_id = @sub_execution_id'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @parent_execution_log_id = @parent_execution_log_id'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @current_execution_guid = @current_execution_guid'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @proc_id = @proc_id'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @proc_schema_name = @proc_schema_name'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @proc_name = @proc_name'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @event_info = @event_info'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @step_id = @step_id'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @step_name = @step_name'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @source_object = @source_object'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , ' , @target_object = @target_object'
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , Case log_flag_InsertUpdateDelete
                                                             When 'I'
                                                                 Then
                                                                 ' , @inserted = @rows'
                                                             When 'U'
                                                                 Then
                                                                 ' , @updated = @rows'
                                                             When 'D'
                                                                 Then
                                                                 ' , @deleted = @rows'
                                                         End
                                                       , Case
                                                             When Not info_01 Is Null
                                                                 Then
                                                                 Concat (
                                                                            Char ( 13 ) + Char ( 10 )
                                                                          , ' , @info_01 = '''
                                                                          , info_01
                                                                          , ''''
                                                                        )
                                                         End
                                                       , Case
                                                             When Not info_02 Is Null
                                                                 Then
                                                                 Concat (
                                                                            Char ( 13 ) + Char ( 10 )
                                                                          , ' , @info_01 = '''
                                                                          , info_02
                                                                          , ''''
                                                                        )
                                                         End
                                                       , Case
                                                             When Not info_03 Is Null
                                                                 Then
                                                                 Concat (
                                                                            Char ( 13 ) + Char ( 10 )
                                                                          , ' , @info_01 = '''
                                                                          , info_03
                                                                          , ''''
                                                                        )
                                                         End
                                                       , Case
                                                             When Not info_04 Is Null
                                                                 Then
                                                                 Concat (
                                                                            Char ( 13 ) + Char ( 10 )
                                                                          , ' , @info_01 = '''
                                                                          , info_04
                                                                          , ''''
                                                                        )
                                                         End
                                                       , Case
                                                             When Not info_05 Is Null
                                                                 Then
                                                                 Concat (
                                                                            Char ( 13 ) + Char ( 10 )
                                                                          , ' , @info_01 = '''
                                                                          , info_05
                                                                          , ''''
                                                                        )
                                                         End
                                                       , Case
                                                             When Not info_06 Is Null
                                                                 Then
                                                                 Concat (
                                                                            Char ( 13 ) + Char ( 10 )
                                                                          , ' , @info_01 = '''
                                                                          , info_06
                                                                          , ''''
                                                                        )
                                                         End
                                                       , Case
                                                             When Not info_07 Is Null
                                                                 Then
                                                                 Concat (
                                                                            Char ( 13 ) + Char ( 10 )
                                                                          , ' , @info_01 = '''
                                                                          , info_07
                                                                          , ''''
                                                                        )
                                                         End
                                                       , Case
                                                             When Not info_08 Is Null
                                                                 Then
                                                                 Concat (
                                                                            Char ( 13 ) + Char ( 10 )
                                                                          , ' , @info_01 = '''
                                                                          , info_08
                                                                          , ''''
                                                                        )
                                                         End
                                                       , Case
                                                             When Not info_09 Is Null
                                                                 Then
                                                                 Concat (
                                                                            Char ( 13 ) + Char ( 10 )
                                                                          , ' , @info_01 = '''
                                                                          , info_09
                                                                          , ''''
                                                                        )
                                                         End
                                                       , Char ( 13 ) + Char ( 10 )
                                                       , '-- Logging END --'
                                                     --, char(13), char(10)
                                                     )
                                      End
                                  )
                   End
                 , Replicate ( Char ( 13 ) + Char ( 10 ) + 'END;', @required_End_count )
                 , Char ( 13 ) + Char ( 10 )
               )
      , Number
      , Statement
    From
        [uspgenerator].GeneratorUspStep s
    Where
        s.usp_id     = @usp_id
        And s.Number = @number
);

----
// end::sql_modules_definition[]


