= [uspgenerator].[GeneratorUspStep_Persistence]

== existing_properties

// tag::existing_properties[]
:ExistsProperty--antorareferencedlist:
:ExistsProperty--antorareferencinglist:
:ExistsProperty--pk_index_guid:
:ExistsProperty--pk_indexpatterncolumndatatype:
:ExistsProperty--pk_indexpatterncolumnname:
:ExistsProperty--referencedobjectlist:
:ExistsProperty--sql_modules_definition:
:ExistsProperty--FK:
:ExistsProperty--AntoraIndexList:
:ExistsProperty--Columns:
// end::existing_properties[]

== RepoObject_guid

// tag::RepoObject_guid[]
8190291C-9D61-EB11-84DC-A81E8446D5B0
// end::RepoObject_guid[]

== SysObject_type

// tag::SysObject_type[]
V 
// end::SysObject_type[]

== SysObject_type_name

// tag::SysObject_type_name[]
view
// end::SysObject_type_name[]

== SysObject_id

// tag::SysObject_id[]
1538820544
// end::SysObject_id[]

== SysObject_modify_date

// tag::SysObject_modify_date[]
2021-04-13 19:59:19
// end::SysObject_modify_date[]

== AntoraColumnDetails

// tag::AntoraColumnDetails[]
[[column-usp_id]]
=== usp_id

[cols="d,m,m,m,m,d"]
|===
|1
|*usp_id*
|int
|NOT NULL
|
|
|===


[[column-has_logging]]
=== has_logging

[cols="d,m,m,m,m,d"]
|===
|
|has_logging
|int
|NOT NULL
|
|
|===


[[column-is_condition]]
=== is_condition

[cols="d,m,m,m,m,d"]
|===
|
|is_condition
|int
|NOT NULL
|
|
|===


[[column-is_inactive]]
=== is_inactive

[cols="d,m,m,m,m,d"]
|===
|
|is_inactive
|int
|NOT NULL
|
|
|===


[[column-is_SubProcedure]]
=== is_SubProcedure

[cols="d,m,m,m,m,d"]
|===
|
|is_SubProcedure
|int
|NOT NULL
|
|
|===


[[column-log_flag_InsertUpdateDelete]]
=== log_flag_InsertUpdateDelete

[cols="d,m,m,m,m,d"]
|===
|
|log_flag_InsertUpdateDelete
|varchar(1)
|NULL
|
|
|===


[[column-log_source_object]]
=== log_source_object

[cols="d,m,m,m,m,d"]
|===
|
|log_source_object
|nvarchar(261)
|NULL
|
|
|===


[[column-log_target_object]]
=== log_target_object

[cols="d,m,m,m,m,d"]
|===
|
|log_target_object
|nvarchar(261)
|NULL
|
|
|===


[[column-Name]]
=== Name

[cols="d,m,m,m,m,d"]
|===
|
|Name
|varchar(45)
|NOT NULL
|
|
|===


[[column-Number]]
=== Number

[cols="d,m,m,m,m,d"]
|===
|
|Number
|int
|NOT NULL
|
|
|===


[[column-Parent_Number]]
=== Parent_Number

[cols="d,m,m,m,m,d"]
|===
|
|Parent_Number
|int
|NULL
|
|
|===


[[column-RepoObject_guid]]
=== RepoObject_guid

[cols="d,m,m,m,m,d"]
|===
|
|RepoObject_guid
|uniqueidentifier
|NOT NULL
|
|
|===


[[column-Statement]]
=== Statement

[cols="d,m,m,m,m,d"]
|===
|
|Statement
|nvarchar(max)
|NULL
|
|
|===


[[column-usp_fullname]]
=== usp_fullname

[cols="d,m,m,m,m,d"]
|===
|
|usp_fullname
|nvarchar(261)
|NOT NULL
|
|
|===


// end::AntoraColumnDetails[]

== AntoraPkColumnTableRows

// tag::AntoraPkColumnTableRows[]
|1
|*<<column-usp_id>>*
|int
|NOT NULL
|
|














// end::AntoraPkColumnTableRows[]

== AntoraNonPkColumnTableRows

// tag::AntoraNonPkColumnTableRows[]

|
|<<column-has_logging>>
|int
|NOT NULL
|
|

|
|<<column-is_condition>>
|int
|NOT NULL
|
|

|
|<<column-is_inactive>>
|int
|NOT NULL
|
|

|
|<<column-is_SubProcedure>>
|int
|NOT NULL
|
|

|
|<<column-log_flag_InsertUpdateDelete>>
|varchar(1)
|NULL
|
|

|
|<<column-log_source_object>>
|nvarchar(261)
|NULL
|
|

|
|<<column-log_target_object>>
|nvarchar(261)
|NULL
|
|

|
|<<column-Name>>
|varchar(45)
|NOT NULL
|
|

|
|<<column-Number>>
|int
|NOT NULL
|
|

|
|<<column-Parent_Number>>
|int
|NULL
|
|

|
|<<column-RepoObject_guid>>
|uniqueidentifier
|NOT NULL
|
|

|
|<<column-Statement>>
|nvarchar(max)
|NULL
|
|

|
|<<column-usp_fullname>>
|nvarchar(261)
|NOT NULL
|
|

// end::AntoraNonPkColumnTableRows[]

== AntoraIndexList

// tag::AntoraIndexList[]

[[index-PK_GeneratorUspStep_Persistence]]
=== PK_GeneratorUspStep_Persistence

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_no_group[no_group]
+
--
* <<column-usp_id>>; int
--
* PK, Unique, Real: 1, 1, 0


[[index-UK_GeneratorUspStep_Persistence__2]]
=== UK_GeneratorUspStep_Persistence__2

* IndexSemanticGroup: xref:index/IndexSemanticGroup.adoc#_no_group[no_group]
+
--
* <<column-usp_id>>; int
* <<column-Number>>; int
--
* PK, Unique, Real: 0, 1, 0

// end::AntoraIndexList[]

== AntoraParameterList

// tag::AntoraParameterList[]

// end::AntoraParameterList[]

== AdocUspSteps

// tag::adocuspsteps[]

// end::adocuspsteps[]


== AntoraReferencedList

// tag::antorareferencedlist[]
* xref:repo.Index_ColumList.adoc[]
* xref:repo.RepoObject_gross.adoc[]
* xref:uspgenerator.GeneratorUsp.adoc[]
// end::antorareferencedlist[]


== AntoraReferencingList

// tag::antorareferencinglist[]
* xref:uspgenerator.usp_GeneratorUsp_insert_update_persistence.adoc[]
// end::antorareferencinglist[]


== exampleUsage

// tag::exampleusage[]

// end::exampleusage[]


== exampleUsage_2

// tag::exampleusage_2[]

// end::exampleusage_2[]


== exampleWrong_Usage

// tag::examplewrong_usage[]

// end::examplewrong_usage[]


== has_execution_plan_issue

// tag::has_execution_plan_issue[]

// end::has_execution_plan_issue[]


== has_get_referenced_issue

// tag::has_get_referenced_issue[]

// end::has_get_referenced_issue[]


== has_history

// tag::has_history[]

// end::has_history[]


== has_history_columns

// tag::has_history_columns[]

// end::has_history_columns[]


== is_persistence

// tag::is_persistence[]

// end::is_persistence[]


== is_persistence_check_duplicate_per_pk

// tag::is_persistence_check_duplicate_per_pk[]

// end::is_persistence_check_duplicate_per_pk[]


== is_persistence_check_for_empty_source

// tag::is_persistence_check_for_empty_source[]

// end::is_persistence_check_for_empty_source[]


== is_persistence_delete_changed

// tag::is_persistence_delete_changed[]

// end::is_persistence_delete_changed[]


== is_persistence_delete_missing

// tag::is_persistence_delete_missing[]

// end::is_persistence_delete_missing[]


== is_persistence_insert

// tag::is_persistence_insert[]

// end::is_persistence_insert[]


== is_persistence_truncate

// tag::is_persistence_truncate[]

// end::is_persistence_truncate[]


== is_persistence_update_changed

// tag::is_persistence_update_changed[]

// end::is_persistence_update_changed[]


== is_repo_managed

// tag::is_repo_managed[]

// end::is_repo_managed[]


== microsoft_database_tools_support

// tag::microsoft_database_tools_support[]

// end::microsoft_database_tools_support[]


== MS_Description

// tag::ms_description[]

// end::ms_description[]


== persistence_source_RepoObject_fullname

// tag::persistence_source_repoobject_fullname[]

// end::persistence_source_repoobject_fullname[]


== persistence_source_RepoObject_fullname2

// tag::persistence_source_repoobject_fullname2[]

// end::persistence_source_repoobject_fullname2[]


== persistence_source_RepoObject_guid

// tag::persistence_source_repoobject_guid[]

// end::persistence_source_repoobject_guid[]


== persistence_source_RepoObject_xref

// tag::persistence_source_repoobject_xref[]

// end::persistence_source_repoobject_xref[]


== pk_index_guid

// tag::pk_index_guid[]
319D0C2F-0796-EB11-84F4-A81E8446D5B0
// end::pk_index_guid[]


== pk_IndexPatternColumnDatatype

// tag::pk_indexpatterncolumndatatype[]
int
// end::pk_indexpatterncolumndatatype[]


== pk_IndexPatternColumnName

// tag::pk_indexpatterncolumnname[]
usp_id
// end::pk_indexpatterncolumnname[]


== pk_IndexSemanticGroup

// tag::pk_indexsemanticgroup[]

// end::pk_indexsemanticgroup[]


== ReferencedObjectList

// tag::referencedobjectlist[]
* [repo].[Index_ColumList]
* [repo].[RepoObject_gross]
* [uspgenerator].[GeneratorUsp]
// end::referencedobjectlist[]


== usp_persistence_RepoObject_guid

// tag::usp_persistence_repoobject_guid[]

// end::usp_persistence_repoobject_guid[]


== UspParameters

// tag::uspparameters[]

// end::uspparameters[]


== sql_modules_definition

// tag::sql_modules_definition[]
[source,sql]
----


/*
this view creates possible steps for GeneratorUspStep

[repo].[usp_GeneratorUsp_insert_update_persistence]

The content of the steps and the status [is_inactive] are determined and applied separately.

* first all steps are inserted or updated
* [is_inactive] will be set for some steps, to make

*/

CREATE View [uspgenerator].GeneratorUspStep_Persistence
As
Select
    --
    usp_id                      = gu.id
  , Number                      = 100
  , Parent_Number               = Null
  , Name                        = 'check for empty source'
  , has_logging                 = 0
  , is_condition                = 1
  , is_inactive                 = 0
  , is_SubProcedure             = 0
  , Statement                   = '(SELECT count(*) FROM ' + ro.persistence_source_SysObject_fullname + ') = 0'
  , log_source_object           = ro.persistence_source_SysObject_fullname
  , log_target_object           = Cast(Null As NVarchar(261))
  , log_flag_InsertUpdateDelete = Cast(Null As Char(1))
  --
  , gu.usp_fullname
  , ro.RepoObject_guid
From
    repo.RepoObject_gross As ro
    Inner Join
        [uspgenerator].GeneratorUsp As gu
            On
            ro.RepoObject_schema_name   = gu.usp_schema
            And ro.usp_persistence_name = gu.usp_name
Union All
Select
    --
    usp_id                      = gu.id
  , Number                      = 110
  , Parent_Number               = 100
  , Name                        = 'ERROR 50110: persistence source is empty'
  , has_logging                 = 0
  , is_condition                = 0
  , is_inactive                 = 0
  , is_SubProcedure             = 0
  , Statement                   = ' THROW 50110
  , ''persistence source is empty: ' + ro.persistence_source_SysObject_fullname + '''
  , 1;
'
  , log_source_object           = Cast(Null As NVarchar(261))
  , log_target_object           = Cast(Null As NVarchar(261))
  , log_flag_InsertUpdateDelete = Cast(Null As Char(1))
  --
  , gu.usp_fullname
  , ro.RepoObject_guid
From
    repo.RepoObject_gross As ro
    Inner Join
        [uspgenerator].GeneratorUsp As gu
            On
            ro.RepoObject_schema_name   = gu.usp_schema
            And ro.usp_persistence_name = gu.usp_name
Union All
Select
    --will be empty if PK doesn't exist
    usp_id                      = gu.id
  , Number                      = 300
  , Parent_Number               = Null
  , Name                        = 'check duplicate per PK'
  , has_logging                 = 0
  , is_condition                = 1
  , is_inactive                 = 0
  , is_SubProcedure             = 0
  , Statement                   = 'EXISTS(SELECT TOP 1 1 FROM ' + ro.persistence_source_SysObject_fullname + ' GROUP BY ' + i.ColumnList
                                  + ' HAVING COUNT(*) > 1)'
  , log_source_object           = ro.persistence_source_SysObject_fullname
  , log_target_object           = Cast(Null As NVarchar(261))
  , log_flag_InsertUpdateDelete = Cast(Null As Char(1))
  --
  , gu.usp_fullname
  , ro.RepoObject_guid
From
    repo.RepoObject_gross     As ro
    Inner Join
        [uspgenerator].GeneratorUsp     As gu
            On
            ro.RepoObject_schema_name   = gu.usp_schema
            And ro.usp_persistence_name = gu.usp_name
    --INNER JOIN because step 300 should be created only when PK exists in persistence_source

    Inner Join
        repo.RepoObject_gross As ro_s
            On
            ro_s.RepoObject_guid        = ro.persistence_source_RepoObject_guid

    Inner Join
        repo.Index_ColumList  As i
            On
            i.index_guid                = ro_s.pk_index_guid
Union All
Select
    --will be empty if PK doesn't exist
    usp_id                      = gu.id
  , Number                      = 310
  , Parent_Number               = 300
  , Name                        = 'ERROR 50310: persistence source PK not unique'
  , has_logging                 = 0
  , is_condition                = 0
  , is_inactive                 = 0
  , is_SubProcedure             = 0
  , Statement                   = ' THROW 50310
  , ''persistence source PK not unique: ' + ro.persistence_source_SysObject_fullname + '; ' + i.ColumnList
                                  + '''
  , 1;
'
  , log_source_object           = Cast(Null As NVarchar(261))
  , log_target_object           = Cast(Null As NVarchar(261))
  , log_flag_InsertUpdateDelete = Cast(Null As Char(1))
  --
  , gu.usp_fullname
  , ro.RepoObject_guid
From
    repo.RepoObject_gross     As ro
    Inner Join
        [uspgenerator].GeneratorUsp     As gu
            On
            ro.RepoObject_schema_name   = gu.usp_schema
            And ro.usp_persistence_name = gu.usp_name
    --INNER JOIN because step 300 should be created only when PK exists in persistence_source

    Inner Join
        repo.RepoObject_gross As ro_s
            On
            ro_s.RepoObject_guid        = ro.persistence_source_RepoObject_guid

    Inner Join
        repo.Index_ColumList  As i
            On
            i.index_guid                = ro_s.pk_index_guid
Union All
Select
    --
    usp_id                      = gu.id
  , Number                      = 400
  , Parent_Number               = Null
  , Name                        = 'truncate persistence target'
  , has_logging                 = 1
  , is_condition                = 0
  , is_inactive                 = 0
  , is_SubProcedure             = 0
  , Statement                   = 'TRUNCATE TABLE ' + ro.RepoObject_fullname
  , log_source_object           = Cast(Null As NVarchar(261))
  , log_target_object           = ro.RepoObject_fullname
  , log_flag_InsertUpdateDelete = 'D'
  --
  , gu.usp_fullname
  , ro.RepoObject_guid
From
    repo.RepoObject_gross As ro
    Inner Join
        [uspgenerator].GeneratorUsp As gu
            On
            ro.RepoObject_schema_name   = gu.usp_schema
            And ro.usp_persistence_name = gu.usp_name
Union All
Select
    --will be empty if PK doesn't exist
    usp_id                      = gu.id
  , Number                      = 500
  , Parent_Number               = Null
  , Name                        = 'delete persistence target missing in source'
  , has_logging                 = 1
  , is_condition                = 0
  , is_inactive                 = 0
  , is_SubProcedure             = 0
  , Statement                   = 'DELETE T
FROM ' + ro.RepoObject_fullname + ' AS T
WHERE
NOT EXISTS
(SELECT 1 FROM ' + ro.persistence_source_SysObject_fullname + ' AS S
WHERE
' + i.PersistenceWhereColumnList + ')
 '
  , log_source_object           = ro.persistence_source_SysObject_fullname
  , log_target_object           = ro.RepoObject_fullname
  , log_flag_InsertUpdateDelete = 'D'
  --
  , gu.usp_fullname
  , ro.RepoObject_guid
From
    repo.RepoObject_gross     As ro
    Inner Join
        [uspgenerator].GeneratorUsp     As gu
            On
            ro.RepoObject_schema_name   = gu.usp_schema
            And ro.usp_persistence_name = gu.usp_name
    --INNER JOIN because step 500 should be created only when PK exists in persistence_source

    Inner Join
        repo.RepoObject_gross As ro_s
            On
            ro_s.RepoObject_guid        = ro.persistence_source_RepoObject_guid

    Inner Join
        repo.Index_ColumList  As i
            On
            i.index_guid                = ro_s.pk_index_guid
Union All
Select
    --will be empty if PK doesn't exist
    usp_id                      = gu.id
  , Number                      = 550
  , Parent_Number               = Null
  , Name                        = 'delete persistence target changed'
  , has_logging                 = 1
  , is_condition                = 0
  , is_inactive                 = 0
  , is_SubProcedure             = 0
  , Statement                   = 'DELETE T
FROM ' + ro.RepoObject_fullname + ' AS T
INNER JOIN ' + ro.persistence_source_SysObject_fullname + ' AS S
ON
' + i.PersistenceWhereColumnList + '
WHERE
' + ro.PersistenceCompareColumnList
  , log_source_object           = ro.persistence_source_SysObject_fullname
  , log_target_object           = ro.RepoObject_fullname
  , log_flag_InsertUpdateDelete = 'D'
  --
  , gu.usp_fullname
  , ro.RepoObject_guid
From
    repo.RepoObject_gross     As ro
    Inner Join
        [uspgenerator].GeneratorUsp     As gu
            On
            ro.RepoObject_schema_name   = gu.usp_schema
            And ro.usp_persistence_name = gu.usp_name
    --INNER JOIN because step 500 should be created only when PK exists in persistence_source

    Inner Join
        repo.RepoObject_gross As ro_s
            On
            ro_s.RepoObject_guid        = ro.persistence_source_RepoObject_guid

    Inner Join
        repo.Index_ColumList  As i
            On
            i.index_guid                = ro_s.pk_index_guid
Union All
Select
    --will be empty if PK doesn't exist
    usp_id                      = gu.id
  , Number                      = 600
  , Parent_Number               = Null
  , Name                        = 'update changed'
  , has_logging                 = 1
  , is_condition                = 0
  , is_inactive                 = 0
  , is_SubProcedure             = 0
  , Statement                   = 'UPDATE T
SET
' + ro.PersistenceUpdateColumnList + '
FROM ' + ro.RepoObject_fullname + ' AS T
INNER JOIN ' + ro.persistence_source_SysObject_fullname + ' AS S
ON
' + i.PersistenceWhereColumnList + '
WHERE
' + ro.PersistenceCompareColumnList
  , log_source_object           = ro.persistence_source_SysObject_fullname
  , log_target_object           = ro.RepoObject_fullname
  , log_flag_InsertUpdateDelete = 'U'
  --
  , gu.usp_fullname
  , ro.RepoObject_guid
From
    repo.RepoObject_gross     As ro
    Inner Join
        [uspgenerator].GeneratorUsp     As gu
            On
            ro.RepoObject_schema_name   = gu.usp_schema
            And ro.usp_persistence_name = gu.usp_name
    --INNER JOIN because step 500 should be created only when PK exists in persistence_source

    Inner Join
        repo.RepoObject_gross As ro_s
            On
            ro_s.RepoObject_guid        = ro.persistence_source_RepoObject_guid

    Inner Join
        repo.Index_ColumList  As i
            On
            i.index_guid                = ro_s.pk_index_guid
Union All
Select
    --will be empty if PK doesn't exist
    usp_id                      = gu.id
  , Number                      = 700
  , Parent_Number               = Null
  , Name                        = 'insert missing'
  , has_logging                 = 1
  , is_condition                = 0
  , is_inactive                 = 0
  , is_SubProcedure             = 0
  , Statement                   = 'INSERT INTO 
 ' + ro.RepoObject_fullname + '
 (
' + ro.PersistenceInsertColumnList + ')
SELECT
' + ro.PersistenceInsertColumnList + '
FROM ' + ro.persistence_source_SysObject_fullname + ' AS S
WHERE
NOT EXISTS
(SELECT 1
FROM ' + ro.RepoObject_fullname + ' AS T
WHERE
' + i.PersistenceWhereColumnList + ')'
  , log_source_object           = ro.persistence_source_SysObject_fullname
  , log_target_object           = ro.RepoObject_fullname
  , log_flag_InsertUpdateDelete = 'I'
  --
  , gu.usp_fullname
  , ro.RepoObject_guid
From
    repo.RepoObject_gross     As ro
    Inner Join
        [uspgenerator].GeneratorUsp     As gu
            On
            ro.RepoObject_schema_name   = gu.usp_schema
            And ro.usp_persistence_name = gu.usp_name
    --INNER JOIN because step 500 should be created only when PK exists in persistence_source

    Inner Join
        repo.RepoObject_gross As ro_s
            On
            ro_s.RepoObject_guid        = ro.persistence_source_RepoObject_guid

    Inner Join
        repo.Index_ColumList  As i
            On
            i.index_guid                = ro_s.pk_index_guid
Union All
Select
    --should be used in combination with truncate
    usp_id                      = gu.id
  , Number                      = 800
  , Parent_Number               = Null
  , Name                        = 'insert all'
  , has_logging                 = 1
  , is_condition                = 0
  , is_inactive                 = 0
  , is_SubProcedure             = 0
  , Statement                   = 'INSERT INTO 
 ' + ro.RepoObject_fullname + '
 (
' + ro.PersistenceInsertColumnList + ')
SELECT
' + ro.PersistenceInsertColumnList + '
FROM ' + ro.persistence_source_SysObject_fullname + ' AS S'
  , log_source_object           = ro.persistence_source_SysObject_fullname
  , log_target_object           = ro.RepoObject_fullname
  , log_flag_InsertUpdateDelete = 'I'
  --
  , gu.usp_fullname
  , ro.RepoObject_guid
From
    repo.RepoObject_gross As ro
    Inner Join
        [uspgenerator].GeneratorUsp As gu
            On
            ro.RepoObject_schema_name   = gu.usp_schema
            And ro.usp_persistence_name = gu.usp_name;

----
// end::sql_modules_definition[]


