left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.B2B50396-6823-4F79-B8BA-3033BA4D67E9 << U >> {
}

entity docs.RepoObject_Adoc << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml_Entity << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
}

docs.B2B50396-6823-4F79-B8BA-3033BA4D67E9 <.. docs.RepoObject_Adoc
docs.B2B50396-6823-4F79-B8BA-3033BA4D67E9 <.. docs.RepoObject_Plantuml_Entity
docs.B2B50396-6823-4F79-B8BA-3033BA4D67E9 <.. docs.usp_PERSIST_RepoObject_IndexList_T
