Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObjectColumnProperty_ForUpdate << V >> {
- idx_RepoObjectColumnProperty_ForUpdate__1
{RepoObjectColumnProperty_id}
..
RepoObjectColumnProperty_id; int
--
- idx_RepoObjectColumnProperty_ForUpdate__2
{RepoObjectColumn_guid,property_name}
..
RepoObjectColumn_guid; uniqueidentifier
property_name; nvarchar(128)
--
- idx_RepoObjectColumnProperty_ForUpdate__3
{RepoObjectColumn_guid}
..
RepoObjectColumn_guid; uniqueidentifier
--
- idx_RepoObjectColumnProperty_ForUpdate__4
{RepoObject_guid,Column_name}
..
RepoObject_guid; uniqueidentifier
RepoObjectColumn_name; nvarchar(128)
--
- idx_RepoObjectColumnProperty_ForUpdate__5
{RepoObject_guid}
..
RepoObject_guid; uniqueidentifier
}


