Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.SysColumn_RepoObjectColumn_via_guid << V >> {
- idx_SysColumn_RepoObjectColumn_via_guid__1
{RepoObjectColumn_guid}
..
RepoObjectColumn_guid; uniqueidentifier
--
- idx_SysColumn_RepoObjectColumn_via_guid__2
{RepoObjectColumn_guid,Column_name}
..
RepoObjectColumn_guid; uniqueidentifier
SysObjectColumn_name; nvarchar(128)
--
- idx_SysColumn_RepoObjectColumn_via_guid__3
{RepoObject_guid,Column_name}
..
RepoObject_guid; uniqueidentifier
RepoObjectColumn_name; nvarchar(128)
--
- idx_SysColumn_RepoObjectColumn_via_guid__4
{RepoObject_guid}
..
RepoObject_guid; uniqueidentifier
}


