Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.Index_virtual_SysObject << V >> {
- **PK_Index_virtual_SysObject**
{index_guid}
..
index_guid; uniqueidentifier
--
- idx_Index_virtual_SysObject__2
{RepoObject_guid}
..
parent_RepoObject_guid; uniqueidentifier
--
- idx_Index_virtual_SysObject__3
{schema_name,object_name}
..
SysObject_schema_name; nvarchar(128)
SysObject_name; nvarchar(128)
--
- idx_Index_virtual_SysObject__4
{index_guid}
..
pk_index_guid; uniqueidentifier
}


