left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObject_RequiredRepoObjectMerge << V >> {
- **PK_RepoObject_RequiredRepoObjectMerge**
{RepoObject_guid}
..
RepoObject_guid; uniqueidentifier
--
- idx_RepoObject_RequiredRepoObjectMerge__2
{schema_name,object_name}
..
SysObject_schema_name; nvarchar(128)
SysObject_name; nvarchar(128)
--
- idx_RepoObject_RequiredRepoObjectMerge__3

..
SysObject_name; nvarchar(128)
--
- idx_RepoObject_RequiredRepoObjectMerge__4
{schema_name,object_name}
..
RepoObject_schema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
}


