left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.IndexColumn_virtual_referenced_setpoint << V >> {
- **PK_IndexColumn_virtual_referenced_setpoint**

..
index_guid; uniqueidentifier
index_column_id; int
--
- idx_IndexColumn_virtual_referenced_setpoint__2
{index_guid}
..
index_guid; uniqueidentifier
--
- idx_IndexColumn_virtual_referenced_setpoint__3

..
index_column_id; int
}


