Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.ForeignKey_virtual << U >> {
**PK_ForeignKey_virtual**
{ForeignKey_guid}
..
ForeignKey_guid; uniqueidentifier
--
- UK_ForeignKey_virtual__1
{index_guid}
..
referenced_index_guid; uniqueidentifier
--
- idx_ForeignKey_virtual__2
{index_guid}
..
referencing_index_guid; uniqueidentifier
}

entity repo.Index_Settings << U >> {
**PK_Index_Settings**
{index_guid}
..
index_guid; uniqueidentifier
}

entity repo.RepoObject << U >> {
**PK_RepoObject**
{RepoObject_guid}
..
RepoObject_guid; uniqueidentifier
--
UK_RepoObject__RepoNames
{schema_name,object_name}
..
RepoObject_schema_name; nvarchar(128)
RepoObject_name; nvarchar(128)
--
UK_RepoObject__SysNames
{schema_name,object_name}
..
SysObject_schema_name; nvarchar(128)
SysObject_name; nvarchar(128)
--
- idx_RepoObject__1
{index_guid}
..
pk_index_guid; uniqueidentifier
}

repo.Index_Settings::PK_Index_Settings <-- repo.ForeignKey_virtual::idx_ForeignKey_virtual__2
repo.Index_Settings::PK_Index_Settings <-- repo.ForeignKey_virtual::UK_ForeignKey_virtual__1
repo.Index_Settings::PK_Index_Settings <-- repo.RepoObject::idx_RepoObject__1
