Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity uspgenerator.GeneratorUsp << U >> {
**PK_GeneratorUsp**
{usp_id}
..
id; int
--
UK_GeneratorUsp_Schema_Name
{usp_schema,usp_name}
..
usp_schema; nvarchar(128)
usp_name; nvarchar(128)
}

entity uspgenerator.GeneratorUspParameter << U >> {
**PK_GeneratorUspParameter**
{UspParameter_id}
..
id; int
--
UK_GeneratorUspParameter_name
{UK_GeneratorUspParameter_name}
..
usp_id; int
Name; nvarchar(128)
--
UK_GeneratorUspParameter_Number
{UK_GeneratorUspParameter_Number}
..
usp_id; int
Number; int
--
- idx_GeneratorUspParameter__1
{usp_id}
..
usp_id; int
}

uspgenerator.GeneratorUsp::PK_GeneratorUsp <-- uspgenerator.GeneratorUspParameter::idx_GeneratorUspParameter__1
