Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity uspgenerator.GeneratorUsp_SqlUsp << V >> {
- **PK_GeneratorUsp_SqlUsp**

..
usp_id; int
--
- idx_GeneratorUsp_SqlUsp__2
{RepoObject_guid}
..
RepoObject_guid; uniqueidentifier
--
- idx_GeneratorUsp_SqlUsp__3
{usp_schema,usp_name}
..
usp_schema; nvarchar(128)
usp_name; nvarchar(128)
}


