left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity workflow.ProcedureInstanceDependency_gross << V >> {
- idx_ProcedureInstanceDependency_gross__1
{ProcedureInstanceDependency_id}
..
id; int
--
- idx_ProcedureInstanceDependency_gross__2
{UK_ProcedureInstanceDependency}
..
referenced_id; int
referencing_id; int
--
- idx_ProcedureInstanceDependency_gross__3
{ProcedureInstance_id}
..
referenced_id; int
--
- idx_ProcedureInstanceDependency_gross__4
{ProcedureInstance_id}
..
referencing_id; int
}


