= DHW - DataHandwerk toolkit mssql
:description: DHW - DataHandwerk toolkit mssql. Handwerk statt Massenproduktion. Craft instead of mass production. MSSQL based tools for data craftsmen. Individual customization instead of assembly line.
:keywords: dhw, DataHandwerk, dwh, datawarehouse, ms sql server,
:author: Germo Görtz
:date: {docdate}

image::DatenHandwerk-toolkit-mssql.svg[dhw]

== Key contents of the architecture

TIP: Read the xref:arc:architecture.adoc[] documentation to learn why DataHandwerk exists, how it works and is built. +
Some key content from the architecture documentation:

include::arc:partial$01_introduction_and_goals.adoc[tag=introduction]

include::arc:partial$01_introduction_and_goals.adoc[leveloffset=-0,tag=alternatives]

=== Repository database components

[plantuml, structurizr-DWHBDevelopment-RepositorydbProjectB-Component, svg]
....
include::arc:partial$c4_dsl/puml/structurizr-DWHBDevelopment-RepositorydbProjectB-Component.puml[]
....

== User Guide (partially)

// == Learn first steps

* xref:user-guide:create-update-connect-repo-db.adoc[]
* xref:user-guide:sqlparse-to-get-col-references.adoc[]
** xref:user-guide:sqlparser.adoc[]
* xref:user-guide:properties.adoc[]
* xref:user-guide:properties-inheritance.adoc[]
* xref:user-guide:documentation-generator.adoc[]
* xref:user-guide:persistence-generator.adoc[]
// * xref:user-guide:sql-server-issue-views-references.adoc[]

== Database documentation

The *database documentation* was created with the xref:user-guide:documentation-generator.adoc[]: xref:sqldb:docs.usp_antoraexport.adoc[] +
The documentation also contains

* real and *virtual* PK (only for tables and views)
* *column references* extracted and used with *SqlParse* (only for tables and views)
* *Visualizations* of FK, object and column references with https://plantuml.com/[PlantUML]
* formalized Procedure steps for procedures, created with the *Procedure Generator*

== Development status

primary project location: https://gitlab.com/datahandwerk/DataHandwerk-toolkit-mssql[]

https://gitlab.com/datahandwerk/DataHandwerk-toolkit-mssql/-/boards[issue board]

You can read why the project exists and how it developed in the following blog posts (in German):

* http://datahandwerk.aisberg.de/2021-01-06-meine-vision-eines-werkzeugkastens-fur-daten-handwerker/
* http://datahandwerk.aisberg.de/2021-03-23-datahandwerk-toolkit-mssql/
* http://datahandwerk.aisberg.de/2021-04-20-docs-code-mit-asciidoc-und-antora/

CAUTION: The project was launched at the beginning of 2021 and is in the alpha stage. The main focus is currently the implementation. Various refactorings are still taking place in the database. The documentation is being created and is still very incomplete.

////
Azure Boards - Feature board

image::https://dev.azure.com/DataHandwerk/89a7b008-69b9-42e4-b31f-4c2dfb6bd49a/f3077374-71b6-4a5b-bfd6-24a792bbc352/_apis/work/boardbadge/d4f2ae6d-a5e0-439d-9068-67ea1027f7b5?columnOptions=1[link= "https://dev.azure.com/DataHandwerk/89a7b008-69b9-42e4-b31f-4c2dfb6bd49a/_boards/board/t/f3077374-71b6-4a5b-bfd6-24a792bbc352/Microsoft.FeatureCategory/", window=_blank]

Azure Boards - Story board

image::https://dev.azure.com/DataHandwerk/89a7b008-69b9-42e4-b31f-4c2dfb6bd49a/f3077374-71b6-4a5b-bfd6-24a792bbc352/_apis/work/boardbadge/71c0586e-2955-431c-8b07-96da50563abc?columnOptions=1[link="https://dev.azure.com/DataHandwerk/89a7b008-69b9-42e4-b31f-4c2dfb6bd49a/_boards/board/t/f3077374-71b6-4a5b-bfd6-24a792bbc352/Microsoft.RequirementCategory/", window=_blank]


// [![Board Status](https://dev.azure.com/DataHandwerk/89a7b008-69b9-42e4-b31f-4c2dfb6bd49a/f3077374-71b6-4a5b-bfd6-24a792bbc352/_apis/work/boardbadge/d4f2ae6d-a5e0-439d-9068-67ea1027f7b5?columnOptions=1)](https://dev.azure.com/DataHandwerk/89a7b008-69b9-42e4-b31f-4c2dfb6bd49a/_boards/board/t/f3077374-71b6-4a5b-bfd6-24a792bbc352/Microsoft.FeatureCategory/)

////

== Project communication

The preferred channel for project communication is https://datahandwerk.zulipchat.com/

https://zulip.com/why-zulip/[Why Zulip?]