@startuml
title DWH B Production - Containers

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam database<<DWHBProduction.DWHdbProductionProjectB>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<DeploymentTeam>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<ProjectBDWHUser>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

person "==Deployment Team\n<size:10>[Person]</size>" <<DeploymentTeam>> as DeploymentTeam
person "==Project B DWH User\n<size:10>[Person]</size>\n\nuser of DWH (Project B)" <<ProjectBDWHUser>> as ProjectBDWHUser

package "DWH B Production\n[Software System]" <<DWHBProduction>> {
  skinparam PackageBorderColor<<DWHBProduction>> #444444
  skinparam PackageFontColor<<DWHBProduction>> #444444

  database "==DWH db Production (Project B)\n<size:10>[Container: Database]</size>" <<DWHBProduction.DWHdbProductionProjectB>> as DWHBProduction.DWHdbProductionProjectB
}

DeploymentTeam .[#707070,thickness=2].> DWHBProduction.DWHdbProductionProjectB : "<color:#707070>deployes on production system"
ProjectBDWHUser .[#707070,thickness=2].> DWHBProduction.DWHdbProductionProjectB : "<color:#707070>uses"
@enduml