@startuml(id=DataHandwerkDevelopment-SystemContext)
title DataHandwerk Development - System Context

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<31>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<32>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
rectangle "==DHW Developer\n<size:10>[Person]</size>\n\nDeveloper of DataHandwerk Toolkit" <<31>> as 31
rectangle "==DataHandwerk Development\n<size:10>[Software System]</size>" <<32>> as 32
31 .[#707070,thickness=2].> 32 : "uses for testing and development"
@enduml