@startuml(id=DWHBDevelopment-Container)
title DWH B Development - Containers

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<22>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam database<<5>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
skinparam database<<18>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9A9A9A
}
package "DWH B Development\n[Software System]" {
  database "==DWH db Development (Project B)\n<size:10>[Container: Database]</size>" <<18>> as 18
  rectangle "==GUI\n<size:10>[Container: GUI]</size>\n\nGraphical User Interface" <<22>> as 22
  database "==Repository db (Project B)\n<size:10>[Container: Database]</size>" <<5>> as 5
}
18 .[#707070].> 5 : "RepoObject correspond with extended properties"
22 .[#707070].> 5 : "uses"
5 .[#707070].> 18 : "Synonyms link to DWH System Views"
@enduml