@startuml
title DWH B Development - Repository db (Project B) - Components

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<DWHBDevelopment.Businessandtechnicaldocumentation>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.Configuration>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam database<<DWHBDevelopment.DWHdbDevelopmentProjectB>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.GUI>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.PersistenceGenerator>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.Properties>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.PropertiesInheritance>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.Reference>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.RepoObject>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.SSAS>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.SSASModelsProjectB>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.SSIS>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.SSISProjectsProjectB>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.SqlParser>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.Synonyms>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.USPGenerator>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.ViewGenerator>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.Visualization>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.RepositorydbProjectB.Workflow>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

rectangle "==Business and technical documentation\n<size:10>[Container: documentation]</size>\n\nstatic website" <<DWHBDevelopment.Businessandtechnicaldocumentation>> as DWHBDevelopment.Businessandtechnicaldocumentation
rectangle "==SSAS Models (Project B)\n<size:10>[Container: SSAS Model]</size>" <<DWHBDevelopment.SSASModelsProjectB>> as DWHBDevelopment.SSASModelsProjectB
rectangle "==SSIS Projects (Project B)\n<size:10>[Container: SSIS Folder]</size>" <<DWHBDevelopment.SSISProjectsProjectB>> as DWHBDevelopment.SSISProjectsProjectB
rectangle "==GUI\n<size:10>[Container: GUI]</size>\n\nGraphical User Interface. Not yet implemented" <<DWHBDevelopment.GUI>> as DWHBDevelopment.GUI
database "==DWH db Development (Project B)\n<size:10>[Container: Database]</size>" <<DWHBDevelopment.DWHdbDevelopmentProjectB>> as DWHBDevelopment.DWHdbDevelopmentProjectB

package "Repository db (Project B)\n[Container: Database]" <<DWHBDevelopment.RepositorydbProjectB>> {
  skinparam PackageBorderColor<<DWHBDevelopment.RepositorydbProjectB>> #444444
  skinparam PackageFontColor<<DWHBDevelopment.RepositorydbProjectB>> #444444

  rectangle "==Reference\n<size:10>[Component]</size>\n\nDetermination and management of references (dependencies) between RepoObjects or RepoObject columns" <<DWHBDevelopment.RepositorydbProjectB.Reference>> as DWHBDevelopment.RepositorydbProjectB.Reference
  rectangle "==Properties\n<size:10>[Component]</size>\n\nProperties for RepoObjects or RepoObject columns" <<DWHBDevelopment.RepositorydbProjectB.Properties>> as DWHBDevelopment.RepositorydbProjectB.Properties [[https://datahandwerk.gitlab.io/dhw/user-guide/properties.html]]
  rectangle "==Properties Inheritance\n<size:10>[Component]</size>\n\nInheritance or determination of properties, based on references" <<DWHBDevelopment.RepositorydbProjectB.PropertiesInheritance>> as DWHBDevelopment.RepositorydbProjectB.PropertiesInheritance [[https://datahandwerk.gitlab.io/dhw/user-guide/properties-inheritance.html]]
  rectangle "==USP Generator\n<size:10>[Component]</size>\n\nusp (userdefined stored procedures) can be generated in a formalized way: containing optional logging and some workflow elements (sub procedures, conditions, parent-child logic)" <<DWHBDevelopment.RepositorydbProjectB.USPGenerator>> as DWHBDevelopment.RepositorydbProjectB.USPGenerator [[https://datahandwerk.gitlab.io/dhw/user-guide/uspgenerator.html]]
  rectangle "==Persistence Generator\n<size:10>[Component]</size>\n\nViews or tables can be persisted in tables, with or without history with temporal tables. Code for performing the persistations is created." <<DWHBDevelopment.RepositorydbProjectB.PersistenceGenerator>> as DWHBDevelopment.RepositorydbProjectB.PersistenceGenerator [[https://datahandwerk.gitlab.io/dhw/user-guide/persistence-generator.html]]
  rectangle "==View Generator\n<size:10>[Component]</size>\n\nNot yet implemented" <<DWHBDevelopment.RepositorydbProjectB.ViewGenerator>> as DWHBDevelopment.RepositorydbProjectB.ViewGenerator
  rectangle "==Documentation Generator\n<size:10>[Component]</size>\n\nAntora, AsciiDoc" <<DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator>> as DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator [[https://datahandwerk.gitlab.io/dhw/user-guide/documentation-generator.html]]
  rectangle "==SSAS\n<size:10>[Component]</size>\n\nImport and parse SSAS Tabular models for documenation" <<DWHBDevelopment.RepositorydbProjectB.SSAS>> as DWHBDevelopment.RepositorydbProjectB.SSAS
  rectangle "==SSIS\n<size:10>[Component]</size>\n\nImport and parse SSIS projects for documenation" <<DWHBDevelopment.RepositorydbProjectB.SSIS>> as DWHBDevelopment.RepositorydbProjectB.SSIS
  rectangle "==Workflow\n<size:10>[Component]</size>\n\nA workflow executes procedures in a specific and necessary order." <<DWHBDevelopment.RepositorydbProjectB.Workflow>> as DWHBDevelopment.RepositorydbProjectB.Workflow
  rectangle "==Visualization\n<size:10>[Component]</size>\n\npreparation for PlantUML Visualization of data lineage (references), real and virtual PK, FK-PK" <<DWHBDevelopment.RepositorydbProjectB.Visualization>> as DWHBDevelopment.RepositorydbProjectB.Visualization
  rectangle "==Synonyms\n<size:10>[Component]</size>\n\nSynonyms are used to connect the repository database with the corresponding DWH database" <<DWHBDevelopment.RepositorydbProjectB.Synonyms>> as DWHBDevelopment.RepositorydbProjectB.Synonyms
  rectangle "==Configuration\n<size:10>[Component]</size>\n\nConnection with DWH database and various settings for the behavior of the processes in the repository." <<DWHBDevelopment.RepositorydbProjectB.Configuration>> as DWHBDevelopment.RepositorydbProjectB.Configuration
  rectangle "==RepoObject\n<size:10>[Component]</size>\n\nCentral construct to represent objects (tables, views, procedures, functions, index, ...) and their subunits (columns, index columns, procedure parameters, ...), their properties and relationships between them." <<DWHBDevelopment.RepositorydbProjectB.RepoObject>> as DWHBDevelopment.RepositorydbProjectB.RepoObject
  rectangle "==SqlParser\n<size:10>[Component]</size>\n\nParse the code of views to extract column-level references or other logic from them" <<DWHBDevelopment.RepositorydbProjectB.SqlParser>> as DWHBDevelopment.RepositorydbProjectB.SqlParser [[https://datahandwerk.gitlab.io/dhw/user-guide/sqlparse-to-get-col-references.html]]
}

DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.USPGenerator : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.Properties : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.SSAS : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.SSIS : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.Visualization : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.Properties .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.USPGenerator : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.PersistenceGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.USPGenerator : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.ViewGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.SqlParser : "<color:#707070>"
DWHBDevelopment.GUI .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.RepoObject : "<color:#707070>"
DWHBDevelopment.Businessandtechnicaldocumentation .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator : "<color:#707070>generated by"
DWHBDevelopment.RepositorydbProjectB.Synonyms .[#707070,thickness=2].> DWHBDevelopment.DWHdbDevelopmentProjectB : "<color:#707070>Synonyms link to DWH System Views"
DWHBDevelopment.DWHdbDevelopmentProjectB .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.RepoObject : "<color:#707070>RepoObject correspond with extended properties"
DWHBDevelopment.RepositorydbProjectB.RepoObject .[#707070,thickness=2].> DWHBDevelopment.DWHdbDevelopmentProjectB : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.SSAS .[#707070,thickness=2].> DWHBDevelopment.SSASModelsProjectB : "<color:#707070>imports"
DWHBDevelopment.RepositorydbProjectB.SSIS .[#707070,thickness=2].> DWHBDevelopment.SSISProjectsProjectB : "<color:#707070>imports"
DWHBDevelopment.RepositorydbProjectB.RepoObject .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.SSAS : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.RepoObject .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.Synonyms : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.SqlParser .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.Synonyms : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.Reference .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.RepoObject : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.Properties .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.RepoObject : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.USPGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.RepoObject : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.PersistenceGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.RepoObject : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.ViewGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.RepoObject : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.PropertiesInheritance .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.Properties : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.Properties .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.PropertiesInheritance : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.Reference .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.SqlParser : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.PropertiesInheritance .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.Reference : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.Workflow .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.Reference : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.PersistenceGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.Reference : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.Visualization .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.Reference : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.RepoObject : "<color:#707070>"
DWHBDevelopment.RepositorydbProjectB.DocumentationGenerator .[#707070,thickness=2].> DWHBDevelopment.RepositorydbProjectB.Reference : "<color:#707070>"
@enduml