@startuml(id=DWHBgit-SystemContext)
title DWH B git - System Context

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<2>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam folder<<30>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
package "Customer" {
  rectangle "==DWH Developer\n<size:10>[Person]</size>\n\nDeveloper of some DWH" <<1>> as 1
  rectangle "==Deployment Team\n<size:10>[Person]</size>" <<2>> as 2
  folder "==DWH B git\n<size:10>[Software System]</size>\n\nCode of Project B in Version Control (git, subversion, ...)" <<30>> as 30
}
1 .[#707070,thickness=2].> 30 : "uses"
2 .[#707070,thickness=2].> 30 : "takes code or builds"
@enduml