@startuml
title DataHandwerk Development - System Context

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam person<<DHWDeveloper>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DataHandwerkDevelopment>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

person "==DHW Developer\n<size:10>[Person]</size>\n\nDeveloper of DataHandwerk Toolkit" <<DHWDeveloper>> as DHWDeveloper
rectangle "==DataHandwerk Development\n<size:10>[Software System]</size>" <<DataHandwerkDevelopment>> as DataHandwerkDevelopment

DHWDeveloper .[#707070,thickness=2].> DataHandwerkDevelopment : "<color:#707070>uses for testing and development"
@enduml