@startuml
title DWH B Development - documentation - Components

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<DWHBDevelopment.documentation.Indexdocumentation>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.documentation.Objectdocumentation>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

package "documentation\n[Container: documentation]" <<DWHBDevelopment.documentation>> {
  skinparam PackageBorderColor<<DWHBDevelopment.documentation>> #444444
  skinparam PackageFontColor<<DWHBDevelopment.documentation>> #444444

  rectangle "==Object documentation\n<size:10>[Component: Antora]</size>\n\npage per object; docs including descriptions, examples, columns, data lineage (references), real and virtual PK, FK-PK, code" <<DWHBDevelopment.documentation.Objectdocumentation>> as DWHBDevelopment.documentation.Objectdocumentation
  rectangle "==Index documentation\n<size:10>[Component: Antora]</size>\n\nIndexes by Semantic Group" <<DWHBDevelopment.documentation.Indexdocumentation>> as DWHBDevelopment.documentation.Indexdocumentation
}

@enduml