@startuml(id=SystemLandscape)
title System Landscape for Customer

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam folder<<35>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<2>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<3>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<4>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<28>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam folder<<30>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<31>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<32>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
rectangle "==DHW Developer\n<size:10>[Person]</size>\n\nDeveloper of DataHandwerk Toolkit" <<31>> as 31
rectangle "==DataHandwerk Development\n<size:10>[Software System]</size>" <<32>> as 32
folder "==DataHandwerk git\n<size:10>[Software System]</size>\n\nCode of DataHandwerk in Version Control" <<35>> as 35
package "Customer" {
  rectangle "==DWH Developer\n<size:10>[Person]</size>\n\nDeveloper of some DWH" <<1>> as 1
  rectangle "==Deployment Team\n<size:10>[Person]</size>" <<2>> as 2
  rectangle "==Project B DWH User\n<size:10>[Person]</size>\n\nuser of DWH (Project B)" <<3>> as 3
  rectangle "==DWH B Development\n<size:10>[Software System]</size>" <<4>> as 4
  rectangle "==DWH B Production\n<size:10>[Software System]</size>" <<28>> as 28
  folder "==DWH B git\n<size:10>[Software System]</size>\n\nCode of Project B in Version Control (git, subversion, ...)" <<30>> as 30
}
31 .[#707070,thickness=2].> 32 : "uses for testing and development"
31 .[#707070,thickness=2].> 35 : "uses"
1 .[#707070,thickness=2].> 4 : "developes"
1 .[#707070,thickness=2].> 30 : "uses"
1 .[#707070,thickness=2].> 35 : "takes code or builds"
2 .[#707070,thickness=2].> 28 : "deployes on production system"
2 .[#707070,thickness=2].> 30 : "takes code or builds"
3 .[#707070,thickness=2].> 28 : "uses"
@enduml