@startuml(id=DWHBProduction-SystemContext)
title DWH B Production - System Context

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<2>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<3>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<28>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
package "Customer" {
  rectangle "==Deployment Team\n<size:10>[Person]</size>" <<2>> as 2
  rectangle "==Project B DWH User\n<size:10>[Person]</size>\n\nuser of DWH (Project B)" <<3>> as 3
  rectangle "==DWH B Production\n<size:10>[Software System]</size>" <<28>> as 28
}
2 .[#707070,thickness=2].> 28 : "deployes on production system"
3 .[#707070,thickness=2].> 28 : "uses"
@enduml