@startuml
title DWH B Development - System Context

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<DWHBDevelopment>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<DWHDeveloper>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<ProjectBDWHUser>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

package "Customer" <<enterprise>> {
  skinparam PackageBorderColor<<enterprise>> #444444
  skinparam PackageFontColor<<enterprise>> #444444

  person "==DWH Developer\n<size:10>[Person]</size>\n\nDeveloper of some DWH" <<DWHDeveloper>> as DWHDeveloper
  person "==Project B DWH User\n<size:10>[Person]</size>\n\nuser of DWH (Project B)" <<ProjectBDWHUser>> as ProjectBDWHUser
  rectangle "==DWH B Development\n<size:10>[Software System]</size>" <<DWHBDevelopment>> as DWHBDevelopment
}


DWHDeveloper .[#707070,thickness=2].> DWHBDevelopment : "<color:#707070>developes"
ProjectBDWHUser .[#707070,thickness=2].> DWHBDevelopment : "<color:#707070>uses"
@enduml