@startuml
title DWH B Development - SSIS Folders (Project B) - Components

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam database<<DWHBDevelopment.RepositorydbProjectB>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.SSISFoldersProjectB.SSISProject1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment.SSISFoldersProjectB.SSISProject2>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

database "==Repository db (Project B)\n<size:10>[Container: Database]</size>" <<DWHBDevelopment.RepositorydbProjectB>> as DWHBDevelopment.RepositorydbProjectB

package "SSIS Folders (Project B)\n[Container: SSIS Folder]" <<DWHBDevelopment.SSISFoldersProjectB>> {
  skinparam PackageBorderColor<<DWHBDevelopment.SSISFoldersProjectB>> #444444
  skinparam PackageFontColor<<DWHBDevelopment.SSISFoldersProjectB>> #444444

  rectangle "==SSIS Project 1\n<size:10>[Component: SSIS Folder]</size>" <<DWHBDevelopment.SSISFoldersProjectB.SSISProject1>> as DWHBDevelopment.SSISFoldersProjectB.SSISProject1
  rectangle "==SSIS Project 2\n<size:10>[Component: SSIS Folder]</size>" <<DWHBDevelopment.SSISFoldersProjectB.SSISProject2>> as DWHBDevelopment.SSISFoldersProjectB.SSISProject2
}

DWHBDevelopment.RepositorydbProjectB .[#707070,thickness=2].> DWHBDevelopment.SSISFoldersProjectB.SSISProject1 : "<color:#707070>imports"
DWHBDevelopment.RepositorydbProjectB .[#707070,thickness=2].> DWHBDevelopment.SSISFoldersProjectB.SSISProject2 : "<color:#707070>imports"
@enduml