@startuml
title System Landscape for Customer

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam person<<DHWDeveloper>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBDevelopment>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DWHBProduction>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam folder<<DWHBgit>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<DWHDeveloper>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<DataHandwerkDevelopment>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam folder<<DataHandwerkgit>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<DeploymentTeam>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<ProjectBDWHUser>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

package "Customer" <<enterprise>> {
  skinparam PackageBorderColor<<enterprise>> #444444
  skinparam PackageFontColor<<enterprise>> #444444

  person "==DWH Developer\n<size:10>[Person]</size>\n\nDeveloper of some DWH" <<DWHDeveloper>> as DWHDeveloper
  person "==Deployment Team\n<size:10>[Person]</size>" <<DeploymentTeam>> as DeploymentTeam
  person "==Project B DWH User\n<size:10>[Person]</size>\n\nuser of DWH (Project B)" <<ProjectBDWHUser>> as ProjectBDWHUser
  rectangle "==DWH B Production\n<size:10>[Software System]</size>" <<DWHBProduction>> as DWHBProduction
  rectangle "==DWH B Development\n<size:10>[Software System]</size>" <<DWHBDevelopment>> as DWHBDevelopment
  folder "==DWH B git\n<size:10>[Software System]</size>\n\nCode of Project B in Version Control (git, subversion, ...)" <<DWHBgit>> as DWHBgit
}

person "==DHW Developer\n<size:10>[Person]</size>\n\nDeveloper of DataHandwerk Toolkit" <<DHWDeveloper>> as DHWDeveloper
rectangle "==DataHandwerk Development\n<size:10>[Software System]</size>" <<DataHandwerkDevelopment>> as DataHandwerkDevelopment
folder "==DataHandwerk git\n<size:10>[Software System]</size>\n\nCode of DataHandwerk in Version Control" <<DataHandwerkgit>> as DataHandwerkgit

DHWDeveloper .[#707070,thickness=2].> DataHandwerkDevelopment : "<color:#707070>uses for testing and development"
DHWDeveloper .[#707070,thickness=2].> DataHandwerkgit : "<color:#707070>uses"
DWHDeveloper .[#707070,thickness=2].> DataHandwerkgit : "<color:#707070>takes code or builds"
DWHDeveloper .[#707070,thickness=2].> DWHBDevelopment : "<color:#707070>developes"
DWHDeveloper .[#707070,thickness=2].> DWHBgit : "<color:#707070>uses"
DeploymentTeam .[#707070,thickness=2].> DWHBgit : "<color:#707070>takes code or builds"
DeploymentTeam .[#707070,thickness=2].> DWHBProduction : "<color:#707070>deployes on production system"
ProjectBDWHUser .[#707070,thickness=2].> DWHBProduction : "<color:#707070>uses"
ProjectBDWHUser .[#707070,thickness=2].> DWHBDevelopment : "<color:#707070>uses"
@enduml