@startuml
title DataHandwerk Development - Containers

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam database<<DataHandwerkDevelopment.DWHdbProjectA>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam database<<DataHandwerkDevelopment.RepositorydbProjectA>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

package "DataHandwerk Development\n[Software System]" <<DataHandwerkDevelopment>> {
  skinparam PackageBorderColor<<DataHandwerkDevelopment>> #444444
  skinparam PackageFontColor<<DataHandwerkDevelopment>> #444444

  database "==Repository db (Project A)\n<size:10>[Container: Database]</size>" <<DataHandwerkDevelopment.RepositorydbProjectA>> as DataHandwerkDevelopment.RepositorydbProjectA
  database "==DWH db (Project A)\n<size:10>[Container: Database]</size>" <<DataHandwerkDevelopment.DWHdbProjectA>> as DataHandwerkDevelopment.DWHdbProjectA
}

@enduml