@startuml(id=DWHBDevelopment-GUI-Component)
title DWH B Development - GUI - Components

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<23>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<24>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam database<<5>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
database "==Repository db (Project B)\n<size:10>[Container: Database]</size>" <<5>> as 5
package "GUI\n[Container: GUI]" {
  rectangle "==CRUD GUI\n<size:10>[Component: ?]</size>\n\nCRUD - Create, Read, Update, Delete" <<24>> as 24
  rectangle "==Visualization GUI\n<size:10>[Component: ?]</size>\n\nVisualization of data lineage (references), real and virtual PK, FK-PK" <<23>> as 23
}
24 .[#707070,thickness=2].> 5 : ""
@enduml