@startuml(id=DataHandwerkDevelopment-Container)
title DataHandwerk Development - Containers

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam database<<33>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam database<<34>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
package "DataHandwerk Development\n[Software System]" {
  database "==DWH db (Project A)\n<size:10>[Container: Database]</size>" <<34>> as 34
  database "==Repository db (Project A)\n<size:10>[Container: Database]</size>" <<33>> as 33
}
@enduml