@startuml
title DWH B git - System Context

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam folder<<DWHBgit>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<DWHDeveloper>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<DeploymentTeam>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

package "Customer" <<enterprise>> {
  skinparam PackageBorderColor<<enterprise>> #444444
  skinparam PackageFontColor<<enterprise>> #444444

  person "==DWH Developer\n<size:10>[Person]</size>\n\nDeveloper of some DWH" <<DWHDeveloper>> as DWHDeveloper
  person "==Deployment Team\n<size:10>[Person]</size>" <<DeploymentTeam>> as DeploymentTeam
  folder "==DWH B git\n<size:10>[Software System]</size>\n\nCode of Project B in Version Control (git, subversion, ...)" <<DWHBgit>> as DWHBgit
}


DWHDeveloper .[#707070,thickness=2].> DWHBgit : "<color:#707070>uses"
DeploymentTeam .[#707070,thickness=2].> DWHBgit : "<color:#707070>takes code or builds"
@enduml