@startuml
title DWH B Production - System Context

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<DWHBProduction>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<DeploymentTeam>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam person<<ProjectBDWHUser>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

package "Customer" <<enterprise>> {
  skinparam PackageBorderColor<<enterprise>> #444444
  skinparam PackageFontColor<<enterprise>> #444444

  person "==Deployment Team\n<size:10>[Person]</size>" <<DeploymentTeam>> as DeploymentTeam
  person "==Project B DWH User\n<size:10>[Person]</size>\n\nuser of DWH (Project B)" <<ProjectBDWHUser>> as ProjectBDWHUser
  rectangle "==DWH B Production\n<size:10>[Software System]</size>" <<DWHBProduction>> as DWHBProduction
}


DeploymentTeam .[#707070,thickness=2].> DWHBProduction : "<color:#707070>deployes on production system"
ProjectBDWHUser .[#707070,thickness=2].> DWHBProduction : "<color:#707070>uses"
@enduml