@startuml(id=DataHandwerkgit-SystemContext)
title DataHandwerk git - System Context

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<1>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam folder<<35>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
skinparam rectangle<<31>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #dddddd
}
rectangle "==DHW Developer\n<size:10>[Person]</size>\n\nDeveloper of DataHandwerk Toolkit" <<31>> as 31
folder "==DataHandwerk git\n<size:10>[Software System]</size>\n\nCode of DataHandwerk in Version Control" <<35>> as 35
package "Customer" {
  rectangle "==DWH Developer\n<size:10>[Person]</size>\n\nDeveloper of some DWH" <<1>> as 1
}
31 .[#707070,thickness=2].> 35 : "uses"
1 .[#707070,thickness=2].> 35 : "takes code or builds"
@enduml