= Persistence generator

IMPORTANT: The procedure xref:sqldb:repo.usp_persistence_set.adoc[] is not called automatically. If a persistence is to be created or changed, this must be done manually!

IMPORTANT: Before you execute the procedure xref:sqldb:repo.usp_persistence_set.adoc[], check, if the persistence source should have a real or virtual PK. Some persistence actions are not available, if no PK is defined in the source. Execute xref:sqldb:repo.usp_index_virtual_set.adoc[] to define virtual PK, whenever this is possible.

TIP: If SSMS is used to retrieve the generated code, then the xref:user-guide:ssms-configuration.adoc[] should be checked and adjusted.

== Persistence definition

use xref:sqldb:repo.usp_persistence_set.adoc[] to define (or change) a persistence.

====
[source,sql]
----
include::sqldb:partial$repo.usp_persistence_set.adoc[tag=exampleusage]
----
====

* This will insert new required entries into xref:sqldb:repo.repoobjectcolumn.adoc[]. 
* It will update properties for entries of existing target columns
* It will not delete entries for columns in the persistence target, which have been added to the persistence table definition (it is possible to have additional columns, for example calculated columns or just additional columns to input some data independently of the source)

In order for the persistence to be updated correctly, one (or sometimes two) execution(s) of xref:sqldb:repo.usp_main.adoc[] are required:

* the new or changed columns have to be synchronized between DWH and repository database
* xref:sqldb:repo.repoobjectcolumn.adoc#column-RepoObjectColumn_column_id[repo.RepoObjectColumn.RepoObjectColumn_column_id] must get a value, this happens depending on the fulfilled prerequisites already in the first or only in the second pass

The SQL code for the persistence target table is located in xref:sqldb:repo.repoobject_sqlcreatetable.adoc#column-SqlCreateTable[repo.RepoObject_SqlCreateTable.SqlCreateTable]

== Persistence procedure code generation

DataHandwerk provides the code for a persistence stored procedure for each managed persistence. The code of this procedure will change depending on:

* the columns of the persistence source
* settings in xref:sqldb:repo.repoobject_persistence.adoc[]

The xref:user-guide:persistence-generator.adoc[] is used to create the persistence procedure code. Depending on changed settings in xref:sqldb:repo.repoobject_persistence.adoc[] the generated code will change. After changing settings it is required to execute xref:sqldb:repo.usp_main.adoc[]

The final code of the procedure is available in xref:sqldb:uspgenerator.generatorusp_sqlusp.adoc#column-SqlUsp[uspgenerator.GeneratorUsp_SqlUsp.SqlUsp]

== change exisisting persistence

IMPORTANT: A change script for existing tables is not yet created! You need to compare the generated code and the existing code!

TIP: You could use the generated code in a Visual Studio database project and deploy it to the database using Schema compare.

[WARNING]
--
Currently, it could be tricky to rename columns in persistence source and to promote this into the target. It still needs some testing and investigation to suggest the best practice. It looks like you should:

* start to change the source
* `EXEC repo.[usp_persistence_set]`
* check [repo].[RepoObjectColumn_gross]
* `EXEC [repo].[usp_main]`
* check [repo].[RepoObjectColumn_gross]
* maybe you need to edit the content of the column [persistence_source_RepoObjectColumn_guid]
--

[WARNING]
--
It can be very difficult to change the design of graph tables in SQL Server, especially when https://docs.microsoft.com/en-us/sql/relational-databases/tables/graph-edge-constraints?view=sql-server-ver15[Edge Constraints] are used. The code created by SSMS or by Visual Studio code is then unusable and does not work. And Azure Data Studio it is even worse.
--

// New source columns have been added for persistence source. Why are these columns not updated in 
// [repo].[RepoObject_SqlCreateTable].[SqlCreateTable]?

// Columns are defined in [repo].[RepoObject_ColumnList].CreateColumnList

// [repo].[usp_persistence_set] 

// New columns have been added for a persistence target. And why they are not included into 
// by the persistence?

// tag::to-do[]
// end::to-do[]
