= SqlParse to detect column references

include::user-guide:page$sqlparser.adoc[tag=shortdescription]

see more details (and how to run): xref:user-guide:sqlparser.adoc[]

After parsing, the results are available in xref:sqldb:sqlparse.RepoObject_SqlModules.adoc[]

Some views and persistences on top of this table are build to extract column references: +
You need to execute 2 persistence procedures after each import of the parsing results. +
It's a good idea to also execute `repo.usp_main` to use the parsed content.

[source,sql]
----
EXEC [sqlparse].[usp_sqlparse]

Exec repo.usp_main;
----

Finally, column references are available in xref:sqldb:reference.RepoObjectColumn_reference_SqlModules.adoc[]

They will be combined with other column reference sources in xref:sqldb:reference.RepoObjectColumn_reference_union.adoc[].

xref:user-guide:properties-inheritance.adoc[] and xref:user-guide:documentation-generator.adoc[] are also based on column references.

// tag::to-do[]
// end::to-do[]
