= SqlParse to detect column references

include::manual:page$sqlparser.adoc[tag=shortdescription]

see more details (and how to run): xref:manual:sqlparser.adoc[]

After parsing, the results are available in xref:sqldb:sqlparse.RepoObject_SqlModules.adoc[]

Some views and persistences on top of this table are build to extract column references: +
You need to execute 2 persistence procedures after each import of the parsing results. +
It's a good idea to also execute `repo.usp_main` to use the parsed content.

[source,sql]
----
Exec sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T;
Exec sqlparse.usp_PERSIST_RepoObject_SqlModules_61_SelectIdentifier_Union_T;

Exec repo.usp_main;
----

Finally, column references are available in xref:sqldb:reference.RepoObjectColumn_reference_SqlModules.adoc[]

They will be combined with other column reference sources in xref:sqldb:reference.RepoObjectColumn_reference_union.adoc[].

xref:manual:properties-inheritance.adoc[] and xref:manual:documentation-generator.adoc[] are also based on column references.

// tag::to-do[]
// end::to-do[]
