'Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObject_ReferenceTree_referenced << V >> {
  **RepoObject_guid** : uniqueidentifier
  **Referenced_Depth** : int
  **Referencing_Depth** : int
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObject_ReferenceTree_referencing << V >> {
  **RepoObject_guid** : uniqueidentifier
  **Referenced_Depth** : int
  **Referencing_Depth** : int
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObjectProperty_Collect_source_ROGross << V >> {
}

entity docs.AntoraIndexSemanticgroup << V >> {
  **IndexSemanticGroup** : nvarchar(512)
}

entity docs.AntoraIndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : nvarchar(512)
  **IndexPatternColumnDatatype** : nvarchar(4000)
}

entity docs.AntoraNavListPage_by_type << V >> {
  **type** : nvarchar(128)
}

entity docs.AntoraNavListRepoObject_by_schema << V >> {
  * **RepoObject_schema_name** : nvarchar(128)
}

entity docs.AntoraNavListRepoObject_by_schema_type << V >> {
  * **RepoObject_schema_name** : nvarchar(128)
  **type** : char(2)
}

entity docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : char(2)
}

entity docs.AntoraPage_IndexSemanticGroup << V >> {
  * **page_content** : nvarchar(max)
}

entity docs.AntoraPage_ObjectBySchema << V >> {
}

entity docs.AntoraPage_ObjectByType << V >> {
}

entity docs.AntoraTemplate_examples << V >> {
}

entity docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
}

entity docs.RepoObject_Adoc << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Adoc_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_IndexList_T << U >> {
  **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_OutputFilter << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml_Entity << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml_Entity_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.usp_AntoraExport << P >> {
}

entity docs.usp_AntoraExport_navigation << P >> {
}

entity docs.usp_AntoraExport_ObjectPage << P >> {
}

entity docs.usp_AntoraExport_ObjectPartialProperties << P >> {
}

entity docs.usp_AntoraExport_ObjectPuml << P >> {
}

entity docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
}

entity docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
}

entity docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
}

entity docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
}

entity graph.Index << U >> {
}

entity graph.Index_S << V >> {
  * **Index_guid** : uniqueidentifier
}

entity graph.usp_PERSIST_Index << P >> {
}

entity repo.ExtendedProperty_Repo2Sys_level1 << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  * **property_name** : nvarchar(128)
}

entity repo.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  **level2type** : varchar(10)
  * **level2name** : nvarchar(128)
  * **property_name** : nvarchar(128)
}

entity repo.ExtendedProperty_Repo2Sys_level2_Union << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  **level2type** : nvarchar(10)
  * **level2name** : nvarchar(128)
  * **property_name** : nvarchar(128)
}

entity repo.ForeignKey_gross << V >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_Indexes << V >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_virtual_Indexes << V >> {
  * **ForeignKey_guid** : uniqueidentifier
}

entity repo.fs_get_RepoObjectProperty_nvarchar << FN >> {
}

entity repo.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
}

entity repo.Index_gross << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Index_virtual_ForUpdate << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Match_RepoObject_referenced_UspPersistence << V >> {
  **FirstNode** : uniqueidentifier
  **LastNode** : uniqueidentifier
}

entity repo.PropertyName_RepoObject << V >> {
  * **property_name** : nvarchar(128)
}

entity repo.Reference_UspPersistence << V >> {
  **referenced_usp_RepoObject_guid** : uniqueidentifier
  **referencing_usp_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_ReferenceTree << V >> {
  **RepoObject_guid** : uniqueidentifier
  **Referenced_Depth** : int
  **Referencing_Depth** : int
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : uniqueidentifier
  **included_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_SqlCreateTable << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObjectProperty << U >> {
  * **RepoObjectProperty_id** : int
}

entity repo.RepoObjectProperty_cross << V >> {
}

entity repo.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **property_name** : nvarchar(128)
}

entity repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
}

entity repo.RepoObjectProperty_sys_repo << V >> {
}

entity repo.usp_Index_finish << P >> {
}

entity repo.usp_Index_ForeignKey << P >> {
}

entity repo.usp_index_inheritance << P >> {
}

entity repo.usp_Index_virtual_set << P >> {
}

entity repo.usp_main << P >> {
}

entity repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
}

entity repo.usp_RepoObject_Inheritance << P >> {
}

entity repo.usp_RepoObject_update_SysObjectQueryPlan << P >> {
}

entity repo.usp_RepoObjectProperty_collect << P >> {
}

entity repo.usp_RepoObjectProperty_set << P >> {
}

entity repo.usp_RepoObjectSource_FirstResultSet << P >> {
}

entity repo.usp_RepoObjectSource_QueryPlan << P >> {
}

entity repo.usp_sync_ExtendedProperties_Repo2Sys_Delete << P >> {
}

entity repo.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate << P >> {
}

entity repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
}

entity uspgenerator.GeneratorUspStep_Persistence << V >> {
  * **usp_id** : int
}

entity uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint << V >> {
  * **usp_id** : int
}

entity uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
}

 <.. repo.usp_RepoObjectProperty_collect
docs.AntoraIndexSemanticgroup <.. docs.AntoraPage_IndexSemanticGroup
docs.AntoraIndexSemanticgroupPatterndatatype <.. docs.AntoraIndexSemanticgroup
docs.AntoraNavListRepoObject_by_schema <.. docs.AntoraPage_ObjectBySchema
docs.AntoraNavListRepoObject_by_schema <.. docs.usp_AntoraExport_navigation
docs.AntoraNavListRepoObject_by_schema_type <.. docs.usp_AntoraExport_navigation
docs.AntoraNavListRepoObject_by_type <.. docs.usp_AntoraExport_navigation
docs.AntoraNavListRepoObject_by_type <.. docs.AntoraPage_ObjectByType
docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.RepoObject_OutputFilter <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter <.. docs.usp_AntoraExport_ObjectPuml
docs.RepoObject_OutputFilter <.. docs.AntoraNavListPage_by_type
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.usp_AntoraExport_navigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialProperties <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
graph.Index <.. graph.usp_PERSIST_Index
graph.Index_S <.. graph.usp_PERSIST_Index
graph.Index_S <.. graph.Index
graph.usp_PERSIST_Index <.. repo.usp_Index_finish
repo.ExtendedProperty_Repo2Sys_level1 <.. repo.usp_sync_ExtendedProperties_Repo2Sys_Delete
repo.ExtendedProperty_Repo2Sys_level1 <.. repo.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
repo.ExtendedProperty_Repo2Sys_level2_RepoObject <.. repo.ExtendedProperty_Repo2Sys_level2_Union
repo.ExtendedProperty_Repo2Sys_level2_Union <.. repo.usp_sync_ExtendedProperties_Repo2Sys_InsertUpdate
repo.ExtendedProperty_Repo2Sys_level2_Union <.. repo.usp_sync_ExtendedProperties_Repo2Sys_Delete
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.fs_get_RepoObjectProperty_nvarchar <.. repo.RepoObject_gross
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_gross <.. docs.AntoraIndexSemanticgroupPatterndatatype
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_gross <.. graph.Index_S
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.Match_RepoObject_referenced_UspPersistence <.. repo.Reference_UspPersistence
repo.Match_RepoObject_referenced_UspPersistence <.. repo.usp_main
repo.PropertyName_RepoObject <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.PropertyName_RepoObject <.. repo.RepoObjectProperty_cross
repo.PropertyName_RepoObject <.. docs.AntoraTemplate_examples
repo.RepoObject_gross <.. 
repo.RepoObject_gross <.. 
repo.RepoObject_gross <.. 
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross <.. docs.RepoObject_Plantuml
repo.RepoObject_gross <.. docs.RepoObject_Adoc
repo.RepoObject_gross <.. repo.RepoObject_ReferenceTree
repo.RepoObject_gross <.. repo.Match_RepoObject_referenced_UspPersistence
repo.RepoObject_gross <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. repo.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. repo.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_SqlCreateTable <.. repo.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectProperty <.. docs.RepoObject_Adoc
repo.RepoObjectProperty <.. repo.fs_get_RepoObjectProperty_nvarchar
repo.RepoObjectProperty <.. repo.ExtendedProperty_Repo2Sys_level1
repo.RepoObjectProperty <.. repo.ExtendedProperty_Repo2Sys_level2_RepoObject
repo.RepoObjectProperty <.. repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
repo.RepoObjectProperty <.. repo.PropertyName_RepoObject
repo.RepoObjectProperty <.. repo.usp_RepoObject_Inheritance
repo.RepoObjectProperty <.. repo.RepoObjectProperty_sys_repo
repo.RepoObjectProperty <.. repo.usp_RepoObjectProperty_set
repo.RepoObjectProperty <.. repo.usp_RepoObjectProperty_collect
repo.RepoObjectProperty <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectProperty_cross <.. docs.RepoObject_Adoc
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition <.. repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition
repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition <.. repo.usp_RepoObject_Inheritance
repo.RepoObjectProperty_sys_repo <.. repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_RepoObject_Inheritance <.. repo.usp_main
repo.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
repo.usp_RepoObjectProperty_collect <.. docs.usp_AntoraExport
repo.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
repo.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
uspgenerator.GeneratorUspStep_Persistence <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
