'Left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObjectColumnProperty_ForUpdate << V >> {
}

entity repo.RepoObject_ReferenceTree_referenced << V >> {
  **RepoObject_guid** : uniqueidentifier
  **Referenced_Depth** : int
  **Referencing_Depth** : int
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObject_ReferenceTree_referencing << V >> {
  **RepoObject_guid** : uniqueidentifier
  **Referenced_Depth** : int
  **Referencing_Depth** : int
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObjectProperty_Collect_source_ROGross << V >> {
}

entity docs.AntoraIndexSemanticgroup << V >> {
  **IndexSemanticGroup** : nvarchar(512)
}

entity docs.AntoraIndexSemanticgroupPatterndatatype << V >> {
  **IndexSemanticGroup** : nvarchar(512)
  **IndexPatternColumnDatatype** : nvarchar(4000)
}

entity docs.AntoraNavListPage_by_type << V >> {
  **type** : nvarchar(128)
}

entity docs.AntoraNavListRepoObject_by_schema << V >> {
  * **RepoObject_schema_name** : nvarchar(128)
}

entity docs.AntoraNavListRepoObject_by_schema_type << V >> {
  * **RepoObject_schema_name** : nvarchar(128)
  **type** : char(2)
}

entity docs.AntoraNavListRepoObject_by_type << V >> {
  **type** : char(2)
}

entity docs.AntoraPage_IndexSemanticGroup << V >> {
  * **page_content** : nvarchar(max)
}

entity docs.AntoraPage_ObjectBySchema << V >> {
}

entity docs.AntoraPage_ObjectByType << V >> {
}

entity docs.ForeignKey_RelationScript << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
}

entity docs.RepoObject_Adoc << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Adoc_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_ColumnList << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_IndexList << V >> {
  **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_IndexList_T << U >> {
  **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_OutputFilter << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml_ColRefList << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml_Entity << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml_Entity_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_PlantUml_FkRefList << V >> {
  **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_PlantUml_PumlEntityFkList << V >> {
  **RepoObject_guid** : uniqueidentifier
}

entity docs.RepoObject_Plantuml_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity docs.usp_AntoraExport << P >> {
}

entity docs.usp_AntoraExport_navigation << P >> {
}

entity docs.usp_AntoraExport_ObjectPage << P >> {
}

entity docs.usp_AntoraExport_ObjectPartialProperties << P >> {
}

entity docs.usp_AntoraExport_ObjectPuml << P >> {
}

entity docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
}

entity docs.usp_PERSIST_RepoObject_IndexList_T << P >> {
}

entity docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
}

entity docs.usp_PERSIST_RepoObject_Plantuml_T << P >> {
}

entity docs.visjs_EdgeList_object_test01 << V >> {
}

entity graph.Index << U >> {
}

entity graph.Index_S << V >> {
  * **Index_guid** : uniqueidentifier
}

entity graph.RepoObjectColumn << U >> {
}

entity graph.RepoObjectColumn_ReferencingReferenced << V >> {
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity graph.RepoObjectColumn_S << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity graph.usp_PERSIST_Index << P >> {
}

entity graph.usp_PERSIST_RepoObjectColumn << P >> {
}

entity repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  * **index_guid** : uniqueidentifier
  * **index_column_id** : int
}

entity repo.ForeignKey_gross << V >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_Indexes << V >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_Indexes_union << V >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_Indexes_union_T << U >> {
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_IndexPattern << V >> {
  * **constraint_object_id** : int
  **ForeignKey_guid** : uniqueidentifier
}

entity repo.ForeignKey_virtual_Indexes << V >> {
  * **ForeignKey_guid** : uniqueidentifier
}

entity repo.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
}

entity repo.ftv_RepoObject_DbmlColumnRelation << IF >> {
}

entity repo.ftv_RepoObjectColumn_ReferenceTree << IF >> {
}

entity repo.Index_ColumList << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_gross << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.Index_IndexPattern << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.Index_SqlConstraint_PkUq << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_union << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_unique_IndexPatternColumnGuid << V >> {
  **index_guid** : uniqueidentifier
}

entity repo.Index_virtual_ForUpdate << V >> {
  * **index_guid** : uniqueidentifier
}

entity repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  **RowNumberInReferencing** : bigint
}

entity repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  **RowNumberInReferencing** : bigint
}

entity repo.IndexColumn_union << V >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
}

entity repo.IndexColumn_virtual_referenced_setpoint << V >> {
  * **index_guid** : uniqueidentifier
  * **index_column_id** : int
}

entity repo.IndexReferencedReferencing << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.Match_RepoObject_referenced_UspPersistence << V >> {
  **FirstNode** : uniqueidentifier
  **LastNode** : uniqueidentifier
}

entity repo.Reference_UspPersistence << V >> {
  **referenced_usp_RepoObject_guid** : uniqueidentifier
  **referencing_usp_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_ColumnList << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_reference_SqlExpressionDependencies << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_ReferenceTree << V >> {
  **RepoObject_guid** : uniqueidentifier
  **Referenced_Depth** : int
  **Referencing_Depth** : int
  **Referenced_guid** : uniqueidentifier
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : uniqueidentifier
  **included_RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObject_SqlCreateTable << V >> {
  * **RepoObject_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_gross << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_MissingSource_TypeV << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_reference_BySamePredecessors << V >> {
}

entity repo.RepoObjectColumn_reference_FirstResultSet << V >> {
}

entity repo.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : int
  **referencing_minor_id** : int
  **referenced_id** : int
  **referenced_minor_id** : int
}

entity repo.RepoObjectColumn_reference_SqlExpressionDependencies << V >> {
  * **referencing_id** : int
  * **referencing_minor_id** : int
  **referenced_id** : int
  * **referenced_minor_id** : int
}

entity repo.RepoObjectColumn_reference_union << V >> {
}

entity repo.RepoObjectColumn_ReferencedList << V >> {
  **Referencing_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_ReferenceTree << V >> {
}

entity repo.RepoObjectColumn_ReferencingList << V >> {
  **Referenced_guid** : uniqueidentifier
}

entity repo.RepoObjectColumn_RelationScript << V >> {
}

entity repo.SysColumn_RepoObjectColumn_via_guid << V >> {
}

entity repo.SysColumn_RepoObjectColumn_via_name << V >> {
}

entity repo.SysObjectColumn_QueryPlanExpression << V >> {
}

entity repo.usp_Index_finish << P >> {
}

entity repo.usp_Index_ForeignKey << P >> {
}

entity repo.usp_index_inheritance << P >> {
}

entity repo.usp_Index_Settings << P >> {
}

entity repo.usp_Index_virtual_set << P >> {
}

entity repo.usp_main << P >> {
}

entity repo.usp_PERSIST_ForeignKey_Indexes_union_T << P >> {
}

entity repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
}

entity repo.usp_persistence_set << P >> {
}

entity repo.usp_RepoObject_update_SysObjectQueryPlan << P >> {
}

entity repo.usp_RepoObjectProperty_collect << P >> {
}

entity repo.usp_RepoObjectSource_FirstResultSet << P >> {
}

entity repo.usp_RepoObjectSource_QueryPlan << P >> {
}

entity repo.usp_sync_guid << P >> {
}

entity repo.usp_sync_guid_RepoObjectColumn << P >> {
}

entity repo_sys.ForeignKeyColumn << V >> {
}

entity repo_sys.IndexColumn_unique << V >> {
}

entity repo_sys.sql_expression_dependencies << V >> {
}

entity repo_sys.SysColumn << V >> {
}

entity sys_dwh.computed_columns << SN >> {
}

entity uspgenerator.GeneratorUspStep_Persistence << V >> {
  * **usp_id** : int
}

entity uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint << V >> {
  * **usp_id** : int
}

entity uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
}

 <.. repo.usp_RepoObjectProperty_collect
docs.AntoraIndexSemanticgroup <.. docs.AntoraPage_IndexSemanticGroup
docs.AntoraIndexSemanticgroupPatterndatatype <.. docs.AntoraIndexSemanticgroup
docs.AntoraNavListRepoObject_by_schema <.. docs.AntoraPage_ObjectBySchema
docs.AntoraNavListRepoObject_by_schema <.. docs.usp_AntoraExport_navigation
docs.AntoraNavListRepoObject_by_schema_type <.. docs.usp_AntoraExport_navigation
docs.AntoraNavListRepoObject_by_type <.. docs.usp_AntoraExport_navigation
docs.AntoraNavListRepoObject_by_type <.. docs.AntoraPage_ObjectByType
docs.ftv_RepoObject_Reference_PlantUml_EntityRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_ColumnList <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_ColumnList <.. docs.RepoObject_Adoc
docs.RepoObject_IndexList <.. docs.RepoObject_IndexList_T
docs.RepoObject_IndexList <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.usp_PERSIST_RepoObject_IndexList_T
docs.RepoObject_IndexList_T <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_IndexList_T <.. docs.RepoObject_Adoc
docs.RepoObject_OutputFilter <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.RepoObject_OutputFilter <.. docs.AntoraNavListRepoObject_by_type
docs.RepoObject_OutputFilter <.. docs.AntoraNavListRepoObject_by_schema
docs.RepoObject_OutputFilter <.. docs.AntoraNavListRepoObject_by_schema_type
docs.RepoObject_OutputFilter <.. docs.usp_AntoraExport_ObjectPage
docs.RepoObject_OutputFilter <.. docs.usp_AntoraExport_ObjectPuml
docs.RepoObject_OutputFilter <.. docs.RepoObject_Plantuml_Entity
docs.RepoObject_OutputFilter <.. docs.AntoraNavListPage_by_type
docs.RepoObject_Plantuml <.. docs.RepoObject_Plantuml_T
docs.RepoObject_Plantuml <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.RepoObject_Plantuml_ColRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_Entity <.. docs.RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.RepoObject_Plantuml_Entity_T <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
docs.RepoObject_Plantuml_Entity_T <.. docs.RepoObject_PlantUml_PumlEntityFkList
docs.RepoObject_PlantUml_FkRefList <.. docs.RepoObject_Plantuml
docs.RepoObject_PlantUml_PumlEntityFkList <.. docs.RepoObject_Plantuml
docs.RepoObject_Plantuml_T <.. docs.usp_PERSIST_RepoObject_Plantuml_T
docs.usp_AntoraExport_navigation <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPage <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPartialProperties <.. docs.usp_AntoraExport
docs.usp_AntoraExport_ObjectPuml <.. docs.usp_AntoraExport
docs.usp_PERSIST_RepoObject_Adoc_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_IndexList_T <.. docs.usp_AntoraExport_ObjectPartialProperties
docs.usp_PERSIST_RepoObject_Plantuml_Entity_T <.. docs.usp_AntoraExport_ObjectPuml
docs.usp_PERSIST_RepoObject_Plantuml_T <.. docs.usp_AntoraExport_ObjectPuml
graph.Index <.. graph.usp_PERSIST_Index
graph.Index_S <.. graph.usp_PERSIST_Index
graph.Index_S <.. graph.Index
graph.RepoObjectColumn <.. docs.RepoObject_Plantuml_ColRefList
graph.RepoObjectColumn <.. graph.RepoObjectColumn_ReferencingReferenced
graph.RepoObjectColumn <.. graph.usp_PERSIST_RepoObjectColumn
graph.RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
graph.RepoObjectColumn <.. repo.usp_main
graph.RepoObjectColumn_ReferencingReferenced <.. repo.ftv_RepoObjectColumn_ReferenceTree
graph.RepoObjectColumn_ReferencingReferenced <.. repo.ftv_RepoObject_DbmlColumnRelation
graph.RepoObjectColumn_ReferencingReferenced <.. repo.RepoObjectColumn_ReferencedList
graph.RepoObjectColumn_ReferencingReferenced <.. repo.RepoObjectColumn_ReferencingList
graph.RepoObjectColumn_S <.. graph.usp_PERSIST_RepoObjectColumn
graph.RepoObjectColumn_S <.. graph.RepoObjectColumn
graph.RepoObjectColumn_S <.. repo.usp_sync_guid_RepoObjectColumn
graph.usp_PERSIST_Index <.. repo.usp_Index_finish
graph.usp_PERSIST_RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo.ForeignKey_gross <.. docs.RepoObject_IndexList
repo.ForeignKey_Indexes <.. repo.usp_Index_ForeignKey
repo.ForeignKey_Indexes <.. repo.ForeignKey_Indexes_union
repo.ForeignKey_Indexes_union <.. repo.ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. repo.usp_PERSIST_ForeignKey_Indexes_union_T
repo.ForeignKey_Indexes_union_T <.. docs.RepoObject_PlantUml_FkRefList
repo.ForeignKey_Indexes_union_T <.. repo.RepoObject_related_FK_union
repo.ForeignKey_Indexes_union_T <.. repo.ForeignKey_gross
repo.ForeignKey_Indexes_union_T <.. repo.usp_Index_finish
repo.ForeignKey_Indexes_union_T <.. docs.ForeignKey_RelationScript
repo.ForeignKey_IndexPattern <.. repo.ForeignKey_Indexes
repo.ForeignKey_virtual_Indexes <.. repo.ForeignKey_Indexes_union
repo.ftv_RepoObjectColumn_ReferenceTree <.. repo.RepoObjectColumn_ReferenceTree
repo.Index_ColumList <.. repo.Index_SqlConstraint_PkUq
repo.Index_ColumList <.. uspgenerator.GeneratorUspStep_Persistence
repo.Index_ColumList <.. repo.Index_gross
repo.Index_gross <.. repo.RepoObject_SqlCreateTable
repo.Index_gross <.. repo.usp_Index_finish
repo.Index_gross <.. repo.ForeignKey_virtual_Indexes
repo.Index_gross <.. repo.ForeignKey_Indexes
repo.Index_gross <.. repo.usp_index_inheritance
repo.Index_gross <.. repo.usp_Index_virtual_set
repo.Index_gross <.. repo.ForeignKey_gross
repo.Index_gross <.. docs.AntoraIndexSemanticgroupPatterndatatype
repo.Index_gross <.. graph.Index_S
repo.Index_gross <.. docs.RepoObject_IndexList
repo.Index_IndexPattern <.. repo.usp_Index_Settings
repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.Index_SqlConstraint_PkUq <.. repo.RepoObject_SqlCreateTable
repo.Index_union <.. repo.Index_gross
repo.Index_union <.. repo.Index_SqlConstraint_PkUq
repo.Index_union <.. repo.IndexReferencedReferencing
repo.Index_union <.. repo.usp_Index_finish
repo.Index_unique_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_union <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_union <.. repo.Index_ColumList
repo.IndexColumn_union <.. repo.RepoObjectColumn_gross
repo.IndexColumn_union <.. repo.Index_IndexPattern
repo.IndexColumn_virtual_referenced_setpoint <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.IndexColumn_virtual_referenced_setpoint <.. repo.usp_index_inheritance
repo.IndexReferencedReferencing <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_index_inheritance
repo.Match_RepoObject_referenced_UspPersistence <.. repo.usp_main
repo.Match_RepoObject_referenced_UspPersistence <.. repo.Reference_UspPersistence
repo.RepoObject_ColumnList <.. repo.RepoObject_gross
repo.RepoObject_ColumnList <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross <.. repo.Index_gross
repo.RepoObject_gross <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint
repo.RepoObject_gross <.. uspgenerator.GeneratorUspStep_Persistence
repo.RepoObject_gross <.. repo.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. repo.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
repo.RepoObject_gross <.. repo.Match_RepoObject_referenced_UspPersistence
repo.RepoObject_gross <.. repo.RepoObject_ReferenceTree
repo.RepoObject_gross <.. docs.RepoObject_Adoc
repo.RepoObject_gross <.. docs.RepoObject_OutputFilter
repo.RepoObject_gross <.. docs.RepoObject_Plantuml
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross <.. 
repo.RepoObject_gross <.. 
repo.RepoObject_gross <.. 
repo.RepoObject_reference_SqlExpressionDependencies <.. docs.visjs_EdgeList_object_test01
repo.RepoObject_reference_SqlExpressionDependencies <.. repo.RepoObject_reference_union
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_SqlExpressionDependencies
repo.RepoObject_reference_union <.. repo.IndexReferencedReferencing
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_BySamePredecessors
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_FirstResultSet
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObject_reference_union <.. repo.usp_main
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_PumlEntityFkList
repo.RepoObject_related_FK_union <.. docs.RepoObject_PlantUml_FkRefList
repo.RepoObject_SqlCreateTable <.. repo.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross <.. 
repo.RepoObjectColumn_gross <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_reference_FirstResultSet <.. repo.RepoObjectColumn_reference_BySamePredecessors
repo.RepoObjectColumn_reference_QueryPlan <.. repo.SysObjectColumn_QueryPlanExpression
repo.RepoObjectColumn_reference_SqlExpressionDependencies <.. repo.RepoObjectColumn_reference_union
repo.RepoObjectColumn_reference_union <.. repo.RepoObjectColumn_MissingSource_TypeV
repo.RepoObjectColumn_reference_union <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing
repo.RepoObjectColumn_reference_union <.. repo.RepoObjectColumn_RelationScript
repo.RepoObjectColumn_reference_union <.. repo.usp_main
repo.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_ReferenceTree <.. repo.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_RelationScript <.. repo.ftv_RepoObject_ColumReferenceRepoObject
repo.SysColumn_RepoObjectColumn_via_guid <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.SysObjectColumn_QueryPlanExpression <.. repo.usp_RepoObjectSource_QueryPlan
repo.usp_Index_finish <.. repo.usp_index_inheritance
repo.usp_Index_finish <.. repo.usp_Index_ForeignKey
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.usp_Index_virtual_set <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_ForeignKey_Indexes_union_T <.. repo.usp_Index_ForeignKey
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
repo.usp_RepoObjectProperty_collect <.. docs.usp_AntoraExport
repo.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
repo.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_persistence_set
repo.usp_sync_guid <.. repo.usp_main
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo_sys.ForeignKeyColumn <.. repo.ForeignKey_IndexPattern
repo_sys.IndexColumn_unique <.. repo.Index_unique_IndexPatternColumnGuid
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.sql_expression_dependencies <.. repo.RepoObjectColumn_reference_SqlExpressionDependencies
repo_sys.sql_expression_dependencies <.. repo.RepoObject_reference_SqlExpressionDependencies
repo_sys.SysColumn <.. repo_sys.sql_expression_dependencies
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.SysColumn <.. repo_sys.ForeignKeyColumn
sys_dwh.computed_columns <.. repo_sys.SysColumn
uspgenerator.GeneratorUspStep_Persistence <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep_Persistence_IsInactive_setpoint <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main
