left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.fs_dwh_database_name << FN >> {
  --
}

entity config.fs_get_parameter_value << FN >> {
  --
}

entity config.ftv_dwh_database << IF >> {
  --
  dwh_database_id : smallint
  dwh_database_name : nvarchar(128)
}

entity config.ftv_get_parameter_value << IF >> {
  --
  Parameter_value__result_nvarchar : nvarchar(4000)
}

entity config.Parameter << U >> {
  * **Parameter_name** : varchar(100)
  * **sub_Parameter** : nvarchar(128)
  --
  Parameter_default_value : sql_variant
  Parameter_desciption : nvarchar(1000)
  Parameter_value : sql_variant
  {abstract} Parameter_value__result_int : int
  {abstract} Parameter_value__result_nvarchar : nvarchar(4000)
}

entity config.usp_init_parameter << P >> {
  --
}

entity config.usp_parameter_set << P >> {
  --
}

entity docs.usp_AntoraExport_ObjectPageTemplate << P >> {
  --
}

entity repo.PropertyName_RepoObject << V >> {
  * **property_name** : nvarchar(128)
  --
}

entity repo.PropertyName_RepoObjectColumn << V >> {
  * **property_name** : nvarchar(128)
  --
}

entity repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : int
  par_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  par_InheritanceDefinition : nvarchar(4000)
  par_InheritanceType : int
  * property_name : nvarchar(128)
  property_value : sql_variant
  * RepoObjectColumn_guid : uniqueidentifier
  * RepoObjectColumn_name : nvarchar(128)
  roc_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  roc_InheritanceDefinition : nvarchar(4000)
  roc_InheritanceType : tinyint
  sub_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  sub_InheritanceDefinition : nvarchar(4000)
  sub_InheritanceType : int
}

entity repo.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **property_name** : nvarchar(128)
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : int
  par_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  par_InheritanceDefintion : nvarchar(4000)
  par_InheritanceType : int
  property_value : sql_variant
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_type : char(2)
  ro_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  ro_InheritanceDefinition : nvarchar(4000)
  ro_InheritanceType : tinyint
  sub_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  sub_InheritanceDefintion : nvarchar(4000)
  sub_InheritanceType : int
}

entity repo.usp_persistence_set << P >> {
  --
}

config.fs_get_parameter_value <.. docs.usp_AntoraExport_ObjectPageTemplate
config.Parameter <.. docs.usp_AntoraExport_ObjectPageTemplate
config.Parameter <.. repo.PropertyName_RepoObjectColumn
config.Parameter <.. repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
config.Parameter <.. repo.PropertyName_RepoObject
config.Parameter <.. config.fs_get_parameter_value
config.Parameter <.. config.fs_dwh_database_name
config.Parameter <.. config.ftv_dwh_database
config.Parameter <.. config.ftv_get_parameter_value
config.Parameter <.. config.usp_init_parameter
config.Parameter <.. repo.usp_persistence_set
config.Parameter <.. config.usp_parameter_set
repo.PropertyName_RepoObject <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.PropertyName_RepoObjectColumn <.. repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
config.Parameter::Parameter_value__result_int <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_InheritanceType
config.Parameter::Parameter_value__result_int <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_InheritanceType
config.Parameter::Parameter_value__result_int <-- repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::sub_InheritanceType
config.Parameter::Parameter_value__result_int <-- repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::par_InheritanceType
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::par_Inheritance_StringAggSeparatorSql
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::par_InheritanceDefinition
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::sub_Inheritance_StringAggSeparatorSql
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::sub_InheritanceDefinition
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_Inheritance_StringAggSeparatorSql
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_InheritanceDefintion
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_Inheritance_StringAggSeparatorSql
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_InheritanceDefintion
repo.PropertyName_RepoObject::property_name <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_name
repo.PropertyName_RepoObjectColumn::property_name <-- repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::property_name
