left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.join_type << V >> {
  * **join_type** : varchar(16)
  --
  * join_type_variant : varchar(16)
}

entity sqlparse.RepoObject_SqlModules_41_from << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  --
  children : nvarchar(max)
  class : nvarchar(500)
  identifier_alias : nvarchar(max)
  identifier_name : nvarchar(max)
  * is_from : int
  is_group : bit
  * is_join : int
  is_keyword : bit
  is_whitespace : bit
  join_type : varchar(16)
  Min_RowNumber_From : bigint
  Min_RowNumber_GroupBy : bigint
  Min_RowNumber_Where : bigint
  normalized : nvarchar(max)
  normalized_PatIndex_Select : bigint
  normalized_wo_nolock : nvarchar(max)
  patindex_nolock : bigint
  RowNumber_per_Object : bigint
  SysObject_fullname : nvarchar(261)
}

config.join_type <.. sqlparse.RepoObject_SqlModules_41_from
config.join_type::join_type <-- sqlparse.RepoObject_SqlModules_41_from::join_type
