left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_Adoc << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  * AdocContent : nvarchar(max)
  is_DocsOutput : int
  PropertyCount : int
  RepoObject_fullname : nvarchar(261)
  RepoObject_fullname2 : nvarchar(257)
  RepoObject_schema_name : nvarchar(128)
  SysObject_fullname : nvarchar(261)
  SysObject_fullname2 : nvarchar(257)
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObject_type_name : nvarchar(128)
}

entity docs.RepoObject_Adoc_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  * AdocContent : nvarchar(max)
  is_DocsOutput : int
  PropertyCount : int
  RepoObject_fullname : nvarchar(261)
  RepoObject_fullname2 : nvarchar(257)
  RepoObject_schema_name : nvarchar(128)
  SysObject_fullname : nvarchar(261)
  SysObject_fullname2 : nvarchar(257)
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObject_type_name : nvarchar(128)
}

entity docs.usp_PERSIST_RepoObject_Adoc_T << P >> {
  --
}

docs.RepoObject_Adoc <.. docs.RepoObject_Adoc_T
docs.RepoObject_Adoc <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc_T <.. docs.usp_PERSIST_RepoObject_Adoc_T
docs.RepoObject_Adoc::AdocContent <-- docs.RepoObject_Adoc_T::AdocContent
docs.RepoObject_Adoc::is_DocsOutput <-- docs.RepoObject_Adoc_T::is_DocsOutput
docs.RepoObject_Adoc::PropertyCount <-- docs.RepoObject_Adoc_T::PropertyCount
docs.RepoObject_Adoc::RepoObject_fullname <-- docs.RepoObject_Adoc_T::RepoObject_fullname
docs.RepoObject_Adoc::RepoObject_fullname2 <-- docs.RepoObject_Adoc_T::RepoObject_fullname2
docs.RepoObject_Adoc::RepoObject_guid <-- docs.RepoObject_Adoc_T::RepoObject_guid
docs.RepoObject_Adoc::RepoObject_schema_name <-- docs.RepoObject_Adoc_T::RepoObject_schema_name
docs.RepoObject_Adoc::SysObject_fullname <-- docs.RepoObject_Adoc_T::SysObject_fullname
docs.RepoObject_Adoc::SysObject_fullname2 <-- docs.RepoObject_Adoc_T::SysObject_fullname2
docs.RepoObject_Adoc::SysObject_schema_name <-- docs.RepoObject_Adoc_T::SysObject_schema_name
docs.RepoObject_Adoc::SysObject_type <-- docs.RepoObject_Adoc_T::SysObject_type
docs.RepoObject_Adoc::SysObject_type_name <-- docs.RepoObject_Adoc_T::SysObject_type_name
