left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none

skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}

entity docs.B22A59FA-8061-4E8B-B3C8-E2C3DB891AEA << U >> {
  --
  * RepoObject_guid : uniqueidentifier
  * RepoObject_Plantuml : nvarchar(max)
}

entity docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
  PlantumlEntityList : nvarchar(max)
  Referenced_Depth : int
  Referencing_Depth : int
  ro_guid : uniqueidentifier
}

entity docs.usp_PERSIST_RepoObject_Plantuml_Entity_T << P >> {
  --
}

docs.B22A59FA-8061-4E8B-B3C8-E2C3DB891AEA <.. docs.usp_PERSIST_RepoObject_Plantuml_Entity_T
docs.B22A59FA-8061-4E8B-B3C8-E2C3DB891AEA <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList

