left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity graph.ProcedureInstance << U >> {
  --
  * $node_id_3FC7AA841B564294B72482DE078E7EB2 : nvarchar(1000)
  * graph_id_3091B0F8FDFD4CCBAA8FF240634B29BA : bigint
  * Instance : varchar(500)
  * Procedure_fullname : nvarchar(261)
  * Procedure_RepoObject_guid : uniqueidentifier
}

entity graph.ProcedureInstance_S << V >> {
  * **Procedure_RepoObject_guid** : uniqueidentifier
  * **Instance** : varchar(500)
  --
  * Procedure_fullname : nvarchar(261)
}

entity graph.usp_PERSIST_ProcedureInstance << P >> {
  --
}

entity logs.usp_ExecutionLog_insert << P >> {
  --
}

entity repo.usp_sync_guid_RepoObject << P >> {
  --
}

graph.ProcedureInstance <.. graph.usp_PERSIST_ProcedureInstance
graph.ProcedureInstance_S <.. graph.ProcedureInstance
graph.ProcedureInstance_S <.. graph.usp_PERSIST_ProcedureInstance
graph.usp_PERSIST_ProcedureInstance <.. repo.usp_sync_guid_RepoObject
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObject
logs.usp_ExecutionLog_insert <.. graph.usp_PERSIST_ProcedureInstance
graph.ProcedureInstance_S::Instance <-- graph.ProcedureInstance::Instance
graph.ProcedureInstance_S::Procedure_fullname <-- graph.ProcedureInstance::Procedure_fullname
graph.ProcedureInstance_S::Procedure_RepoObject_guid <-- graph.ProcedureInstance::Procedure_RepoObject_guid
