left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity graph.ReferencingObject << U >> {
  --
  * $edge_id_21A14F7820EC4E65A2181C77070E4599 : nvarchar(1000)
  $from_id_0076F61972EE4CFBAB773755DA860F3E : nvarchar(1000)
  $to_id_24A0471B483E40D58582E894797FDBD5 : nvarchar(1000)
  * from_id_472B24420B624B14BB7713C2D61A6825 : bigint
  * from_obj_id_841F6E8E64074738851E57246A265384 : int
  * graph_id_09F977CF6E984C91A3DCB80DFCA167DF : bigint
  * to_id_481A7B86C080421583F830CBBB2D1D40 : bigint
  * to_obj_id_E20461DCDFE345938DA61BDA2DFCEDB6 : int
}

entity repo.RepoObject_referencing_level << V >> {
  **StartingNode_guid** : uniqueidentifier
  **LastNode_guid** : uniqueidentifier
  * **referencing_level** : int
  --
  LastNode_fullname : nvarchar(261)
  LastNode_fullname2 : nvarchar(257)
  ListNode : nvarchar(4000)
  StartingNode_fullname : nvarchar(261)
  StartingNode_fullname2 : nvarchar(257)
}

entity repo.usp_main << P >> {
  --
}

graph.ReferencingObject <.. repo.RepoObject_referencing_level
graph.ReferencingObject <.. repo.usp_main

