left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_repo_managed : bit
  is_required_ObjectMerge : bit
  is_SysObject_missing : bit
  * modify_dt : datetime
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnName_new : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObject_name_uniqueidentifier : int
  * {static} is_SysObject_name_uniqueidentifier : int
  {abstract} node_id : bigint
  * {static} RepoObject_fullname : nvarchar(261)
  * {static} RepoObject_fullname2 : nvarchar(257)
  * {static} SysObject_fullname : nvarchar(261)
  * {static} SysObject_fullname2 : nvarchar(257)
  * {abstract} SysObject_query_sql : nvarchar(406)
  * {static} usp_persistence_name : nvarchar(140)
}

entity repo.SysObject_RepoObject_via_name << V >> {
  --
  history_table_guid : uniqueidentifier
  history_table_id : int
  is_repo_managed : bit
  is_RepoObject_name_uniqueidentifier : int
  is_SysObject_name_uniqueidentifier : int
  * modify_date : datetime
  * parent_object_id : int
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  RepoObject_guid : uniqueidentifier
  RepoObject_is_SysObject_missing : bit
  RepoObject_name : nvarchar(128)
  RepoObject_schema_name : nvarchar(128)
  RepoObject_SysObject_id : int
  RepoObject_SysObject_modify_date : datetime
  RepoObject_SysObject_name : nvarchar(128)
  RepoObject_SysObject_parent_object_id : int
  RepoObject_SysObject_schema_name : nvarchar(128)
  RepoObject_SysObject_type : char(2)
  RepoObject_type : char(2)
  * SysObject_id : int
  * SysObject_name : sysname
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_schema_name : sysname
  SysObject_type : char(2)
  temporal_type : tinyint
}

entity repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity repo_sys.IndexColumn_unique << V >> {
  --
  * index_column_id : int
  index_guid : uniqueidentifier
  * index_id : int
  index_name : sysname
  is_descending_key : bit
  is_index_primary_key : bit
  is_index_real : bit
  is_index_unique : bit
  parent_RepoObject_guid : uniqueidentifier
  parent_schema_name : nvarchar(128)
  parent_SysObject_fullname : nvarchar(261)
  parent_SysObject_name : nvarchar(128)
  RepoObjectColumn_guid : uniqueidentifier
  SysObject_column_name : sysname
  SysObject_column_user_type_fullname : nvarchar(182)
}

entity repo_sys.SysObject << V >> {
  --
  * create_date : datetime
  history_table_id : int
  * is_ms_shipped : bit
  * is_published : bit
  * is_schema_published : bit
  max_column_id_used : int
  * modify_date : datetime
  * parent_object_id : int
  principal_id : int
  * schema_id : int
  sql_modules_definition : nvarchar(max)
  * SysObject_fullname : nvarchar(517)
  * SysObject_fullname2 : nvarchar(257)
  * SysObject_id : int
  * SysObject_name : sysname
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_schema_name : sysname
  temporal_type : tinyint
  temporal_type_desc : nvarchar(60)
  type : char(2)
  type_desc : nvarchar(60)
}

repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo_sys.SysObject <.. repo.usp_sync_guid_RepoObject
repo_sys.SysObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject::is_repo_managed <-- repo.SysObject_RepoObject_via_name::is_repo_managed
repo.RepoObject::is_RepoObject_name_uniqueidentifier <-- repo.SysObject_RepoObject_via_name::is_RepoObject_name_uniqueidentifier
repo.RepoObject::is_SysObject_name_uniqueidentifier <-- repo.SysObject_RepoObject_via_name::is_SysObject_name_uniqueidentifier
repo.RepoObject::Repo_history_table_guid <-- repo.SysObject_RepoObject_via_name::Repo_history_table_guid
repo.RepoObject::Repo_temporal_type <-- repo.SysObject_RepoObject_via_name::Repo_temporal_type
repo.RepoObject::RepoObject_guid <-- repo.SysObject_RepoObject_via_name::RepoObject_guid
repo.RepoObject::RepoObject_name <-- repo.SysObject_RepoObject_via_name::RepoObject_name
repo.RepoObject::RepoObject_schema_name <-- repo.SysObject_RepoObject_via_name::RepoObject_schema_name
repo.RepoObject::RepoObject_type <-- repo.SysObject_RepoObject_via_name::RepoObject_type
repo.RepoObject::SysObject_id <-- repo.SysObject_RepoObject_via_name::SysObject_id
repo.RepoObject::SysObject_name <-- repo.SysObject_RepoObject_via_name::SysObject_name
repo.RepoObject::SysObject_schema_name <-- repo.SysObject_RepoObject_via_name::SysObject_schema_name
repo.RepoObject::SysObject_type <-- repo.SysObject_RepoObject_via_name::SysObject_type
repo.SysObject_RepoObject_via_name::RepoObject_guid <-- repo_sys.IndexColumn_unique::index_guid
repo_sys.SysObject::history_table_id <-- repo.SysObject_RepoObject_via_name::history_table_id
repo_sys.SysObject::modify_date <-- repo.SysObject_RepoObject_via_name::modify_date
repo_sys.SysObject::parent_object_id <-- repo.SysObject_RepoObject_via_name::parent_object_id
repo_sys.SysObject::SysObject_id <-- repo.SysObject_RepoObject_via_name::SysObject_id
repo_sys.SysObject::SysObject_name <-- repo.SysObject_RepoObject_via_name::SysObject_name
repo_sys.SysObject::SysObject_RepoObject_guid <-- repo.SysObject_RepoObject_via_name::SysObject_RepoObject_guid
repo_sys.SysObject::SysObject_schema_name <-- repo.SysObject_RepoObject_via_name::SysObject_schema_name
repo_sys.SysObject::temporal_type <-- repo.SysObject_RepoObject_via_name::temporal_type
