left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity graph.ReferencedObject << U >> {
  --
  * $edge_id_25B0DD35E10A49DE8B49228E6802F3EB : nvarchar(1000)
  $from_id_7B1BEB60463741CAA681054A489A2714 : nvarchar(1000)
  $to_id_26820C41BE034B00BCBC470518101233 : nvarchar(1000)
  * from_id_7F3CEF660D794A2A81530928BC4B36F1 : bigint
  * from_obj_id_A00C6316716D4F9DABE96A189F3A214A : int
  * graph_id_85ECDD019A4C46AF80CFD8DDFA08F479 : bigint
  * to_id_45A2D6271B224A08B66CA0CF6A200A54 : bigint
  * to_obj_id_F1F1771130674EE9A9DAE06330740E13 : int
}

entity graph.RepoObject << U >> {
  --
  * $node_id_FAC3EF4690DB4CD6A98F097DAF0885CC : nvarchar(1000)
  * 33091D88-929D-488C-B30F-7328A9D970B6 : char(2)
  * 906BEFD3-76BA-432D-9792-128CEA80A6EE : nvarchar(257)
  * 9D326C2A-F564-4176-B51F-7BE9FB6685B2 : nvarchar(261)
  * graph_id_60367FDA1A70430CA390F8144C223EC4 : bigint
  * RepoObject_fullname : nvarchar(261)
  RepoObject_fullname2 : nvarchar(257)
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
}

entity repo.Match_RepoObject_referenced_UspPersistence << V >> {
  **FirstNode** : uniqueidentifier
  **LastNode** : uniqueidentifier
  --
  First_usp_persistence_name : nvarchar(140)
  First_usp_persistence_RepoObject_guid : uniqueidentifier
  FirstNodeName : nvarchar(261)
  Last_usp_persistence_name : nvarchar(140)
  Last_usp_persistence_RepoObject_guid : uniqueidentifier
  LastNodeName : nvarchar(261)
  ListNodeName : nvarchar(4000)
}

entity repo.Reference_UspPersistence << V >> {
  --
  referenced_usp_persistence_name : nvarchar(140)
  referenced_usp_RepoObject_guid : uniqueidentifier
  referencing_usp_persistence_name : nvarchar(140)
  referencing_usp_RepoObject_guid : uniqueidentifier
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  AntoraReferencedList : nvarchar(max)
  AntoraReferencingList : nvarchar(max)
  CreateColumnList : nvarchar(max)
  DbmlColumnList : nvarchar(max)
  has_different_sys_names : bit
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  has_history : bit
  has_history_columns : bit
  history_schema_name : nvarchar(128)
  history_table_name : nvarchar(128)
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_DocsOutput : int
  * is_in_reference : int
  is_persistence : bit
  is_persistence_check_duplicate_per_pk : bit
  is_persistence_check_for_empty_source : bit
  is_persistence_delete_changed : bit
  is_persistence_delete_missing : bit
  is_persistence_insert : bit
  is_persistence_truncate : bit
  is_persistence_update_changed : bit
  is_repo_managed : bit
  * is_RepoObject_name_uniqueidentifier : int
  is_SysObject_missing : bit
  * is_SysObject_name_uniqueidentifier : int
  * modify_dt : datetime
  node_id : bigint
  persistence_source_RepoObject_fullname : nvarchar(261)
  persistence_source_RepoObject_fullname2 : nvarchar(257)
  persistence_source_RepoObject_guid : uniqueidentifier
  persistence_source_RepoObject_xref : nvarchar(269)
  persistence_source_SysObject_fullname : nvarchar(261)
  persistence_source_SysObject_fullname2 : nvarchar(257)
  persistence_source_SysObject_xref : nvarchar(269)
  PersistenceCompareColumnList : nvarchar(max)
  PersistenceInsertColumnList : nvarchar(max)
  PersistenceUpdateColumnList : nvarchar(max)
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnDatatype : nvarchar(4000)
  pk_IndexPatternColumnName : nvarchar(4000)
  pk_IndexPatternColumnName_new : nvarchar(4000)
  pk_IndexSemanticGroup : nvarchar(512)
  Property_ms_description : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  RepoObject_type_name : nvarchar(128)
  sql_modules_antora : nvarchar(max)
  sql_modules_definition : nvarchar(max)
  sql_modules_formatted : nvarchar(max)
  sql_modules_formatted2 : nvarchar(max)
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  SysObject_query_executed_dt : datetime
  SysObject_query_plan : xml
  * SysObject_query_sql : nvarchar(406)
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObject_type_name : nvarchar(128)
  temporal_type : tinyint
  * usp_persistence_name : nvarchar(140)
  usp_persistence_RepoObject_guid : uniqueidentifier
}

graph.ReferencedObject <.. repo.Match_RepoObject_referenced_UspPersistence
graph.RepoObject <.. repo.Match_RepoObject_referenced_UspPersistence
repo.Match_RepoObject_referenced_UspPersistence <.. repo.Reference_UspPersistence
repo.RepoObject_gross <.. repo.Match_RepoObject_referenced_UspPersistence

