left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.usp_RepoObjectColumnProperty_set << P >> {
  --
}

entity repo.RepoObjectColumnProperty_ForUpdate << V >> {
  --
  inheritance : tinyint
  property_basetype : sql_variant
  * property_name : nvarchar(128)
  * property_value : sql_variant
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  * RepoObject_guid : uniqueidentifier
  * RepoObjectColumn_fullname : nvarchar(520)
  * RepoObjectColumn_fullname2 : nvarchar(386)
  * RepoObjectColumn_guid : uniqueidentifier
  * RepoObjectColumn_name : nvarchar(128)
  * RepoObjectColumnProperty_id : int
}

entity repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  * **level2type** : nvarchar(6)
  * **level2name** : nvarchar(128)
  * **property_name** : nvarchar(128)
  --
  * parent_RepoObject_guid : uniqueidentifier
  * parent_RepoObject_type : char(2)
  * property_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  * RepoObjectColumn_guid : uniqueidentifier
}

entity repo.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity repo.PropertyName_RepoObjectColumn << V >> {
  * **property_name** : nvarchar(128)
  --
}

entity repo.RepoObjectColumnProperty << U >> {
  * **RepoObjectColumnProperty_id** : int
  --
  inheritance : tinyint
  * property_name : nvarchar(128)
  * property_value : sql_variant
  * RepoObjectColumn_guid : uniqueidentifier
  {abstract} property_basetype : sql_variant
  {abstract} property_bigint : bigint
  {abstract} property_float : float
  {abstract} property_int : int
  {abstract} property_money : money
  {abstract} property_nvarchar : nvarchar(4000)
  {abstract} property_real : real
  {abstract} property_varchar : varchar(8000)
}

entity repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition << V >> {
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : int
  par_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  par_InheritanceDefinition : nvarchar(4000)
  par_InheritanceType : int
  * property_name : nvarchar(128)
  property_value : sql_variant
  * RepoObjectColumn_guid : uniqueidentifier
  * RepoObjectColumn_name : nvarchar(128)
  roc_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  roc_InheritanceDefinition : nvarchar(4000)
  roc_InheritanceType : tinyint
  sub_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  sub_InheritanceDefinition : nvarchar(4000)
  sub_InheritanceType : int
}

entity repo.RepoObjectColumnProperty_sys_repo << V >> {
  --
  * property_name : sysname
  property_value : sql_variant
  * RepoObjectColumn_guid : uniqueidentifier
  RepoObjectColumnProperty_id : int
  RepoObjectColumnProperty_property_value : sql_variant
  SysObject_name : nvarchar(128)
  SysObject_schema_name : nvarchar(128)
  SysObjectColumn_name : nvarchar(128)
}

entity repo.usp_RepoObjectColumn_Inheritance << P >> {
  --
}

entity repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate << P >> {
  --
}

repo.PropertyName_RepoObjectColumn <.. repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectColumnProperty <.. repo.fs_get_RepoObjectColumnProperty_nvarchar
repo.RepoObjectColumnProperty <.. repo.PropertyName_RepoObjectColumn
repo.RepoObjectColumnProperty <.. repo.usp_RepoObjectColumn_Inheritance
repo.RepoObjectColumnProperty <.. 
repo.RepoObjectColumnProperty <.. 
repo.RepoObjectColumnProperty <.. repo.RepoObjectColumnProperty_sys_repo
repo.RepoObjectColumnProperty <.. repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
repo.RepoObjectColumnProperty <.. repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
repo.RepoObjectColumnProperty <.. repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectColumnProperty_sys_repo <.. repo.usp_sync_ExtendedProperties_Sys2Repo_InsertUpdate
repo.PropertyName_RepoObjectColumn::property_name <-- repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::property_name
repo.RepoObjectColumnProperty::inheritance <-- ::inheritance
repo.RepoObjectColumnProperty::property_basetype <-- ::property_basetype
repo.RepoObjectColumnProperty::property_name <-- ::property_name
repo.RepoObjectColumnProperty::property_name <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn::property_name
repo.RepoObjectColumnProperty::property_value <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn::property_value
repo.RepoObjectColumnProperty::property_value <-- ::property_value
repo.RepoObjectColumnProperty::property_value <-- repo.RepoObjectColumnProperty_InheritanceType_InheritanceDefinition::property_value
repo.RepoObjectColumnProperty::RepoObjectColumn_guid <-- ::RepoObjectColumn_guid
repo.RepoObjectColumnProperty::RepoObjectColumn_guid <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn::RepoObjectColumn_guid
repo.RepoObjectColumnProperty::RepoObjectColumnProperty_id <-- ::RepoObjectColumnProperty_id
