left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_repo_managed : bit
  is_SysObject_missing : bit
  * modify_dt : datetime
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnName_new : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObject_name_uniqueidentifier : int
  * {static} is_SysObject_name_uniqueidentifier : int
  {abstract} node_id : bigint
  * {static} RepoObject_fullname : nvarchar(261)
  * {static} RepoObject_fullname2 : nvarchar(257)
  * {static} SysObject_fullname : nvarchar(261)
  * {static} SysObject_fullname2 : nvarchar(257)
  * {abstract} SysObject_query_sql : nvarchar(406)
  * {static} usp_persistence_name : nvarchar(140)
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_persistence_no_check : bit
  is_persistence_no_include : bit
  is_persistence_no_update : bit
  is_query_plan_expression : bit
  is_SysObjectColumn_missing : bit
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  * Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  * Repo_is_computed : bit
  * Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  * RepoObject_guid : uniqueidentifier
  RepoObjectColumn_column_id : int
  * RepoObjectColumn_name : nvarchar(128)
  SysObjectColumn_column_id : int
  * SysObjectColumn_name : nvarchar(128)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObjectColumn_name_uniqueidentifier : int
  * {static} is_SysObjectColumn_name_uniqueidentifier : int
}

entity repo.SysColumn_RepoObjectColumn_via_guid << V >> {
  --
  default_definition : nvarchar(max)
  default_is_system_named : bit
  default_name : sysname
  definition : nvarchar(max)
  generated_always_type : tinyint
  graph_type : int
  has_different_sys_names : bit
  increment_value : sql_variant
  * is_computed : bit
  * is_identity : bit
  is_nullable : bit
  is_persisted : bit
  is_query_plan_expression : bit
  is_repo_managed : bit
  is_RepoObjectColumn_name_uniqueidentifier : int
  is_SysObjectColumn_missing : bit
  is_SysObjectColumn_name_uniqueidentifier : int
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  Repo_is_computed : bit
  Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  RepoObject_fullname : nvarchar(261)
  RepoObject_guid : uniqueidentifier
  RepoObjectColumn_guid : uniqueidentifier
  RepoObjectColumn_name : nvarchar(128)
  RowNumberOverName : bigint
  seed_value : sql_variant
  * SysObject_column_id : int
  SysObject_column_name : sysname
  SysObject_fullname : nvarchar(261)
  * SysObject_id : int
  SysObject_name : nvarchar(128)
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_RepoObjectColumn_guid : uniqueidentifier
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObjectColumn_column_id : int
  SysObjectColumn_name : nvarchar(128)
  user_type_fullname : nvarchar(182)
  user_type_name : sysname
  uses_database_collation : bit
}

entity repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity repo_sys.SysColumn << V >> {
  --
  collation_name : sysname
  column_encryption_key_database_name : sysname
  column_encryption_key_id : int
  default_definition : nvarchar(max)
  default_is_system_named : bit
  default_name : sysname
  * default_object_id : int
  default_parent_column_id : int
  definition : nvarchar(max)
  encryption_algorithm_name : sysname
  encryption_type : int
  encryption_type_desc : nvarchar(64)
  generated_always_type : tinyint
  generated_always_type_desc : nvarchar(60)
  graph_type : int
  graph_type_desc : nvarchar(60)
  increment_value : sql_variant
  * is_ansi_padded : bit
  is_column_set : bit
  * is_computed : bit
  is_dts_replicated : bit
  * is_filestream : bit
  is_hidden : bit
  * is_identity : bit
  * is_masked : bit
  is_merge_published : bit
  is_non_sql_subscribed : bit
  is_nullable : bit
  is_persisted : bit
  is_replicated : bit
  * is_rowguidcol : bit
  is_sparse : bit
  * is_xml_document : bit
  last_value : sql_variant
  * max_length : smallint
  * precision : tinyint
  * rule_object_id : int
  * scale : tinyint
  seed_value : sql_variant
  * SysObject_column_id : int
  SysObject_column_name : sysname
  * SysObject_id : int
  SysObject_name : nvarchar(128)
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_RepoObjectColumn_guid : uniqueidentifier
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObject_type_desc : nvarchar(60)
  * system_type_id : tinyint
  user_type_fullname : nvarchar(182)
  * user_type_id : int
  user_type_name : sysname
  uses_database_collation : bit
  * xml_collection_id : int
}

repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObject <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_guid <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo_sys.SysColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject::is_repo_managed <-- repo.SysColumn_RepoObjectColumn_via_guid::is_repo_managed
repo.RepoObject::RepoObject_fullname <-- repo.SysColumn_RepoObjectColumn_via_guid::RepoObject_fullname
repo.RepoObject::SysObject_fullname <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_fullname
repo.RepoObjectColumn::has_different_sys_names <-- repo.SysColumn_RepoObjectColumn_via_guid::has_different_sys_names
repo.RepoObjectColumn::is_query_plan_expression <-- repo.SysColumn_RepoObjectColumn_via_guid::is_query_plan_expression
repo.RepoObjectColumn::is_RepoObjectColumn_name_uniqueidentifier <-- repo.SysColumn_RepoObjectColumn_via_guid::is_RepoObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn::is_SysObjectColumn_missing <-- repo.SysColumn_RepoObjectColumn_via_guid::is_SysObjectColumn_missing
repo.RepoObjectColumn::is_SysObjectColumn_name_uniqueidentifier <-- repo.SysColumn_RepoObjectColumn_via_guid::is_SysObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn::persistence_source_RepoObjectColumn_guid <-- repo.SysColumn_RepoObjectColumn_via_guid::persistence_source_RepoObjectColumn_guid
repo.RepoObjectColumn::Referencing_Count <-- repo.SysColumn_RepoObjectColumn_via_guid::Referencing_Count
repo.RepoObjectColumn::Repo_default_definition <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_default_definition
repo.RepoObjectColumn::Repo_default_is_system_named <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_default_is_system_named
repo.RepoObjectColumn::Repo_default_name <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_default_name
repo.RepoObjectColumn::Repo_definition <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_definition
repo.RepoObjectColumn::Repo_generated_always_type <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_generated_always_type
repo.RepoObjectColumn::Repo_graph_type <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_graph_type
repo.RepoObjectColumn::Repo_increment_value <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_increment_value
repo.RepoObjectColumn::Repo_is_computed <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_is_computed
repo.RepoObjectColumn::Repo_is_identity <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_is_identity
repo.RepoObjectColumn::Repo_is_nullable <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_is_nullable
repo.RepoObjectColumn::Repo_is_persisted <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_is_persisted
repo.RepoObjectColumn::Repo_seed_value <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_seed_value
repo.RepoObjectColumn::Repo_user_type_fullname <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_user_type_fullname
repo.RepoObjectColumn::Repo_user_type_name <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_user_type_name
repo.RepoObjectColumn::Repo_uses_database_collation <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_uses_database_collation
repo.RepoObjectColumn::RepoObject_guid <-- repo.SysColumn_RepoObjectColumn_via_guid::RepoObject_guid
repo.RepoObjectColumn::RepoObjectColumn_guid <-- repo.SysColumn_RepoObjectColumn_via_guid::RepoObjectColumn_guid
repo.RepoObjectColumn::RepoObjectColumn_name <-- repo.SysColumn_RepoObjectColumn_via_guid::RepoObjectColumn_name
repo.RepoObjectColumn::SysObjectColumn_column_id <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObjectColumn_column_id
repo.RepoObjectColumn::SysObjectColumn_name <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObjectColumn_name
repo_sys.SysColumn::default_definition <-- repo.SysColumn_RepoObjectColumn_via_guid::default_definition
repo_sys.SysColumn::default_is_system_named <-- repo.SysColumn_RepoObjectColumn_via_guid::default_is_system_named
repo_sys.SysColumn::default_name <-- repo.SysColumn_RepoObjectColumn_via_guid::default_name
repo_sys.SysColumn::definition <-- repo.SysColumn_RepoObjectColumn_via_guid::definition
repo_sys.SysColumn::generated_always_type <-- repo.SysColumn_RepoObjectColumn_via_guid::generated_always_type
repo_sys.SysColumn::graph_type <-- repo.SysColumn_RepoObjectColumn_via_guid::graph_type
repo_sys.SysColumn::increment_value <-- repo.SysColumn_RepoObjectColumn_via_guid::increment_value
repo_sys.SysColumn::is_computed <-- repo.SysColumn_RepoObjectColumn_via_guid::is_computed
repo_sys.SysColumn::is_identity <-- repo.SysColumn_RepoObjectColumn_via_guid::is_identity
repo_sys.SysColumn::is_nullable <-- repo.SysColumn_RepoObjectColumn_via_guid::is_nullable
repo_sys.SysColumn::is_persisted <-- repo.SysColumn_RepoObjectColumn_via_guid::is_persisted
repo_sys.SysColumn::seed_value <-- repo.SysColumn_RepoObjectColumn_via_guid::seed_value
repo_sys.SysColumn::SysObject_column_id <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_column_id
repo_sys.SysColumn::SysObject_column_name <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_column_name
repo_sys.SysColumn::SysObject_id <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_id
repo_sys.SysColumn::SysObject_name <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_name
repo_sys.SysColumn::SysObject_RepoObject_guid <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_RepoObject_guid
repo_sys.SysColumn::SysObject_RepoObjectColumn_guid <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_RepoObjectColumn_guid
repo_sys.SysColumn::SysObject_schema_name <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_schema_name
repo_sys.SysColumn::SysObject_type <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_type
repo_sys.SysColumn::user_type_fullname <-- repo.SysColumn_RepoObjectColumn_via_guid::user_type_fullname
repo_sys.SysColumn::user_type_name <-- repo.SysColumn_RepoObjectColumn_via_guid::user_type_name
repo_sys.SysColumn::uses_database_collation <-- repo.SysColumn_RepoObjectColumn_via_guid::uses_database_collation
