left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.usp_RepoObjectColumnProperty_set << P >> {
  --
}

entity workflow.ProcedureDependency_gross << V >> {
  --
  Description : nvarchar(4000)
  * id : int
  * is_active : bit
  * is_PersistenceDependency : bit
  * referenced_Procedure_RepoObject_guid : uniqueidentifier
  * referenced_RepoObject_fullname : nvarchar(261)
  * referenced_RepoObject_fullname2 : nvarchar(257)
  * referenced_RepoObject_schema_name : nvarchar(128)
  * referencing_Procedure_RepoObject_guid : uniqueidentifier
  * referencing_RepoObject_fullname : nvarchar(261)
  * referencing_RepoObject_fullname2 : nvarchar(257)
  * referencing_RepoObject_schema_name : nvarchar(128)
}

entity docs.RepoObject_Plantuml_ObjectRefList_0_30 << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  ObjectRefList : nvarchar(max)
  * RepoObject_fullname2 : nvarchar(257)
}

entity docs.RepoObject_Plantuml_ObjectRefList_30_0 << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  ObjectRefList : nvarchar(max)
  * RepoObject_fullname2 : nvarchar(257)
}

entity docs.AntoraNavListPage_by_schema << V >> {
  * **RepoObject_schema_name** : nvarchar(128)
  --
  * nav_list : nvarchar(311)
}

entity docs.ftv_RepoObject_Reference_PlantUml_EntityRefList << IF >> {
  --
  PumlEntityList : nvarchar(max)
  PumlEntityOnlyPkList : nvarchar(max)
  Referenced_Depth : int
  Referencing_Depth : int
  ro_guid : uniqueidentifier
}

entity docs.RepoObject_Plantuml_ColRefList << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  ColRefList : nvarchar(max)
  * RepoObject_fullname2 : nvarchar(257)
}

entity docs.RepoObject_Plantuml_ObjectRefList << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  ObjectRefList : nvarchar(max)
  * RepoObject_fullname2 : nvarchar(257)
}

entity docs.visjs_nodelist_object_test01 << V >> {
  --
  node_id : bigint
  * NodeListElement : nvarchar(303)
  * RepoObject_guid : uniqueidentifier
  * SysObject_fullname : nvarchar(261)
  SysObject_type : char(2)
}

entity graph.RepoObject_S << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  * RepoObject_fullname : nvarchar(261)
  RepoObject_fullname2 : nvarchar(257)
  * RepoObject_type : char(2)
}

entity repo.check_IndexColumn_virtual_referenced_setpoint << V >> {
  * **index_guid** : uniqueidentifier
  * **index_column_id** : int
  --
  referenced_index_guid : uniqueidentifier
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
  RepoObject_guid_s : uniqueidentifier
  RepoObject_guid_t : uniqueidentifier
  RepoObjectColumn_guid_t : uniqueidentifier
  SysObject_fullname_s : nvarchar(261)
  SysObject_fullname_t : nvarchar(261)
  SysObjectColumn_name_s : nvarchar(128)
  SysObjectColumn_name_t : nvarchar(128)
}

entity repo.ExtendedProperty_Repo2Sys_level1 << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  * **property_name** : nvarchar(128)
  --
  level2name : varchar(128)
  level2type : varchar(10)
  property_value : sql_variant
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
}

entity repo.ExtendedProperty_Repo2Sys_level2_RepoObject << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  **level2type** : varchar(10)
  * **level2name** : nvarchar(128)
  * **property_name** : nvarchar(128)
  --
  * parent_RepoObject_guid : uniqueidentifier
  * parent_RepoObject_type : char(2)
  property_value : sql_variant
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
}

entity repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn << V >> {
  * **level0type** : nvarchar(6)
  * **level0name** : nvarchar(128)
  **level1type** : varchar(9)
  * **level1name** : nvarchar(128)
  * **level2type** : nvarchar(6)
  * **level2name** : nvarchar(128)
  * **property_name** : nvarchar(128)
  --
  * parent_RepoObject_guid : uniqueidentifier
  * parent_RepoObject_type : char(2)
  * property_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  * RepoObjectColumn_guid : uniqueidentifier
}

entity repo.ftv_RepoObject_ReferencedReferencing << IF >> {
  --
  Node_fullname2 : nvarchar(257)
  Node_guid : uniqueidentifier
  Referenced_Depth : int
  Referencing_Depth : int
  ro_guid : uniqueidentifier
}

entity repo.Index_virtual_ForUpdate << V >> {
  * **index_guid** : uniqueidentifier
  --
  * has_managedName : bit
  index_name : nvarchar(128)
  * index_type : tinyint
  IndexPatternColumnDatatype : nvarchar(4000)
  IndexPatternColumnName : nvarchar(4000)
  IndexSemanticGroup : nvarchar(512)
  * is_index_disabled : bit
  * is_index_primary_key : bit
  * is_index_unique : bit
  is_persistence : bit
  is_repo_managed : bit
  * parent_RepoObject_guid : uniqueidentifier
  referenced_index_guid : uniqueidentifier
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  RowNumberInReferencing : int
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
}

entity repo.Index_virtual_SysObject << V >> {
  * **index_guid** : uniqueidentifier
  --
  index_name : nvarchar(128)
  IndexPatternColumnDatatype : nvarchar(4000)
  IndexPatternColumnName : nvarchar(4000)
  IndexSemanticGroup : nvarchar(512)
  * is_index_disabled : bit
  * is_index_primary_key : bit
  * is_index_unique : bit
  * parent_RepoObject_guid : uniqueidentifier
  pk_index_guid : uniqueidentifier
  referenced_index_guid : uniqueidentifier
  SysObject_id : int
  * SysObject_name : nvarchar(128)
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
}

entity repo.IndexColumn_virtual_gross << V >> {
  * **index_column_id** : int
  --
  column_user_type_fullname : nvarchar(128)
  * index_guid : uniqueidentifier
  index_name : nvarchar(128)
  * is_descending_key : bit
  * is_index_primary_key : bit
  is_index_real : bit
  * is_index_unique : bit
  * Object_column_name : nvarchar(128)
  parent_Object_fullname : nvarchar(261)
  parent_Object_name : nvarchar(128)
  * parent_RepoObject_guid : uniqueidentifier
  parent_schema_name : nvarchar(128)
  * RepoObjectColumn_guid : uniqueidentifier
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_repo_managed : bit
  is_required_ObjectMerge : bit
  is_SysObject_missing : bit
  * modify_dt : datetime
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnName_new : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObject_name_uniqueidentifier : int
  * {static} is_SysObject_name_uniqueidentifier : int
  {abstract} node_id : bigint
  * {static} RepoObject_fullname : nvarchar(261)
  * {static} RepoObject_fullname2 : nvarchar(257)
  * {static} SysObject_fullname : nvarchar(261)
  * {static} SysObject_fullname2 : nvarchar(257)
  * {abstract} SysObject_query_sql : nvarchar(406)
  * {static} usp_persistence_name : nvarchar(140)
}

entity repo.RepoObject_fullname_u_v << V >> {
  * **RepoObject_fullname** : nvarchar(261)
  --
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  AntoraReferencedList : nvarchar(max)
  AntoraReferencingList : nvarchar(max)
  CreateColumnList : nvarchar(max)
  DbmlColumnList : nvarchar(max)
  has_different_sys_names : bit
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  has_history : bit
  has_history_columns : bit
  history_schema_name : nvarchar(128)
  history_table_name : nvarchar(128)
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_DocsOutput : int
  * is_in_reference : int
  is_persistence : bit
  is_persistence_check_duplicate_per_pk : bit
  is_persistence_check_for_empty_source : bit
  is_persistence_delete_changed : bit
  is_persistence_delete_missing : bit
  is_persistence_insert : bit
  is_persistence_truncate : bit
  is_persistence_update_changed : bit
  is_repo_managed : bit
  * is_RepoObject_name_uniqueidentifier : int
  is_required_ObjectMerge : bit
  is_SysObject_missing : bit
  * is_SysObject_name_uniqueidentifier : int
  * modify_dt : datetime
  node_id : bigint
  persistence_source_RepoObject_fullname : nvarchar(261)
  persistence_source_RepoObject_fullname2 : nvarchar(257)
  persistence_source_RepoObject_guid : uniqueidentifier
  persistence_source_RepoObject_xref : nvarchar(269)
  persistence_source_SysObject_fullname : nvarchar(261)
  persistence_source_SysObject_fullname2 : nvarchar(257)
  persistence_source_SysObject_xref : nvarchar(269)
  PersistenceCompareColumnList : nvarchar(max)
  PersistenceInsertColumnList : nvarchar(max)
  PersistenceUpdateColumnList : nvarchar(max)
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnDatatype : nvarchar(4000)
  pk_IndexPatternColumnName : nvarchar(4000)
  pk_IndexPatternColumnName_new : nvarchar(4000)
  pk_IndexSemanticGroup : nvarchar(512)
  Property_ms_description : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  RepoObject_type_name : nvarchar(128)
  sql_modules_antora : nvarchar(max)
  sql_modules_definition : nvarchar(max)
  sql_modules_formatted : nvarchar(max)
  sql_modules_formatted2 : nvarchar(max)
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  SysObject_query_executed_dt : datetime
  SysObject_query_plan : xml
  * SysObject_query_sql : nvarchar(406)
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObject_type_name : nvarchar(128)
  temporal_type : tinyint
  * usp_persistence_name : nvarchar(140)
  usp_persistence_RepoObject_guid : uniqueidentifier
}

entity repo.RepoObject_persistence_column << V >> {
  * **target_RepoObject_guid** : uniqueidentifier
  **RepoObjectColumn_guid_s** : uniqueidentifier
  --
  * has_history : bit
  * has_history_columns : bit
  history_schema_name : nvarchar(128)
  history_table_name : nvarchar(128)
  is_persistence : bit
  * is_persistence_check_for_empty_source : bit
  * is_persistence_delete_changed : bit
  * is_persistence_delete_missing : bit
  * is_persistence_insert : bit
  * is_persistence_truncate : bit
  * is_persistence_update_changed : bit
  is_repo_managed_t : bit
  * RepoObject_name_t : nvarchar(128)
  * RepoObject_schema_name_t : nvarchar(128)
  * RepoObject_type_t : char(2)
  RepoObjectColumn_name_t : nvarchar(128)
  source_RepoObject_guid : uniqueidentifier
  SysObject_name_s : nvarchar(128)
  SysObject_schema_name_s : nvarchar(128)
  SysObject_type_s : char(2)
  SysObjectColumn_name_s : nvarchar(128)
}

entity repo.RepoObject_persistence_ForUpdate << V >> {
  * **target_RepoObject_guid** : uniqueidentifier
  --
  * has_history : bit
  * has_history_columns : bit
  history_schema_name : nvarchar(128)
  history_table_name : nvarchar(128)
  is_persistence : bit
  * is_persistence_check_duplicate_per_pk : bit
  * is_persistence_check_for_empty_source : bit
  * is_persistence_delete_changed : bit
  * is_persistence_delete_missing : bit
  * is_persistence_insert : bit
  * is_persistence_truncate : bit
  * is_persistence_update_changed : bit
  source_RepoObject_guid : uniqueidentifier
  * target_RepoObject_fullname : nvarchar(261)
  temporal_type : tinyint
}

entity repo.RepoObject_persistence_ObjectNames << V >> {
  * **target_RepoObject_guid** : uniqueidentifier
  --
  * has_history : bit
  * has_history_columns : bit
  history_schema_name : nvarchar(128)
  history_table_name : nvarchar(128)
  is_persistence : bit
  * is_persistence_check_for_empty_source : bit
  * is_persistence_delete_changed : bit
  * is_persistence_delete_missing : bit
  * is_persistence_insert : bit
  * is_persistence_truncate : bit
  * is_persistence_update_changed : bit
  is_repo_managed_t : bit
  * RepoObject_name_t : nvarchar(128)
  * RepoObject_schema_name_t : nvarchar(128)
  * RepoObject_type_t : char(2)
  source_RepoObject_guid : uniqueidentifier
  SysObject_name_s : nvarchar(128)
  SysObject_schema_name_s : nvarchar(128)
  SysObject_type_s : char(2)
}

entity repo.RepoObject_reference_persistence << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  * **referencing_RepoObject_guid** : uniqueidentifier
  --
  * InformationSource : varchar(27)
  * referenced_entity_name : nvarchar(128)
  * referenced_fullname : nvarchar(261)
  referenced_id : int
  referenced_node_id : bigint
  * referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  * referencing_entity_name : nvarchar(128)
  * referencing_fullname : nvarchar(261)
  referencing_id : int
  referencing_node_id : bigint
  * referencing_schema_name : nvarchar(128)
  referencing_type : varchar(2)
}

entity repo.RepoObject_related_FK_union << V >> {
  **RepoObject_guid** : uniqueidentifier
  **included_RepoObject_guid** : uniqueidentifier
  --
  included_RepoObject_fullname2 : nvarchar(257)
  RepoObject_fullname2 : nvarchar(257)
}

entity repo.RepoObject_RequiredRepoObjectMerge << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **ro2_RepoObject_guid** : uniqueidentifier
  --
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_name : nvarchar(128)
  * RepoObject_schema_name : nvarchar(128)
  * ro2_RepoObject_fullname : nvarchar(261)
  * ro2_RepoObject_name : nvarchar(128)
  * ro2_RepoObject_schema_name : nvarchar(128)
  * ro2_SysObject_fullname : nvarchar(261)
  * ro2_SysObject_name : nvarchar(128)
  * SysObject_fullname : nvarchar(261)
  * SysObject_name : nvarchar(128)
  * SysObject_schema_name : nvarchar(128)
}

entity repo.RepoObject_SqlCreateTable << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  ConList : nvarchar(max)
  * DbmlTable : nvarchar(max)
  persistence_source_RepoObject_fullname : nvarchar(261)
  persistence_source_RepoObject_guid : uniqueidentifier
  persistence_source_SysObject_fullname : nvarchar(261)
  * RepoObject_fullname : nvarchar(261)
  * SqlCreateTable : nvarchar(max)
}

entity repo.RepoObjectColumn_gross << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
  AntoraReferencedColumnList : nvarchar(max)
  AntoraReferencingColumnList : nvarchar(max)
  has_different_sys_names : bit
  has_get_referenced_issue : bit
  index_column_id : int
  index_name : nvarchar(128)
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_index_primary_key : bit
  is_persistence_no_check : bit
  is_persistence_no_include : bit
  is_persistence_no_update : bit
  is_query_plan_expression : bit
  is_repo_managed : bit
  * is_RepoObject_name_uniqueidentifier : int
  * is_RepoObjectColumn_name_uniqueidentifier : int
  is_required_ColumnMerge : bit
  is_SysObject_missing : bit
  * is_SysObject_name_uniqueidentifier : int
  is_SysObjectColumn_missing : bit
  * is_SysObjectColumn_name_uniqueidentifier : int
  * modify_dt : datetime
  node_id : bigint
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  pk_index_guid : uniqueidentifier
  Property_ms_description : nvarchar(4000)
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  * Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  * Repo_is_computed : bit
  * Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  * RepoObject_guid : uniqueidentifier
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  RepoObjectColumn_column_id : int
  * RepoObjectColumn_fullname : nvarchar(520)
  * RepoObjectColumn_fullname2 : nvarchar(386)
  * RepoObjectColumn_name : nvarchar(128)
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObjectColumn_column_id : int
  * SysObjectColumn_name : nvarchar(128)
}

entity repo.RepoObjectColumn_MissingSource_TypeV << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
  has_different_sys_names : bit
  is_query_plan_expression : bit
  * is_RepoObjectColumn_name_uniqueidentifier : int
  is_SysObjectColumn_missing : bit
  * is_SysObjectColumn_name_uniqueidentifier : int
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  * Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  * Repo_is_computed : bit
  * Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_guid : uniqueidentifier
  * RepoObjectColumn_name : nvarchar(128)
  * SysObject_fullname : nvarchar(261)
  SysObjectColumn_column_id : int
  * SysObjectColumn_name : nvarchar(128)
}

entity repo.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
  * InformationSource : varchar(37)
  is_hidden : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  referenced_column_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_id : int
  referenced_minor_id : int
  referenced_node_id : bigint
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_column_name : nvarchar(128)
  * referencing_entity_name : nvarchar(128)
  referencing_id : int
  referencing_minor_id : int
  referencing_node_id : bigint
  * referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
  * referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
}

entity repo.RepoObjectColumn_reference_Persistence << V >> {
  **referencing_id** : int
  **referencing_minor_id** : int
  **referenced_id** : int
  **referenced_minor_id** : int
  --
  definition : nvarchar(max)
  * InformationSource : varchar(27)
  is_computed : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  * referenced_column_name : nvarchar(128)
  * referenced_entity_name : nvarchar(128)
  referenced_node_id : bigint
  referenced_RepoObject_guid : uniqueidentifier
  * referenced_RepoObjectColumn_guid : uniqueidentifier
  * referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  * referencing_column_name : nvarchar(128)
  * referencing_entity_name : nvarchar(128)
  referencing_node_id : bigint
  * referencing_RepoObject_guid : uniqueidentifier
  * referencing_RepoObjectColumn_guid : uniqueidentifier
  * referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
}

entity repo.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : int
  **referencing_minor_id** : int
  **referenced_id** : int
  **referenced_minor_id** : int
  --
  definition : nvarchar(max)
  * InformationSource : varchar(10)
  is_computed : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  is_source_column_name_expression : bit
  is_target_column_name_expression : bit
  referenced_column_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_node_id : bigint
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_column_name : nvarchar(128)
  * referencing_entity_name : nvarchar(128)
  referencing_node_id : bigint
  * referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
  * referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
  source_schema_name_quoted : nvarchar(128)
  source_table_name_quoted : nvarchar(128)
}

entity repo.RepoObjectColumn_reference_SqlModules << V >> {
  **referencing_id** : int
  **referencing_minor_id** : int
  **referenced_id** : int
  **referenced_minor_id** : int
  --
  definition : nvarchar(max)
  * InformationSource : varchar(27)
  is_computed : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  * referenced_column_name : nvarchar(128)
  * referenced_entity_name : nvarchar(128)
  referenced_node_id : bigint
  * referenced_RepoObject_guid : uniqueidentifier
  * referenced_RepoObjectColumn_guid : uniqueidentifier
  * referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  * referencing_column_name : nvarchar(128)
  * referencing_entity_name : nvarchar(128)
  referencing_node_id : bigint
  * referencing_RepoObject_guid : uniqueidentifier
  * referencing_RepoObjectColumn_guid : uniqueidentifier
  * referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
  SysObject_fullname : nvarchar(261)
}

entity repo.RepoObjectColumnProperty_sys_repo << V >> {
  --
  * property_name : sysname
  property_value : sql_variant
  * RepoObjectColumn_guid : uniqueidentifier
  RepoObjectColumnProperty_id : int
  RepoObjectColumnProperty_property_value : sql_variant
  SysObject_name : nvarchar(128)
  SysObject_schema_name : nvarchar(128)
  SysObjectColumn_name : nvarchar(128)
}

entity repo.RepoObjectProperty_cross << V >> {
  --
  * property_name : nvarchar(128)
  * RepoObject_guid : uniqueidentifier
}

entity repo.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **property_name** : nvarchar(128)
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : int
  par_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  par_InheritanceDefintion : nvarchar(4000)
  par_InheritanceType : int
  property_value : sql_variant
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_type : char(2)
  ro_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  ro_InheritanceDefinition : nvarchar(4000)
  ro_InheritanceType : tinyint
  sub_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  sub_InheritanceDefintion : nvarchar(4000)
  sub_InheritanceType : int
}

entity repo.RepoObjectProperty_sys_repo << V >> {
  --
  * property_name : sysname
  property_value : sql_variant
  * RepoObject_guid : uniqueidentifier
  RepoObjectProperty_id : int
  RepoObjectProperty_property_value : sql_variant
  SysObject_name : nvarchar(128)
  SysObject_schema_name : nvarchar(128)
}

entity repo.SysColumn_RepoObjectColumn_via_guid << V >> {
  --
  default_definition : nvarchar(max)
  default_is_system_named : bit
  default_name : sysname
  definition : nvarchar(max)
  generated_always_type : tinyint
  graph_type : int
  has_different_sys_names : bit
  increment_value : sql_variant
  * is_computed : bit
  * is_identity : bit
  is_nullable : bit
  is_persisted : bit
  is_query_plan_expression : bit
  is_repo_managed : bit
  is_RepoObjectColumn_name_uniqueidentifier : int
  is_SysObjectColumn_missing : bit
  is_SysObjectColumn_name_uniqueidentifier : int
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  Repo_is_computed : bit
  Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  RepoObject_fullname : nvarchar(261)
  RepoObject_guid : uniqueidentifier
  RepoObjectColumn_guid : uniqueidentifier
  RepoObjectColumn_name : nvarchar(128)
  RowNumberOverName : bigint
  seed_value : sql_variant
  * SysObject_column_id : int
  SysObject_column_name : sysname
  SysObject_fullname : nvarchar(261)
  * SysObject_id : int
  SysObject_name : nvarchar(128)
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_RepoObjectColumn_guid : uniqueidentifier
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObjectColumn_column_id : int
  SysObjectColumn_name : nvarchar(128)
  user_type_fullname : nvarchar(182)
  user_type_name : sysname
  uses_database_collation : bit
}

entity repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
  default_definition : nvarchar(max)
  default_is_system_named : bit
  default_name : sysname
  definition : nvarchar(max)
  generated_always_type : tinyint
  graph_type : int
  has_different_sys_names : bit
  increment_value : sql_variant
  * is_computed : bit
  * is_identity : bit
  is_nullable : bit
  is_persisted : bit
  is_query_plan_expression : bit
  is_repo_managed : bit
  is_RepoObjectColumn_name_uniqueidentifier : int
  is_SysObjectColumn_missing : bit
  is_SysObjectColumn_name_uniqueidentifier : int
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  Repo_is_computed : bit
  Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  RepoObject_fullname : nvarchar(261)
  RepoObject_guid : uniqueidentifier
  RepoObjectColumn_guid : uniqueidentifier
  RepoObjectColumn_name : nvarchar(128)
  RowNumberOverName : bigint
  seed_value : sql_variant
  * SysObject_column_id : int
  SysObject_column_name : sysname
  SysObject_fullname : nvarchar(261)
  * SysObject_id : int
  SysObject_name : nvarchar(128)
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_RepoObjectColumn_guid : uniqueidentifier
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObjectColumn_column_id : int
  SysObjectColumn_name : nvarchar(128)
  user_type_fullname : nvarchar(182)
  user_type_name : sysname
  uses_database_collation : bit
}

entity repo.SysObject_RepoObject_via_guid << V >> {
  --
  history_table_guid : uniqueidentifier
  history_table_id : int
  is_repo_managed : bit
  is_RepoObject_name_uniqueidentifier : int
  is_SysObject_name_uniqueidentifier : int
  * modify_date : datetime
  * parent_object_id : int
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  RepoObject_guid : uniqueidentifier
  RepoObject_is_SysObject_missing : bit
  RepoObject_name : nvarchar(128)
  RepoObject_schema_name : nvarchar(128)
  RepoObject_SysObject_id : int
  RepoObject_SysObject_modify_date : datetime
  RepoObject_SysObject_name : nvarchar(128)
  RepoObject_SysObject_parent_object_id : int
  RepoObject_SysObject_schema_name : nvarchar(128)
  RepoObject_SysObject_type : char(2)
  RepoObject_type : char(2)
  * SysObject_id : int
  * SysObject_name : sysname
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_schema_name : sysname
  SysObject_type : char(2)
  temporal_type : tinyint
}

entity repo.SysObject_RepoObject_via_name << V >> {
  --
  history_table_guid : uniqueidentifier
  history_table_id : int
  is_repo_managed : bit
  is_RepoObject_name_uniqueidentifier : int
  is_SysObject_name_uniqueidentifier : int
  * modify_date : datetime
  * parent_object_id : int
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  RepoObject_guid : uniqueidentifier
  RepoObject_is_SysObject_missing : bit
  RepoObject_name : nvarchar(128)
  RepoObject_schema_name : nvarchar(128)
  RepoObject_SysObject_id : int
  RepoObject_SysObject_modify_date : datetime
  RepoObject_SysObject_name : nvarchar(128)
  RepoObject_SysObject_parent_object_id : int
  RepoObject_SysObject_schema_name : nvarchar(128)
  RepoObject_SysObject_type : char(2)
  RepoObject_type : char(2)
  * SysObject_id : int
  * SysObject_name : sysname
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_schema_name : sysname
  SysObject_type : char(2)
  temporal_type : tinyint
}

entity repo.usp_Index_finish << P >> {
  --
}

entity repo.usp_Index_virtual_set << P >> {
  --
}

entity repo.usp_persistence_set << P >> {
  --
}

entity repo.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity repo.usp_RepoObjectProperty_set << P >> {
  --
}

entity repo.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity repo.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity repo.usp_sync_guid_RepoObject << P >> {
  --
}

entity repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity repo.usp_update_Referencing_Count << P >> {
  --
}

entity repo_sys.ForeignKey << V >> {
  --
  * create_date : datetime
  delete_referential_action : tinyint
  delete_referential_action_desc : nvarchar(60)
  ForeignKey_fullname : nvarchar(261)
  ForeignKey_guid : uniqueidentifier
  * is_disabled : bit
  * is_ms_shipped : bit
  * is_not_for_replication : bit
  * is_not_trusted : bit
  * is_published : bit
  * is_schema_published : bit
  * is_system_named : bit
  key_index_id : int
  * modify_date : datetime
  * name : sysname
  * object_id : int
  * parent_object_id : int
  parent_RepoObject_fullname : nvarchar(261)
  parent_RepoObject_guid : uniqueidentifier
  parent_SysObject_fullname : nvarchar(261)
  principal_id : int
  referenced_object_id : int
  * schema_id : int
  type : char(2)
  type_desc : nvarchar(60)
  update_referential_action : tinyint
  update_referential_action_desc : nvarchar(60)
}

entity repo_sys.Index_unique << V >> {
  --
  index_guid : uniqueidentifier
  * index_id : int
  index_name : sysname
  * index_type : tinyint
  index_type_desc : nvarchar(60)
  is_index_disabled : bit
  is_index_primary_key : bit
  is_index_unique : bit
  is_index_unique_constraint : bit
  parent_RepoObject_guid : uniqueidentifier
  parent_schema_name : nvarchar(128)
  parent_SysObject_fullname : nvarchar(261)
  parent_SysObject_name : nvarchar(128)
}

entity repo_sys.RepoObjectReferenced << V >> {
  --
  has_different_sys_names : bit
  * is_all_columns_found : bit
  * is_ambiguous : bit
  * is_caller_dependent : bit
  * is_incomplete : bit
  * is_insert_all : bit
  is_repo_managed : bit
  * is_select_all : bit
  * is_selected : bit
  * is_updated : bit
  referenced_class : tinyint
  referenced_class_desc : nvarchar(60)
  referenced_database_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_id : int
  referenced_minor_id : int
  referenced_minor_name : nvarchar(128)
  referenced_schema_name : nvarchar(128)
  referenced_server_name : nvarchar(128)
  referencing_minor_id : int
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_guid : uniqueidentifier
  * SysObject_fullname : nvarchar(261)
  SysObject_id : int
  SysObject_modify_date : datetime
  SysObject_type : char(2)
}

entity repo_sys.RepoObjectReferencing << V >> {
  --
  has_different_sys_names : bit
  * is_caller_dependent : bit
  is_repo_managed : bit
  referencing_class : tinyint
  referencing_class_desc : nvarchar(60)
  referencing_entity_name : sysname
  * referencing_id : int
  referencing_schema_name : sysname
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_guid : uniqueidentifier
  * SysObject_fullname : nvarchar(261)
  SysObject_id : int
  SysObject_modify_date : datetime
  SysObject_type : char(2)
}

entity sqlparse.RepoObject_SqlModules_10_statement << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  children : nvarchar(max)
  class : nvarchar(500)
  is_group : bit
  is_keyword : bit
  is_whitespace : bit
  normalized : nvarchar(max)
  sql_modules_json : nvarchar(max)
  SysObject_fullname : nvarchar(261)
}

entity sqlparse.RepoObject_SqlModules_39_object << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_GroupBy : int
  is_1_create : int
  is_2_view : int
  is_3_Identifier : int
  is_4_as : int
  is_5_select : int
  is_6_Identifier : int
  is_6_IdentifierList : int
  is_7_from : int
  is_7_IdentifierList : int
  is_8_IdentifierList : int
  is_create_view_Identifier_as_select : int
  is_select_IdentifierList_from : int
  is_union : int
  Min_RowNumber_From : bigint
  Min_RowNumber_GroupBy : bigint
  Min_RowNumber_IdentifierList : bigint
  Min_RowNumber_Where : bigint
  SysObject_fullname : nvarchar(261)
}

entity sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias << V >> {
  --
  alias_QuoteName : nvarchar(max)
  normalized : nvarchar(max)
  * RepoObject_guid : uniqueidentifier
  * RepoObjectColumn_guid : uniqueidentifier
  * RepoObjectColumn_name : nvarchar(128)
  source_column_QuoteName : nvarchar(max)
  * source_RepoObject_guid : uniqueidentifier
  * source_RepoObjectColumn_guid : uniqueidentifier
  * source_RepoObjectColumn_name : nvarchar(128)
  * source_SysObject_fullname : nvarchar(261)
  source_table_QuoteName : nvarchar(max)
  SysObject_fullname : nvarchar(261)
}

entity sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias << V >> {
  --
  alias_QuoteName : nvarchar(max)
  normalized : nvarchar(max)
  * RepoObject_guid : uniqueidentifier
  * RepoObjectColumn_guid : uniqueidentifier
  * RepoObjectColumn_name : nvarchar(128)
  source_column_QuoteName : nvarchar(max)
  * source_RepoObject_guid : uniqueidentifier
  * source_RepoObjectColumn_guid : uniqueidentifier
  * source_RepoObjectColumn_name : nvarchar(128)
  * source_SysObject_fullname : nvarchar(261)
  source_table_QuoteName : nvarchar(max)
  SysObject_fullname : nvarchar(261)
}

entity sqlparse.RepoObject_SqlModules_Repo_Sys << V >> {
  --
  is_json_sql_modules_json : int
  is_outdated : bit
  * modify_date : datetime
  * RepoObject_guid : uniqueidentifier
  sql_modules_definition : nvarchar(max)
  sql_modules_dt : datetime
  sql_modules_formatted : nvarchar(max)
  sql_modules_formatted2 : nvarchar(max)
  sql_modules_json : nvarchar(max)
  SysObject_type : char(2)
}

entity uspgenerator.GeneratorUsp_SqlUsp << V >> {
  * **usp_id** : int
  --
  * AdocUspSteps : nvarchar(max)
  * has_logging : tinyint
  MS_Description : nvarchar(4000)
  RepoObject_guid : uniqueidentifier
  SqlStepList : nvarchar(max)
  * SqlUsp : nvarchar(max)
  usp_Description : nvarchar(4000)
  * usp_fullname : nvarchar(261)
  * usp_name : nvarchar(128)
  * usp_schema : nvarchar(128)
  * UspExamples : nvarchar(4000)
  UspParameters : nvarchar(max)
}

graph.RepoObject_S <.. repo.usp_sync_guid_RepoObject
repo.ftv_RepoObject_ReferencedReferencing <.. docs.RepoObject_Plantuml_ColRefList
repo.ftv_RepoObject_ReferencedReferencing <.. docs.RepoObject_Plantuml_ObjectRefList
repo.ftv_RepoObject_ReferencedReferencing <.. 
repo.ftv_RepoObject_ReferencedReferencing <.. 
repo.RepoObject <.. 
repo.RepoObject <.. repo.usp_RepoObjectProperty_set
repo.RepoObject <.. repo.Index_virtual_ForUpdate
repo.RepoObject <.. docs.ftv_RepoObject_Reference_PlantUml_EntityRefList
repo.RepoObject <.. repo.RepoObjectProperty_cross
repo.RepoObject <.. docs.RepoObject_Plantuml_ObjectRefList
repo.RepoObject <.. docs.AntoraNavListPage_by_schema
repo.RepoObject <.. repo.RepoObject_related_FK_union
repo.RepoObject <.. repo_sys.ForeignKey
repo.RepoObject <.. repo.usp_Index_finish
repo.RepoObject <.. repo.RepoObject_fullname_u_v
repo.RepoObject <.. repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn
repo.RepoObject <.. repo.ExtendedProperty_Repo2Sys_level1
repo.RepoObject <.. repo.ExtendedProperty_Repo2Sys_level2_RepoObject
repo.RepoObject <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObject <.. repo.RepoObject_RequiredRepoObjectMerge
repo.RepoObject <.. graph.RepoObject_S
repo.RepoObject <.. repo.RepoObjectColumn_reference_SqlModules
repo.RepoObject <.. 
repo.RepoObject <.. 
repo.RepoObject <.. 
repo.RepoObject <.. repo.usp_persistence_set
repo.RepoObject <.. repo.ftv_RepoObject_ReferencedReferencing
repo.RepoObject <.. docs.RepoObject_Plantuml_ColRefList
repo.RepoObject <.. repo.usp_RepoObjectSource_FirstResultSet
repo.RepoObject <.. repo.usp_sync_guid_RepoObject
repo.RepoObject <.. repo.RepoObjectColumn_MissingSource_TypeV
repo.RepoObject <.. repo.check_IndexColumn_virtual_referenced_setpoint
repo.RepoObject <.. repo.RepoObject_persistence_ForUpdate
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias
repo.RepoObject <.. repo.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject <.. repo.usp_Index_virtual_set
repo.RepoObject <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject <.. repo.Index_virtual_SysObject
repo.RepoObject <.. repo_sys.Index_unique
repo.RepoObject <.. repo.RepoObject_persistence_ObjectNames
repo.RepoObject <.. repo.IndexColumn_virtual_gross
repo.RepoObject <.. repo_sys.RepoObjectReferenced
repo.RepoObject <.. repo_sys.RepoObjectReferencing
repo.RepoObject <.. repo.RepoObject_reference_persistence
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_10_statement
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_39_object
repo.RepoObject <.. repo.RepoObjectColumn_reference_Persistence
repo.RepoObject <.. docs.visjs_nodelist_object_test01
repo.RepoObject <.. repo.RepoObject_persistence_column
repo.RepoObject <.. uspgenerator.GeneratorUsp_SqlUsp
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObject <.. repo.SysObject_RepoObject_via_guid
repo.RepoObject <.. repo.RepoObjectProperty_sys_repo
repo.RepoObject <.. repo.SysObject_RepoObject_via_name
repo.RepoObject <.. sqlparse.RepoObject_SqlModules_Repo_Sys
repo.RepoObject <.. repo.RepoObjectColumnProperty_sys_repo
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObjectColumn_reference_FirstResultSet
repo.RepoObject <.. repo.RepoObject_SqlCreateTable
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObject <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObject <.. repo.usp_update_Referencing_Count
repo.RepoObject_gross <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObject_gross <.. repo.RepoObject_SqlCreateTable
repo.RepoObject_gross <.. repo.usp_RepoObject_update_SysObjectQueryPlan
repo.RepoObject_gross <.. repo.usp_RepoObjectSource_FirstResultSet
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_RequiredRepoObjectMerge <.. repo.usp_sync_guid_RepoObject
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_reference_FirstResultSet
repo.SysColumn_RepoObjectColumn_via_guid <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysObject_RepoObject_via_guid <.. repo.usp_sync_guid_RepoObject
repo.SysObject_RepoObject_via_name <.. repo.usp_sync_guid_RepoObject
repo_sys.RepoObjectReferenced <.. repo.usp_update_Referencing_Count
repo_sys.RepoObjectReferencing <.. repo.usp_update_Referencing_Count
sqlparse.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_gross
repo.RepoObject::has_different_sys_names <-- repo_sys.RepoObjectReferenced::has_different_sys_names
repo.RepoObject::has_different_sys_names <-- repo_sys.RepoObjectReferencing::has_different_sys_names
repo.RepoObject::has_different_sys_names <-- repo.RepoObject_gross::has_different_sys_names
repo.RepoObject::has_execution_plan_issue <-- repo.RepoObject_gross::has_execution_plan_issue
repo.RepoObject::has_get_referenced_issue <-- repo.RepoObject_gross::has_get_referenced_issue
repo.RepoObject::has_get_referenced_issue <-- repo.RepoObjectColumn_gross::has_get_referenced_issue
repo.RepoObject::Inheritance_StringAggSeparatorSql <-- repo.RepoObject_gross::Inheritance_StringAggSeparatorSql
repo.RepoObject::Inheritance_StringAggSeparatorSql <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::Inheritance_StringAggSeparatorSql
repo.RepoObject::Inheritance_StringAggSeparatorSql <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::ro_Inheritance_StringAggSeparatorSql
repo.RepoObject::InheritanceDefinition <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::ro_InheritanceDefinition
repo.RepoObject::InheritanceDefinition <-- repo.RepoObject_gross::InheritanceDefinition
repo.RepoObject::InheritanceType <-- repo.RepoObject_gross::InheritanceType
repo.RepoObject::InheritanceType <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::ro_InheritanceType
repo.RepoObject::is_repo_managed <-- repo.RepoObject_gross::is_repo_managed
repo.RepoObject::is_repo_managed <-- repo.RepoObjectColumn_gross::is_repo_managed
repo.RepoObject::is_repo_managed <-- repo.SysObject_RepoObject_via_guid::is_repo_managed
repo.RepoObject::is_repo_managed <-- repo.SysColumn_RepoObjectColumn_via_guid::is_repo_managed
repo.RepoObject::is_repo_managed <-- repo.SysColumn_RepoObjectColumn_via_name::is_repo_managed
repo.RepoObject::is_repo_managed <-- repo_sys.RepoObjectReferencing::is_repo_managed
repo.RepoObject::is_repo_managed <-- repo.SysObject_RepoObject_via_name::is_repo_managed
repo.RepoObject::is_repo_managed <-- repo_sys.RepoObjectReferenced::is_repo_managed
repo.RepoObject::is_RepoObject_name_uniqueidentifier <-- repo.SysObject_RepoObject_via_name::is_RepoObject_name_uniqueidentifier
repo.RepoObject::is_RepoObject_name_uniqueidentifier <-- repo.SysObject_RepoObject_via_guid::is_RepoObject_name_uniqueidentifier
repo.RepoObject::is_RepoObject_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_RepoObject_name_uniqueidentifier
repo.RepoObject::is_RepoObject_name_uniqueidentifier <-- repo.RepoObject_gross::is_RepoObject_name_uniqueidentifier
repo.RepoObject::is_required_ObjectMerge <-- repo.RepoObject_gross::is_required_ObjectMerge
repo.RepoObject::is_SysObject_missing <-- repo.RepoObject_gross::is_SysObject_missing
repo.RepoObject::is_SysObject_missing <-- repo.RepoObjectColumn_gross::is_SysObject_missing
repo.RepoObject::is_SysObject_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_SysObject_name_uniqueidentifier
repo.RepoObject::is_SysObject_name_uniqueidentifier <-- repo.SysObject_RepoObject_via_guid::is_SysObject_name_uniqueidentifier
repo.RepoObject::is_SysObject_name_uniqueidentifier <-- repo.SysObject_RepoObject_via_name::is_SysObject_name_uniqueidentifier
repo.RepoObject::is_SysObject_name_uniqueidentifier <-- repo.RepoObject_gross::is_SysObject_name_uniqueidentifier
repo.RepoObject::modify_dt <-- repo.RepoObject_gross::modify_dt
repo.RepoObject::modify_dt <-- repo.RepoObjectColumn_gross::modify_dt
repo.RepoObject::node_id <-- repo.RepoObjectColumn_gross::node_id
repo.RepoObject::node_id <-- docs.visjs_nodelist_object_test01::node_id
repo.RepoObject::node_id <-- repo.RepoObject_reference_persistence::referenced_node_id
repo.RepoObject::node_id <-- repo.RepoObject_reference_persistence::referencing_node_id
repo.RepoObject::node_id <-- repo.RepoObjectColumn_reference_Persistence::referenced_node_id
repo.RepoObject::node_id <-- repo.RepoObjectColumn_reference_Persistence::referencing_node_id
repo.RepoObject::node_id <-- repo.RepoObject_gross::node_id
repo.RepoObject::node_id <-- repo.RepoObjectColumn_reference_SqlModules::referenced_node_id
repo.RepoObject::node_id <-- repo.RepoObjectColumn_reference_SqlModules::referencing_node_id
repo.RepoObject::pk_index_guid <-- repo.RepoObject_gross::pk_index_guid
repo.RepoObject::pk_index_guid <-- repo.Index_virtual_SysObject::pk_index_guid
repo.RepoObject::pk_index_guid <-- repo.RepoObjectColumn_gross::pk_index_guid
repo.RepoObject::pk_IndexPatternColumnName_new <-- repo.RepoObject_gross::pk_IndexPatternColumnName_new
repo.RepoObject::Repo_history_table_guid <-- repo.RepoObject_gross::Repo_history_table_guid
repo.RepoObject::Repo_history_table_guid <-- repo.SysObject_RepoObject_via_guid::Repo_history_table_guid
repo.RepoObject::Repo_history_table_guid <-- repo.SysObject_RepoObject_via_name::Repo_history_table_guid
repo.RepoObject::Repo_temporal_type <-- repo.SysObject_RepoObject_via_name::Repo_temporal_type
repo.RepoObject::Repo_temporal_type <-- repo.SysObject_RepoObject_via_guid::Repo_temporal_type
repo.RepoObject::Repo_temporal_type <-- repo.RepoObject_gross::Repo_temporal_type
repo.RepoObject::RepoObject_fullname <-- repo.RepoObject_gross::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo.RepoObjectColumn_MissingSource_TypeV::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- graph.RepoObject_S::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo.RepoObject_RequiredRepoObjectMerge::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo.SysColumn_RepoObjectColumn_via_guid::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo.SysColumn_RepoObjectColumn_via_name::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo.RepoObjectColumn_gross::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo_sys.RepoObjectReferencing::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo_sys.RepoObjectReferenced::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo.RepoObject_reference_persistence::referencing_fullname
repo.RepoObject::RepoObject_fullname <-- repo.RepoObject_reference_persistence::referenced_fullname
repo.RepoObject::RepoObject_fullname <-- repo.Index_virtual_ForUpdate::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo_sys.ForeignKey::parent_RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo_sys.ForeignKey::ForeignKey_fullname
repo.RepoObject::RepoObject_fullname <-- repo.RepoObject_fullname_u_v::RepoObject_fullname
repo.RepoObject::RepoObject_fullname2 <-- repo.Index_virtual_ForUpdate::RepoObject_fullname2
repo.RepoObject::RepoObject_fullname2 <-- repo.RepoObjectColumn_gross::RepoObject_fullname2
repo.RepoObject::RepoObject_fullname2 <-- repo.RepoObject_gross::RepoObject_fullname2
repo.RepoObject::RepoObject_guid <-- repo.RepoObject_gross::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo.RepoObject_RequiredRepoObjectMerge::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn::parent_RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObject::parent_RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- graph.RepoObject_S::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias::source_RepoObject_guid
repo.RepoObject::RepoObject_guid <-- sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias::source_RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo.SysObject_RepoObject_via_guid::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo_sys.RepoObjectReferenced::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo_sys.Index_unique::index_guid
repo.RepoObject::RepoObject_guid <-- repo_sys.Index_unique::parent_RepoObject_guid
repo.RepoObject::RepoObject_guid <-- docs.visjs_nodelist_object_test01::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo_sys.RepoObjectReferencing::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- uspgenerator.GeneratorUsp_SqlUsp::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo.SysObject_RepoObject_via_name::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- sqlparse.RepoObject_SqlModules_Repo_Sys::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo.RepoObjectProperty_sys_repo::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo.RepoObjectProperty_cross::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo_sys.ForeignKey::parent_RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo_sys.ForeignKey::ForeignKey_guid
repo.RepoObject::RepoObject_name <-- repo.SysObject_RepoObject_via_name::RepoObject_name
repo.RepoObject::RepoObject_name <-- repo.SysObject_RepoObject_via_guid::RepoObject_name
repo.RepoObject::RepoObject_name <-- repo.RepoObjectColumn_gross::RepoObject_name
repo.RepoObject::RepoObject_name <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObject::level2name
repo.RepoObject::RepoObject_name <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObject::level1name
repo.RepoObject::RepoObject_name <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn::level1name
repo.RepoObject::RepoObject_name <-- repo.ExtendedProperty_Repo2Sys_level1::level1name
repo.RepoObject::RepoObject_name <-- repo.RepoObject_RequiredRepoObjectMerge::RepoObject_name
repo.RepoObject::RepoObject_name <-- repo.RepoObject_gross::RepoObject_name
repo.RepoObject::RepoObject_Referencing_Count <-- repo.RepoObject_gross::RepoObject_Referencing_Count
repo.RepoObject::RepoObject_Referencing_Count <-- repo.RepoObjectColumn_gross::RepoObject_Referencing_Count
repo.RepoObject::RepoObject_schema_name <-- repo.RepoObjectColumn_gross::RepoObject_schema_name
repo.RepoObject::RepoObject_schema_name <-- repo.SysObject_RepoObject_via_guid::RepoObject_schema_name
repo.RepoObject::RepoObject_schema_name <-- repo.SysObject_RepoObject_via_name::RepoObject_schema_name
repo.RepoObject::RepoObject_schema_name <-- repo.RepoObject_gross::RepoObject_schema_name
repo.RepoObject::RepoObject_schema_name <-- repo.RepoObject_RequiredRepoObjectMerge::RepoObject_schema_name
repo.RepoObject::RepoObject_schema_name <-- repo.ExtendedProperty_Repo2Sys_level1::level0name
repo.RepoObject::RepoObject_schema_name <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObject::level0name
repo.RepoObject::RepoObject_schema_name <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn::level0name
repo.RepoObject::RepoObject_schema_name <-- docs.AntoraNavListPage_by_schema::RepoObject_schema_name
repo.RepoObject::RepoObject_type <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_type
repo.RepoObject::RepoObject_type <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObject::RepoObject_type
repo.RepoObject::RepoObject_type <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObject::parent_RepoObject_type
repo.RepoObject::RepoObject_type <-- repo.ExtendedProperty_Repo2Sys_level1::RepoObject_type
repo.RepoObject::RepoObject_type <-- repo.ExtendedProperty_Repo2Sys_level2_RepoObjectColumn::parent_RepoObject_type
repo.RepoObject::RepoObject_type <-- graph.RepoObject_S::RepoObject_type
repo.RepoObject::RepoObject_type <-- repo.RepoObject_gross::RepoObject_type
repo.RepoObject::RepoObject_type <-- repo.SysObject_RepoObject_via_name::RepoObject_type
repo.RepoObject::RepoObject_type <-- repo.SysObject_RepoObject_via_guid::RepoObject_type
repo.RepoObject::RepoObject_type <-- repo.RepoObjectColumn_gross::RepoObject_type
repo.RepoObject::SysObject_fullname <-- repo.RepoObjectColumn_gross::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo.SysColumn_RepoObjectColumn_via_name::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo_sys.RepoObjectReferencing::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- docs.visjs_nodelist_object_test01::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo_sys.Index_unique::parent_SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo_sys.RepoObjectReferenced::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- sqlparse.RepoObject_SqlModules_10_statement::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- sqlparse.RepoObject_SqlModules_39_object::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo.RepoObject_gross::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo.RepoObjectColumn_MissingSource_TypeV::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- sqlparse.RepoObject_SqlModules_72_reference_NoTableAlias::source_SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo.RepoObject_RequiredRepoObjectMerge::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- sqlparse.RepoObject_SqlModules_71_reference_ExpliciteTableAlias::source_SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo.Index_virtual_ForUpdate::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo_sys.ForeignKey::parent_SysObject_fullname
repo.RepoObject::SysObject_fullname2 <-- repo.Index_virtual_ForUpdate::SysObject_fullname2
repo.RepoObject::SysObject_fullname2 <-- repo.RepoObject_gross::SysObject_fullname2
repo.RepoObject::SysObject_fullname2 <-- repo.RepoObjectColumn_gross::SysObject_fullname2
repo.RepoObject::SysObject_id <-- repo.RepoObjectColumn_gross::SysObject_id
repo.RepoObject::SysObject_id <-- repo.SysObject_RepoObject_via_guid::SysObject_id
repo.RepoObject::SysObject_id <-- repo.RepoObjectColumn_reference_Persistence::referenced_id
repo.RepoObject::SysObject_id <-- repo.RepoObjectColumn_reference_Persistence::referencing_id
repo.RepoObject::SysObject_id <-- repo.RepoObject_reference_persistence::referencing_id
repo.RepoObject::SysObject_id <-- repo.RepoObject_reference_persistence::referenced_id
repo.RepoObject::SysObject_id <-- repo_sys.RepoObjectReferenced::SysObject_id
repo.RepoObject::SysObject_id <-- repo.Index_virtual_SysObject::SysObject_id
repo.RepoObject::SysObject_id <-- repo_sys.RepoObjectReferencing::SysObject_id
repo.RepoObject::SysObject_id <-- repo.SysObject_RepoObject_via_name::SysObject_id
repo.RepoObject::SysObject_id <-- repo.RepoObject_gross::SysObject_id
repo.RepoObject::SysObject_id <-- repo.RepoObjectColumn_reference_SqlModules::referencing_id
repo.RepoObject::SysObject_id <-- repo.RepoObjectColumn_reference_SqlModules::referenced_id
repo.RepoObject::SysObject_modify_date <-- repo.RepoObject_gross::SysObject_modify_date
repo.RepoObject::SysObject_modify_date <-- repo_sys.RepoObjectReferencing::SysObject_modify_date
repo.RepoObject::SysObject_modify_date <-- repo_sys.RepoObjectReferenced::SysObject_modify_date
repo.RepoObject::SysObject_modify_date <-- repo.RepoObjectColumn_gross::SysObject_modify_date
repo.RepoObject::SysObject_name <-- repo.RepoObjectColumn_gross::SysObject_name
repo.RepoObject::SysObject_name <-- repo.SysObject_RepoObject_via_guid::SysObject_name
repo.RepoObject::SysObject_name <-- repo_sys.Index_unique::parent_SysObject_name
repo.RepoObject::SysObject_name <-- repo.Index_virtual_SysObject::SysObject_name
repo.RepoObject::SysObject_name <-- repo.RepoObject_reference_persistence::referenced_entity_name
repo.RepoObject::SysObject_name <-- repo.RepoObject_reference_persistence::referencing_entity_name
repo.RepoObject::SysObject_name <-- repo.RepoObjectColumn_reference_Persistence::referenced_entity_name
repo.RepoObject::SysObject_name <-- repo.RepoObjectColumn_reference_Persistence::referencing_entity_name
repo.RepoObject::SysObject_name <-- repo.SysObject_RepoObject_via_name::SysObject_name
repo.RepoObject::SysObject_name <-- repo.RepoObject_gross::SysObject_name
repo.RepoObject::SysObject_name <-- repo.RepoObjectColumn_reference_SqlModules::referenced_entity_name
repo.RepoObject::SysObject_name <-- repo.RepoObjectColumn_reference_SqlModules::referencing_entity_name
repo.RepoObject::SysObject_name <-- repo.RepoObject_RequiredRepoObjectMerge::SysObject_name
repo.RepoObject::SysObject_parent_object_id <-- repo.RepoObject_gross::SysObject_parent_object_id
repo.RepoObject::SysObject_parent_object_id <-- repo.RepoObjectColumn_gross::SysObject_parent_object_id
repo.RepoObject::SysObject_query_sql <-- repo.RepoObject_gross::SysObject_query_sql
repo.RepoObject::SysObject_schema_name <-- repo.RepoObject_gross::SysObject_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.RepoObject_RequiredRepoObjectMerge::SysObject_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.RepoObjectColumn_reference_SqlModules::referenced_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.RepoObjectColumn_reference_SqlModules::referencing_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.RepoObjectColumn_gross::SysObject_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.SysObject_RepoObject_via_guid::SysObject_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.SysObject_RepoObject_via_name::SysObject_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.RepoObjectColumn_reference_Persistence::referencing_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.RepoObjectColumn_reference_Persistence::referenced_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.RepoObject_reference_persistence::referenced_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.RepoObject_reference_persistence::referencing_schema_name
repo.RepoObject::SysObject_schema_name <-- repo.Index_virtual_SysObject::SysObject_schema_name
repo.RepoObject::SysObject_schema_name <-- repo_sys.Index_unique::parent_schema_name
repo.RepoObject::SysObject_type <-- repo_sys.RepoObjectReferenced::SysObject_type
repo.RepoObject::SysObject_type <-- repo.Index_virtual_SysObject::SysObject_type
repo.RepoObject::SysObject_type <-- docs.visjs_nodelist_object_test01::SysObject_type
repo.RepoObject::SysObject_type <-- repo.RepoObject_reference_persistence::referenced_type
repo.RepoObject::SysObject_type <-- repo.RepoObjectColumn_reference_Persistence::referenced_type
repo.RepoObject::SysObject_type <-- repo.RepoObjectColumn_reference_Persistence::referencing_type
repo.RepoObject::SysObject_type <-- repo.SysObject_RepoObject_via_name::SysObject_type
repo.RepoObject::SysObject_type <-- sqlparse.RepoObject_SqlModules_Repo_Sys::SysObject_type
repo.RepoObject::SysObject_type <-- repo_sys.RepoObjectReferencing::SysObject_type
repo.RepoObject::SysObject_type <-- repo.SysObject_RepoObject_via_guid::SysObject_type
repo.RepoObject::SysObject_type <-- repo.RepoObjectColumn_gross::SysObject_type
repo.RepoObject::SysObject_type <-- repo.RepoObjectColumn_reference_SqlModules::referencing_type
repo.RepoObject::SysObject_type <-- repo.RepoObjectColumn_reference_SqlModules::referenced_type
repo.RepoObject::SysObject_type <-- repo.RepoObject_gross::SysObject_type
repo.RepoObject::usp_persistence_name <-- repo.RepoObject_gross::usp_persistence_name
repo.RepoObject_gross::is_persistence <-- repo.Index_virtual_ForUpdate::is_persistence
repo.RepoObject_gross::is_repo_managed <-- repo.Index_virtual_ForUpdate::is_repo_managed
sqlparse.RepoObject_SqlModules_Repo_Sys::sql_modules_definition <-- repo.RepoObject_gross::sql_modules_definition
sqlparse.RepoObject_SqlModules_Repo_Sys::sql_modules_formatted <-- repo.RepoObject_gross::sql_modules_formatted
sqlparse.RepoObject_SqlModules_Repo_Sys::sql_modules_formatted2 <-- repo.RepoObject_gross::sql_modules_formatted2
