left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.ProcedureInstanceDependency << U >> {
  * **id** : int
  --
  Description : nvarchar(4000)
  * is_active : bit
  * is_PersistenceDependency : bit
  * referenced_id : int
  * referencing_id : int
}

entity repo.ProcedureInstanceDependency_gross << V >> {
  * **id** : int
  --
  Description : nvarchar(4000)
  * is_active : bit
  * is_PersistenceDependency : bit
  * referenced_id : int
  * referenced_Instance : varchar(500)
  * referenced_Procedure_RepoObject_guid : uniqueidentifier
  * referenced_RepoObject_fullname : nvarchar(261)
  * referencing_id : int
  * referencing_Instance : varchar(500)
  * referencing_Procedure_RepoObject_guid : uniqueidentifier
  * referencing_RepoObject_fullname : nvarchar(261)
}

repo.ProcedureInstanceDependency <.. repo.ProcedureInstanceDependency_gross
repo.ProcedureInstanceDependency::Description <-- repo.ProcedureInstanceDependency_gross::Description
repo.ProcedureInstanceDependency::id <-- repo.ProcedureInstanceDependency_gross::id
repo.ProcedureInstanceDependency::is_active <-- repo.ProcedureInstanceDependency_gross::is_active
repo.ProcedureInstanceDependency::is_PersistenceDependency <-- repo.ProcedureInstanceDependency_gross::is_PersistenceDependency
repo.ProcedureInstanceDependency::referenced_id <-- repo.ProcedureInstanceDependency_gross::referenced_id
repo.ProcedureInstanceDependency::referencing_id <-- repo.ProcedureInstanceDependency_gross::referencing_id
