left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.Index_IndexPattern << V >> {
  **index_guid** : uniqueidentifier
  --
  IndexPatternColumnDatatype : nvarchar(4000)
  IndexPatternColumnName : nvarchar(4000)
}

entity repo.IndexColumn_union << V >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  --
  index_name : nvarchar(128)
  is_descending_key : bit
  is_index_primary_key : bit
  is_index_real : bit
  is_index_unique : bit
  parent_RepoObject_guid : uniqueidentifier
  parent_schema_name : nvarchar(128)
  parent_SysObject_fullname : nvarchar(261)
  parent_SysObject_name : nvarchar(128)
  RepoObjectColumn_guid : uniqueidentifier
  SysObject_column_name : nvarchar(128)
  SysObject_column_user_type_fullname : nvarchar(182)
}

entity repo.usp_Index_Settings << P >> {
  --
}

repo.Index_IndexPattern <.. repo.usp_Index_Settings
repo.IndexColumn_union <.. repo.Index_IndexPattern
repo.IndexColumn_union::index_guid <-- repo.Index_IndexPattern::index_guid
