left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.Index_referencing_IndexPatternColumnGuid << V >> {
  **source_index_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
  --
  referencing_IndexPatternColumnGuid : varchar(8000)
}

entity repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  **RowNumberInReferencing** : bigint
  --
  is_descending_key : bit
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
}

entity repo.IndexReferencedReferencing_HasFullColumnsInReferencing << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
  --
  referenced_index_guid : uniqueidentifier
  referencing_IndexPatternColumnGuid : varchar(8000)
  RowNumberInReferencing : bigint
  RowNumberInReferencing_Target : int
  source_index_guid : uniqueidentifier
  * source_index_type : tinyint
}

repo.Index_referencing_IndexPatternColumnGuid <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.IndexReferencedReferencing_HasFullColumnsInReferencing
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.Index_referencing_IndexPatternColumnGuid
repo.Index_referencing_IndexPatternColumnGuid::referencing_IndexPatternColumnGuid <-- repo.IndexReferencedReferencing_HasFullColumnsInReferencing::referencing_IndexPatternColumnGuid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::index_guid <-- repo.Index_referencing_IndexPatternColumnGuid::source_index_guid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::referencing_RepoObject_guid <-- repo.Index_referencing_IndexPatternColumnGuid::referencing_RepoObject_guid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::RowNumberInReferencing <-- repo.IndexReferencedReferencing_HasFullColumnsInReferencing::RowNumberInReferencing
