left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
  * InformationSource : varchar(37)
  is_hidden : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  referenced_column_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_id : int
  referenced_minor_id : int
  referenced_node_id : bigint
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_column_name : nvarchar(128)
  * referencing_entity_name : nvarchar(128)
  referencing_id : int
  referencing_minor_id : int
  referencing_node_id : bigint
  * referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
  * referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
}

entity repo.RepoObjectSource_FirstResultSet << U >> {
  * **RepoObject_guid** : uniqueidentifier
  * **column_ordinal** : int
  --
  * created_dt : datetime
  is_hidden : bit
  source_column_name : nvarchar(128)
  source_database_name : nvarchar(128)
  source_schema_name : nvarchar(128)
  source_server_name : nvarchar(128)
  source_table_name : nvarchar(128)
  system_type_id : int
  system_type_name : nvarchar(128)
  target_column_name : nvarchar(128)
}

entity repo.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

repo.RepoObjectSource_FirstResultSet <.. repo.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectSource_FirstResultSet <.. repo.usp_RepoObjectSource_FirstResultSet
repo.RepoObjectSource_FirstResultSet::is_hidden <-- repo.RepoObjectColumn_reference_FirstResultSet::is_hidden
