left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.Index_gross << V >> {
  * **index_guid** : uniqueidentifier
  --
  AntoraIndexColumnList : nvarchar(max)
  ColumnList : nvarchar(max)
  ConstraintColumnList : nvarchar(max)
  DbmlIndexColumnList : nvarchar(max)
  index_name : nvarchar(128)
  * index_type : tinyint
  IndexPatternColumnDatatype : nvarchar(4000)
  IndexPatternColumnName : nvarchar(4000)
  IndexSemanticGroup : nvarchar(512)
  is_index_disabled : bit
  is_index_primary_key : bit
  is_index_real : bit
  is_index_unique : bit
  is_persistence : bit
  is_repo_managed : bit
  parent_RepoObject_guid : uniqueidentifier
  PersistenceWhereColumnList : nvarchar(max)
  PumlIndexColumnList : nvarchar(max)
  referenced_index_guid : uniqueidentifier
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  RowNumber_PatternPerParentObject : bigint
  RowNumber_PkPerParentObject : bigint
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
  SysObject_id : int
  * SysObject_name : nvarchar(128)
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
}

entity repo.Index_Settings << U >> {
  * **index_guid** : uniqueidentifier
  --
  IndexPatternColumnDatatype : nvarchar(4000)
  IndexPatternColumnName : nvarchar(4000)
  IndexSemanticGroup : nvarchar(512)
  * is_create_constraint : bit
}

entity repo.Index_SqlConstraint_PkUq << V >> {
  **index_guid** : uniqueidentifier
  --
  parent_RepoObject_guid : uniqueidentifier
  * SqlConstraint : nvarchar(max)
}

entity repo.Index_virtual_ForUpdate << V >> {
  * **index_guid** : uniqueidentifier
  --
  * has_managedName : bit
  index_name : nvarchar(128)
  * index_type : tinyint
  IndexPatternColumnDatatype : nvarchar(4000)
  IndexPatternColumnName : nvarchar(4000)
  IndexSemanticGroup : nvarchar(512)
  * is_index_disabled : bit
  * is_index_primary_key : bit
  * is_index_unique : bit
  is_persistence : bit
  is_repo_managed : bit
  * parent_RepoObject_guid : uniqueidentifier
  referenced_index_guid : uniqueidentifier
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  RowNumberInReferencing : int
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
}

entity repo.Index_virtual_SysObject << V >> {
  * **index_guid** : uniqueidentifier
  --
  index_name : nvarchar(128)
  IndexPatternColumnDatatype : nvarchar(4000)
  IndexPatternColumnName : nvarchar(4000)
  IndexSemanticGroup : nvarchar(512)
  * is_index_disabled : bit
  * is_index_primary_key : bit
  * is_index_unique : bit
  * parent_RepoObject_guid : uniqueidentifier
  pk_index_guid : uniqueidentifier
  referenced_index_guid : uniqueidentifier
  SysObject_id : int
  * SysObject_name : nvarchar(128)
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  AntoraReferencedList : nvarchar(max)
  AntoraReferencingList : nvarchar(max)
  CreateColumnList : nvarchar(max)
  DbmlColumnList : nvarchar(max)
  has_different_sys_names : bit
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  has_history : bit
  has_history_columns : bit
  history_schema_name : nvarchar(128)
  history_table_name : nvarchar(128)
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_DocsOutput : int
  * is_in_reference : int
  is_persistence : bit
  is_persistence_check_duplicate_per_pk : bit
  is_persistence_check_for_empty_source : bit
  is_persistence_delete_changed : bit
  is_persistence_delete_missing : bit
  is_persistence_insert : bit
  is_persistence_truncate : bit
  is_persistence_update_changed : bit
  is_repo_managed : bit
  * is_RepoObject_name_uniqueidentifier : int
  is_required_ObjectMerge : bit
  is_SysObject_missing : bit
  * is_SysObject_name_uniqueidentifier : int
  * modify_dt : datetime
  node_id : bigint
  persistence_source_RepoObject_fullname : nvarchar(261)
  persistence_source_RepoObject_fullname2 : nvarchar(257)
  persistence_source_RepoObject_guid : uniqueidentifier
  persistence_source_RepoObject_xref : nvarchar(269)
  persistence_source_SysObject_fullname : nvarchar(261)
  persistence_source_SysObject_fullname2 : nvarchar(257)
  persistence_source_SysObject_xref : nvarchar(269)
  PersistenceCompareColumnList : nvarchar(max)
  PersistenceInsertColumnList : nvarchar(max)
  PersistenceUpdateColumnList : nvarchar(max)
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnDatatype : nvarchar(4000)
  pk_IndexPatternColumnName : nvarchar(4000)
  pk_IndexPatternColumnName_new : nvarchar(4000)
  pk_IndexSemanticGroup : nvarchar(512)
  Property_ms_description : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  RepoObject_type_name : nvarchar(128)
  sql_modules_antora : nvarchar(max)
  sql_modules_definition : nvarchar(max)
  sql_modules_formatted : nvarchar(max)
  sql_modules_formatted2 : nvarchar(max)
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  SysObject_query_executed_dt : datetime
  SysObject_query_plan : xml
  * SysObject_query_sql : nvarchar(406)
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObject_type_name : nvarchar(128)
  temporal_type : tinyint
  * usp_persistence_name : nvarchar(140)
  usp_persistence_RepoObject_guid : uniqueidentifier
}

entity repo.usp_Index_finish << P >> {
  --
}

entity repo.usp_Index_Settings << P >> {
  --
}

repo.Index_gross <.. repo.usp_Index_finish
repo.Index_Settings <.. repo.usp_Index_Settings
repo.Index_Settings <.. repo.Index_SqlConstraint_PkUq
repo.Index_Settings <.. repo.RepoObject_gross
repo.Index_Settings <.. repo.usp_Index_finish
repo.Index_Settings <.. repo.Index_virtual_SysObject
repo.Index_Settings <.. repo.Index_gross
repo.Index_Settings <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.RepoObject_gross <.. repo.Index_gross
repo.usp_Index_Settings <.. repo.usp_Index_finish
repo.Index_Settings::index_guid <-- repo.Index_gross::index_guid
repo.Index_Settings::IndexPatternColumnDatatype <-- repo.Index_gross::IndexPatternColumnDatatype
repo.Index_Settings::IndexPatternColumnDatatype <-- repo.Index_virtual_SysObject::IndexPatternColumnDatatype
repo.Index_Settings::IndexPatternColumnDatatype <-- repo.Index_virtual_ForUpdate::IndexPatternColumnDatatype
repo.Index_Settings::IndexPatternColumnName <-- repo.Index_virtual_ForUpdate::IndexPatternColumnName
repo.Index_Settings::IndexPatternColumnName <-- repo.Index_virtual_SysObject::IndexPatternColumnName
repo.Index_Settings::IndexPatternColumnName <-- repo.Index_gross::IndexPatternColumnName
repo.Index_Settings::IndexSemanticGroup <-- repo.Index_gross::IndexSemanticGroup
repo.Index_Settings::IndexSemanticGroup <-- repo.Index_virtual_SysObject::IndexSemanticGroup
repo.Index_Settings::IndexSemanticGroup <-- repo.Index_virtual_ForUpdate::IndexSemanticGroup
repo.RepoObject_gross::is_persistence <-- repo.Index_virtual_ForUpdate::is_persistence
repo.RepoObject_gross::is_persistence <-- repo.Index_gross::is_persistence
repo.RepoObject_gross::is_repo_managed <-- repo.Index_gross::is_repo_managed
repo.RepoObject_gross::is_repo_managed <-- repo.Index_virtual_ForUpdate::is_repo_managed
repo.RepoObject_gross::RepoObject_fullname <-- repo.Index_gross::RepoObject_fullname
repo.RepoObject_gross::RepoObject_fullname2 <-- repo.Index_gross::RepoObject_fullname2
repo.RepoObject_gross::SysObject_fullname <-- repo.Index_gross::SysObject_fullname
repo.RepoObject_gross::SysObject_fullname2 <-- repo.Index_gross::SysObject_fullname2
repo.RepoObject_gross::SysObject_id <-- repo.Index_gross::SysObject_id
repo.RepoObject_gross::SysObject_name <-- repo.Index_gross::SysObject_name
repo.RepoObject_gross::SysObject_schema_name <-- repo.Index_gross::SysObject_schema_name
repo.RepoObject_gross::SysObject_type <-- repo.Index_gross::SysObject_type
