left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.Parameter << U >> {
  * **Parameter_name** : varchar(100)
  * **sub_Parameter** : nvarchar(128)
  --
  Parameter_default_value : sql_variant
  Parameter_desciption : nvarchar(1000)
  Parameter_value : sql_variant
  {abstract} Parameter_value__result_int : int
  {abstract} Parameter_value__result_nvarchar : nvarchar(4000)
}

entity repo.PropertyName_RepoObject << V >> {
  * **property_name** : nvarchar(128)
  --
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_repo_managed : bit
  is_required_ObjectMerge : bit
  is_SysObject_missing : bit
  * modify_dt : datetime
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnName_new : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObject_name_uniqueidentifier : int
  * {static} is_SysObject_name_uniqueidentifier : int
  {abstract} node_id : bigint
  * {static} RepoObject_fullname : nvarchar(261)
  * {static} RepoObject_fullname2 : nvarchar(257)
  * {static} SysObject_fullname : nvarchar(261)
  * {static} SysObject_fullname2 : nvarchar(257)
  * {abstract} SysObject_query_sql : nvarchar(406)
  * {static} usp_persistence_name : nvarchar(140)
}

entity repo.RepoObjectProperty << U >> {
  * **RepoObjectProperty_id** : int
  --
  inheritance : tinyint
  * property_name : nvarchar(128)
  property_value : sql_variant
  * RepoObject_guid : uniqueidentifier
  {abstract} property_basetype : sql_variant
  {abstract} property_bigint : bigint
  {abstract} property_float : float
  {abstract} property_int : int
  {abstract} property_money : money
  {abstract} property_nvarchar : nvarchar(4000)
  {abstract} property_real : real
  {abstract} property_varchar : varchar(8000)
}

entity repo.RepoObjectProperty_InheritanceType_InheritanceDefinition << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **property_name** : nvarchar(128)
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : int
  par_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  par_InheritanceDefintion : nvarchar(4000)
  par_InheritanceType : int
  property_value : sql_variant
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_type : char(2)
  ro_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  ro_InheritanceDefinition : nvarchar(4000)
  ro_InheritanceType : tinyint
  sub_Inheritance_StringAggSeparatorSql : nvarchar(4000)
  sub_InheritanceDefintion : nvarchar(4000)
  sub_InheritanceType : int
}

entity repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition << V >> {
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : int
  * is_force_inherit_empty_source : int
  * is_StringAggAllSources : int
  * property_name : nvarchar(128)
  property_value : sql_variant
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
  resulting_InheritanceDefinition : nvarchar(4000)
}

config.Parameter <.. repo.PropertyName_RepoObject
config.Parameter <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.PropertyName_RepoObject <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObject <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectProperty <.. repo.RepoObjectProperty_InheritanceType_InheritanceDefinition
repo.RepoObjectProperty <.. repo.PropertyName_RepoObject
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition <.. repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition
config.Parameter::Parameter_value__result_int <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_InheritanceType
config.Parameter::Parameter_value__result_int <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_InheritanceType
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_Inheritance_StringAggSeparatorSql
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::par_InheritanceDefintion
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_Inheritance_StringAggSeparatorSql
config.Parameter::Parameter_value__result_nvarchar <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::sub_InheritanceDefintion
repo.PropertyName_RepoObject::property_name <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_name
repo.RepoObject::Inheritance_StringAggSeparatorSql <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::Inheritance_StringAggSeparatorSql
repo.RepoObject::Inheritance_StringAggSeparatorSql <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::ro_Inheritance_StringAggSeparatorSql
repo.RepoObject::InheritanceDefinition <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::ro_InheritanceDefinition
repo.RepoObject::InheritanceType <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::ro_InheritanceType
repo.RepoObject::RepoObject_fullname <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_fullname
repo.RepoObject::RepoObject_guid <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_guid
repo.RepoObject::RepoObject_type <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_type
repo.RepoObjectProperty::property_value <-- repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_value
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::Inheritance_StringAggSeparatorSql <-- repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::Inheritance_StringAggSeparatorSql
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::InheritanceDefinition <-- repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::InheritanceDefinition
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::InheritanceType <-- repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::InheritanceType
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_name <-- repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::property_name
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::property_value <-- repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::property_value
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_fullname <-- repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::RepoObject_fullname
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_guid <-- repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::RepoObject_guid
repo.RepoObjectProperty_InheritanceType_InheritanceDefinition::RepoObject_type <-- repo.RepoObjectProperty_InheritanceType_resulting_InheritanceDefinition::RepoObject_type
