left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.Index_gross << V >> {
  * **index_guid** : uniqueidentifier
  --
  AntoraIndexColumnList : nvarchar(max)
  ColumnList : nvarchar(max)
  ConstraintColumnList : nvarchar(max)
  DbmlIndexColumnList : nvarchar(max)
  index_name : nvarchar(128)
  * index_type : tinyint
  IndexPatternColumnDatatype : nvarchar(4000)
  IndexPatternColumnName : nvarchar(4000)
  IndexSemanticGroup : nvarchar(512)
  is_index_disabled : bit
  is_index_primary_key : bit
  is_index_real : bit
  is_index_unique : bit
  is_persistence : bit
  is_repo_managed : bit
  parent_RepoObject_guid : uniqueidentifier
  PersistenceWhereColumnList : nvarchar(max)
  PumlIndexColumnList : nvarchar(max)
  referenced_index_guid : uniqueidentifier
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  RowNumber_PatternPerParentObject : bigint
  RowNumber_PkPerParentObject : bigint
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
  SysObject_id : int
  * SysObject_name : nvarchar(128)
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
}

entity repo.Index_SqlConstraint_PkUq << V >> {
  **index_guid** : uniqueidentifier
  --
  parent_RepoObject_guid : uniqueidentifier
  * SqlConstraint : nvarchar(max)
}

entity repo.Index_union << V >> {
  **index_guid** : uniqueidentifier
  --
  index_name : nvarchar(128)
  * index_type : tinyint
  IndexPatternColumnGuid : varchar(8000)
  is_index_disabled : bit
  is_index_primary_key : bit
  is_index_real : bit
  is_index_unique : bit
  parent_RepoObject_guid : uniqueidentifier
  referenced_index_guid : uniqueidentifier
}

entity repo.Index_unique_IndexPatternColumnGuid << V >> {
  **index_guid** : uniqueidentifier
  --
  IndexPatternColumnGuid : varchar(8000)
}

entity repo.Index_virtual << U >> {
  * **index_guid** : uniqueidentifier
  --
  * has_managedName : bit
  index_name : nvarchar(128)
  * index_type : tinyint
  * is_index_disabled : bit
  * is_index_primary_key : bit
  * is_index_unique : bit
  * parent_RepoObject_guid : uniqueidentifier
  referenced_index_guid : uniqueidentifier
  RowNumberInReferencing : int
}

entity repo.Index_virtual_IndexPatternColumnGuid << V >> {
  * **index_guid** : uniqueidentifier
  --
  IndexPatternColumnGuid : varchar(8000)
  parent_RepoObject_guid : uniqueidentifier
}

entity repo.IndexReferencedReferencing << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
  --
  referenced_index_guid : uniqueidentifier
  RowNumberInReferencing_Target : int
  source_index_guid : uniqueidentifier
  * source_index_type : tinyint
}

entity repo.usp_Index_finish << P >> {
  --
}

entity repo_sys.Index_unique << V >> {
  --
  index_guid : uniqueidentifier
  * index_id : int
  index_name : sysname
  * index_type : tinyint
  index_type_desc : nvarchar(60)
  is_index_disabled : bit
  is_index_primary_key : bit
  is_index_unique : bit
  is_index_unique_constraint : bit
  parent_RepoObject_guid : uniqueidentifier
  parent_schema_name : nvarchar(128)
  parent_SysObject_fullname : nvarchar(261)
  parent_SysObject_name : nvarchar(128)
}

repo.Index_gross <.. repo.usp_Index_finish
repo.Index_union <.. repo.IndexReferencedReferencing
repo.Index_union <.. repo.Index_SqlConstraint_PkUq
repo.Index_union <.. repo.Index_gross
repo.Index_union <.. repo.usp_Index_finish
repo.Index_unique_IndexPatternColumnGuid <.. repo.Index_union
repo.Index_virtual <.. repo.Index_union
repo.Index_virtual <.. repo.IndexReferencedReferencing
repo.Index_virtual <.. repo.Index_virtual_IndexPatternColumnGuid
repo.Index_virtual <.. repo.usp_Index_finish
repo.Index_virtual_IndexPatternColumnGuid <.. repo.Index_union
repo_sys.Index_unique <.. repo.Index_union
repo.Index_union::index_guid <-- repo.Index_SqlConstraint_PkUq::index_guid
repo.Index_union::index_name <-- repo.Index_gross::index_name
repo.Index_union::index_type <-- repo.Index_gross::index_type
repo.Index_union::is_index_disabled <-- repo.Index_gross::is_index_disabled
repo.Index_union::is_index_primary_key <-- repo.Index_gross::is_index_primary_key
repo.Index_union::is_index_real <-- repo.Index_gross::is_index_real
repo.Index_union::is_index_unique <-- repo.Index_gross::is_index_unique
repo.Index_union::parent_RepoObject_guid <-- repo.Index_gross::parent_RepoObject_guid
repo.Index_union::parent_RepoObject_guid <-- repo.Index_SqlConstraint_PkUq::parent_RepoObject_guid
repo.Index_union::referenced_index_guid <-- repo.Index_gross::referenced_index_guid
repo.Index_virtual::index_guid <-- repo.Index_virtual_IndexPatternColumnGuid::index_guid
repo.Index_virtual::referenced_index_guid <-- repo.IndexReferencedReferencing::referenced_index_guid
