left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.ftv_query_plan_extract_source << IF >> {
  --
  const_info : xml
  const_value : nvarchar(4000)
  source_column_info : xml
  source_column_name : nvarchar(4000)
  source_database_name : nvarchar(4000)
  source_schema_name : nvarchar(4000)
  source_server_name : nvarchar(4000)
  source_table_name : nvarchar(4000)
  target_column_info : xml
  target_column_name : nvarchar(4000)
}

entity repo.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

repo.ftv_query_plan_extract_source <.. repo.usp_RepoObjectSource_QueryPlan

