left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity workflow.ProcedureDependency << U >> {
  * **id** : int
  --
  Description : nvarchar(4000)
  * is_active : bit
  * is_PersistenceDependency : bit
  * referenced_Procedure_RepoObject_guid : uniqueidentifier
  * referencing_Procedure_RepoObject_guid : uniqueidentifier
}

entity config.fs_get_parameter_value << FN >> {
  --
}

entity graph.ReferencedObject << U >> {
  --
  * $edge_id_25B0DD35E10A49DE8B49228E6802F3EB : nvarchar(1000)
  $from_id_7B1BEB60463741CAA681054A489A2714 : nvarchar(1000)
  $to_id_26820C41BE034B00BCBC470518101233 : nvarchar(1000)
  * from_id_7F3CEF660D794A2A81530928BC4B36F1 : bigint
  * from_obj_id_A00C6316716D4F9DABE96A189F3A214A : int
  * graph_id_85ECDD019A4C46AF80CFD8DDFA08F479 : bigint
  * to_id_45A2D6271B224A08B66CA0CF6A200A54 : bigint
  * to_obj_id_F1F1771130674EE9A9DAE06330740E13 : int
}

entity graph.ReferencedObjectColumn << U >> {
  --
  * $edge_id_7C154492F0954C769C843FC0BEA97AFC : nvarchar(1000)
  $from_id_F5982CB6A96041F69453F5D5DBE84FFB : nvarchar(1000)
  $to_id_9D5378D2AACD4945A48693ABF17CD063 : nvarchar(1000)
  * from_id_7E00AE91C08D4B1FA35C7A8270AC9E8C : bigint
  * from_obj_id_11EC88C0730D4B5993BF0DBC6FAC2E36 : int
  * graph_id_E9F774DD8CA2460A924F6173983BE220 : bigint
  * to_id_085F365914414A0AAB9A494884264043 : bigint
  * to_obj_id_1AB5BC0BD7FD4956AA05F7CB026BC43D : int
}

entity graph.ReferencingObject << U >> {
  --
  * $edge_id_21A14F7820EC4E65A2181C77070E4599 : nvarchar(1000)
  $from_id_0076F61972EE4CFBAB773755DA860F3E : nvarchar(1000)
  $to_id_24A0471B483E40D58582E894797FDBD5 : nvarchar(1000)
  * from_id_472B24420B624B14BB7713C2D61A6825 : bigint
  * from_obj_id_841F6E8E64074738851E57246A265384 : int
  * graph_id_09F977CF6E984C91A3DCB80DFCA167DF : bigint
  * to_id_481A7B86C080421583F830CBBB2D1D40 : bigint
  * to_obj_id_E20461DCDFE345938DA61BDA2DFCEDB6 : int
}

entity graph.ReferencingObjectColumn << U >> {
  --
  * $edge_id_DC70EA9971F145D9892721EBFAD6DA3B : nvarchar(1000)
  $from_id_E02FBFD790F541C5888A72743EC0C66D : nvarchar(1000)
  $to_id_82344FE7FA59415C82FF9A4D37C1712A : nvarchar(1000)
  * from_id_AF95740FA51A459CAD5E73CCDA2BB9A1 : bigint
  * from_obj_id_E30A518916BD429EAA4BC746BAB803B8 : int
  * graph_id_33EABAD1D448423BA763A06B2E100A3D : bigint
  * to_id_BC6FD8D77D2B4F3292EFDF7454BE0A57 : bigint
  * to_obj_id_B789CEA675414B248EC7F2E6F9E8738E : int
}

entity graph.RepoObject << U >> {
  --
  * $node_id_FAC3EF4690DB4CD6A98F097DAF0885CC : nvarchar(1000)
  * graph_id_60367FDA1A70430CA390F8144C223EC4 : bigint
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
}

entity graph.RepoObjectColumn << U >> {
  --
  * $node_id_347F7C762E2642A98518838371CE6BB1 : nvarchar(1000)
  * graph_id_58E017E29B684D7FBC6E4E880C609245 : bigint
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
  * RepoObjectColumn_guid : uniqueidentifier
  * RepoObjectColumn_name : nvarchar(128)
}

entity logs.usp_ExecutionLog_insert << P >> {
  --
}

entity repo.Match_RepoObject_referenced_UspPersistence << V >> {
  **FirstNode** : uniqueidentifier
  **LastNode** : uniqueidentifier
  --
  First_usp_persistence_name : nvarchar(140)
  First_usp_persistence_RepoObject_guid : uniqueidentifier
  FirstNode_schema_name : nvarchar(128)
  FirstNodeName : nvarchar(261)
  Last_usp_persistence_name : nvarchar(140)
  Last_usp_persistence_RepoObject_guid : uniqueidentifier
  LastNode_schema_name : nvarchar(128)
  LastNodeName : nvarchar(261)
  ListNodeName : nvarchar(4000)
}

entity repo.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
  --
  * InformationSource : varchar(31)
  * one : int
  referenced_entity_name : nvarchar(128)
  * referenced_fullname : nvarchar(517)
  referenced_id : int
  referenced_node_id : bigint
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_entity_name : nvarchar(128)
  * referencing_fullname : nvarchar(517)
  referencing_id : int
  referencing_node_id : bigint
  referencing_schema_name : nvarchar(128)
  referencing_type : varchar(2)
}

entity repo.RepoObjectColumn_reference_union << V >> {
  --
  definition : nvarchar(max)
  * InformationSource : varchar(31)
  is_computed : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  referenced_column_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_id : int
  referenced_minor_id : int
  referenced_node_id : bigint
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_column_name : nvarchar(128)
  referencing_entity_name : nvarchar(128)
  referencing_id : int
  referencing_minor_id : int
  referencing_node_id : bigint
  referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
  referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
}

entity repo.usp_Index_ForeignKey << P >> {
  --
}

entity repo.usp_index_inheritance << P >> {
  --
}

entity repo.usp_main << P >> {
  --
}

entity repo.usp_RepoObject_Inheritance << P >> {
  --
}

entity repo.usp_RepoObject_update_SysObjectQueryPlan << P >> {
  --
}

entity repo.usp_RepoObjectColumn_Inheritance << P >> {
  --
}

entity repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id << P >> {
  --
}

entity repo.usp_RepoObjectSource_FirstResultSet << P >> {
  --
}

entity repo.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

entity repo.usp_sync_guid << P >> {
  --
}

entity repo.usp_update_Referencing_Count << P >> {
  --
}

entity uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

 <.. repo.usp_main
config.fs_get_parameter_value <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
config.fs_get_parameter_value <.. repo.usp_main
graph.ReferencedObject <.. repo.Match_RepoObject_referenced_UspPersistence
graph.ReferencedObject <.. repo.usp_main
graph.ReferencedObjectColumn <.. repo.usp_main
graph.ReferencingObject <.. repo.usp_main
graph.ReferencingObjectColumn <.. repo.usp_main
graph.RepoObject <.. repo.usp_main
graph.RepoObject <.. repo.Match_RepoObject_referenced_UspPersistence
graph.RepoObjectColumn <.. repo.usp_main
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObject_Inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectColumn_Inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectSource_QueryPlan
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectSource_FirstResultSet
logs.usp_ExecutionLog_insert <.. repo.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. repo.usp_Index_ForeignKey
logs.usp_ExecutionLog_insert <.. repo.usp_main
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id
logs.usp_ExecutionLog_insert <.. repo.usp_sync_guid
logs.usp_ExecutionLog_insert <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
logs.usp_ExecutionLog_insert <.. repo.usp_index_inheritance
logs.usp_ExecutionLog_insert <.. repo.usp_RepoObject_update_SysObjectQueryPlan
repo.Match_RepoObject_referenced_UspPersistence <.. repo.usp_main
repo.RepoObject_reference_union <.. repo.usp_main
repo.RepoObjectColumn_reference_union <.. repo.usp_main
repo.usp_Index_ForeignKey <.. repo.usp_main
repo.usp_index_inheritance <.. repo.usp_main
repo.usp_RepoObject_Inheritance <.. repo.usp_main
repo.usp_RepoObject_update_SysObjectQueryPlan <.. repo.usp_main
repo.usp_RepoObjectColumn_Inheritance <.. repo.usp_main
repo.usp_RepoObjectColumn_update_RepoObjectColumn_column_id <.. repo.usp_main
repo.usp_RepoObjectSource_FirstResultSet <.. repo.usp_main
repo.usp_RepoObjectSource_QueryPlan <.. repo.usp_main
repo.usp_sync_guid <.. repo.usp_main
repo.usp_update_Referencing_Count <.. repo.usp_main
uspgenerator.usp_GeneratorUsp_insert_update_persistence <.. repo.usp_main

