left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_ColumnList << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  AntoraColumnDetails : nvarchar(max)
  AntoraNonPkColumnTableRows : nvarchar(max)
  AntoraPkColumnTableRows : nvarchar(max)
  PlantumlNonPkEntityColumns : nvarchar(max)
  PlantumlPkEntityColumns : nvarchar(max)
}

entity graph.RepoObjectColumn_S << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
  * RepoObject_fullname : nvarchar(261)
  RepoObject_fullname2 : nvarchar(257)
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
  * RepoObjectColumn_fullname : nvarchar(520)
  RepoObjectColumn_fullname2 : nvarchar(386)
  * RepoObjectColumn_name : nvarchar(128)
  RepoObjectColumn_type : nvarchar(128)
}

entity repo.fs_get_RepoObjectColumnProperty_nvarchar << FN >> {
  --
}

entity repo.IndexColumn_union << V >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  --
  index_name : nvarchar(128)
  is_descending_key : bit
  is_index_primary_key : bit
  is_index_real : bit
  is_index_unique : bit
  parent_RepoObject_guid : uniqueidentifier
  parent_schema_name : nvarchar(128)
  parent_SysObject_fullname : nvarchar(261)
  parent_SysObject_name : nvarchar(128)
  RepoObjectColumn_guid : uniqueidentifier
  SysObject_column_name : nvarchar(128)
  SysObject_column_user_type_fullname : nvarchar(182)
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_repo_managed : bit
  is_SysObject_missing : bit
  * modify_dt : datetime
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnName_new : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObject_name_uniqueidentifier : int
  * {static} is_SysObject_name_uniqueidentifier : int
  {abstract} node_id : bigint
  * {static} RepoObject_fullname : nvarchar(261)
  * {static} RepoObject_fullname2 : nvarchar(257)
  * {static} SysObject_fullname : nvarchar(261)
  * {static} SysObject_fullname2 : nvarchar(257)
  * {abstract} SysObject_query_sql : nvarchar(406)
  * {static} usp_persistence_name : nvarchar(140)
}

entity repo.RepoObject_ColumnList << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  CreateColumnList : nvarchar(max)
  DbmlColumnList : nvarchar(max)
  PersistenceCompareColumnList : nvarchar(max)
  PersistenceInsertColumnList : nvarchar(max)
  PersistenceUpdateColumnList : nvarchar(max)
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_persistence_no_check : bit
  is_persistence_no_include : bit
  is_persistence_no_update : bit
  is_query_plan_expression : bit
  is_SysObjectColumn_missing : bit
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  * Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  * Repo_is_computed : bit
  * Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  * RepoObject_guid : uniqueidentifier
  RepoObjectColumn_column_id : int
  * RepoObjectColumn_name : nvarchar(128)
  SysObjectColumn_column_id : int
  * SysObjectColumn_name : nvarchar(128)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObjectColumn_name_uniqueidentifier : int
  * {static} is_SysObjectColumn_name_uniqueidentifier : int
}

entity repo.RepoObjectColumn_gross << V >> {
  --
  AntoraReferencedColumnList : nvarchar(max)
  AntoraReferencingColumnList : nvarchar(max)
  has_different_sys_names : bit
  has_get_referenced_issue : bit
  index_column_id : int
  index_name : nvarchar(128)
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_index_primary_key : bit
  is_persistence_no_check : bit
  is_persistence_no_include : bit
  is_persistence_no_update : bit
  is_query_plan_expression : bit
  is_repo_managed : bit
  * is_RepoObject_name_uniqueidentifier : int
  * is_RepoObjectColumn_name_uniqueidentifier : int
  is_SysObject_missing : bit
  * is_SysObject_name_uniqueidentifier : int
  is_SysObjectColumn_missing : bit
  * is_SysObjectColumn_name_uniqueidentifier : int
  * modify_dt : datetime
  node_id : bigint
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  pk_index_guid : uniqueidentifier
  Property_ms_description : nvarchar(4000)
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  * Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  * Repo_is_computed : bit
  * Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  * RepoObject_guid : uniqueidentifier
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  RepoObjectColumn_column_id : int
  * RepoObjectColumn_fullname : nvarchar(520)
  * RepoObjectColumn_fullname2 : nvarchar(386)
  * RepoObjectColumn_guid : uniqueidentifier
  * RepoObjectColumn_name : nvarchar(128)
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObjectColumn_column_id : int
  * SysObjectColumn_name : nvarchar(128)
}

entity repo.RepoObjectColumn_reference_FirstResultSet << V >> {
  --
  * InformationSource : varchar(37)
  is_hidden : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  referenced_column_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_id : int
  referenced_minor_id : int
  referenced_node_id : bigint
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_column_name : nvarchar(128)
  * referencing_entity_name : nvarchar(128)
  referencing_id : int
  referencing_minor_id : int
  referencing_node_id : bigint
  * referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
  * referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
}

entity repo.RepoObjectColumn_reference_QueryPlan << V >> {
  --
  definition : nvarchar(max)
  * InformationSource : varchar(10)
  is_computed : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  is_source_column_name_expression : bit
  is_target_column_name_expression : bit
  referenced_column_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_id : int
  referenced_minor_id : int
  referenced_node_id : bigint
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_column_name : nvarchar(128)
  * referencing_entity_name : nvarchar(128)
  referencing_id : int
  referencing_minor_id : int
  referencing_node_id : bigint
  * referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
  * referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
  source_schema_name_quoted : nvarchar(128)
  source_table_name_quoted : nvarchar(128)
}

entity repo.RepoObjectColumn_ReferencedList << V >> {
  --
  AntoraReferencedColumnList : nvarchar(max)
  Referencing_fullname : nvarchar(261)
  Referencing_fullname2 : nvarchar(257)
  Referencing_guid : uniqueidentifier
  Referencing_type : char(2)
  ReferencingColumn_fullname : nvarchar(520)
  ReferencingColumn_fullname2 : nvarchar(386)
}

entity repo.RepoObjectColumn_ReferencingList << V >> {
  --
  AntoraReferencingColumnList : nvarchar(max)
  Referenced_fullname : nvarchar(261)
  Referenced_fullname2 : nvarchar(257)
  Referenced_guid : uniqueidentifier
  Referenced_type : char(2)
  ReferencedColumn_fullname : nvarchar(520)
  ReferencedColumn_fullname2 : nvarchar(386)
}

repo.fs_get_RepoObjectColumnProperty_nvarchar <.. repo.RepoObjectColumn_gross
repo.IndexColumn_union <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObjectColumn_reference_FirstResultSet
repo.RepoObject <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_reference_FirstResultSet
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. repo.RepoObject_ColumnList
repo.RepoObjectColumn_gross <.. graph.RepoObjectColumn_S
repo.RepoObjectColumn_gross <.. docs.RepoObject_ColumnList
repo.RepoObjectColumn_ReferencedList <.. repo.RepoObjectColumn_gross
repo.RepoObjectColumn_ReferencingList <.. repo.RepoObjectColumn_gross
repo.IndexColumn_union::index_column_id <-- repo.RepoObjectColumn_gross::index_column_id
repo.IndexColumn_union::index_name <-- repo.RepoObjectColumn_gross::index_name
repo.IndexColumn_union::is_index_primary_key <-- repo.RepoObjectColumn_gross::is_index_primary_key
repo.RepoObject::has_get_referenced_issue <-- repo.RepoObjectColumn_gross::has_get_referenced_issue
repo.RepoObject::is_repo_managed <-- repo.RepoObjectColumn_gross::is_repo_managed
repo.RepoObject::is_RepoObject_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_RepoObject_name_uniqueidentifier
repo.RepoObject::is_SysObject_missing <-- repo.RepoObjectColumn_gross::is_SysObject_missing
repo.RepoObject::is_SysObject_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_SysObject_name_uniqueidentifier
repo.RepoObject::modify_dt <-- repo.RepoObjectColumn_gross::modify_dt
repo.RepoObject::node_id <-- repo.RepoObjectColumn_gross::node_id
repo.RepoObject::pk_index_guid <-- repo.RepoObjectColumn_gross::pk_index_guid
repo.RepoObject::RepoObject_fullname <-- repo.RepoObjectColumn_gross::RepoObject_fullname
repo.RepoObject::RepoObject_fullname2 <-- repo.RepoObjectColumn_gross::RepoObject_fullname2
repo.RepoObject::RepoObject_name <-- repo.RepoObjectColumn_gross::RepoObject_name
repo.RepoObject::RepoObject_Referencing_Count <-- repo.RepoObjectColumn_gross::RepoObject_Referencing_Count
repo.RepoObject::RepoObject_schema_name <-- repo.RepoObjectColumn_gross::RepoObject_schema_name
repo.RepoObject::RepoObject_type <-- repo.RepoObjectColumn_gross::RepoObject_type
repo.RepoObject::SysObject_fullname <-- repo.RepoObjectColumn_gross::SysObject_fullname
repo.RepoObject::SysObject_fullname2 <-- repo.RepoObjectColumn_gross::SysObject_fullname2
repo.RepoObject::SysObject_id <-- repo.RepoObjectColumn_gross::SysObject_id
repo.RepoObject::SysObject_modify_date <-- repo.RepoObjectColumn_gross::SysObject_modify_date
repo.RepoObject::SysObject_name <-- repo.RepoObjectColumn_gross::SysObject_name
repo.RepoObject::SysObject_parent_object_id <-- repo.RepoObjectColumn_gross::SysObject_parent_object_id
repo.RepoObject::SysObject_schema_name <-- repo.RepoObjectColumn_gross::SysObject_schema_name
repo.RepoObject::SysObject_type <-- repo.RepoObjectColumn_gross::SysObject_type
repo.RepoObjectColumn::has_different_sys_names <-- repo.RepoObjectColumn_gross::has_different_sys_names
repo.RepoObjectColumn::Inheritance_StringAggSeparatorSql <-- repo.RepoObjectColumn_gross::Inheritance_StringAggSeparatorSql
repo.RepoObjectColumn::InheritanceDefinition <-- repo.RepoObjectColumn_gross::InheritanceDefinition
repo.RepoObjectColumn::InheritanceType <-- repo.RepoObjectColumn_gross::InheritanceType
repo.RepoObjectColumn::is_persistence_no_check <-- repo.RepoObjectColumn_gross::is_persistence_no_check
repo.RepoObjectColumn::is_persistence_no_include <-- repo.RepoObjectColumn_gross::is_persistence_no_include
repo.RepoObjectColumn::is_persistence_no_update <-- repo.RepoObjectColumn_gross::is_persistence_no_update
repo.RepoObjectColumn::is_query_plan_expression <-- repo.RepoObjectColumn_gross::is_query_plan_expression
repo.RepoObjectColumn::is_RepoObjectColumn_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_RepoObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn::is_SysObjectColumn_missing <-- repo.RepoObjectColumn_gross::is_SysObjectColumn_missing
repo.RepoObjectColumn::is_SysObjectColumn_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_SysObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn::persistence_source_RepoObjectColumn_guid <-- repo.RepoObjectColumn_gross::persistence_source_RepoObjectColumn_guid
repo.RepoObjectColumn::Referencing_Count <-- repo.RepoObjectColumn_gross::Referencing_Count
repo.RepoObjectColumn::Repo_default_definition <-- repo.RepoObjectColumn_gross::Repo_default_definition
repo.RepoObjectColumn::Repo_default_is_system_named <-- repo.RepoObjectColumn_gross::Repo_default_is_system_named
repo.RepoObjectColumn::Repo_default_name <-- repo.RepoObjectColumn_gross::Repo_default_name
repo.RepoObjectColumn::Repo_definition <-- repo.RepoObjectColumn_gross::Repo_definition
repo.RepoObjectColumn::Repo_generated_always_type <-- repo.RepoObjectColumn_gross::Repo_generated_always_type
repo.RepoObjectColumn::Repo_graph_type <-- repo.RepoObjectColumn_gross::Repo_graph_type
repo.RepoObjectColumn::Repo_increment_value <-- repo.RepoObjectColumn_gross::Repo_increment_value
repo.RepoObjectColumn::Repo_is_computed <-- repo.RepoObjectColumn_gross::Repo_is_computed
repo.RepoObjectColumn::Repo_is_identity <-- repo.RepoObjectColumn_gross::Repo_is_identity
repo.RepoObjectColumn::Repo_is_nullable <-- repo.RepoObjectColumn_gross::Repo_is_nullable
repo.RepoObjectColumn::Repo_is_persisted <-- repo.RepoObjectColumn_gross::Repo_is_persisted
repo.RepoObjectColumn::Repo_seed_value <-- repo.RepoObjectColumn_gross::Repo_seed_value
repo.RepoObjectColumn::Repo_user_type_fullname <-- repo.RepoObjectColumn_gross::Repo_user_type_fullname
repo.RepoObjectColumn::Repo_user_type_name <-- repo.RepoObjectColumn_gross::Repo_user_type_name
repo.RepoObjectColumn::Repo_uses_database_collation <-- repo.RepoObjectColumn_gross::Repo_uses_database_collation
repo.RepoObjectColumn::RepoObject_guid <-- repo.RepoObjectColumn_gross::RepoObject_guid
repo.RepoObjectColumn::RepoObjectColumn_column_id <-- repo.RepoObjectColumn_gross::RepoObjectColumn_column_id
repo.RepoObjectColumn::RepoObjectColumn_guid <-- repo.RepoObjectColumn_gross::RepoObjectColumn_guid
repo.RepoObjectColumn::RepoObjectColumn_name <-- repo.RepoObjectColumn_gross::RepoObjectColumn_name
repo.RepoObjectColumn::SysObjectColumn_column_id <-- repo.RepoObjectColumn_gross::SysObjectColumn_column_id
repo.RepoObjectColumn::SysObjectColumn_name <-- repo.RepoObjectColumn_gross::SysObjectColumn_name
repo.RepoObjectColumn_gross::RepoObject_fullname <-- graph.RepoObjectColumn_S::RepoObject_fullname
repo.RepoObjectColumn_gross::RepoObject_guid <-- graph.RepoObjectColumn_S::RepoObject_guid
repo.RepoObjectColumn_gross::RepoObject_guid <-- docs.RepoObject_ColumnList::RepoObject_guid
repo.RepoObjectColumn_gross::RepoObject_guid <-- repo.RepoObject_ColumnList::RepoObject_guid
repo.RepoObjectColumn_gross::RepoObject_type <-- graph.RepoObjectColumn_S::RepoObject_type
repo.RepoObjectColumn_gross::RepoObjectColumn_fullname <-- graph.RepoObjectColumn_S::RepoObjectColumn_fullname
repo.RepoObjectColumn_gross::RepoObjectColumn_guid <-- graph.RepoObjectColumn_S::RepoObjectColumn_guid
repo.RepoObjectColumn_gross::RepoObjectColumn_name <-- graph.RepoObjectColumn_S::RepoObjectColumn_name
repo.RepoObjectColumn_ReferencedList::AntoraReferencedColumnList <-- repo.RepoObjectColumn_gross::AntoraReferencedColumnList
repo.RepoObjectColumn_ReferencingList::AntoraReferencingColumnList <-- repo.RepoObjectColumn_gross::AntoraReferencingColumnList
