left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObjectColumn_reference_QueryPlan << V >> {
  **referencing_id** : int
  **referencing_minor_id** : int
  **referenced_id** : int
  **referenced_minor_id** : int
  --
  definition : nvarchar(max)
  * InformationSource : varchar(10)
  is_computed : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  is_source_column_name_expression : bit
  is_target_column_name_expression : bit
  referenced_column_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_node_id : bigint
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_column_name : nvarchar(128)
  * referencing_entity_name : nvarchar(128)
  referencing_node_id : bigint
  * referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
  * referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
  source_schema_name_quoted : nvarchar(128)
  source_table_name_quoted : nvarchar(128)
}

entity repo.RepoObjectSource_QueryPlan << U >> {
  --
  const_info : xml
  const_value : nvarchar(4000)
  * RepoObject_guid : uniqueidentifier
  source_column_info : xml
  source_column_name : nvarchar(128)
  source_database_name : nvarchar(128)
  source_schema_name : nvarchar(128)
  source_server_name : nvarchar(128)
  source_table_name : nvarchar(128)
  SysObject_query_executed_dt : datetime
  target_column_info : xml
  target_column_name : nvarchar(128)
  {abstract} is_source_column_name_expression : bit
  {abstract} is_target_column_name_expression : bit
}

entity repo.usp_RepoObjectSource_QueryPlan << P >> {
  --
}

repo.RepoObjectSource_QueryPlan <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectSource_QueryPlan <.. repo.usp_RepoObjectSource_QueryPlan
repo.RepoObjectSource_QueryPlan::is_source_column_name_expression <-- repo.RepoObjectColumn_reference_QueryPlan::is_source_column_name_expression
repo.RepoObjectSource_QueryPlan::is_target_column_name_expression <-- repo.RepoObjectColumn_reference_QueryPlan::is_target_column_name_expression
