left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.Index_Settings << U >> {
  * **index_guid** : uniqueidentifier
  --
  IndexPatternColumnDatatype : nvarchar(4000)
  IndexPatternColumnName : nvarchar(4000)
  IndexSemanticGroup : nvarchar(512)
  * is_create_constraint : bit
}

entity repo.Index_virtual << U >> {
  * **index_guid** : uniqueidentifier
  --
  * has_managedName : bit
  index_name : nvarchar(128)
  * index_type : tinyint
  * is_index_disabled : bit
  * is_index_primary_key : bit
  * is_index_unique : bit
  * parent_RepoObject_guid : uniqueidentifier
  referenced_index_guid : uniqueidentifier
  RowNumberInReferencing : int
}

entity repo.Index_virtual_ForUpdate << V >> {
  * **index_guid** : uniqueidentifier
  --
  * has_managedName : bit
  index_name : nvarchar(128)
  * index_type : tinyint
  IndexPatternColumnDatatype : nvarchar(4000)
  IndexPatternColumnName : nvarchar(4000)
  IndexSemanticGroup : nvarchar(512)
  * is_index_disabled : bit
  * is_index_primary_key : bit
  * is_index_unique : bit
  is_persistence : bit
  is_repo_managed : bit
  * parent_RepoObject_guid : uniqueidentifier
  referenced_index_guid : uniqueidentifier
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  RowNumberInReferencing : int
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_repo_managed : bit
  is_required_ObjectMerge : bit
  is_SysObject_missing : bit
  * modify_dt : datetime
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnName_new : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObject_name_uniqueidentifier : int
  * {static} is_SysObject_name_uniqueidentifier : int
  {abstract} node_id : bigint
  * {static} RepoObject_fullname : nvarchar(261)
  * {static} RepoObject_fullname2 : nvarchar(257)
  * {static} SysObject_fullname : nvarchar(261)
  * {static} SysObject_fullname2 : nvarchar(257)
  * {abstract} SysObject_query_sql : nvarchar(406)
  * {static} usp_persistence_name : nvarchar(140)
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  AntoraReferencedList : nvarchar(max)
  AntoraReferencingList : nvarchar(max)
  CreateColumnList : nvarchar(max)
  DbmlColumnList : nvarchar(max)
  has_different_sys_names : bit
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  has_history : bit
  has_history_columns : bit
  history_schema_name : nvarchar(128)
  history_table_name : nvarchar(128)
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_DocsOutput : int
  * is_in_reference : int
  is_persistence : bit
  is_persistence_check_duplicate_per_pk : bit
  is_persistence_check_for_empty_source : bit
  is_persistence_delete_changed : bit
  is_persistence_delete_missing : bit
  is_persistence_insert : bit
  is_persistence_truncate : bit
  is_persistence_update_changed : bit
  is_repo_managed : bit
  * is_RepoObject_name_uniqueidentifier : int
  is_required_ObjectMerge : bit
  is_SysObject_missing : bit
  * is_SysObject_name_uniqueidentifier : int
  * modify_dt : datetime
  node_id : bigint
  persistence_source_RepoObject_fullname : nvarchar(261)
  persistence_source_RepoObject_fullname2 : nvarchar(257)
  persistence_source_RepoObject_guid : uniqueidentifier
  persistence_source_RepoObject_xref : nvarchar(269)
  persistence_source_SysObject_fullname : nvarchar(261)
  persistence_source_SysObject_fullname2 : nvarchar(257)
  persistence_source_SysObject_xref : nvarchar(269)
  PersistenceCompareColumnList : nvarchar(max)
  PersistenceInsertColumnList : nvarchar(max)
  PersistenceUpdateColumnList : nvarchar(max)
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnDatatype : nvarchar(4000)
  pk_IndexPatternColumnName : nvarchar(4000)
  pk_IndexPatternColumnName_new : nvarchar(4000)
  pk_IndexSemanticGroup : nvarchar(512)
  Property_ms_description : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  RepoObject_type_name : nvarchar(128)
  sql_modules_antora : nvarchar(max)
  sql_modules_definition : nvarchar(max)
  sql_modules_formatted : nvarchar(max)
  sql_modules_formatted2 : nvarchar(max)
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  SysObject_query_executed_dt : datetime
  SysObject_query_plan : xml
  * SysObject_query_sql : nvarchar(406)
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObject_type_name : nvarchar(128)
  temporal_type : tinyint
  * usp_persistence_name : nvarchar(140)
  usp_persistence_RepoObject_guid : uniqueidentifier
}

entity repo.usp_index_inheritance << P >> {
  --
}

repo.Index_Settings <.. repo.RepoObject_gross
repo.Index_Settings <.. repo.Index_virtual_ForUpdate
repo.Index_virtual <.. repo.Index_virtual_ForUpdate
repo.Index_virtual <.. repo.usp_index_inheritance
repo.Index_virtual_ForUpdate <.. repo.usp_index_inheritance
repo.RepoObject <.. repo.Index_virtual_ForUpdate
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject_gross <.. repo.Index_virtual_ForUpdate
repo.Index_Settings::IndexPatternColumnDatatype <-- repo.Index_virtual_ForUpdate::IndexPatternColumnDatatype
repo.Index_Settings::IndexPatternColumnName <-- repo.Index_virtual_ForUpdate::IndexPatternColumnName
repo.Index_Settings::IndexSemanticGroup <-- repo.Index_virtual_ForUpdate::IndexSemanticGroup
repo.Index_virtual::has_managedName <-- repo.Index_virtual_ForUpdate::has_managedName
repo.Index_virtual::index_guid <-- repo.Index_virtual_ForUpdate::index_guid
repo.Index_virtual::index_name <-- repo.Index_virtual_ForUpdate::index_name
repo.Index_virtual::index_type <-- repo.Index_virtual_ForUpdate::index_type
repo.Index_virtual::is_index_disabled <-- repo.Index_virtual_ForUpdate::is_index_disabled
repo.Index_virtual::is_index_primary_key <-- repo.Index_virtual_ForUpdate::is_index_primary_key
repo.Index_virtual::is_index_unique <-- repo.Index_virtual_ForUpdate::is_index_unique
repo.Index_virtual::parent_RepoObject_guid <-- repo.Index_virtual_ForUpdate::parent_RepoObject_guid
repo.Index_virtual::referenced_index_guid <-- repo.Index_virtual_ForUpdate::referenced_index_guid
repo.Index_virtual::RowNumberInReferencing <-- repo.Index_virtual_ForUpdate::RowNumberInReferencing
repo.RepoObject::has_different_sys_names <-- repo.RepoObject_gross::has_different_sys_names
repo.RepoObject::has_execution_plan_issue <-- repo.RepoObject_gross::has_execution_plan_issue
repo.RepoObject::has_get_referenced_issue <-- repo.RepoObject_gross::has_get_referenced_issue
repo.RepoObject::Inheritance_StringAggSeparatorSql <-- repo.RepoObject_gross::Inheritance_StringAggSeparatorSql
repo.RepoObject::InheritanceDefinition <-- repo.RepoObject_gross::InheritanceDefinition
repo.RepoObject::InheritanceType <-- repo.RepoObject_gross::InheritanceType
repo.RepoObject::is_repo_managed <-- repo.RepoObject_gross::is_repo_managed
repo.RepoObject::is_RepoObject_name_uniqueidentifier <-- repo.RepoObject_gross::is_RepoObject_name_uniqueidentifier
repo.RepoObject::is_required_ObjectMerge <-- repo.RepoObject_gross::is_required_ObjectMerge
repo.RepoObject::is_SysObject_missing <-- repo.RepoObject_gross::is_SysObject_missing
repo.RepoObject::is_SysObject_name_uniqueidentifier <-- repo.RepoObject_gross::is_SysObject_name_uniqueidentifier
repo.RepoObject::modify_dt <-- repo.RepoObject_gross::modify_dt
repo.RepoObject::node_id <-- repo.RepoObject_gross::node_id
repo.RepoObject::pk_index_guid <-- repo.RepoObject_gross::pk_index_guid
repo.RepoObject::pk_IndexPatternColumnName_new <-- repo.RepoObject_gross::pk_IndexPatternColumnName_new
repo.RepoObject::Repo_history_table_guid <-- repo.RepoObject_gross::Repo_history_table_guid
repo.RepoObject::Repo_temporal_type <-- repo.RepoObject_gross::Repo_temporal_type
repo.RepoObject::RepoObject_fullname <-- repo.RepoObject_gross::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo.Index_virtual_ForUpdate::RepoObject_fullname
repo.RepoObject::RepoObject_fullname2 <-- repo.Index_virtual_ForUpdate::RepoObject_fullname2
repo.RepoObject::RepoObject_fullname2 <-- repo.RepoObject_gross::RepoObject_fullname2
repo.RepoObject::RepoObject_guid <-- repo.RepoObject_gross::RepoObject_guid
repo.RepoObject::RepoObject_name <-- repo.RepoObject_gross::RepoObject_name
repo.RepoObject::RepoObject_Referencing_Count <-- repo.RepoObject_gross::RepoObject_Referencing_Count
repo.RepoObject::RepoObject_schema_name <-- repo.RepoObject_gross::RepoObject_schema_name
repo.RepoObject::RepoObject_type <-- repo.RepoObject_gross::RepoObject_type
repo.RepoObject::SysObject_fullname <-- repo.RepoObject_gross::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo.Index_virtual_ForUpdate::SysObject_fullname
repo.RepoObject::SysObject_fullname2 <-- repo.Index_virtual_ForUpdate::SysObject_fullname2
repo.RepoObject::SysObject_fullname2 <-- repo.RepoObject_gross::SysObject_fullname2
repo.RepoObject::SysObject_id <-- repo.RepoObject_gross::SysObject_id
repo.RepoObject::SysObject_modify_date <-- repo.RepoObject_gross::SysObject_modify_date
repo.RepoObject::SysObject_name <-- repo.RepoObject_gross::SysObject_name
repo.RepoObject::SysObject_parent_object_id <-- repo.RepoObject_gross::SysObject_parent_object_id
repo.RepoObject::SysObject_query_sql <-- repo.RepoObject_gross::SysObject_query_sql
repo.RepoObject::SysObject_schema_name <-- repo.RepoObject_gross::SysObject_schema_name
repo.RepoObject::SysObject_type <-- repo.RepoObject_gross::SysObject_type
repo.RepoObject::usp_persistence_name <-- repo.RepoObject_gross::usp_persistence_name
repo.RepoObject_gross::is_persistence <-- repo.Index_virtual_ForUpdate::is_persistence
repo.RepoObject_gross::is_repo_managed <-- repo.Index_virtual_ForUpdate::is_repo_managed
