left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.type_level1type_level2type << V >> {
  **type** : nvarchar(128)
  --
  level1type : varchar(9)
  level2type : varchar(10)
  type_desc : nvarchar(128)
}

entity graph.RepoObjectColumn << U >> {
  --
  * $node_id_347F7C762E2642A98518838371CE6BB1 : nvarchar(1000)
  033FA47C-4D2F-4D6A-8B50-43D42BB835EE : nvarchar(386)
  * 3BEB9175-44B5-426B-8409-577C841C619B : uniqueidentifier
  * 62AB1D86-A0D1-4DBF-B60C-4F4F0E6D1D35 : nvarchar(128)
  AFC74650-9FE6-4EB8-871A-4F5868DC2FE1 : nvarchar(128)
  * B1FCD5B8-85AB-48F2-B870-E85A25753638 : nvarchar(261)
  D9A2A770-88F7-4CE2-A442-B33ABE6FA570 : nvarchar(257)
  DCE6F0AF-8705-4010-9800-BDE64B3D9D44 : nvarchar(520)
  * E59AE2FF-4777-4954-A263-436BB2E6C52D : char(2)
  * graph_id_58E017E29B684D7FBC6E4E880C609245 : bigint
  * RepoObject_fullname : nvarchar(261)
  RepoObject_fullname2 : nvarchar(257)
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
  * RepoObjectColumn_fullname : nvarchar(520)
  RepoObjectColumn_fullname2 : nvarchar(386)
  * RepoObjectColumn_guid : uniqueidentifier
  * RepoObjectColumn_name : nvarchar(128)
  RepoObjectColumn_type : nvarchar(128)
}

entity graph.RepoObjectColumn_S << V >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
  * RepoObject_fullname : nvarchar(261)
  RepoObject_fullname2 : nvarchar(257)
  * RepoObject_guid : uniqueidentifier
  * RepoObject_type : char(2)
  * RepoObjectColumn_fullname : nvarchar(520)
  RepoObjectColumn_fullname2 : nvarchar(386)
  * RepoObjectColumn_name : nvarchar(128)
  RepoObjectColumn_type : nvarchar(128)
}

entity graph.usp_PERSIST_RepoObjectColumn << P >> {
  --
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_repo_managed : bit
  is_SysObject_missing : bit
  * modify_dt : datetime
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnName_new : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObject_name_uniqueidentifier : int
  * {static} is_SysObject_name_uniqueidentifier : int
  {abstract} node_id : bigint
  * {static} RepoObject_fullname : nvarchar(261)
  * {static} RepoObject_fullname2 : nvarchar(257)
  * {static} SysObject_fullname : nvarchar(261)
  * {static} SysObject_fullname2 : nvarchar(257)
  * {abstract} SysObject_query_sql : nvarchar(406)
  * {static} usp_persistence_name : nvarchar(140)
}

entity repo.RepoObject_persistence << U >> {
  * **target_RepoObject_guid** : uniqueidentifier
  --
  * has_history : bit
  * has_history_columns : bit
  history_schema_name : nvarchar(128)
  history_table_name : nvarchar(128)
  * is_persistence_check_duplicate_per_pk : bit
  * is_persistence_check_for_empty_source : bit
  * is_persistence_delete_changed : bit
  * is_persistence_delete_missing : bit
  * is_persistence_insert : bit
  * is_persistence_truncate : bit
  * is_persistence_update_changed : bit
  source_RepoObject_guid : uniqueidentifier
  {abstract} is_persistence : bit
  {abstract} temporal_type : tinyint
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_persistence_no_check : bit
  is_persistence_no_include : bit
  is_persistence_no_update : bit
  is_query_plan_expression : bit
  is_SysObjectColumn_missing : bit
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  * Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  * Repo_is_computed : bit
  * Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  * RepoObject_guid : uniqueidentifier
  RepoObjectColumn_column_id : int
  * RepoObjectColumn_name : nvarchar(128)
  SysObjectColumn_column_id : int
  * SysObjectColumn_name : nvarchar(128)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObjectColumn_name_uniqueidentifier : int
  * {static} is_SysObjectColumn_name_uniqueidentifier : int
}

entity repo.RepoObjectColumn_HistValidColums_setpoint << V >> {
  --
  * Repo_generated_always_type : int
  * Repo_is_nullable : int
  * Repo_user_type_fullname : varchar(12)
  * Repo_user_type_name : varchar(9)
  * RepoObject_guid : uniqueidentifier
  RepoObjectColumn_name : sysname
}

entity repo.SysColumn_RepoObjectColumn_via_guid << V >> {
  --
  default_definition : nvarchar(max)
  default_is_system_named : bit
  default_name : sysname
  definition : nvarchar(max)
  generated_always_type : tinyint
  graph_type : int
  has_different_sys_names : bit
  increment_value : sql_variant
  * is_computed : bit
  * is_identity : bit
  is_nullable : bit
  is_persisted : bit
  is_query_plan_expression : bit
  is_repo_managed : bit
  is_RepoObjectColumn_name_uniqueidentifier : int
  is_SysObjectColumn_missing : bit
  is_SysObjectColumn_name_uniqueidentifier : int
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  Repo_is_computed : bit
  Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  RepoObject_fullname : nvarchar(261)
  RepoObject_guid : uniqueidentifier
  RepoObjectColumn_guid : uniqueidentifier
  RepoObjectColumn_name : nvarchar(128)
  RowNumberOverName : bigint
  seed_value : sql_variant
  * SysObject_column_id : int
  SysObject_column_name : sysname
  SysObject_fullname : nvarchar(261)
  * SysObject_id : int
  SysObject_name : nvarchar(128)
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_RepoObjectColumn_guid : uniqueidentifier
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObjectColumn_column_id : int
  SysObjectColumn_name : nvarchar(128)
  user_type_fullname : nvarchar(182)
  user_type_name : sysname
  uses_database_collation : bit
}

entity repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
  default_definition : nvarchar(max)
  default_is_system_named : bit
  default_name : sysname
  definition : nvarchar(max)
  generated_always_type : tinyint
  graph_type : int
  has_different_sys_names : bit
  increment_value : sql_variant
  * is_computed : bit
  * is_identity : bit
  is_nullable : bit
  is_persisted : bit
  is_query_plan_expression : bit
  is_repo_managed : bit
  is_RepoObjectColumn_name_uniqueidentifier : int
  is_SysObjectColumn_missing : bit
  is_SysObjectColumn_name_uniqueidentifier : int
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  Repo_is_computed : bit
  Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  RepoObject_fullname : nvarchar(261)
  RepoObject_guid : uniqueidentifier
  RepoObjectColumn_guid : uniqueidentifier
  RepoObjectColumn_name : nvarchar(128)
  RowNumberOverName : bigint
  seed_value : sql_variant
  * SysObject_column_id : int
  SysObject_column_name : sysname
  SysObject_fullname : nvarchar(261)
  * SysObject_id : int
  SysObject_name : nvarchar(128)
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_RepoObjectColumn_guid : uniqueidentifier
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObjectColumn_column_id : int
  SysObjectColumn_name : nvarchar(128)
  user_type_fullname : nvarchar(182)
  user_type_name : sysname
  uses_database_collation : bit
}

entity repo.usp_ExecutionLog_insert << P >> {
  --
}

entity repo.usp_sync_guid << P >> {
  --
}

entity repo.usp_sync_guid_RepoObjectColumn << P >> {
  --
}

entity repo_sys.SysColumn << V >> {
  --
  collation_name : sysname
  column_encryption_key_database_name : sysname
  column_encryption_key_id : int
  default_definition : nvarchar(max)
  default_is_system_named : bit
  default_name : sysname
  * default_object_id : int
  default_parent_column_id : int
  definition : nvarchar(max)
  encryption_algorithm_name : sysname
  encryption_type : int
  encryption_type_desc : nvarchar(64)
  generated_always_type : tinyint
  generated_always_type_desc : nvarchar(60)
  graph_type : int
  graph_type_desc : nvarchar(60)
  increment_value : sql_variant
  * is_ansi_padded : bit
  is_column_set : bit
  * is_computed : bit
  is_dts_replicated : bit
  * is_filestream : bit
  is_hidden : bit
  * is_identity : bit
  * is_masked : bit
  is_merge_published : bit
  is_non_sql_subscribed : bit
  is_nullable : bit
  is_persisted : bit
  is_replicated : bit
  * is_rowguidcol : bit
  is_sparse : bit
  * is_xml_document : bit
  last_value : sql_variant
  * max_length : smallint
  * precision : tinyint
  * rule_object_id : int
  * scale : tinyint
  seed_value : sql_variant
  * SysObject_column_id : int
  SysObject_column_name : sysname
  * SysObject_id : int
  SysObject_name : nvarchar(128)
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_RepoObjectColumn_guid : uniqueidentifier
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObject_type_desc : nvarchar(60)
  * system_type_id : tinyint
  user_type_fullname : nvarchar(182)
  * user_type_id : int
  user_type_name : sysname
  uses_database_collation : bit
  * xml_collection_id : int
}

entity repo_sys.usp_AddOrUpdateExtendedProperty << P >> {
  --
}

config.type_level1type_level2type <.. repo.usp_sync_guid_RepoObjectColumn
graph.RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
graph.RepoObjectColumn_S <.. graph.RepoObjectColumn
graph.RepoObjectColumn_S <.. graph.usp_PERSIST_RepoObjectColumn
graph.RepoObjectColumn_S <.. repo.usp_sync_guid_RepoObjectColumn
graph.usp_PERSIST_RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObject <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObject <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObject_persistence <.. repo.RepoObjectColumn_HistValidColums_setpoint
repo.RepoObject_persistence <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo.RepoObjectColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo.RepoObjectColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo.RepoObjectColumn_HistValidColums_setpoint <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_guid <.. repo.usp_sync_guid_RepoObjectColumn
repo.SysColumn_RepoObjectColumn_via_name <.. repo.usp_sync_guid_RepoObjectColumn
repo.usp_ExecutionLog_insert <.. graph.usp_PERSIST_RepoObjectColumn
repo.usp_ExecutionLog_insert <.. repo.usp_sync_guid_RepoObjectColumn
repo.usp_ExecutionLog_insert <.. repo.usp_sync_guid
repo.usp_sync_guid_RepoObjectColumn <.. repo.usp_sync_guid
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_guid
repo_sys.SysColumn <.. repo.SysColumn_RepoObjectColumn_via_name
repo_sys.SysColumn <.. repo.usp_sync_guid_RepoObjectColumn
repo_sys.usp_AddOrUpdateExtendedProperty <.. repo.usp_sync_guid_RepoObjectColumn
graph.RepoObjectColumn_S::RepoObject_fullname <-- graph.RepoObjectColumn::RepoObject_fullname
graph.RepoObjectColumn_S::RepoObject_fullname2 <-- graph.RepoObjectColumn::RepoObject_fullname2
graph.RepoObjectColumn_S::RepoObject_guid <-- graph.RepoObjectColumn::RepoObject_guid
graph.RepoObjectColumn_S::RepoObject_type <-- graph.RepoObjectColumn::RepoObject_type
graph.RepoObjectColumn_S::RepoObjectColumn_fullname <-- graph.RepoObjectColumn::RepoObjectColumn_fullname
graph.RepoObjectColumn_S::RepoObjectColumn_fullname2 <-- graph.RepoObjectColumn::RepoObjectColumn_fullname2
graph.RepoObjectColumn_S::RepoObjectColumn_guid <-- graph.RepoObjectColumn::RepoObjectColumn_guid
graph.RepoObjectColumn_S::RepoObjectColumn_name <-- graph.RepoObjectColumn::RepoObjectColumn_name
graph.RepoObjectColumn_S::RepoObjectColumn_type <-- graph.RepoObjectColumn::RepoObjectColumn_type
repo.RepoObject::is_repo_managed <-- repo.SysColumn_RepoObjectColumn_via_guid::is_repo_managed
repo.RepoObject::is_repo_managed <-- repo.SysColumn_RepoObjectColumn_via_name::is_repo_managed
repo.RepoObject::RepoObject_fullname <-- repo.SysColumn_RepoObjectColumn_via_name::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo.SysColumn_RepoObjectColumn_via_guid::RepoObject_fullname
repo.RepoObject::SysObject_fullname <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo.SysColumn_RepoObjectColumn_via_name::SysObject_fullname
repo.RepoObjectColumn::has_different_sys_names <-- repo.SysColumn_RepoObjectColumn_via_guid::has_different_sys_names
repo.RepoObjectColumn::has_different_sys_names <-- repo.SysColumn_RepoObjectColumn_via_name::has_different_sys_names
repo.RepoObjectColumn::is_query_plan_expression <-- repo.SysColumn_RepoObjectColumn_via_guid::is_query_plan_expression
repo.RepoObjectColumn::is_query_plan_expression <-- repo.SysColumn_RepoObjectColumn_via_name::is_query_plan_expression
repo.RepoObjectColumn::is_RepoObjectColumn_name_uniqueidentifier <-- repo.SysColumn_RepoObjectColumn_via_name::is_RepoObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn::is_RepoObjectColumn_name_uniqueidentifier <-- repo.SysColumn_RepoObjectColumn_via_guid::is_RepoObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn::is_SysObjectColumn_missing <-- repo.SysColumn_RepoObjectColumn_via_guid::is_SysObjectColumn_missing
repo.RepoObjectColumn::is_SysObjectColumn_missing <-- repo.SysColumn_RepoObjectColumn_via_name::is_SysObjectColumn_missing
repo.RepoObjectColumn::is_SysObjectColumn_name_uniqueidentifier <-- repo.SysColumn_RepoObjectColumn_via_name::is_SysObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn::is_SysObjectColumn_name_uniqueidentifier <-- repo.SysColumn_RepoObjectColumn_via_guid::is_SysObjectColumn_name_uniqueidentifier
repo.RepoObjectColumn::persistence_source_RepoObjectColumn_guid <-- repo.SysColumn_RepoObjectColumn_via_guid::persistence_source_RepoObjectColumn_guid
repo.RepoObjectColumn::persistence_source_RepoObjectColumn_guid <-- repo.SysColumn_RepoObjectColumn_via_name::persistence_source_RepoObjectColumn_guid
repo.RepoObjectColumn::Referencing_Count <-- repo.SysColumn_RepoObjectColumn_via_name::Referencing_Count
repo.RepoObjectColumn::Referencing_Count <-- repo.SysColumn_RepoObjectColumn_via_guid::Referencing_Count
repo.RepoObjectColumn::Repo_default_definition <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_default_definition
repo.RepoObjectColumn::Repo_default_definition <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_default_definition
repo.RepoObjectColumn::Repo_default_is_system_named <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_default_is_system_named
repo.RepoObjectColumn::Repo_default_is_system_named <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_default_is_system_named
repo.RepoObjectColumn::Repo_default_name <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_default_name
repo.RepoObjectColumn::Repo_default_name <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_default_name
repo.RepoObjectColumn::Repo_definition <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_definition
repo.RepoObjectColumn::Repo_definition <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_definition
repo.RepoObjectColumn::Repo_generated_always_type <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_generated_always_type
repo.RepoObjectColumn::Repo_generated_always_type <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_generated_always_type
repo.RepoObjectColumn::Repo_graph_type <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_graph_type
repo.RepoObjectColumn::Repo_graph_type <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_graph_type
repo.RepoObjectColumn::Repo_increment_value <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_increment_value
repo.RepoObjectColumn::Repo_increment_value <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_increment_value
repo.RepoObjectColumn::Repo_is_computed <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_is_computed
repo.RepoObjectColumn::Repo_is_computed <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_is_computed
repo.RepoObjectColumn::Repo_is_identity <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_is_identity
repo.RepoObjectColumn::Repo_is_identity <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_is_identity
repo.RepoObjectColumn::Repo_is_nullable <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_is_nullable
repo.RepoObjectColumn::Repo_is_nullable <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_is_nullable
repo.RepoObjectColumn::Repo_is_persisted <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_is_persisted
repo.RepoObjectColumn::Repo_is_persisted <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_is_persisted
repo.RepoObjectColumn::Repo_seed_value <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_seed_value
repo.RepoObjectColumn::Repo_seed_value <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_seed_value
repo.RepoObjectColumn::Repo_user_type_fullname <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_user_type_fullname
repo.RepoObjectColumn::Repo_user_type_fullname <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_user_type_fullname
repo.RepoObjectColumn::Repo_user_type_name <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_user_type_name
repo.RepoObjectColumn::Repo_user_type_name <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_user_type_name
repo.RepoObjectColumn::Repo_uses_database_collation <-- repo.SysColumn_RepoObjectColumn_via_name::Repo_uses_database_collation
repo.RepoObjectColumn::Repo_uses_database_collation <-- repo.SysColumn_RepoObjectColumn_via_guid::Repo_uses_database_collation
repo.RepoObjectColumn::RepoObject_guid <-- repo.SysColumn_RepoObjectColumn_via_name::RepoObject_guid
repo.RepoObjectColumn::RepoObject_guid <-- repo.SysColumn_RepoObjectColumn_via_guid::RepoObject_guid
repo.RepoObjectColumn::RepoObjectColumn_guid <-- repo.SysColumn_RepoObjectColumn_via_guid::RepoObjectColumn_guid
repo.RepoObjectColumn::RepoObjectColumn_guid <-- repo.SysColumn_RepoObjectColumn_via_name::RepoObjectColumn_guid
repo.RepoObjectColumn::RepoObjectColumn_name <-- repo.SysColumn_RepoObjectColumn_via_name::RepoObjectColumn_name
repo.RepoObjectColumn::RepoObjectColumn_name <-- repo.SysColumn_RepoObjectColumn_via_guid::RepoObjectColumn_name
repo.RepoObjectColumn::SysObjectColumn_column_id <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObjectColumn_column_id
repo.RepoObjectColumn::SysObjectColumn_column_id <-- repo.SysColumn_RepoObjectColumn_via_name::SysObjectColumn_column_id
repo.RepoObjectColumn::SysObjectColumn_name <-- repo.SysColumn_RepoObjectColumn_via_name::SysObjectColumn_name
repo.RepoObjectColumn::SysObjectColumn_name <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObjectColumn_name
repo_sys.SysColumn::default_definition <-- repo.SysColumn_RepoObjectColumn_via_name::default_definition
repo_sys.SysColumn::default_definition <-- repo.SysColumn_RepoObjectColumn_via_guid::default_definition
repo_sys.SysColumn::default_is_system_named <-- repo.SysColumn_RepoObjectColumn_via_guid::default_is_system_named
repo_sys.SysColumn::default_is_system_named <-- repo.SysColumn_RepoObjectColumn_via_name::default_is_system_named
repo_sys.SysColumn::default_name <-- repo.SysColumn_RepoObjectColumn_via_name::default_name
repo_sys.SysColumn::default_name <-- repo.SysColumn_RepoObjectColumn_via_guid::default_name
repo_sys.SysColumn::definition <-- repo.SysColumn_RepoObjectColumn_via_guid::definition
repo_sys.SysColumn::definition <-- repo.SysColumn_RepoObjectColumn_via_name::definition
repo_sys.SysColumn::generated_always_type <-- repo.SysColumn_RepoObjectColumn_via_name::generated_always_type
repo_sys.SysColumn::generated_always_type <-- repo.SysColumn_RepoObjectColumn_via_guid::generated_always_type
repo_sys.SysColumn::graph_type <-- repo.SysColumn_RepoObjectColumn_via_guid::graph_type
repo_sys.SysColumn::graph_type <-- repo.SysColumn_RepoObjectColumn_via_name::graph_type
repo_sys.SysColumn::increment_value <-- repo.SysColumn_RepoObjectColumn_via_guid::increment_value
repo_sys.SysColumn::increment_value <-- repo.SysColumn_RepoObjectColumn_via_name::increment_value
repo_sys.SysColumn::is_computed <-- repo.SysColumn_RepoObjectColumn_via_name::is_computed
repo_sys.SysColumn::is_computed <-- repo.SysColumn_RepoObjectColumn_via_guid::is_computed
repo_sys.SysColumn::is_identity <-- repo.SysColumn_RepoObjectColumn_via_guid::is_identity
repo_sys.SysColumn::is_identity <-- repo.SysColumn_RepoObjectColumn_via_name::is_identity
repo_sys.SysColumn::is_nullable <-- repo.SysColumn_RepoObjectColumn_via_name::is_nullable
repo_sys.SysColumn::is_nullable <-- repo.SysColumn_RepoObjectColumn_via_guid::is_nullable
repo_sys.SysColumn::is_persisted <-- repo.SysColumn_RepoObjectColumn_via_guid::is_persisted
repo_sys.SysColumn::is_persisted <-- repo.SysColumn_RepoObjectColumn_via_name::is_persisted
repo_sys.SysColumn::seed_value <-- repo.SysColumn_RepoObjectColumn_via_name::seed_value
repo_sys.SysColumn::seed_value <-- repo.SysColumn_RepoObjectColumn_via_guid::seed_value
repo_sys.SysColumn::SysObject_column_id <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_column_id
repo_sys.SysColumn::SysObject_column_id <-- repo.SysColumn_RepoObjectColumn_via_name::SysObject_column_id
repo_sys.SysColumn::SysObject_column_name <-- repo.SysColumn_RepoObjectColumn_via_name::SysObject_column_name
repo_sys.SysColumn::SysObject_column_name <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_column_name
repo_sys.SysColumn::SysObject_id <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_id
repo_sys.SysColumn::SysObject_id <-- repo.SysColumn_RepoObjectColumn_via_name::SysObject_id
repo_sys.SysColumn::SysObject_name <-- repo.SysColumn_RepoObjectColumn_via_name::SysObject_name
repo_sys.SysColumn::SysObject_name <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_name
repo_sys.SysColumn::SysObject_RepoObject_guid <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_RepoObject_guid
repo_sys.SysColumn::SysObject_RepoObject_guid <-- repo.SysColumn_RepoObjectColumn_via_name::SysObject_RepoObject_guid
repo_sys.SysColumn::SysObject_RepoObjectColumn_guid <-- repo.SysColumn_RepoObjectColumn_via_name::SysObject_RepoObjectColumn_guid
repo_sys.SysColumn::SysObject_RepoObjectColumn_guid <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_RepoObjectColumn_guid
repo_sys.SysColumn::SysObject_schema_name <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_schema_name
repo_sys.SysColumn::SysObject_schema_name <-- repo.SysColumn_RepoObjectColumn_via_name::SysObject_schema_name
repo_sys.SysColumn::SysObject_type <-- repo.SysColumn_RepoObjectColumn_via_name::SysObject_type
repo_sys.SysColumn::SysObject_type <-- repo.SysColumn_RepoObjectColumn_via_guid::SysObject_type
repo_sys.SysColumn::user_type_fullname <-- repo.SysColumn_RepoObjectColumn_via_guid::user_type_fullname
repo_sys.SysColumn::user_type_fullname <-- repo.SysColumn_RepoObjectColumn_via_name::user_type_fullname
repo_sys.SysColumn::user_type_name <-- repo.SysColumn_RepoObjectColumn_via_name::user_type_name
repo_sys.SysColumn::user_type_name <-- repo.SysColumn_RepoObjectColumn_via_guid::user_type_name
repo_sys.SysColumn::uses_database_collation <-- repo.SysColumn_RepoObjectColumn_via_guid::uses_database_collation
repo_sys.SysColumn::uses_database_collation <-- repo.SysColumn_RepoObjectColumn_via_name::uses_database_collation
