left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.fs_dwh_database_name << FN >> {
  --
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_repo_managed : bit
  is_SysObject_missing : bit
  * modify_dt : datetime
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnName_new : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObject_name_uniqueidentifier : int
  * {static} is_SysObject_name_uniqueidentifier : int
  {abstract} node_id : bigint
  * {static} RepoObject_fullname : nvarchar(261)
  * {static} RepoObject_fullname2 : nvarchar(257)
  * {static} SysObject_fullname : nvarchar(261)
  * {static} SysObject_fullname2 : nvarchar(257)
  * {abstract} SysObject_query_sql : nvarchar(406)
  * {static} usp_persistence_name : nvarchar(140)
}

entity repo.RepoObject_reference_union << V >> {
  **referenced_RepoObject_guid** : uniqueidentifier
  **referencing_RepoObject_guid** : uniqueidentifier
  --
  * InformationSource : varchar(31)
  * one : int
  referenced_entity_name : nvarchar(128)
  * referenced_fullname : nvarchar(517)
  referenced_id : int
  referenced_node_id : bigint
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_entity_name : nvarchar(128)
  * referencing_fullname : nvarchar(517)
  referencing_id : int
  referencing_node_id : bigint
  referencing_schema_name : nvarchar(128)
  referencing_type : varchar(2)
}

entity repo.RepoObjectColumn_gross << V >> {
  --
  AntoraReferencedColumnList : nvarchar(max)
  AntoraReferencingColumnList : nvarchar(max)
  has_different_sys_names : bit
  has_get_referenced_issue : bit
  index_column_id : int
  index_name : nvarchar(128)
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_index_primary_key : bit
  is_persistence_no_check : bit
  is_persistence_no_include : bit
  is_persistence_no_update : bit
  is_query_plan_expression : bit
  is_repo_managed : bit
  * is_RepoObject_name_uniqueidentifier : int
  * is_RepoObjectColumn_name_uniqueidentifier : int
  is_SysObject_missing : bit
  * is_SysObject_name_uniqueidentifier : int
  is_SysObjectColumn_missing : bit
  * is_SysObjectColumn_name_uniqueidentifier : int
  * modify_dt : datetime
  node_id : bigint
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  pk_index_guid : uniqueidentifier
  Property_ms_description : nvarchar(4000)
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  * Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  * Repo_is_computed : bit
  * Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  * RepoObject_guid : uniqueidentifier
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  RepoObjectColumn_column_id : int
  * RepoObjectColumn_fullname : nvarchar(520)
  * RepoObjectColumn_fullname2 : nvarchar(386)
  * RepoObjectColumn_guid : uniqueidentifier
  * RepoObjectColumn_name : nvarchar(128)
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObjectColumn_column_id : int
  * SysObjectColumn_name : nvarchar(128)
}

entity repo.RepoObjectColumn_reference_QueryPlan << V >> {
  --
  definition : nvarchar(max)
  * InformationSource : varchar(10)
  is_computed : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  is_source_column_name_expression : bit
  is_target_column_name_expression : bit
  referenced_column_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_id : int
  referenced_minor_id : int
  referenced_node_id : bigint
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_column_name : nvarchar(128)
  * referencing_entity_name : nvarchar(128)
  referencing_id : int
  referencing_minor_id : int
  referencing_node_id : bigint
  * referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
  * referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
  source_schema_name_quoted : nvarchar(128)
  source_table_name_quoted : nvarchar(128)
}

entity repo.RepoObjectSource_QueryPlan << U >> {
  --
  const_info : xml
  const_value : nvarchar(4000)
  * RepoObject_guid : uniqueidentifier
  source_column_info : xml
  source_column_name : nvarchar(128)
  source_database_name : nvarchar(128)
  source_schema_name : nvarchar(128)
  source_server_name : nvarchar(128)
  source_table_name : nvarchar(128)
  SysObject_query_executed_dt : datetime
  target_column_info : xml
  target_column_name : nvarchar(128)
  {abstract} is_source_column_name_expression : bit
  {abstract} is_target_column_name_expression : bit
}

entity repo.SysObjectColumn_QueryPlanExpression << V >> {
  --
  RepoObject_guid : uniqueidentifier
  SysObjectColumn_column_id : int
  SysObjectColumn_name : nvarchar(128)
}

repo.fs_dwh_database_name <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObject <.. repo.RepoObjectColumn_gross
repo.RepoObject <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObject_reference_union <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_gross <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObjectColumn_reference_QueryPlan <.. repo.SysObjectColumn_QueryPlanExpression
repo.RepoObjectSource_QueryPlan <.. repo.RepoObjectColumn_reference_QueryPlan
repo.RepoObject::has_get_referenced_issue <-- repo.RepoObjectColumn_gross::has_get_referenced_issue
repo.RepoObject::is_repo_managed <-- repo.RepoObjectColumn_gross::is_repo_managed
repo.RepoObject::is_RepoObject_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_RepoObject_name_uniqueidentifier
repo.RepoObject::is_SysObject_missing <-- repo.RepoObjectColumn_gross::is_SysObject_missing
repo.RepoObject::is_SysObject_name_uniqueidentifier <-- repo.RepoObjectColumn_gross::is_SysObject_name_uniqueidentifier
repo.RepoObject::modify_dt <-- repo.RepoObjectColumn_gross::modify_dt
repo.RepoObject::node_id <-- repo.RepoObjectColumn_gross::node_id
repo.RepoObject::pk_index_guid <-- repo.RepoObjectColumn_gross::pk_index_guid
repo.RepoObject::RepoObject_fullname <-- repo.RepoObjectColumn_gross::RepoObject_fullname
repo.RepoObject::RepoObject_fullname2 <-- repo.RepoObjectColumn_gross::RepoObject_fullname2
repo.RepoObject::RepoObject_name <-- repo.RepoObjectColumn_gross::RepoObject_name
repo.RepoObject::RepoObject_Referencing_Count <-- repo.RepoObjectColumn_gross::RepoObject_Referencing_Count
repo.RepoObject::RepoObject_schema_name <-- repo.RepoObjectColumn_gross::RepoObject_schema_name
repo.RepoObject::RepoObject_type <-- repo.RepoObjectColumn_gross::RepoObject_type
repo.RepoObject::SysObject_fullname <-- repo.RepoObjectColumn_gross::SysObject_fullname
repo.RepoObject::SysObject_fullname2 <-- repo.RepoObjectColumn_gross::SysObject_fullname2
repo.RepoObject::SysObject_id <-- repo.RepoObjectColumn_gross::SysObject_id
repo.RepoObject::SysObject_modify_date <-- repo.RepoObjectColumn_gross::SysObject_modify_date
repo.RepoObject::SysObject_name <-- repo.RepoObjectColumn_gross::SysObject_name
repo.RepoObject::SysObject_parent_object_id <-- repo.RepoObjectColumn_gross::SysObject_parent_object_id
repo.RepoObject::SysObject_schema_name <-- repo.RepoObjectColumn_gross::SysObject_schema_name
repo.RepoObject::SysObject_type <-- repo.RepoObjectColumn_gross::SysObject_type
repo.RepoObjectSource_QueryPlan::is_source_column_name_expression <-- repo.RepoObjectColumn_reference_QueryPlan::is_source_column_name_expression
repo.RepoObjectSource_QueryPlan::is_target_column_name_expression <-- repo.RepoObjectColumn_reference_QueryPlan::is_target_column_name_expression
