left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity logs.usp_ExecutionLog_insert << P >> {
  --
}

entity repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing << V >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  **RowNumberInReferencing** : bigint
  --
  is_descending_key : bit
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
}

entity repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << U >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  **RowNumberInReferencing** : bigint
  --
  is_descending_key : bit
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
}

entity repo.usp_index_inheritance << P >> {
  --
}

entity repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T << P >> {
  --
}

logs.usp_ExecutionLog_insert <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
logs.usp_ExecutionLog_insert <.. repo.usp_index_inheritance
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T
repo.usp_PERSIST_IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T <.. repo.usp_index_inheritance
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing::index_column_id <-- repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::index_column_id
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing::index_guid <-- repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::index_guid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing::is_descending_key <-- repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::is_descending_key
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing::referenced_RepoObject_guid <-- repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::referenced_RepoObject_guid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing::referenced_RepoObjectColumn_guid <-- repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::referenced_RepoObjectColumn_guid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing::referencing_RepoObject_guid <-- repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::referencing_RepoObject_guid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing::referencing_RepoObjectColumn_guid <-- repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::referencing_RepoObjectColumn_guid
repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing::RowNumberInReferencing <-- repo.IndexColumn_ReferencedReferencing_HasFullColumnsInReferencing_T::RowNumberInReferencing
