left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_repo_managed : bit
  is_required_ObjectMerge : bit
  is_SysObject_missing : bit
  * modify_dt : datetime
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnName_new : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObject_name_uniqueidentifier : int
  * {static} is_SysObject_name_uniqueidentifier : int
  {abstract} node_id : bigint
  * {static} RepoObject_fullname : nvarchar(261)
  * {static} RepoObject_fullname2 : nvarchar(257)
  * {static} SysObject_fullname : nvarchar(261)
  * {static} SysObject_fullname2 : nvarchar(257)
  * {abstract} SysObject_query_sql : nvarchar(406)
  * {static} usp_persistence_name : nvarchar(140)
}

entity repo.RepoObject_gross << V >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  AntoraReferencedList : nvarchar(max)
  AntoraReferencingList : nvarchar(max)
  CreateColumnList : nvarchar(max)
  DbmlColumnList : nvarchar(max)
  has_different_sys_names : bit
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  has_history : bit
  has_history_columns : bit
  history_schema_name : nvarchar(128)
  history_table_name : nvarchar(128)
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_DocsOutput : int
  * is_in_reference : int
  is_persistence : bit
  is_persistence_check_duplicate_per_pk : bit
  is_persistence_check_for_empty_source : bit
  is_persistence_delete_changed : bit
  is_persistence_delete_missing : bit
  is_persistence_insert : bit
  is_persistence_truncate : bit
  is_persistence_update_changed : bit
  is_repo_managed : bit
  * is_RepoObject_name_uniqueidentifier : int
  is_required_ObjectMerge : bit
  is_SysObject_missing : bit
  * is_SysObject_name_uniqueidentifier : int
  * modify_dt : datetime
  node_id : bigint
  persistence_source_RepoObject_fullname : nvarchar(261)
  persistence_source_RepoObject_fullname2 : nvarchar(257)
  persistence_source_RepoObject_guid : uniqueidentifier
  persistence_source_RepoObject_xref : nvarchar(269)
  persistence_source_SysObject_fullname : nvarchar(261)
  persistence_source_SysObject_fullname2 : nvarchar(257)
  persistence_source_SysObject_xref : nvarchar(269)
  PersistenceCompareColumnList : nvarchar(max)
  PersistenceInsertColumnList : nvarchar(max)
  PersistenceUpdateColumnList : nvarchar(max)
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnDatatype : nvarchar(4000)
  pk_IndexPatternColumnName : nvarchar(4000)
  pk_IndexPatternColumnName_new : nvarchar(4000)
  pk_IndexSemanticGroup : nvarchar(512)
  Property_ms_description : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_fullname2 : nvarchar(257)
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  RepoObject_type_name : nvarchar(128)
  sql_modules_antora : nvarchar(max)
  sql_modules_definition : nvarchar(max)
  sql_modules_formatted : nvarchar(max)
  sql_modules_formatted2 : nvarchar(max)
  * SysObject_fullname : nvarchar(261)
  * SysObject_fullname2 : nvarchar(257)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  SysObject_query_executed_dt : datetime
  SysObject_query_plan : xml
  * SysObject_query_sql : nvarchar(406)
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObject_type_name : nvarchar(128)
  temporal_type : tinyint
  * usp_persistence_name : nvarchar(140)
  usp_persistence_RepoObject_guid : uniqueidentifier
}

entity repo.RepoObject_SqlModules << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  * sql_modules_dt : datetime
  sql_modules_formatted : nvarchar(max)
  sql_modules_formatted2 : nvarchar(max)
  sql_modules_json : nvarchar(max)
  {static} is_json_sql_modules_json : int
}

entity repo.RepoObject_SqlModules_Repo_Sys << V >> {
  --
  is_json_sql_modules_json : int
  is_outdated : bit
  * modify_date : datetime
  * RepoObject_guid : uniqueidentifier
  sql_modules_definition : nvarchar(max)
  sql_modules_dt : datetime
  sql_modules_formatted : nvarchar(max)
  sql_modules_formatted2 : nvarchar(max)
  sql_modules_json : nvarchar(max)
  SysObject_type : char(2)
}

entity repo.RepoObjectProperty_from_sql_modules_definition << V >> {
  --
  property_name : nvarchar(128)
  property_value : nvarchar(4000)
  * RepoObject_guid : uniqueidentifier
}

entity repo_sys.SysObject << V >> {
  --
  * create_date : datetime
  history_table_id : int
  * is_ms_shipped : bit
  * is_published : bit
  * is_schema_published : bit
  max_column_id_used : int
  * modify_date : datetime
  * parent_object_id : int
  principal_id : int
  * schema_id : int
  sql_modules_definition : nvarchar(max)
  * SysObject_fullname : nvarchar(517)
  * SysObject_fullname2 : nvarchar(257)
  * SysObject_id : int
  * SysObject_name : sysname
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_schema_name : sysname
  temporal_type : tinyint
  temporal_type_desc : nvarchar(60)
  type : char(2)
  type_desc : nvarchar(60)
}

repo.RepoObject <.. repo.RepoObject_SqlModules_Repo_Sys
repo.RepoObject <.. repo.RepoObject_gross
repo.RepoObject_SqlModules <.. repo.RepoObject_SqlModules_Repo_Sys
repo.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObject_gross
repo.RepoObject_SqlModules_Repo_Sys <.. repo.RepoObjectProperty_from_sql_modules_definition
repo_sys.SysObject <.. repo.RepoObject_SqlModules_Repo_Sys
repo.RepoObject::has_different_sys_names <-- repo.RepoObject_gross::has_different_sys_names
repo.RepoObject::has_execution_plan_issue <-- repo.RepoObject_gross::has_execution_plan_issue
repo.RepoObject::has_get_referenced_issue <-- repo.RepoObject_gross::has_get_referenced_issue
repo.RepoObject::Inheritance_StringAggSeparatorSql <-- repo.RepoObject_gross::Inheritance_StringAggSeparatorSql
repo.RepoObject::InheritanceDefinition <-- repo.RepoObject_gross::InheritanceDefinition
repo.RepoObject::InheritanceType <-- repo.RepoObject_gross::InheritanceType
repo.RepoObject::is_repo_managed <-- repo.RepoObject_gross::is_repo_managed
repo.RepoObject::is_RepoObject_name_uniqueidentifier <-- repo.RepoObject_gross::is_RepoObject_name_uniqueidentifier
repo.RepoObject::is_required_ObjectMerge <-- repo.RepoObject_gross::is_required_ObjectMerge
repo.RepoObject::is_SysObject_missing <-- repo.RepoObject_gross::is_SysObject_missing
repo.RepoObject::is_SysObject_name_uniqueidentifier <-- repo.RepoObject_gross::is_SysObject_name_uniqueidentifier
repo.RepoObject::modify_dt <-- repo.RepoObject_gross::modify_dt
repo.RepoObject::node_id <-- repo.RepoObject_gross::node_id
repo.RepoObject::pk_index_guid <-- repo.RepoObject_gross::pk_index_guid
repo.RepoObject::pk_IndexPatternColumnName_new <-- repo.RepoObject_gross::pk_IndexPatternColumnName_new
repo.RepoObject::Repo_history_table_guid <-- repo.RepoObject_gross::Repo_history_table_guid
repo.RepoObject::Repo_temporal_type <-- repo.RepoObject_gross::Repo_temporal_type
repo.RepoObject::RepoObject_fullname <-- repo.RepoObject_gross::RepoObject_fullname
repo.RepoObject::RepoObject_fullname2 <-- repo.RepoObject_gross::RepoObject_fullname2
repo.RepoObject::RepoObject_guid <-- repo.RepoObject_SqlModules_Repo_Sys::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo.RepoObject_gross::RepoObject_guid
repo.RepoObject::RepoObject_name <-- repo.RepoObject_gross::RepoObject_name
repo.RepoObject::RepoObject_Referencing_Count <-- repo.RepoObject_gross::RepoObject_Referencing_Count
repo.RepoObject::RepoObject_schema_name <-- repo.RepoObject_gross::RepoObject_schema_name
repo.RepoObject::RepoObject_type <-- repo.RepoObject_gross::RepoObject_type
repo.RepoObject::SysObject_fullname <-- repo.RepoObject_gross::SysObject_fullname
repo.RepoObject::SysObject_fullname2 <-- repo.RepoObject_gross::SysObject_fullname2
repo.RepoObject::SysObject_id <-- repo.RepoObject_gross::SysObject_id
repo.RepoObject::SysObject_modify_date <-- repo.RepoObject_gross::SysObject_modify_date
repo.RepoObject::SysObject_name <-- repo.RepoObject_gross::SysObject_name
repo.RepoObject::SysObject_parent_object_id <-- repo.RepoObject_gross::SysObject_parent_object_id
repo.RepoObject::SysObject_query_sql <-- repo.RepoObject_gross::SysObject_query_sql
repo.RepoObject::SysObject_schema_name <-- repo.RepoObject_gross::SysObject_schema_name
repo.RepoObject::SysObject_type <-- repo.RepoObject_gross::SysObject_type
repo.RepoObject::SysObject_type <-- repo.RepoObject_SqlModules_Repo_Sys::SysObject_type
repo.RepoObject::usp_persistence_name <-- repo.RepoObject_gross::usp_persistence_name
repo.RepoObject_SqlModules::is_json_sql_modules_json <-- repo.RepoObject_SqlModules_Repo_Sys::is_json_sql_modules_json
repo.RepoObject_SqlModules::sql_modules_dt <-- repo.RepoObject_SqlModules_Repo_Sys::sql_modules_dt
repo.RepoObject_SqlModules::sql_modules_formatted <-- repo.RepoObject_SqlModules_Repo_Sys::sql_modules_formatted
repo.RepoObject_SqlModules::sql_modules_formatted2 <-- repo.RepoObject_SqlModules_Repo_Sys::sql_modules_formatted2
repo.RepoObject_SqlModules::sql_modules_json <-- repo.RepoObject_SqlModules_Repo_Sys::sql_modules_json
repo.RepoObject_SqlModules_Repo_Sys::RepoObject_guid <-- repo.RepoObjectProperty_from_sql_modules_definition::RepoObject_guid
repo.RepoObject_SqlModules_Repo_Sys::sql_modules_definition <-- repo.RepoObject_gross::sql_modules_definition
repo.RepoObject_SqlModules_Repo_Sys::sql_modules_formatted <-- repo.RepoObject_gross::sql_modules_formatted
repo.RepoObject_SqlModules_Repo_Sys::sql_modules_formatted2 <-- repo.RepoObject_gross::sql_modules_formatted2
repo_sys.SysObject::modify_date <-- repo.RepoObject_SqlModules_Repo_Sys::modify_date
repo_sys.SysObject::sql_modules_definition <-- repo.RepoObject_SqlModules_Repo_Sys::sql_modules_definition
