left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.Index_unique_IndexPatternColumnGuid << V >> {
  **index_guid** : uniqueidentifier
  --
  IndexPatternColumnGuid : varchar(8000)
}

entity repo.IndexColumn_union << V >> {
  **index_guid** : uniqueidentifier
  * **index_column_id** : int
  --
  index_name : nvarchar(128)
  is_descending_key : bit
  is_index_primary_key : bit
  is_index_real : bit
  is_index_unique : bit
  parent_RepoObject_guid : uniqueidentifier
  parent_schema_name : nvarchar(128)
  parent_SysObject_fullname : nvarchar(261)
  parent_SysObject_name : nvarchar(128)
  RepoObjectColumn_guid : uniqueidentifier
  SysObject_column_name : nvarchar(128)
  SysObject_column_user_type_fullname : nvarchar(182)
}

entity repo.SysColumn_RepoObjectColumn_via_name << V >> {
  --
  default_definition : nvarchar(max)
  default_is_system_named : bit
  default_name : sysname
  definition : nvarchar(max)
  generated_always_type : tinyint
  graph_type : int
  has_different_sys_names : bit
  increment_value : sql_variant
  * is_computed : bit
  * is_identity : bit
  is_nullable : bit
  is_persisted : bit
  is_query_plan_expression : bit
  is_repo_managed : bit
  is_RepoObjectColumn_name_uniqueidentifier : int
  is_SysObjectColumn_missing : bit
  is_SysObjectColumn_name_uniqueidentifier : int
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  Repo_is_computed : bit
  Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  RepoObject_fullname : nvarchar(261)
  RepoObject_guid : uniqueidentifier
  RepoObjectColumn_guid : uniqueidentifier
  RepoObjectColumn_name : nvarchar(128)
  RowNumberOverName : bigint
  seed_value : sql_variant
  * SysObject_column_id : int
  SysObject_column_name : sysname
  SysObject_fullname : nvarchar(261)
  * SysObject_id : int
  SysObject_name : nvarchar(128)
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_RepoObjectColumn_guid : uniqueidentifier
  SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  SysObjectColumn_column_id : int
  SysObjectColumn_name : nvarchar(128)
  user_type_fullname : nvarchar(182)
  user_type_name : sysname
  uses_database_collation : bit
}

entity repo.SysObject_RepoObject_via_name << V >> {
  --
  history_table_guid : uniqueidentifier
  history_table_id : int
  is_repo_managed : bit
  is_RepoObject_name_uniqueidentifier : int
  is_SysObject_name_uniqueidentifier : int
  * modify_date : datetime
  * parent_object_id : int
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  RepoObject_guid : uniqueidentifier
  RepoObject_is_SysObject_missing : bit
  RepoObject_name : nvarchar(128)
  RepoObject_schema_name : nvarchar(128)
  RepoObject_SysObject_id : int
  RepoObject_SysObject_modify_date : datetime
  RepoObject_SysObject_name : nvarchar(128)
  RepoObject_SysObject_parent_object_id : int
  RepoObject_SysObject_schema_name : nvarchar(128)
  RepoObject_SysObject_type : char(2)
  RepoObject_type : char(2)
  * SysObject_id : int
  * SysObject_name : sysname
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_schema_name : sysname
  SysObject_type : char(2)
  temporal_type : tinyint
}

entity repo_sys.IndexColumn_unique << V >> {
  --
  * index_column_id : int
  index_guid : uniqueidentifier
  * index_id : int
  index_name : sysname
  is_descending_key : bit
  is_index_primary_key : bit
  is_index_real : bit
  is_index_unique : bit
  parent_RepoObject_guid : uniqueidentifier
  parent_schema_name : nvarchar(128)
  parent_SysObject_fullname : nvarchar(261)
  parent_SysObject_name : nvarchar(128)
  RepoObjectColumn_guid : uniqueidentifier
  SysObject_column_name : sysname
  SysObject_column_user_type_fullname : nvarchar(182)
}

entity sys_dwh.index_columns << SN >> {
  --
}

entity sys_dwh.indexes << SN >> {
  --
}

repo.SysColumn_RepoObjectColumn_via_name <.. repo_sys.IndexColumn_unique
repo.SysObject_RepoObject_via_name <.. repo_sys.IndexColumn_unique
repo_sys.IndexColumn_unique <.. repo.IndexColumn_union
repo_sys.IndexColumn_unique <.. repo.Index_unique_IndexPatternColumnGuid
sys_dwh.index_columns <.. repo_sys.IndexColumn_unique
sys_dwh.indexes <.. repo_sys.IndexColumn_unique
repo.SysColumn_RepoObjectColumn_via_name::RepoObject_guid <-- repo_sys.IndexColumn_unique::parent_RepoObject_guid
repo.SysColumn_RepoObjectColumn_via_name::RepoObjectColumn_guid <-- repo_sys.IndexColumn_unique::RepoObjectColumn_guid
repo.SysColumn_RepoObjectColumn_via_name::SysObject_column_name <-- repo_sys.IndexColumn_unique::SysObject_column_name
repo.SysColumn_RepoObjectColumn_via_name::SysObject_fullname <-- repo_sys.IndexColumn_unique::parent_SysObject_fullname
repo.SysColumn_RepoObjectColumn_via_name::SysObject_name <-- repo_sys.IndexColumn_unique::parent_SysObject_name
repo.SysColumn_RepoObjectColumn_via_name::SysObject_schema_name <-- repo_sys.IndexColumn_unique::parent_schema_name
repo.SysObject_RepoObject_via_name::RepoObject_guid <-- repo_sys.IndexColumn_unique::index_guid
repo_sys.IndexColumn_unique::index_guid <-- repo.Index_unique_IndexPatternColumnGuid::index_guid
