left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity config.ftv_dwh_database << IF >> {
  --
  dwh_database_id : smallint
  dwh_database_name : nvarchar(128)
}

entity logs.usp_ExecutionLog_insert << P >> {
  --
}

entity repo.RepoObject << U >> {
  * **RepoObject_guid** : uniqueidentifier
  --
  has_execution_plan_issue : bit
  has_get_referenced_issue : bit
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_repo_managed : bit
  is_required_ObjectMerge : bit
  is_SysObject_missing : bit
  * modify_dt : datetime
  pk_index_guid : uniqueidentifier
  pk_IndexPatternColumnName_new : nvarchar(4000)
  Repo_history_table_guid : uniqueidentifier
  Repo_temporal_type : tinyint
  * RepoObject_name : nvarchar(128)
  RepoObject_Referencing_Count : int
  * RepoObject_schema_name : nvarchar(128)
  * RepoObject_type : char(2)
  SysObject_id : int
  SysObject_modify_date : datetime
  * SysObject_name : nvarchar(128)
  * SysObject_parent_object_id : int
  * SysObject_schema_name : nvarchar(128)
  SysObject_type : char(2)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObject_name_uniqueidentifier : int
  * {static} is_SysObject_name_uniqueidentifier : int
  {abstract} node_id : bigint
  * {static} RepoObject_fullname : nvarchar(261)
  * {static} RepoObject_fullname2 : nvarchar(257)
  * {static} SysObject_fullname : nvarchar(261)
  * {static} SysObject_fullname2 : nvarchar(257)
  * {abstract} SysObject_query_sql : nvarchar(406)
  * {static} usp_persistence_name : nvarchar(140)
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_persistence_no_check : bit
  is_persistence_no_include : bit
  is_persistence_no_update : bit
  is_query_plan_expression : bit
  is_required_ColumnMerge : bit
  is_SysObjectColumn_missing : bit
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  * Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  * Repo_is_computed : bit
  * Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  * RepoObject_guid : uniqueidentifier
  RepoObjectColumn_column_id : int
  * RepoObjectColumn_name : nvarchar(128)
  SysObjectColumn_column_id : int
  * SysObjectColumn_name : nvarchar(128)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObjectColumn_name_uniqueidentifier : int
  * {static} is_SysObjectColumn_name_uniqueidentifier : int
}

entity repo.usp_main << P >> {
  --
}

entity repo.usp_update_Referencing_Count << P >> {
  --
}

entity repo_sys.RepoObjectReferenced << V >> {
  --
  has_different_sys_names : bit
  * is_all_columns_found : bit
  * is_ambiguous : bit
  * is_caller_dependent : bit
  * is_incomplete : bit
  * is_insert_all : bit
  is_repo_managed : bit
  * is_select_all : bit
  * is_selected : bit
  * is_updated : bit
  referenced_class : tinyint
  referenced_class_desc : nvarchar(60)
  referenced_database_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_id : int
  referenced_minor_id : int
  referenced_minor_name : nvarchar(128)
  referenced_schema_name : nvarchar(128)
  referenced_server_name : nvarchar(128)
  referencing_minor_id : int
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_guid : uniqueidentifier
  * SysObject_fullname : nvarchar(261)
  SysObject_id : int
  SysObject_modify_date : datetime
  SysObject_type : char(2)
}

entity repo_sys.RepoObjectReferencing << V >> {
  --
  has_different_sys_names : bit
  * is_caller_dependent : bit
  is_repo_managed : bit
  referencing_class : tinyint
  referencing_class_desc : nvarchar(60)
  referencing_entity_name : sysname
  * referencing_id : int
  referencing_schema_name : sysname
  * RepoObject_fullname : nvarchar(261)
  * RepoObject_guid : uniqueidentifier
  * SysObject_fullname : nvarchar(261)
  SysObject_id : int
  SysObject_modify_date : datetime
  SysObject_type : char(2)
}

config.ftv_dwh_database <.. repo.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. repo.usp_update_Referencing_Count
logs.usp_ExecutionLog_insert <.. repo.usp_main
repo.RepoObject <.. repo_sys.RepoObjectReferenced
repo.RepoObject <.. repo_sys.RepoObjectReferencing
repo.RepoObject <.. repo.usp_update_Referencing_Count
repo.RepoObjectColumn <.. repo.usp_update_Referencing_Count
repo.usp_update_Referencing_Count <.. repo.usp_main
repo_sys.RepoObjectReferenced <.. repo.usp_update_Referencing_Count
repo_sys.RepoObjectReferencing <.. repo.usp_update_Referencing_Count
repo.RepoObject::has_different_sys_names <-- repo_sys.RepoObjectReferenced::has_different_sys_names
repo.RepoObject::has_different_sys_names <-- repo_sys.RepoObjectReferencing::has_different_sys_names
repo.RepoObject::is_repo_managed <-- repo_sys.RepoObjectReferenced::is_repo_managed
repo.RepoObject::is_repo_managed <-- repo_sys.RepoObjectReferencing::is_repo_managed
repo.RepoObject::RepoObject_fullname <-- repo_sys.RepoObjectReferenced::RepoObject_fullname
repo.RepoObject::RepoObject_fullname <-- repo_sys.RepoObjectReferencing::RepoObject_fullname
repo.RepoObject::RepoObject_guid <-- repo_sys.RepoObjectReferencing::RepoObject_guid
repo.RepoObject::RepoObject_guid <-- repo_sys.RepoObjectReferenced::RepoObject_guid
repo.RepoObject::SysObject_fullname <-- repo_sys.RepoObjectReferencing::SysObject_fullname
repo.RepoObject::SysObject_fullname <-- repo_sys.RepoObjectReferenced::SysObject_fullname
repo.RepoObject::SysObject_id <-- repo_sys.RepoObjectReferenced::SysObject_id
repo.RepoObject::SysObject_id <-- repo_sys.RepoObjectReferencing::SysObject_id
repo.RepoObject::SysObject_modify_date <-- repo_sys.RepoObjectReferencing::SysObject_modify_date
repo.RepoObject::SysObject_modify_date <-- repo_sys.RepoObjectReferenced::SysObject_modify_date
repo.RepoObject::SysObject_type <-- repo_sys.RepoObjectReferenced::SysObject_type
repo.RepoObject::SysObject_type <-- repo_sys.RepoObjectReferencing::SysObject_type
