left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity docs.RepoObject_ParameterList << V >> {
  **RepoObject_guid** : uniqueidentifier
  --
  AntoraParameterList : nvarchar(max)
}

entity repo_sys.parameters << V >> {
  --
  column_encryption_key_database_name : sysname
  column_encryption_key_id : int
  default_value : sql_variant
  encryption_algorithm_name : sysname
  encryption_type : int
  encryption_type_desc : nvarchar(64)
  * has_default_value : bit
  * is_cursor_ref : bit
  is_nullable : bit
  * is_output : bit
  * is_readonly : bit
  * is_xml_document : bit
  * max_length : smallint
  name : sysname
  * object_id : int
  * parameter_id : int
  * precision : tinyint
  * scale : tinyint
  SysObject_fullname : nvarchar(517)
  SysObject_fullname2 : nvarchar(257)
  SysObject_name : sysname
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_schema_name : sysname
  SysObject_type : char(2)
  * system_type_id : tinyint
  user_type_fullname : nvarchar(182)
  * user_type_id : int
  user_type_name : sysname
  * xml_collection_id : int
}

entity repo_sys.SysObject << V >> {
  --
  * create_date : datetime
  history_table_id : int
  * is_ms_shipped : bit
  * is_published : bit
  * is_schema_published : bit
  max_column_id_used : int
  * modify_date : datetime
  * parent_object_id : int
  principal_id : int
  * schema_id : int
  sql_modules_definition : nvarchar(max)
  * SysObject_fullname : nvarchar(517)
  * SysObject_fullname2 : nvarchar(257)
  * SysObject_id : int
  * SysObject_name : sysname
  SysObject_RepoObject_guid : uniqueidentifier
  SysObject_schema_name : sysname
  temporal_type : tinyint
  temporal_type_desc : nvarchar(60)
  type : char(2)
  type_desc : nvarchar(60)
}

entity sys_dwh.parameters << SN >> {
  --
}

entity sys_dwh.types << SN >> {
  --
}

repo_sys.parameters <.. docs.RepoObject_ParameterList
repo_sys.SysObject <.. repo_sys.parameters
sys_dwh.parameters <.. repo_sys.parameters
sys_dwh.types <.. repo_sys.parameters
repo_sys.parameters::SysObject_RepoObject_guid <-- docs.RepoObject_ParameterList::RepoObject_guid
repo_sys.SysObject::SysObject_fullname <-- repo_sys.parameters::SysObject_fullname
repo_sys.SysObject::SysObject_fullname2 <-- repo_sys.parameters::SysObject_fullname2
repo_sys.SysObject::SysObject_name <-- repo_sys.parameters::SysObject_name
repo_sys.SysObject::SysObject_RepoObject_guid <-- repo_sys.parameters::SysObject_RepoObject_guid
repo_sys.SysObject::SysObject_schema_name <-- repo_sys.parameters::SysObject_schema_name
repo_sys.SysObject::type <-- repo_sys.parameters::SysObject_type
