left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.Match_RepoObject_referenced_UspPersistence << V >> {
  **FirstNode** : uniqueidentifier
  **LastNode** : uniqueidentifier
  --
  First_usp_persistence_name : nvarchar(140)
  First_usp_persistence_RepoObject_guid : uniqueidentifier
  FirstNode_schema_name : nvarchar(128)
  FirstNodeName : nvarchar(261)
  Last_usp_persistence_name : nvarchar(140)
  Last_usp_persistence_RepoObject_guid : uniqueidentifier
  LastNode_schema_name : nvarchar(128)
  LastNodeName : nvarchar(261)
  ListNodeName : nvarchar(4000)
}

entity repo.Reference_UspPersistence << V >> {
  **referenced_usp_RepoObject_guid** : uniqueidentifier
  **referencing_usp_RepoObject_guid** : uniqueidentifier
  --
  referenced_usp_persistence_name : nvarchar(140)
  referencing_usp_persistence_name : nvarchar(140)
}

repo.Match_RepoObject_referenced_UspPersistence <.. repo.Reference_UspPersistence

