left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity repo.ftv_RepoObject_ColumReferenceRepoObject << IF >> {
  --
  Dbml : nvarchar(max)
  Parameter_RepoObject_guid : uniqueidentifier
  RepoObject_fullname : nvarchar(261)
  RepoObject_guid : uniqueidentifier
  RepoObject_type : uniqueidentifier
}

entity repo.RepoObjectColumn << U >> {
  * **RepoObjectColumn_guid** : uniqueidentifier
  --
  Inheritance_StringAggSeparatorSql : nvarchar(4000)
  InheritanceDefinition : nvarchar(4000)
  InheritanceType : tinyint
  is_persistence_no_check : bit
  is_persistence_no_include : bit
  is_persistence_no_update : bit
  is_query_plan_expression : bit
  is_SysObjectColumn_missing : bit
  persistence_source_RepoObjectColumn_guid : uniqueidentifier
  Referencing_Count : int
  Repo_default_definition : nvarchar(max)
  Repo_default_is_system_named : bit
  Repo_default_name : nvarchar(128)
  Repo_definition : nvarchar(max)
  * Repo_generated_always_type : tinyint
  Repo_graph_type : int
  Repo_increment_value : sql_variant
  * Repo_is_computed : bit
  * Repo_is_identity : bit
  Repo_is_nullable : bit
  Repo_is_persisted : bit
  Repo_seed_value : sql_variant
  Repo_user_type_fullname : nvarchar(128)
  Repo_user_type_name : nvarchar(128)
  Repo_uses_database_collation : bit
  * RepoObject_guid : uniqueidentifier
  RepoObjectColumn_column_id : int
  * RepoObjectColumn_name : nvarchar(128)
  SysObjectColumn_column_id : int
  * SysObjectColumn_name : nvarchar(128)
  {abstract} has_different_sys_names : bit
  * {static} is_RepoObjectColumn_name_uniqueidentifier : int
  * {static} is_SysObjectColumn_name_uniqueidentifier : int
}

entity repo.RepoObjectColumn_reference_union << V >> {
  --
  definition : nvarchar(max)
  * InformationSource : varchar(31)
  is_computed : bit
  is_referenced_object : bit
  is_referencing_object_equal_referenced_object : bit
  referenced_column_name : nvarchar(128)
  referenced_entity_name : nvarchar(128)
  referenced_id : int
  referenced_minor_id : int
  referenced_node_id : bigint
  referenced_RepoObject_guid : uniqueidentifier
  referenced_RepoObjectColumn_guid : uniqueidentifier
  referenced_schema_name : nvarchar(128)
  referenced_type : char(2)
  referencing_column_name : nvarchar(128)
  referencing_entity_name : nvarchar(128)
  referencing_id : int
  referencing_minor_id : int
  referencing_node_id : bigint
  referencing_RepoObject_guid : uniqueidentifier
  referencing_RepoObjectColumn_guid : uniqueidentifier
  referencing_schema_name : nvarchar(128)
  referencing_type : char(2)
}

entity repo.RepoObjectColumn_RelationScript << V >> {
  --
  * DbmlRelation : nvarchar(786)
  referenced_RepoObject_guid : uniqueidentifier
  referencing_RepoObject_guid : uniqueidentifier
}

repo.RepoObjectColumn <.. repo.RepoObjectColumn_RelationScript
repo.RepoObjectColumn_reference_union <.. repo.RepoObjectColumn_RelationScript
repo.RepoObjectColumn_RelationScript <.. repo.ftv_RepoObject_ColumReferenceRepoObject
repo.RepoObjectColumn_reference_union::referenced_RepoObject_guid <-- repo.RepoObjectColumn_RelationScript::referenced_RepoObject_guid
repo.RepoObjectColumn_reference_union::referencing_RepoObject_guid <-- repo.RepoObjectColumn_RelationScript::referencing_RepoObject_guid
