left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity sqlparse.ftv_sqlparse << IF >> {
  --
  children : nvarchar(max)
  class : nvarchar(500)
  is_group : bit
  is_keyword : bit
  is_whitespace : bit
  * json_key : nvarchar(4000)
  normalized : nvarchar(max)
}

entity sqlparse.RepoObject_SqlModules_20_statement_children << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  --
  child0_children : nvarchar(max)
  child0_class : nvarchar(500)
  child0_is_group : bit
  child0_is_keyword : bit
  child0_is_whitespace : bit
  child0_normalized : nvarchar(max)
  child1_children : nvarchar(max)
  child1_class : nvarchar(500)
  child1_is_group : bit
  child1_is_keyword : bit
  child1_is_whitespace : bit
  child1_normalized : nvarchar(max)
  child2_children : nvarchar(max)
  child2_class : nvarchar(500)
  child2_is_group : bit
  child2_is_keyword : bit
  child2_is_whitespace : bit
  child2_normalized : nvarchar(max)
  child3_children : nvarchar(max)
  child3_class : nvarchar(500)
  child3_is_group : bit
  child3_is_keyword : bit
  child3_is_whitespace : bit
  child3_normalized : nvarchar(max)
  child4_children : nvarchar(max)
  child4_class : nvarchar(500)
  child4_is_group : bit
  child4_is_keyword : bit
  child4_is_whitespace : bit
  child4_normalized : nvarchar(max)
  children : nvarchar(max)
  class : nvarchar(500)
  is_group : bit
  is_keyword : bit
  is_whitespace : bit
  normalized : nvarchar(max)
  RowNumber_per_Object : bigint
  SysObject_fullname : nvarchar(261)
}

entity sqlparse.RepoObject_SqlModules_22_identifier_alias_AS << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  **RowNumber** : bigint
  --
  identifier_alias : nvarchar(max)
  identifier_name : nvarchar(max)
  SysObject_fullname : nvarchar(261)
}

entity sqlparse.RepoObject_SqlModules_41_from << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  --
  children : nvarchar(max)
  class : nvarchar(500)
  identifier_alias : nvarchar(max)
  identifier_name : nvarchar(max)
  * is_from : int
  is_group : bit
  * is_join : int
  is_keyword : bit
  is_whitespace : bit
  join_type : varchar(16)
  Min_RowNumber_From : bigint
  Min_RowNumber_GroupBy : bigint
  Min_RowNumber_Where : bigint
  normalized : nvarchar(max)
  normalized_PatIndex_Select : bigint
  normalized_wo_nolock : nvarchar(max)
  patindex_nolock : bigint
  RowNumber_per_Object : bigint
  SysObject_fullname : nvarchar(261)
}

sqlparse.ftv_sqlparse <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_20_statement_children <.. sqlparse.RepoObject_SqlModules_22_identifier_alias_AS
sqlparse.RepoObject_SqlModules_22_identifier_alias_AS <.. sqlparse.RepoObject_SqlModules_41_from
sqlparse.RepoObject_SqlModules_20_statement_children::children <-- sqlparse.RepoObject_SqlModules_41_from::children
sqlparse.RepoObject_SqlModules_20_statement_children::class <-- sqlparse.RepoObject_SqlModules_41_from::class
sqlparse.RepoObject_SqlModules_20_statement_children::is_group <-- sqlparse.RepoObject_SqlModules_41_from::is_group
sqlparse.RepoObject_SqlModules_20_statement_children::is_keyword <-- sqlparse.RepoObject_SqlModules_41_from::is_keyword
sqlparse.RepoObject_SqlModules_20_statement_children::is_whitespace <-- sqlparse.RepoObject_SqlModules_41_from::is_whitespace
sqlparse.RepoObject_SqlModules_20_statement_children::json_key <-- sqlparse.RepoObject_SqlModules_41_from::json_key
sqlparse.RepoObject_SqlModules_20_statement_children::json_key <-- sqlparse.RepoObject_SqlModules_22_identifier_alias_AS::json_key
sqlparse.RepoObject_SqlModules_20_statement_children::normalized <-- sqlparse.RepoObject_SqlModules_22_identifier_alias_AS::identifier_name
sqlparse.RepoObject_SqlModules_20_statement_children::normalized <-- sqlparse.RepoObject_SqlModules_41_from::normalized
sqlparse.RepoObject_SqlModules_20_statement_children::RepoObject_guid <-- sqlparse.RepoObject_SqlModules_41_from::RepoObject_guid
sqlparse.RepoObject_SqlModules_20_statement_children::RepoObject_guid <-- sqlparse.RepoObject_SqlModules_22_identifier_alias_AS::RepoObject_guid
sqlparse.RepoObject_SqlModules_20_statement_children::RowNumber_per_Object <-- sqlparse.RepoObject_SqlModules_41_from::RowNumber_per_Object
sqlparse.RepoObject_SqlModules_20_statement_children::SysObject_fullname <-- sqlparse.RepoObject_SqlModules_41_from::SysObject_fullname
sqlparse.RepoObject_SqlModules_20_statement_children::SysObject_fullname <-- sqlparse.RepoObject_SqlModules_22_identifier_alias_AS::SysObject_fullname
sqlparse.RepoObject_SqlModules_22_identifier_alias_AS::identifier_alias <-- sqlparse.RepoObject_SqlModules_41_from::identifier_alias
sqlparse.RepoObject_SqlModules_22_identifier_alias_AS::identifier_name <-- sqlparse.RepoObject_SqlModules_41_from::identifier_name
