left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity logs.usp_ExecutionLog_insert << P >> {
  --
}

entity sqlparse.RepoObject_SqlModules_41_from << V >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  --
  children : nvarchar(max)
  class : nvarchar(500)
  identifier_alias : nvarchar(max)
  identifier_name : nvarchar(max)
  * is_from : int
  is_group : bit
  * is_join : int
  is_keyword : bit
  is_whitespace : bit
  join_type : varchar(16)
  Min_RowNumber_From : bigint
  Min_RowNumber_GroupBy : bigint
  Min_RowNumber_Where : bigint
  normalized : nvarchar(max)
  normalized_PatIndex_Select : bigint
  normalized_wo_nolock : nvarchar(max)
  patindex_nolock : bigint
  RowNumber_per_Object : bigint
  SysObject_fullname : nvarchar(261)
}

entity sqlparse.RepoObject_SqlModules_41_from_T << U >> {
  * **RepoObject_guid** : uniqueidentifier
  * **json_key** : nvarchar(4000)
  --
  children : nvarchar(max)
  class : nvarchar(500)
  identifier_alias : nvarchar(max)
  identifier_name : nvarchar(max)
  * is_from : int
  is_group : bit
  * is_join : int
  is_keyword : bit
  is_whitespace : bit
  join_type : varchar(16)
  Min_RowNumber_From : bigint
  Min_RowNumber_GroupBy : bigint
  Min_RowNumber_Where : bigint
  normalized : nvarchar(max)
  normalized_PatIndex_Select : bigint
  normalized_wo_nolock : nvarchar(max)
  patindex_nolock : bigint
  RowNumber_per_Object : bigint
  SysObject_fullname : nvarchar(261)
}

entity sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T << P >> {
  --
}

logs.usp_ExecutionLog_insert <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from_T <.. sqlparse.usp_PERSIST_RepoObject_SqlModules_41_from_T
sqlparse.RepoObject_SqlModules_41_from::children <-- sqlparse.RepoObject_SqlModules_41_from_T::children
sqlparse.RepoObject_SqlModules_41_from::class <-- sqlparse.RepoObject_SqlModules_41_from_T::class
sqlparse.RepoObject_SqlModules_41_from::identifier_alias <-- sqlparse.RepoObject_SqlModules_41_from_T::identifier_alias
sqlparse.RepoObject_SqlModules_41_from::identifier_name <-- sqlparse.RepoObject_SqlModules_41_from_T::identifier_name
sqlparse.RepoObject_SqlModules_41_from::is_from <-- sqlparse.RepoObject_SqlModules_41_from_T::is_from
sqlparse.RepoObject_SqlModules_41_from::is_group <-- sqlparse.RepoObject_SqlModules_41_from_T::is_group
sqlparse.RepoObject_SqlModules_41_from::is_join <-- sqlparse.RepoObject_SqlModules_41_from_T::is_join
sqlparse.RepoObject_SqlModules_41_from::is_keyword <-- sqlparse.RepoObject_SqlModules_41_from_T::is_keyword
sqlparse.RepoObject_SqlModules_41_from::is_whitespace <-- sqlparse.RepoObject_SqlModules_41_from_T::is_whitespace
sqlparse.RepoObject_SqlModules_41_from::join_type <-- sqlparse.RepoObject_SqlModules_41_from_T::join_type
sqlparse.RepoObject_SqlModules_41_from::json_key <-- sqlparse.RepoObject_SqlModules_41_from_T::json_key
sqlparse.RepoObject_SqlModules_41_from::Min_RowNumber_From <-- sqlparse.RepoObject_SqlModules_41_from_T::Min_RowNumber_From
sqlparse.RepoObject_SqlModules_41_from::Min_RowNumber_GroupBy <-- sqlparse.RepoObject_SqlModules_41_from_T::Min_RowNumber_GroupBy
sqlparse.RepoObject_SqlModules_41_from::Min_RowNumber_Where <-- sqlparse.RepoObject_SqlModules_41_from_T::Min_RowNumber_Where
sqlparse.RepoObject_SqlModules_41_from::normalized <-- sqlparse.RepoObject_SqlModules_41_from_T::normalized
sqlparse.RepoObject_SqlModules_41_from::normalized_PatIndex_Select <-- sqlparse.RepoObject_SqlModules_41_from_T::normalized_PatIndex_Select
sqlparse.RepoObject_SqlModules_41_from::normalized_wo_nolock <-- sqlparse.RepoObject_SqlModules_41_from_T::normalized_wo_nolock
sqlparse.RepoObject_SqlModules_41_from::patindex_nolock <-- sqlparse.RepoObject_SqlModules_41_from_T::patindex_nolock
sqlparse.RepoObject_SqlModules_41_from::RepoObject_guid <-- sqlparse.RepoObject_SqlModules_41_from_T::RepoObject_guid
sqlparse.RepoObject_SqlModules_41_from::RowNumber_per_Object <-- sqlparse.RepoObject_SqlModules_41_from_T::RowNumber_per_Object
sqlparse.RepoObject_SqlModules_41_from::SysObject_fullname <-- sqlparse.RepoObject_SqlModules_41_from_T::SysObject_fullname
