left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity sys_self.ExtendedProperties << V >> {
  --
  * class : tinyint
  class_desc : nvarchar(60)
  entity_column_name : nvarchar(128)
  entity_index_name : nvarchar(128)
  entity_parameter_name : nvarchar(128)
  level2type : varchar(9)
  * major_id : int
  * minor_id : int
  minor_name : nvarchar(128)
  parent_name : sysname
  parent_object_id : int
  parent_type : char(2)
  property_basetype : sql_variant
  * property_name : sysname
  property_nvarchar : nvarchar(4000)
  property_value : sql_variant
  SysObject_name : nvarchar(128)
  SysObject_schema_name : nvarchar(128)
}

entity sys_self.ExtendedProperties_ParameterForAddUpdateDrop << V >> {
  --
  * class : tinyint
  class_desc : nvarchar(60)
  level0name : nvarchar(128)
  * level0type : varchar(6)
  level1name : nvarchar(128)
  level1type : varchar(9)
  level2name : nvarchar(128)
  level2type : varchar(10)
  * minor_id : int
  * property_name : sysname
  property_value : sql_variant
  type : char(2)
  type_level1type : varchar(9)
  type_level2type : varchar(10)
}

sys_self.ExtendedProperties <.. sys_self.ExtendedProperties_ParameterForAddUpdateDrop
sys_self.ExtendedProperties::class <-- sys_self.ExtendedProperties_ParameterForAddUpdateDrop::class
sys_self.ExtendedProperties::class_desc <-- sys_self.ExtendedProperties_ParameterForAddUpdateDrop::class_desc
sys_self.ExtendedProperties::minor_id <-- sys_self.ExtendedProperties_ParameterForAddUpdateDrop::minor_id
sys_self.ExtendedProperties::property_name <-- sys_self.ExtendedProperties_ParameterForAddUpdateDrop::property_name
sys_self.ExtendedProperties::property_value <-- sys_self.ExtendedProperties_ParameterForAddUpdateDrop::property_value
