left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity uspgenerator.GeneratorUsp_SqlUsp << V >> {
  * **usp_id** : int
  --
  * AdocUspSteps : nvarchar(max)
  * has_logging : tinyint
  MS_Description : nvarchar(4000)
  RepoObject_guid : uniqueidentifier
  SqlStepList : nvarchar(max)
  * SqlUsp : nvarchar(max)
  usp_Description : nvarchar(4000)
  * usp_fullname : nvarchar(261)
  * usp_name : nvarchar(128)
  * usp_schema : nvarchar(128)
  * UspExamples : nvarchar(4000)
  UspParameters : nvarchar(max)
}

entity uspgenerator.GeneratorUsp_StepList << V >> {
  --
  AdocStepList : nvarchar(max)
  StepList : nvarchar(max)
  * usp_id : int
}

entity uspgenerator.GeneratorUspStep_Sql << V >> {
  * **usp_id** : int
  **Number** : int
  --
  * AdocStep : nvarchar(max)
  * has_logging : tinyint
  is_required_ELSE : int
  required_Begin_count : int
  required_End_count : int
  RowNumber_PerUsp : bigint
  * SqlStep : nvarchar(max)
  * usp_fullname : nvarchar(261)
}

uspgenerator.GeneratorUsp_StepList <.. uspgenerator.GeneratorUsp_SqlUsp
uspgenerator.GeneratorUspStep_Sql <.. uspgenerator.GeneratorUsp_StepList
uspgenerator.GeneratorUsp_StepList::StepList <-- uspgenerator.GeneratorUsp_SqlUsp::SqlStepList
uspgenerator.GeneratorUspStep_Sql::usp_id <-- uspgenerator.GeneratorUsp_StepList::usp_id
