left to right direction
hide circle
'avoide "." issues:
set namespaceSeparator none


skinparam class {
  BackgroundColor White
  BackgroundColor<<FN>> Yellow
  BackgroundColor<<FS>> Yellow
  BackgroundColor<<FT>> LightGray
  BackgroundColor<<IF>> Yellow
  BackgroundColor<<IS>> Yellow
  BackgroundColor<<P>> Aqua
  BackgroundColor<<PC>> Aqua
  BackgroundColor<<SN>> Yellow
  BackgroundColor<<SO>> SlateBlue
  BackgroundColor<<TF>> LightGray
  BackgroundColor<<TR>> Tomato
  BackgroundColor<<U>> White
  BackgroundColor<<V>> WhiteSmoke
  BackgroundColor<<X>> Aqua
}


entity uspgenerator.ftv_GeneratorUspStep_sql << IF >> {
  --
  * Number : int
  * SqlStep : nvarchar(max)
  Statement : nvarchar(max)
}

entity uspgenerator.ftv_GeneratorUspStep_tree << IF >> {
  --
  Asc_PerParentChild : bigint
  child_PerParent : bigint
  Depth : int
  Desc_PerParentChild : bigint
  is_condition : tinyint
  * is_required_ELSE : int
  Number : int
  Parent_Number : int
  Parent_Sort : int
  Root_Sort : int
  RowNumber_PerUsp : bigint
  Sort : int
  usp_id : int
}

entity uspgenerator.GeneratorUspStep << U >> {
  * **id** : int
  --
  * has_logging : tinyint
  info_01 : nvarchar(max)
  info_02 : nvarchar(max)
  info_03 : nvarchar(max)
  info_04 : nvarchar(max)
  info_05 : nvarchar(max)
  info_06 : nvarchar(max)
  info_07 : nvarchar(max)
  info_08 : nvarchar(max)
  info_09 : nvarchar(max)
  * is_condition : tinyint
  * is_inactive : tinyint
  * is_SubProcedure : tinyint
  log_flag_InsertUpdateDelete : char(1)
  log_source_object : nvarchar(261)
  log_target_object : nvarchar(261)
  Name : nvarchar(1000)
  * Number : int
  Parent_Number : int
  Statement : nvarchar(max)
  * usp_id : int
}

entity uspgenerator.GeneratorUspStep_Sql << V >> {
  * **usp_id** : int
  **Number** : int
  --
  * AdocStep : nvarchar(max)
  * has_logging : tinyint
  is_required_ELSE : int
  required_Begin_count : int
  required_End_count : int
  RowNumber_PerUsp : bigint
  * SqlStep : nvarchar(max)
  * usp_fullname : nvarchar(261)
}

entity uspgenerator.usp_GeneratorUsp_insert_update_persistence << P >> {
  --
}

uspgenerator.ftv_GeneratorUspStep_sql <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.ftv_GeneratorUspStep_tree <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.GeneratorUspStep_Sql
uspgenerator.GeneratorUspStep <.. uspgenerator.usp_GeneratorUsp_insert_update_persistence
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_sql
uspgenerator.GeneratorUspStep <.. uspgenerator.ftv_GeneratorUspStep_tree

